apiVersion: v1
kind: Secret
metadata:
    name: linkwarden
    namespace: linkwarden
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:hpnyNisXteE/b0vt2M1rrZOJXld/a4NUOpSlIYbvdJfci4P5vbowhjLV4vqlT4CBYyuJaF2L/LtLKxmsOTTs0ZYmKIjj9q7SrkwfOSYFE5Z/9yXitKnw9l+LNGPHhY/YeZ20yjqrE3lzHTZ/CPN8Q2q1X5Uu3FFKgYH+og==,iv:j9XDL9xopCnz0lGUi7Yb8Mh5gGlXI0TdTxTHoSNWaVM=,tag:S0yFzznw/l9cgdIJyQ7qQg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:4BUVbcE/Zl77bdek4wE4kIdbUllJ+b/WRmG1qx07edR6ZEs8FSafon5ywKY=,iv:U34x3a2SJtFX147zqEjCc3IZCwxdZ/BUuICHYwSI0bA=,tag:qgQRlhB8YWeC/X/beHwOQQ==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:SNLuzLJ+Chz4n5yxN9z4Ghp3LXDYRA4get+G3AMQktCYs7+4b2Qj58XhgA==,iv:LCuGfJOZSt+RR5HCYBkId43W0pv+8hBxvB8X4Reio3w=,tag:7FmN4FjRcZe7ljF5m5FEJQ==,type:str]
    MEILI_HOST: ENC[AES256_GCM,data:FfAg0DnIbtSaYbLLNK40SCnfeX9UKOFGLr/TMpaF4JLR7nXO/gShDoLsRfE14v8cJiLLOw==,iv:5Dx+DV4L5M/7ImCP+2SlLvutmDfPgyt+7We38Z0Pt8c=,tag:BHBbtZOMP6IyADiP9oBTeg==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:Qo/b+Eb9O61JpreSmbZVYOUruzkrMj4NJaGpRMNXcKc=,iv:+/s8jyebfOgwuqLblQQ6aqSNXOWgvykpLkZdfKm1tgg=,tag:XdaCTEik9EFtNWq3qTcq3A==,type:str]
    NEXT_PUBLIC_DISABLE_REGISTRATION: ENC[AES256_GCM,data:YHnmaw==,iv:rwugyRn28RLN3bir9ql87ndZwhcZbsSNBYIEnEWK5xw=,tag:0O0p3wpcsS/NPuAF/2ZLJw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZGVyUFlsejYrd2d3aW1Q
            ZWl2SnhtR2pnc2hqaW1qMGNKdUxUQU9LWkdvCitaWmRia25DSmR4emhXUDg3UXdh
            OGlKZmxOQWQwdGllUUJDUGJ0WG9IY28KLS0tIDZ4eWhOc0dtT3c0bURqQS9BM0pD
            bDNWYWs1QW1ZbTdWVW8raEUwZFBzLzgKaDAWm8I9yByAFL6U6s9k/rpnDfi8Nry4
            2UMwtws/H/PH2Fo4inQ/hxwzgyAJID1Ig5MHV6Pi/U7fRaALH/Pxsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T20:52:17Z"
    mac: ENC[AES256_GCM,data:uyaVcLtNaEnrCua48jAkOM7Niap1Hpw1SZcKU91SbzJ5IC9YZueKgFez9DC+q7vYfkc7poG7P/v1eAkNfwS4vzHw/1v27Yhshdc8KU3rmajVyLyJm/leqix64LXQPCPsuh7v/nbVcyJJjVGWDpF3Z+SPGgrsPfw6+OGngGI9bko=,iv:xf/1DS0YnEC4U3inIoS/old11vfxOcf+Fc6nx9/0P2M=,tag:oVDyKxgoSDQ49xLhSv1hkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
