apiVersion: v1
kind: Secret
metadata:
    name: linkwarden
    namespace: linkwarden
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:16eieQUBj9s4KNXTDXJ62UjpzTHYkSqIN0MeBNt7jp1W6GAN0ZjEGpKqe96UGMc+2nGF5oWjs8af1HxBrGGKy9uRZsMW4ktMbjZw3S7tYDLZ7C8aNcR5EZf7qj32Ttkd0b/DfPmzg81Ze6yCDsBTcT4m0T6ay9YwoA4Phg==,iv:qXoT40Zc9+um6C66pd+uKhgiMkOmLlXysnP9U2M0pM8=,tag:ntQY4IyPqm/o69sGCcc72w==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:xyVHERrQ2+k5lIPITzxEwAt/VIJH4grppbEQYvCOWa+4FgblKPkGlHPXioA=,iv:HgTu13zItlDbd1t6us7M7kLenv7gYiZ+R/bQYQlzZCE=,tag:alBSijAvfOuAh6DYN9xQ6A==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:gHLVJmVAdspaXT8TPJ3KwtICc9tC/KfwT2mIUwvuuTAtD/dv1Ox9CCeRpg==,iv:L0pz4+IdXXB11AGOJRx4GJdEAoHooIfoH6UY+Ekfdfc=,tag:wY1whZp7F7gku8OhP1ZuNQ==,type:str]
    MEILI_HOST: ENC[AES256_GCM,data:GFo2iHGAB7JV/g6vIdc8gStzPlr7ssVsygcBvhKhsa9sJAMpFn0msed1zqAHOG0MOpDJWQ==,iv:nX8q+IqYWEU0DEm1SjCK2XFgQIGBJ9d9cNxhk/XZi5Y=,tag:OVKpUzzwXngQ/xLy1AjBZg==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:TbNc4ykICN8x8cpB70+OIELAw5a+sxrEvJzY8voU/l0=,iv:1OR0/r3qKR3r35R3puvG3DGZhTbS9LKOcUtK1cmSm60=,tag:FZ8MjDrvFybTz9OaRP5ZgQ==,type:str]
    NEXT_PUBLIC_DISABLE_REGISTRATION: ENC[AES256_GCM,data:CobKxA==,iv:xDxN6Zopu8uy+mWSOvRgUwHf9U0KA1Sm0RhKbTpIdPs=,tag:TSY11uUuQft+YuCULXXiqA==,type:str]
    NEXT_PUBLIC_AUTHENTIK_ENABLED: ENC[AES256_GCM,data:zjBmBw==,iv:I8/IwK50xzTqpFUs+1j/8eKPM5iOaKYOh3K+k6/gj7k=,tag:ftvKPmJku4H3n0qEIWzUKg==,type:str]
    AUTHENTIK_ISSUER: ENC[AES256_GCM,data:0R/ZLZJUVm6AMnKBEdxAIuXbwaM86gF1tuKRU3TLKawNvqPOuNN6iki8OB1WUvjHLkMXeks06fg=,iv:RNRMn6HmAMrMF3Kt/0eIcogrGY42YfSJcfjK414EhCw=,tag:jeUsFzZ5rYC4KO8bx0Lxpg==,type:str]
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:QJ95vhirbOXsKtyshKUfxff/A2aJHMebXWPQdi/GXO0mr0TkazwZzg==,iv:sKXoarJXnxJr3bdRe57LcjVmOwCQ+nyOBsfmpOWVV6k=,tag:A7j7gsPt1/m6cPS/VnOsrQ==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:O0sALKBWXa3rJe8rdo1tD8ualY/crIscxG4r3ZRq/HXHsJhOfbDXf3GbUJjbQH2MVNqfyX92oWL7YxEvf+7qEGI58yyUQrmPaiEsUJInNMpDh7cn1x4gtSMsU1GcjJdpJ8dJa9/qiYnX6Z3wLobV8NEcleKttEvphN4KiO62kRQ=,iv:pocrcFwOkPxmO566s2aBYE/b1xinYj3V1kknDg7Y3X0=,tag:Urpr/kJkxBKkcRK7Ig5JmQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQndCeG9Xc0RVbFdRSmdr
            ek81WllFcGRzYkppQ2lMRXY5ZEFGaXg4dDE4Ckw1WldwVitLckNIMEovb09Jc1Fu
            OUNjQ3N6WXdadnJXSlFML0d0a1FKSGsKLS0tIFV6ZHZXRlBhTy9SMHBUaG1zK2No
            d253NDlWZWlSbjZzaHAvZnVKMUQ0WEUK90BbewwjuoJBZxI2ApXX94/mhWZHkALO
            jUKb+oB8ZO9zyld3OkyBmEHqMH0p5kVyEF23C4wZF51bXIfDXnwTCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-11T21:58:17Z"
    mac: ENC[AES256_GCM,data:hWXknVt8QFx0fJTVsaK75VcOFfMo4C6C66Gymyn7Ceg8LjGJH6Sz6bteHENFkK+XVDm6gjSHnXjvY444blQuTAM0WDXt1CPXIa4LSqCD+SV+D7f35V7eGZ4iaPJqcWF1kzYb85N1ERgu2JIPCFDpT40PbJZyZESQrhztBEjWUzs=,iv:DoHDCGC9L7rPaVRsMsiX6oimnmIaNdfjCUCXefO0O2Y=,tag:ciwQlkkOZQxqSpyxqagdjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
