apiVersion: v1
kind: Secret
metadata:
    name: claude-telegram-ghcr
    namespace: claude-telegram
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:M62knGKwfgM1hqZd91M2ry2C/iZhTw9/D0jKwLkh/e7wavFP91TU8zJsckb69d2/7TuOlNq+4f6zRqrt/h3B9YkI71dUqVxYw9v3EDlWCezind4Ss3h+vvIxy5vulvwcww==,iv:+HGf1tTD1cjHhQxrkX3Mf4yEg6ueFlIXqqJ7/wA0hbk=,tag:FsBTPdKe4IHq6G5lIrdR0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYa29BdXVNTlBtTFNkVlpD
            YTkvVTBxeEorendkejdUMkU1Wlh5NGZGUm4wCmxDeHhQTGpvZ0N3dmFmNk5HaUhI
            aldmTmpIeVNmTC9rb3d0WkRQZ1ZsdDAKLS0tIDlDVi93NFV1aFcxRjRGRjRXc1ox
            V09Ydng1b282bkNoeGc2d2ZwSVoxQ00KlgGH+qd5bEEY2JijA5oy/rt9kHGBwhQ0
            zF6scLOfGXvFvNfMdXK1mTCFfWiOoYNCzbgCDxDT/XVKzxFbH/joYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T20:54:31Z"
    mac: ENC[AES256_GCM,data:vZGv5PKh9CGlFjXWyX67f2xmj1DRvZYAPwqZ62KVC9xGumHfKmRScOLKrSZiSrL5UYwQlUkbUntx1UuIwsfe5H5e79muu7ZGOhW+b/GZwYBnQMNk4vU7NfUCms013azjmpNpNZjm1V9zE8D2nq25g6+LljmUA3lNqhOFaGgIKI4=,iv:TLe8+F0pnTRcq7ejqHhDSXAjlIRDOILogPQG+t9bixg=,tag:7int/1BJxYhZu7fV3CTqkA==,type:str]
    version: 3.13.2
