apiVersion: v1
kind: Secret
metadata:
    name: claude-telegram-env
    namespace: claude-telegram
type: Opaque
stringData:
    telegram-bot-token: ENC[AES256_GCM,data:vzNtrvnWz/SFFKMXtDodBU7kk2U25BmtxjzUC82vpgxRviijYidN1J2nSjGCMQ==,iv:NUIQp1igLxFy8/2zZL2YlQV1MSE6b3ek0ko+47wCgYc=,tag:lj6ycmknN3ZDXTq0W2bOfA==,type:str]
    claude-oauth-token: ENC[AES256_GCM,data:cvDnljbzX6nwWVMmdvE2gb7qwdXLYXYQzL7Ji3hMJNwNX06lMYzvfz6wkpoEbIOHz4lUwP21PX8qeUpkx2iMuuIIHB8tXn7y6I1iKEGZaEO68PFiWWHmAvX7QFG1PvqvvAbUplM5T0JMq5dW,iv:dAsCjRr1tPHKU11lR024s4SP5FYl1yquG/PAtMo0WC0=,tag:U1ZpSyIvBqkBes4tsKJfFQ==,type:str]
    trigger-secret: ENC[AES256_GCM,data:TJQBV+UhiTmshNCrcqbHYMxECYStXnDekcPF5BKgd2sd/Zc5rOHVM0cKkbJ1GytWo2Xggnn1dsi0gl+mzbmv9w==,iv:964Nf5nvOgy6nJEgD6fDMT273DRAYoiKorz4dHnT2r4=,tag:qnkQ96Jiw1BpveNsWSvAVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSmJ5OWdBOVBUN0NWRGJR
            cWRaOWdhYUNmSVZYZnJaMjdXUE5vZWZvQWpRCmZoUWRjTldVM2J0UVlHOVlqZ2Jq
            ZFhvT3VaT2dDdHNYcWdIZnZjSHRsL2MKLS0tIFpoWWFweUpwdU44cmpWWmIxckpO
            c3gvSW5mbG90U2xFYXpiSHdXZWMvdDQKaGaOfqKE1hQcaBsruR4iJbEs3ioCLPYD
            VgSU8JF6E40wW6JMIwU5taIQ9/AuPH2CRbhLiUv3oawi00i3SDFmoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T16:19:12Z"
    mac: ENC[AES256_GCM,data:M8vHolifQDD+eE/f3v1OcwAU2PzfUM6EWSNoMwaC95gPHVKE76hy2BgecqlP4vhUwbxQbcSJWWnFBjRoKkC5FbKZ+82I9vfKiRYQff96u+AdGk17E+lkwORcYfIeSklKFJ6Z+VzC1d8GteB3SQcOZNUtGmDNpWH6ec9yDTmouC4=,iv:hzFiOiwUR1mVDgUUkx9r0iQ0G7t7YAzYQRDdANtSGOo=,tag:HkGNoQRDjJ03AJezXz591Q==,type:str]
    version: 3.12.2
