apiVersion: v1
kind: Secret
metadata:
    name: claude-telegram-env
    namespace: claude-telegram
type: Opaque
stringData:
    telegram-bot-token: ENC[AES256_GCM,data:bdnqPlQQuhi4e/CPIO5q2x9/wkVcszU6XAfg+WkaNx2MDT++w+x7oqwgxqGm6Q==,iv:09bu6z81nc/0mRNi3uihOjvLJ9Z62jCtpzzj6eXunFQ=,tag:3qW/a5yjVVpUEYVzDGRAig==,type:str]
    claude-oauth-token: ENC[AES256_GCM,data:IB3daOmKZra4LIllltpUj+CgAK8XHpbRZAY/ZYfh9T/cK+TBntP6jtNIjjXPVArI78bGwF+P/3wGHjvbdRGB0/MSnt4BYfXhcsYGNo8AZCx7qJ78MdC2Q0m29/9pPly1HFGW9q0gYNBJvr8G,iv:bILP/xgLC9L7KbY2Mh5jeTwibtnOSbqRPJaZv72OJOU=,tag:SUCRiQGlkBYMVvZZotPFzg==,type:str]
    trigger-secret: ENC[AES256_GCM,data:FwNOVTxJKt9x1fL7WlZG61kBbG+u08W/4eHGgquqDXY/EqmV25PnPDUAkn5Nf5lgcznq5Z7UersKBAXSJPDC7w==,iv:BQtks/M5rP4g7qXRSRdleO2Io7Ud0pNaTgn36tyw/2o=,tag:EbawVHtkAW3mAFlM6g/Q5w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTk15RVBMWkREL2F1Z1hW
            Y2JDbnhieElFQjFaL0FoSndjTDJYbTV4U0JnClZQTUoveWl1KzlhaU5CTHkrM2VS
            SkVLOFc3TDJnRGdIcDRsZFd5RFM3c1UKLS0tIGlkMWtlcW5EckFvRWNUNFd4b0py
            MU01Z3orNXE5VEhpVUdWTTFWYi9iQ3cKeQW55TTgs7aAcnlEA2q/Z79vkvwLcn6k
            Wvfag9RqZAFV2QkvcQkOm3E+RfHtPSVG/HW8TpQ/6ftn1SrDNSa9Rw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T12:39:48Z"
    mac: ENC[AES256_GCM,data:axkjwAXdl54OjQ6MQ5riozTQjsiOWEu1AmJe5UWoLft0lnwKIjrBE1QusW6xsnnJi0Dh5/vqbYgMxtnIieoi3Yn8qFjhAIhHPjy7YHnrEDNYJGWbMJAtu+bSahNxRP8k0G1bH7LeUPuUof6sbBeU+/dATEh2hgu7cJOuL9TAQxQ=,iv:UKnr+sGSaXaxmQZvmDvC+fcVPqm7Vb6lobbLmzmbyH0=,tag:eCvrWw9rek6+S/vnt/YIJA==,type:str]
    version: 3.13.3
