apiVersion: v1
kind: Secret
metadata:
    name: couchdb-couchdb
    namespace: databases
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:pPzaam4=,iv:2l9k95h5v4floTOFOl2VkuQ12wthX08TYOX6tgsh2ws=,tag:HXEU3aqnUmyp2HKng78zEQ==,type:str]
    #ENC[AES256_GCM,data:fA4ABiWQ9sPiv1zFtCbPa3ELeoCD2NKx62prwCAs6dF1r2lBM6cln8YcnYWVLIPvLeDuz0kSh3j4dXvdiAAY3kCh/y+UoM17nXjJ626R7BLEwx6gQm/0USE=,iv:S+54sVO0/pDqCKLID0tR4JOibsTnwSN8Zpch63A0By0=,tag:G5YcKUWjTSb53p994p2o+g==,type:comment]
    adminPassword: ENC[AES256_GCM,data:w5+rR+g33i9W4A3++uMVUnR3oKI8ICmLgH7D4M8NeqF8/seFwqwnXzwWaMk0SbNQ,iv:nWjHDH6NGlsEb6SVGB3JDlBfvoR5hIi09BFO4dS3z9Y=,tag:mXCV7b+sHxMHA5hphO9+JA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZTBJZzlHT2FabWUrNUpX
            RXlOVGtZVXNSNFRCZi8wUTdZM3Z5M0tXNVFZCmFNUmUrZFhPbWlHandTY3M3Uzla
            emNhZSt3YWd4S01pazRmODZBbm5FNE0KLS0tIC8zN2c0T2t0dVpmKzVoSEJKWTVq
            NS9WU0QxQjJCOHpBb0x0aDdFVDV3ZzAKNCRKqIV2JUpxDd6/lk98krrRi6Qp9/Sm
            wkZTOVORaU52+vLHHzeo+gyBGk6S/2MAJblQgbmz7D6/ge9BHx7VNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T18:09:40Z"
    mac: ENC[AES256_GCM,data:Zzt5JbtAXPvsXUqsvkF8/43vkVNOmVhYGWg3QTwhUPYvTuazvnrEqA55JLiwZpH86DnNgy5+dOtQUZiszIyrgJt17R5crAlbtFbaf78pJM89nzB7fofNF0fC1vN/xvvvuvKn/L/fO2kyNBsq9/ggy+V5NhyuGt3S05bRSj2iyYE=,iv:uNjqkVr+Wd9Y5xJPNwYG1VBoetQvYf7psR8MWs5hEpY=,tag:l1ky6HCiMN6awrin4duF/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
