apiVersion: v1
kind: Secret
metadata:
    name: couchdb-couchdb
    namespace: databases
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:pPzaam4=,iv:2l9k95h5v4floTOFOl2VkuQ12wthX08TYOX6tgsh2ws=,tag:HXEU3aqnUmyp2HKng78zEQ==,type:str]
    #ENC[AES256_GCM,data:fA4ABiWQ9sPiv1zFtCbPa3ELeoCD2NKx62prwCAs6dF1r2lBM6cln8YcnYWVLIPvLeDuz0kSh3j4dXvdiAAY3kCh/y+UoM17nXjJ626R7BLEwx6gQm/0USE=,iv:S+54sVO0/pDqCKLID0tR4JOibsTnwSN8Zpch63A0By0=,tag:G5YcKUWjTSb53p994p2o+g==,type:comment]
    adminPassword: ENC[AES256_GCM,data:EKne9y6RQMP6O7L2BGUtkWwM2aA1AKQp0OpVaD7s+b/ZL6nxzkWMzg==,iv:kpSQm+gtSKAjsRmB5p9kRBzT992O1b8A6Ut6DX+YRPc=,tag:Yy0mA6iEN3XQ2316IoY6KA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZTBJZzlHT2FabWUrNUpX
            RXlOVGtZVXNSNFRCZi8wUTdZM3Z5M0tXNVFZCmFNUmUrZFhPbWlHandTY3M3Uzla
            emNhZSt3YWd4S01pazRmODZBbm5FNE0KLS0tIC8zN2c0T2t0dVpmKzVoSEJKWTVq
            NS9WU0QxQjJCOHpBb0x0aDdFVDV3ZzAKNCRKqIV2JUpxDd6/lk98krrRi6Qp9/Sm
            wkZTOVORaU52+vLHHzeo+gyBGk6S/2MAJblQgbmz7D6/ge9BHx7VNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T17:30:20Z"
    mac: ENC[AES256_GCM,data:aFfrIP3gfKz2ePfmvthJ2wuCbJdLq7RYsja3PuHpFz7i33QBERycnCMg6uTEA27kfPHpnSq45PQfOnJ+wu/XDISZOIGm+AybiAjd/KFr5UCVhiRxxHsKY+ZUUjrJpHJstxdJ67ozmRGWZK3P3khIDSoyooUW2o/VmohlLT2AWzM=,iv:QGpb+iRaoVlQLBDUJWev1jIaQEuYkx5gPwtXmSFiOac=,tag:2ZDxnbRv+Gcv2qH02fzWGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
