apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-mgmt-token
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:gjASyq5JC12aBilWxrFvnemMkU5wK9DEQE6bVmj06pAFV/aMqe9/dDFpwcgMZbRvGbV9lnE=,iv:/gVWyQfnkk9Ea5h2zlDBKRGZilvG2J057RIqoRl0lTk=,tag:du/QG7xD3MZdaNl+YmtfbQ==,type:str]
    CF_ACCOUNT_ID: ENC[AES256_GCM,data:xnjTTd/GillDkeA7+Xmrv9HJ5IEC+gj9zKDirSmxHqU=,iv:C0cITitxm/FTjdlPE6WZz+sP2SJ8ZhOoNO15VyONpmo=,tag:b+DNAEWvXJUsqLCxnbOLHQ==,type:str]
    CF_TUNNEL_UUID: ENC[AES256_GCM,data:cnH0onkR2tPlumm5QWc14kVhJiRs2OuywGVArp90VRpbPyTW,iv:MBHa5FlmBym0NucJh9EoAhwK+IPASPNVoV1G5td6Le4=,tag:oDQfNul+GK/zUfGMUuLqqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMW0wU2N1ZnFLMWN1YkNY
            Y2VGa0hxVlQ3ZmJlR3VPd2MvWHR3R0ZrV1g0CmxNUTJxSC9zYzU4YXhxNmtTdXNr
            ZTcvUlM5b1dZckhIUVh1MThteEhMN2MKLS0tIDd3YVJWMGU5TkdxU2x1MURDWHlW
            aUM0NUhGcEQzOE1UV0hGai94c3ppSUkKY0ba9vs7pF2iWIEqC025k9V4BLvRB8VY
            lzEwYaYJIoFJOB0KbopAitCCwiwZntRpv2f3Fb5AkOcMei4wlRfQTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T21:37:57Z"
    mac: ENC[AES256_GCM,data:i+7wXqz1hl7QEkENT9Sxtwbdgv+FXMPIEMpoYENRgkuI39awDQ+QX12U5EASI6O+gNJ2hnrTYQ41CH9VTz0ZQSzdQUSyIK6Z3eQ5uJ98NW9uVPUYee2PLGT950z82L6YojCqfI1tjd6ZziROtnVFam4Kd8GPwYWrigDU/zTIR5k=,iv:KmyCsFUwwFoe0l/awUvICy/tMJO4knzUnBt2Ev3uyws=,tag:k5szTHEV7yVJ95GbOoH6YA==,type:str]
    version: 3.12.2
