apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-mgmt-token
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ri+SwuFpmo92XYYCS8NYCqVvtwFmjqVxrF3UFOc0EaUYYQSWrj1sXw==,iv:bSrpS79oos6KlYkBs7IX9urTVodyTYLojv/0yPpi4D0=,tag:wXYifOkj5VdpRORO3hUzIg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCb01OZTY4eERMRWNOSkI2
            MEw5ak5NdGdMbHJWSkZ2MmxLL3B5L3pkdTJBCnlMLzZhZEoxMXZQbnhuY0EyYVNi
            WGl3NjdqREZwNEVEcFlkMDNVc1dSL3MKLS0tIGVva1B2Q1dFZWRkYlhWdWVHT1VT
            K0ZETTlKdmlJU1Exbyt1a2hBdHZPWHMKxxjogm5LTAwTwXMCrI0LES556pJIvjVY
            /etkj8RP+rSslEaHWiAqwypboEA+YGV+2bnMZcNTdRv5BEoVs5qXQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T22:52:59Z"
    mac: ENC[AES256_GCM,data:hjFhErR26YP8H2Zl0TGnRR0Q/KZlBcq8hv+T+3pbhEUO2BK6lDwan0rCpSoYJWlctvrWas0iBAjZbloUqH7Yrd+hJSsQFN3WGnEF5E+ODLMX83zVoMUOqx0Tob44PrnThyG/dvbArL8+GwQJ4FDoP0D3xSAVCd7Isi/y211XxaI=,iv:Fm/3QA5ZvpY2mhWMoz9oVTG9IDDcPmlQ5kSz2j1vwcA=,tag:OkR57MJPyq3jmqymTZCdDg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
