apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: immich
  namespace: immich
spec:
  url: https://github.com/immich-app/immich-charts
  ref:
    branch: main
  interval: 6h
