apiVersion: v1
kind: Secret
metadata:
    name: stirling-pdf-custom-settings
    namespace: stirling-pdf
type: Opaque
stringData:
    custom_settings.yml: ENC[AES256_GCM,data:AYJHxwzZSKJD0E7iqS6yl/khiQhSbkNiB7r8Wao8re0W5G9CGbZjBi0bRVTuLVUSV0YiJZUic6Mu4SjBD/wo8//O9Deg75LUEZaX0o0DiiVzUI1Ra45zO7nSBfpGnm2NYL8T123S+ejHuv/gDX7nCf/3xG2gVdfjLYkeXNB80pK4iUv1tAO/MpC2jbwOotTusY+FfUZztnum5QR4jD38CpsOlP+6uq9NsG0oTEhtNtLBQbLTeJn9XPs9kGRjyngXayOkmHLr51xXpgRkub0gX+DuvBytbiE/PT7VKIqzyVSG+0tsDsGxoi1Suzbhdu3+6JMyb2iaPOCXiW4Y9vAB7PazLayAfoiMvgDcVsxrV/XbjjloO0awmi3CC3YWePuvU7xDWRGsmLr/GQQ7mIjop6Oqb9EbKlNjEbefp5wchjIJEguZqRe13XxARDM+nnv3CE5eza346tk07R5mN/mToj/Ql7eJhVbgIXa47PAPWu0nzCTIA09PkbgJZEOYtNBMVVKgMScADDm3oCTFhwYHFzmMTiK6hPsrfk2DELKwosKgw25CGNc1LI3Y+77Y7nkdis9ZTsADyt9880WyS06A7fYlVENO9wHoiK8vIelFPrKF,iv:HmLwzeGFKOifYr0aEM9j5qcFBTpLi8RgG54i4DTZ2hM=,tag:6nyZBhRTS2moD6u5fbEikA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMGt4OGRpelRmV3pTRDUz
            SWpGeFp2VkNRemtpTER1ajVlMTZOYmJreGhnCkM4dDIxOHd2bWtMaWFvOXZIZE93
            MnM0SkZBUlFwdDZTYkV0VmlHU3BWdUEKLS0tIGtUcHVTU1g3UTJneENyM0FkSDBJ
            blZ2bkJDWndpU2lGUEpEYk8ybUFIZ1EKhvAdaWps2etLCpr2vmLK5A9eBSObQcO4
            X3FEGFExnqhdgCh1WQS8EUhkc8DprRZLXWWnGKA+OYUV7cIf/cfJPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T12:30:32Z"
    mac: ENC[AES256_GCM,data:5hc6FkpVdcPx/0mg7Eqe8E0Om6voAEUHxI5zlGZuaUyD7CYx2mtjzAnbu8CNB7Zk/ISu78Hc5iC64u/NaLN1cPRbWOm7bo6LBRpM9xxkAsuOYKTPQG7ETWzBw/P98ltXJyymdosbOpcFXcxN9wMUGpmAyynP+hAswwtqaKOl878=,iv:RTcxxMaOJSW1YJZPtnQJA5fdoDejBe6lHrnvUF5R5Og=,tag:GS/xEWMxBAHqgs/zq+feSg==,type:str]
    version: 3.12.2
