apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: stirling-pdf-network-policy
  namespace: stirling-pdf
spec:
  podSelector:
    matchLabels:
      app: stirling-pdf
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Internal access
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 8080
    # External access
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: cloudflare-tunnel
      ports:
        - protocol: TCP
          port: 8080
    # Uptime-kuma probes
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: uptime-kuma
      ports:
        - protocol: TCP
          port: 8080
  egress:
    # Authentik OIDC
    - ports:
        - protocol: TCP
          port: 443
