apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: homeassistant
  namespace: databases
spec:
  mariaDbRef:
    name: main-mariadb
    waitForIt: true
  name: homeassistant
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
  retryInterval: 5s
