apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: homeassistant
  namespace: databases
spec:
  mariaDbRef:
    name: main-mariadb
    waitForIt: true
  name: homeassistant
  passwordSecretKeyRef:
    name: ha-mariadb-credentials
    key: password
  maxUserConnections: 20
  retryInterval: 5s
