apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - root-password.yaml
  - mariadb.yaml
  - networkpolicy.yaml
  # User passwords
  - ha-password.yaml
  - discount-bandit-password.yaml
  - uptime-kuma-password.yaml
  # Databases
  - ha-database.yaml
  - discount-bandit-database.yaml
  - uptime-kuma-database.yaml
  # Users
  - ha-user.yaml
  - discount-bandit-user.yaml
  - uptime-kuma-user.yaml
  # Grants
  - ha-grant.yaml
  - discount-bandit-grant.yaml
  - uptime-kuma-grant.yaml
