apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: mariadb-metrics-serviceaccount
  namespace: databases
spec:
  background: false  # This is for admission control, not background scans
  exceptions:
    - policyName: require-non-default-serviceaccount
      ruleNames:
        - non-default-serviceaccount
  match:
    any:
      - resources:
          kinds:
            - Deployment
          names:
            - main-mariadb-metrics
          namespaces:
            - databases
