apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-mariadb-password
    namespace: databases
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:1zOTVhT94TClivFGdjgwESOpjAXfOPxd9zKo,iv:ABRytRsGtdsTIu8DeWXuLlzBprZeFsWdRe1IE1tFB4o=,tag:fki4CaxUMRq6y16EfbakkA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVC9oN2Z4NVVQREhzODMx
            WmpMTng0ZjlPRkVFMTRwMHJzdEprOU9mcDFRClhMbVJBUk02OGI2VXhoN2VFVCtj
            akY2OEUyR2VkV1U0WW5PYVQzZFBXTXMKLS0tIFd0UTNtSUJxWFk0dXlKMi82QmRG
            ZWs2UjhUWTg1RTkyU0N5UXdoSFVHdmsK9EGJESFb3xyCEg4oitXaBuxRg4b2OkCa
            AW/1bAz0HdrNtvmez1LJxzQhBMvK6hp92WudObEBlM8UBO+UQ4Xy7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T18:30:09Z"
    mac: ENC[AES256_GCM,data:ffzq40zKMq/El7307/MxEe74xqXG+Y4HGlahxcHuJ+LTmxWwvB1PceMsQsk7p/ho0zWPK8jXd/r0KnkPGJ6ctkbqedkkcqXKpc1ZnFr9aH7bqX8IZv3hw+yw+ScTlKlN+/O7dUH2W1yoIVRg+fUH7W/PyOxkg3bYoIR01EKfEvE=,iv:svHKw60t5hJoFCOpXGn8cp8ECwkVZo99E6GqJSsMEic=,tag:wLCduEUovQQZtuwi259AGg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
