apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: uptime-kuma
  namespace: databases
spec:
  mariaDbRef:
    name: main-mariadb
    waitForIt: true
  name: uptimekuma
  passwordSecretKeyRef:
    name: uptime-kuma-mariadb-password
    key: password
  maxUserConnections: 10
  retryInterval: 5s
