version: 2
updates:
  # Go modules in analyze-update script
  - package-ecosystem: "gomod"
    directory: "/scripts/analyze-update"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
      - "go"
    reviewers:
      - "AKhozya"
    open-pull-requests-limit: 5

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "AKhozya"
    open-pull-requests-limit: 5
