apiVersion: v1
kind: Secret
metadata:
    name: redis-passwords
    namespace: databases
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:inzRlsfUMXQX911h5ThBfa5ZuxgaACOAkkE9Cwyk4dLpyEVyHlAh2djfFtHp8cloViuEFiBTPdy7bJFv637M2g==,iv:1gZldzWnXk7p8WXI5d3gXqZFVZTmpg/AYwbVM0EEO4A=,tag:NtT9X9nwZa0Y4c6drGmrCA==,type:str]
    authentik-password: ENC[AES256_GCM,data:G8WAvd9EHf4zLsVfVYa7A5IEHBA5bbXG/tJoAzsYamR5C3TlTLcqreVn0Y7MCEJRGdrJjuxO0dvU7L14xadgjg==,iv:7jqAsZ/mwjsccjVEjuwdRw1IRKKlhR/sCJIq8UvPjvk=,tag:2OgLETEmgrd0gl/mVA5niA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NEtvTTJmbG1PTXZzRSs0
            T21TQXNPemVQaUo2ald3Vi9LNzAvaVhramswCnQ4eEhkMzBGelpQL1NGeHFjdG9K
            c3lXQzdVdSsyLzVHOTFDLzZQL0FKR0UKLS0tIEJQYjIvL1lCSnNsSGJidFEzZFRy
            aFo4UjBUeHhzY2NkMythVGc4V3JpZEkKYVungqVWqqIY1Vi5lGGP8CKMixciyp8H
            ssH3NBlFHMa0rKuBkIyGRW7y/91/q64jLQHzCU+v+y9UmU0YjwjgwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T17:55:25Z"
    mac: ENC[AES256_GCM,data:SHAn5ZJNJWIrJPcbAvIT/nBWmbSsppr/ZjU4amYinty/DMvkrNcXyahkjtDpB/PtlxPlcbRzVe7AkV5W8SJ60TRZhHtrLWHaJOSpcTdSrQqwr/mP+eT+FKvq9tHamYc0odd/m8We9/O8NG9quEj49Up65di09RS96DDeG38ZNi0=,iv:qMn9JPa/8f8Aov8VZQLLMeEwVABU2uKSGzhj3b0n8xU=,tag:LI4NEs99tx4w3dC7gGjtbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
