apiVersion: v1
kind: Secret
metadata:
    name: redis-passwords
    namespace: databases
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:4nk+AYIumnSuEOcU1lrp0rcRQ0ZfA3diQCw7ooIWi0NYaJ0xV7GQkW7BpYjyW4H81W8JckIkQav02RqY7kQbig==,iv:b9fZFD3QiquaCW8kNz5UAJ+poG8lvaHVd0UPWC6qpJM=,tag:YvSMn96MkQ+WeyNbAzYY5g==,type:str]
    paperless-password: ENC[AES256_GCM,data:C4CZicvecEgn9zwdVNuJdDUCyaEjHTrN5aAabshL70XSSXptstO2ywje85sVNjJ/hzY5ReuHUO1C0OjT2J6QFw==,iv:mvkUws6pvAW3ez8sbieRT2isFWoM6noqgCccemS9CMk=,tag:FqYmpudS5dFULzhcOrKpng==,type:str]
    immich-password: ENC[AES256_GCM,data:yjHnqCf4UNKTXfFLQgpAzxGhfv7Jd65Hmp9Ny66z9d33XYU7G/elm05yYETgkwURWDUrfNc/p5P5sAiiRCc+6w==,iv:68oImRefHOi40fj9rdozJ8yoTdzKuZRl//2sbEoxUdI=,tag:LYE6vlf0YW/HvwApOlynjg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaTRaaEt3WDNWZ0wzRjJE
            TmFDaXd2VnhkMERNd2dWVENPUENLdVhqckJJCkpxUUdremVRQllOWDhlVWRWN0R5
            ZHl6STZFR2tkTEpwcEdkSW83cFJkU0UKLS0tIFoxTzluYXpBYU5KUnpHQWJDYU5x
            d1puN2dRVjIvWnJsSm5WYzIvUDdlclUKDHh/2rnszXfbNYdUwT6wOLEZJXQ1E/Vm
            gQDyq5eMUQAoS5r7TKzzwt26mk0sjKi74RmFNY/QBE1yBlYaA7Jb4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:45:50Z"
    mac: ENC[AES256_GCM,data:9XMCbE4JMIT/F0bF1qCzDOudU5J0v6sQvv34WZ7ngMVm+0BLdimni85oHhLFZSLlaiZgCP21QCeeCb92IUaAcRfO5WHtbLjAS/AbjlpjdKuchm0XIV2tddPwiW+tjkZ+Tar+VQ5MD6eW0TiRZltFyR4zqrKeGoP+3hHLZaYzEAQ=,iv:+naIEuSk5XtSDX41Woue2hemScqM/CTwLlTLD9a9eGI=,tag:LX2yrFZ/rcmDrli4kLzCLA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
