apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: databases
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
    - port: metrics
      interval: 60s
      path: /metrics
      scrapeTimeout: 10s
