apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-admin
    namespace: uptime-kuma
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:HQxycRu0fQ==,iv:DqGBSPaBUYYpLkBFBUGXWzr9O296eKOTaY0pGdSilr4=,tag:fO5O1H+CwpyA2rxCAhnwDA==,type:str]
    password: ENC[AES256_GCM,data:6weAXAJlYo+iibfQ2CqPbhogPQ==,iv:A8lvtkUwbsKelhDs2LAE4hxlNcRF9BSFaETx4KnD+xo=,tag:jC4PDqHRVP8uf4Avu6M1vg==,type:str]
    totp_secret: ENC[AES256_GCM,data:n8TaK84zTeBCgKK54jYtbl1XU/JsU/U6yjLMPitaIkB62yNs95JLo5infQTDr1Bb/F5jdsteFaxksiF/lLjwnMxBV3Ld9qfkHTzq61Y1NXCsqKWNct8xLkgY7QHxD2rq/YnVzZrMDg==,iv:XFICiNfTu5zvkHqB8uisCd6l/dqWKR9H9iU1C28R/HA=,tag:sc9ciFJ1QMUoeYIdL/yiGg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXd3lBaHpvQW02Vk9CUkNI
            TEplN0JnaEN4S2hUZ0Zvc0lpa1ZyeFIrYmwwCjJ1S2tkSEVCbTJDMXFxMzQxcTdR
            Sk9GbmlqMHR3NU5KOW16WUp6eFp2Y28KLS0tIHN1RzZveVFscVg5N1J1WW5XQ1Jx
            WWdvOW5ORDRWWnd1ZllVNDVNQy9aMXcKEy3VgjR2Ay9Zmm37Kh998cW3vSmKVqlo
            iBVCRCuBkM5q4e7kBeUKcHHiUmNrdIVq4q0oEInGxgjlegr476rkmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T00:41:51Z"
    mac: ENC[AES256_GCM,data:DQTPtGNDKcnlmDUxA5lm2bXg9v8Tvt/OsuCos+HQVGwc1K/TBobFUNC9BcTL0r2ZP0+70oyw4F88tgRo+jXFwhfCBDvQgY2EGb2t/vGZUngMrRw60Gk2wBO/D57r7ISnTK52kivCff9mjJb8y+Rym9GVi3LGAtlAa4EY5leFi94=,iv:Wkse0FoB0EIHqMkTi7vz2w18Tn42DgcR30tFF4GR/Fw=,tag:V9vXQDy7madXUAqagkLJhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
