apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-admin
    namespace: uptime-kuma
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:uMPTK9YLSw==,iv:7BVy+EoUF6R9G5K00l49JqXar1zEK1gCNeLxy9r2T98=,tag:iMBMKPp7XS2Ez3gEeCMmmA==,type:str]
    password: ENC[AES256_GCM,data:Yi/iRm4wcV1k/zvv1sTpCn/GrA==,iv:r9BXTHdMbVFso9o7MGXQ/F6Gj16z5bPz/g/UN61uBQ4=,tag:jZ3LXdMy7GSx6OulL/vjqA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZWVqeDBvKzl5cW9BcFFN
            MHVFRERCaWZmVlZFWE51THZNOVloVE5FK2p3CjRvN2tpcm5nL25ZaExiM1kwVkJY
            ZTAwcEZhQlFjVWZBaVZqdUs0SHhVQXcKLS0tIEN6ekFzd09NM3Qvc0pLTER5aWtz
            blVZcmF3YXRMbEowL2dBN3VXWjNqVEEKaQU3KqfhKRxpITjDpU4W5mzYCxFbG6f1
            l4U5IE3U/ZoKN5SbowEjTKRp1mpByRwrsPHgL7ou3hiFACzcWYegaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T00:51:40Z"
    mac: ENC[AES256_GCM,data:VSuCNqS3dsHSpm1KVxvWTekb27TolZg50GF8GypkQ6OF8AUxMJEeHIngVbCySrYyczx0Sh4FHVNVDI8WS33X1TaZaLKZMMCZrUrmt5Yj4jIrFW9cmaI+qhvfaTrNjciYe6RgrJ8sI1GLbKKibdGOb6fwS8ajCwFsN7aNsA5a4H4=,iv:/BexB+qSfH64zBKhnnc1Lq10yEifQ+cG3F3bDZM0/NA=,tag:+ChxnCIkiL8fPdN0iZkYZQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
