apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-admin
    namespace: uptime-kuma
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8svCxFY5SQ==,iv:VsghzkRI3HM4AVJ8sFR4iMmGurxl6nffYx5ejetSYsM=,tag:hkZb22SKCVaTefBVvB5z5Q==,type:str]
    password: ENC[AES256_GCM,data:lHGQv9DIEAwHBGUX3YNqYTqsjQ==,iv:z32M7hx1Y4VnYUMAn1tlwAUR195o27zjrX6b4i8QJcI=,tag:jSICVeAKJ/H5b7wBqmtwHg==,type:str]
    api_key: ENC[AES256_GCM,data:4MKZNMwuserKGF77AdFLrUNdsltzmdUlhsphBVM81gLEO+UL7C67OWR0ZhI=,iv:A3ZujPKrIUV5/Gzjm8j5ECEwKbgBQPMRkztRC83bL8k=,tag:9iKKmM6n63aGaqTEkiYMYw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIOTRIdy9xa0JGV0t4TnZk
            QnhFUURqZWFtalJhRXdSWVRHbXA3Q1ZWNUdFCmI4eUJwMWx5QXBoWkNTOUptaWU2
            Zm52b0xZbk9xWVc4YjU0eVFSNFBkWmcKLS0tIG9OTStmMU9OS3hweW01cGp2Mm1v
            VVVEdFQ1T042aHIwT3Jtd080L3krWE0K3jCUYar4Sjsa1wB/vu5LTXPfN8HJEoQh
            TIUU1LTseJ846O+LHwfgF6qQoGrmX8EpNK/HTUgHEaKBqa1uvb9yYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T00:32:23Z"
    mac: ENC[AES256_GCM,data:p0ED3463VvrOxRDdBhiW/rnv4UxgguWhsM1GodYYdSZlw/z0U20PkTqNa+PP9dgZUzJnvTC1D4QM4QoVCCHkVaiyuAnFigq7yeoRciWWfGgmPLV9ltr036vCxKn7qNosSTSqoVNSJqcH+Fy9/sCe+CELXk2psyjR7pkdXZQ2ktw=,iv:fDGNJQE8knszWh9DbujCeZSqiNoDPxcahK6J1IUKeuY=,tag:SQ3RwxDsOgZAm1qhIO5j0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
