apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls-cert
  namespace: authentik
spec:
  secretName: authentik-tls-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - authentik.h0melab.work
