apiVersion: v1
kind: Secret
metadata:
    name: immich-admin-credentials
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:5dTG0fe57GolQAomTJOKQzRMhZSMmDgyny5zwmfSHrs=,iv:CqxurDTmP9GAehGyfvRc/j9xEGg+L5nKw8eFVg7MVGw=,tag:V2aNkNrafSBok0w7H7RLWA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaFg3TlJzS0Q3SHA1blFn
            bTlxd25LMjhwQkI5c2NiTUlpR1liVU1BQjFjCkJKOS9CWGs2NlZacTlLWDZqejR3
            TXBsajNsQ3lGeXVVQURUNkhhdVZmeHcKLS0tIDRQOGxDSTB3WXV4bHA5bmFSTUZJ
            R3BHam1IUkt3aUl0WlpUSURPU0RJL00KCCHnaXXNVJ/jh2K5RNJAFLrKIZzG2OSj
            KUSpv3Ah/b5ODN0lkMEgxRaezk7KpoK/fIJz/EL30QaClhYGUJ/N9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-19T14:02:35Z"
    mac: ENC[AES256_GCM,data:0qupPSK83VEubXDSoqjGSu2oHdv7W9H/j1X0s7bja7KZIRqBdNRQMix/5p64fojjks0De226f6c74mLRmDXUbKq/lHkN1z9yLLrhxei03NnIdS8SW/H8uD8SAmFj6R/3tvSBrxYukFRvYtNqTAysA96xJkN6f5KizDynqFuBkFs=,iv:YkYbs7EavrJmWpKPKAMLhndA5BSf/TePtdEh9gSOASI=,tag:tHbz55iewBm5G1Sge0FVxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
