apiVersion: v1
kind: Secret
metadata:
    name: immich-db-password
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:j/82cYNFTIuA71Mfjh5jimf2uhigavKtWYB6OfgHO/+M6ECOBcAqvA9iaKLrpwK8m/eEu+eyt9jJ6KHlvXsiwg==,iv:tOYLT+4A2oS16rTScR2h20WzUdukZ6v159qQpm9iT2Y=,tag:I6AQD4sNkjc5V2xGcitqVQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRW9PWDVYWjlZTklEK05s
            UmgrVzhaZjJ5MTVjL08wQVVOak1YM004RTFRCjZPWngyWGYwM2c3Z0dEc1dtWVNW
            VHVod1F3cU0wbkNwMmIxUmtQaFZzQ0kKLS0tIDdqVEQxc1ZrRDJDUzJ3ejZaa3Yr
            bG1iYlVWTm1mZ2FaUENxZHp5bGovL00K9KbJkMUvaqOd6DERI/2FGT1DBUXzgc+W
            OsXpcQR5cY+D7WYKD57LviROXTXpCnQHSy1YZ4utpv661IQZ02l4Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:40:49Z"
    mac: ENC[AES256_GCM,data:QstXlnz7C7t0LR/W75g85267kfptf2l2XyDvkrB28GzwUuUrCxcTFTI4aegW2pJ44pC68Cefg78MAwiylhICoM+piq07rinOiCR+5aojLExpWCRWmwLdN5fp3Zw8SLCT6gKbNd/+U+31041gddWKQ6DWaUzo7qeNuUdsg9GGVdY=,iv:l+EsUBgwp3H44jZJDy+iLTt0wHUm2PHVFSDTn2J3Asw=,tag:IFmnyc2AZ84jgY/IaZKWNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
