apiVersion: v1
kind: Secret
metadata:
    name: immich-oidc
    namespace: immich
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:Xo7xF7Dr,iv:hoUSFGC8u3ld65IKmtKF7/I1aAdbCBC9E4N6tImkJe4=,tag:oYwmDG6lI5dbxHfmm/HLpQ==,type:str]
    client-secret: ENC[AES256_GCM,data:/FlevS/dbC4KJfA+NXF0EnIsvDbBOxHmKIV8fMTwKi3DVfjP140DVpQchpILziffpcBxW5MDWTS3E7xcLrjvMQ==,iv:BotjPREOOkhK1fb3t3lkwenz4OUhFmKkwbad+ZkiTVw=,tag:3YZHbmJ3BwvX0B0o1pBtAA==,type:str]
    issuer-url: ENC[AES256_GCM,data:9D1W14bl3pBftEQYPe4APMGR1rHFMnRhRmKvornr4eKgj7qHwmsmHE3E1zMCptnIgf68Ew==,iv:sKq0bQs30kcH7iiNBvq6vecYHEUW0NBX06sFjvDImoM=,tag:cSYfCndnH9fksqQOG1aCYw==,type:str]
    authorization-url: ENC[AES256_GCM,data:Bfub1q2j/otXXlrk5vDNmPQmfidBarWNHjuJldVDdmvucH6lh2vOpkVl5L1WVDze0FOvUtnLGQ==,iv:rZmohkyiY8RgV/DdXDGn9pLetrS71qIi0NonZ68ivUs=,tag:koT/nV1EwRIjzzp3lgmigg==,type:str]
    token-url: ENC[AES256_GCM,data:rav2HeymhAN8LPIYlpbqEkVJl6yAMOxaHTNnXcy0ff0F9eBpIK7oqyJxlEEXowZ6Gye0,iv:Z3b1TVB1+BCTLcdDMGiv/graJc5XNo5KffBcl5mp/HY=,tag:QHPPpzKcOqbm5C94+4eXvg==,type:str]
    userinfo-url: ENC[AES256_GCM,data:n6SrC9/hH1RtSNWYhCQXFT/rRN548i3ZlhV9n7qFHfiFirZ2lmCW6N/yjY9aSXWLUqfDoE1U,iv:I3lqol3ySkguaf8gOi/+qZWgIzOp15V7uTpgUHQCPzQ=,tag:aK4+MEymlV0NZ0NVSF2MUA==,type:str]
    jwks-url: ENC[AES256_GCM,data:BoaOQPrcrXNYFtPTjmv5LpudIn+84isBAIWGodgqWJmEtBxjCjWGvypLcTagTkm8DoKM9kZZpCBB,iv:bsu1L6ytb4/am6fcv+7UkaTCajik8aXlBbYwQ/SW2d8=,tag:k4ehvQx/wAMf7j7mMJD4qQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVWhwVGllZ2hBVEt3VU5l
            a2ZQYWxvNDJuUXdROUlLc29xdFZGakc1UzBNCnUzaDcrWTVWRnVMVU1udHdHdnpB
            OFZJVVdBbzlvYi9sSHpVQTVWV2xUNzQKLS0tIEpoRWNncXd1TzFoalB5UGhKeldM
            MmlSNlI3a25YNzB4MnA2R1hnYUJDZ3cKEbomn9tTkAxAggDV16WEUu8tU8oZmiCd
            6lq0Dx8bFaQRlrLKx7bZ8Ehz/y/brZVRjcLgbVaqDdiP62iOy2SMnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T17:41:16Z"
    mac: ENC[AES256_GCM,data:jimJ1CVmI9JitjqOrh++folR0/eixwv/1f1Qcy/AUg2lZuzsI7ACjbERZMiYboH5ALsE5yZClAl2OJwkHL9LjYhk10u1yPgC8c4mYzNFBfrgsRcEwaojoBD0j1u6B6BMSan7mcYQyK7uH9aMFCfRS8lVoWrm5jjOs3rKzBhAkVY=,iv:fgaZZFg82WxlfAVK3sc5KrvtwccGRdFzW2AaRHG00AE=,tag:iHIpB1A/gFNSfcAFNvI45w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
