apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-password
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:8c1QRqGUbCEGjLGQWLLvg+zgLkbxBDg9xo1izP0jVIo8ZwXKMG9GMrRb6Tg5ksNoW6vX35h6GAS5ZsmSZwwbQw==,iv:CseqXj403d9GNErMuRDnCd+afPXgNBu7YzN4Cw5q70c=,tag:6iRBPxH6e1jqWELrV0PjPg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbjZ0c1Q0bmR3a3k1T0tO
            RTlHb1NsU3hyd0p5bVU1SUhhYlltTXBPWmhZCjdSWUoza0lVaDdldVZvMUN2WmY5
            aU1RUDB5alVjZWJsM3dyWlMya2NTQ2sKLS0tIDJ6WjM4ZG5wbFNwa3hTUVBMVUFl
            S0IvUStvaHhjL1ZXOGQ1MkpnQlBWTWcKXtMeq1L637rGvEefFwNAhGoIlvGJwivT
            Hva32K2P7SJzLuDRgc5VD4qEpKpor8Qre+xvApJVOcbGGf4SkOuspw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:45:50Z"
    mac: ENC[AES256_GCM,data:G647t/oPXBFsQaOaKbB7ElxQpavGyKFSM3l6dtviYbgVTVoBtP5xYaAqtjmFupnlfD2cds20AzRQuJU/+afRmv9u7SOwDCoNAgH32CRmd2kVkuqHZqxq3IPnBcwbLiqobyv36EPeknI8M2l6Z8Z69vvRG9JTRYU3ibeFRZtl2aY=,iv:VYf4lZRU0dXzJRb+NVa77KR100eOj6iorwTXGhIvlgQ=,tag:yzUQKSYdT2saSwDmlj3m7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
