apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ../../base/immich
  - immich-db-password-secret.yaml
  - immich-redis-url-secret.yaml
  - admin-secret.yaml
  # OIDC config is stored in immich's DB (configured via admin web UI)
