apiVersion: v1
kind: Secret
metadata:
    name: couchdb-couchdb
    namespace: couchdb
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:g2M5Tos=,iv:sP/kqcaSsXAQGhms9mSrE3DleR1C5ZDfHmYKq/AAKG0=,tag:s+HvsvqJ/B94PIunbLfy7w==,type:str]
    adminPassword: ENC[AES256_GCM,data:yzwYdDxhdZI+je9qYoIQf53xKk5KPOhJgK7TKt6KwlpqRpYZGqH+HynruTo=,iv:/YLgDNZpfLgf1Fps/yCXR4hZhopMkXVl6Z9CDBTWJSw=,tag:B9XVVwT34rc8VvXY7IsxpQ==,type:str]
    cookieAuthSecret: ENC[AES256_GCM,data:tOPdqO5SFEiz/HzmXWUs4+x99SMHc4f+COtdGKQGGYqkjuEyI5U2flbPaO8=,iv:5PDAUW5ctYRTHHOvHd7wXNXWr3QfteTfti8KXSrOLjI=,tag:+/MydOKPZ/xvznlEHzRN4A==,type:str]
    erlangCookie: ENC[AES256_GCM,data:OyaJbWdW37Va031ofIWcJ3xEVTiWn8l1X3oYGN7EQtmAwbIrRmONPd8RcFY=,iv:nO+QpMatElTkfvcMf0HMhqoqC7TtvsdTgvZ9hj73aUM=,tag:ki2+7DaSkRZ/z8IsTm7zZQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MDljOWlJZ0dVWXNhcWRC
            Rmd4cHlYcjlodHUxdlZ1OG43TzNSNlA5eTJZCmN0UCtOR3FOKzh4dkQ5R0NkWU5T
            TkwwMXA0cGwvZ0dQbnRncnVGcFkvdzgKLS0tIEc3QVBJbGc2aGVPNVcwWGNDaVJQ
            V3FtVFYxNXhqZ3ZvRUhVbnVid2hSTUkKQv95UA+qTj2jdTZl8Cde/KGE33bB3VzV
            YE90T9Ft91WcpQgVi3vS2FfBF+HNPKkTIv2Ai0LKu6I5js1k7QFIKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T09:25:46Z"
    mac: ENC[AES256_GCM,data:Muw4CAhXmHxepYxGsrY7Of0liRCUsCsorntn3ZJxAjNNnrQR4en/Hy3GgOUPDu2gBd27CU+0V5M0gHWXSSOV5QKo1oeEa7+dIFiBcK92DAKmLqQ6RFyzDrW6+FvKeT9GSJt2S9rD6huJVfkZYBgQ93WzZOBnyFblAStmC8Aa6pk=,iv:I8Slo1wsGs7DGIIjhlTJk1N6oWDCCWMGyIgL8vqIHmU=,tag:26f58+arJl0sSknu9Euw6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
