apiVersion: v1
kind: Secret
metadata:
    name: redis-acl-secret
    namespace: databases
type: Opaque
stringData:
    user.acl: ENC[AES256_GCM,data:hQpzOOK8qBaA9fg9pXIYpljuiVa43HyxWUZ/xL/1rsTO9NKwUBT05FHblkstzxgAhHAhi2BgEmNZZNl/5oc5/g1xlH3fP84wRcGEDmQDpBlwNJDgsReyesjA+72TnhQPY1eP1s9IYYaOEVspeU9uAnNDq7UY5eHVlcj1cABV9t4Z+5BhbhawFGQLivFJr/fHhW0XsQGiEUFjI2r+K69cTyeQpjZ1aRxpPOJELbZ+HVGSzqD40epRbwLyky03oS0dyfg0Ww5FFlpY7Hb4MRn8OWJip7xmft1Ul40bwOVpfk89nrd9uccN8UnaoktMy0/HKbUBEu9yqnYOT/S+QFvse0VtuvJ3NMRwk3/9Sm76x7zuuWDNzMB6rk38mCHKAlvFNzXlSlD6KF3cH6lAOcg3ETln/kiAip+LsCl7G3F4OoDz4JqVzggJBsrdUHKB8SeQgUIJcLag1o7hZBCJJ2Ez2KncoLXpu6zKVsQWlyXQfhhRbsaWVR64sZzk64mYVGRO5EutGQWLGye7+zKvulyNMXq80wxxmVgu3OIdaPr+UywzN9jDUtdKhrjVkn5eFjE0NADIbNbsHnLVIeSscxI0tB+PvNhZPqmr5gJofPatfuRtjKsgIGcTNxL8aJ0=,iv:PrBE0lhcsVO0ET4l4cKZaqjSQMv7s2o5cXaogMk5P30=,tag:gTB57dvpIt7ODQvVxp1hNg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMzd2RVJodk1UVDlGSHRv
            RG9OWk1LMEE1WklhbEJGY2JtU201VXVOZGxJCkZicU12V0NsaGtGYmVSMDdreDRG
            djY4K0t6REJHOFdvS2laTlUzUW1UTlEKLS0tIDZZQ2FReE5iS0E3MTFJSmxyVFVF
            N3R3dmxYK3lWNUNIZWQxYlVsOEI0NE0K5D31i9Wx5mz4IlBrZA32bHxuSUK1Nd/n
            K/tqyW3yoSmFQeTCJJoobKWXWF6SqAmSss7x6ZA7yiZagvZ6COv/Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T15:14:41Z"
    mac: ENC[AES256_GCM,data:hB2Pq/1FjwMa5GGBoPFDiFo1OjKnctuLA6bWD1nD7gBbysfT187P+DxsGTtFrNq+2di4jdqCBV6Qrlx+eqpEp79iQX7v6PeopF7yilMqgBtAi+AAh7Ah1fPfkOAFh83XNprhM/bkvSKEs26WeD3ndOd2XovmHQX7YwrGL88MYAM=,iv:sNQIiEDRlgmf3Mb5+Bnt0koO4H17hh33gnyODREttjg=,tag:SIcgm22XTL4TmoaS27oCNg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
