apiVersion: v1
kind: Secret
metadata:
    name: n8n-user-credentials
    namespace: n8n
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:uLLe3bgMdVesQ3Zq9U7A5y9BulKXdSnJmns=,iv:uB+Orwul0Gw//HtVh1m/dZHI4sT8oDOqeoXnsTFJ3fA=,tag:4bPFqpi6BbsA3jRu1rnE0w==,type:str]
    firstname: ENC[AES256_GCM,data:rfUofxwOpJix,iv:afdMvB4fbcrF6F7rqudGWQ1Bi/OmUPdz689Ls3qlFy4=,tag:EjClJMknQKLbD8rZ20MbDg==,type:str]
    lastname: ENC[AES256_GCM,data:z1qdOTDb,iv:TqYiieO6TrdWfknpnmj7XxU1+dv8fg6eFTyu03Gnfr8=,tag:Org9YP8Q7PPHaOz/6Kn6og==,type:str]
    password: ENC[AES256_GCM,data:XVKRWRKqcJPsq+D+5YnkPcOdxYNr7saJD0G3PGgSY7M8wqfaYD8IisltJjc=,iv:/u3PrPe6QsXJeotOXPNDRmpmWUY8L0qjf6KqVoQJus0=,tag:/fEb3zC2XaQcYg+P4OWO8w==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WGFlRlZrUjE1cmdkQ2pT
            bGtYaUx5aEFlUDN2b1IvSlYyOFRYVnlVODNRCmhqWnEvQTBFRG5xNkU1aGYvWjdV
            UlVMbWl3b0JSTjE2YjhWRXFROXdYc1EKLS0tIDhwNHMrd3BTYThkbXBjdnJSeThU
            TWY4bVp6elNSTUNBYlhhN3gyTEdhaHMKGAtGnjiBpIN1iANbYvraYq8p/nr1/DIa
            qfkL3Kirh5fWRZMJmL8dogi2+Lbvmdq/KN78QMw6/rCNlDVBkrwRfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T15:15:32Z"
    mac: ENC[AES256_GCM,data:db4ihMAtX/xdRPzSrqb/m7y7QLQeP9Y1b+nbZ0j4miwmbjK/jiwCkfmoewlUJYnOhMR6ONRC4Du4fz8tzxOFskAUMuBuoH7W0RojY+QRifMRS1W3wPqDuayu7wAjuR86hVW2F/F+zU6fa6Owduu+r5QGaDYffgo8Vg+1tBgi7TM=,iv:C+TkZF5UeiterjXfULqt9EDE72j0h1Q/3U+VLN1QrfI=,tag:WuYXfysGBZRmDTiTPtr3RQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
