apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-password
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:o1FzIOuMej8+b6a69kPGqxQxjV1gcD2lP7irutzWi7U4++SWpEfvX6Mca462JoMFzUF+XFDk4hXeO9zcXigqQw==,iv:7vQVjiRy3nkSh086kz45T/9mH35SLwu5+cmoa4Lc+mk=,tag:cHCIvxyaWkyGoCwo0sUIdw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbjZ0c1Q0bmR3a3k1T0tO
            RTlHb1NsU3hyd0p5bVU1SUhhYlltTXBPWmhZCjdSWUoza0lVaDdldVZvMUN2WmY5
            aU1RUDB5alVjZWJsM3dyWlMya2NTQ2sKLS0tIDJ6WjM4ZG5wbFNwa3hTUVBMVUFl
            S0IvUStvaHhjL1ZXOGQ1MkpnQlBWTWcKXtMeq1L637rGvEefFwNAhGoIlvGJwivT
            Hva32K2P7SJzLuDRgc5VD4qEpKpor8Qre+xvApJVOcbGGf4SkOuspw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T23:49:23Z"
    mac: ENC[AES256_GCM,data:fVnSjkao2FWywehc1N5FBWFRb9xhBZulIVjmT/+7Fi+WVaqjWE/atwNDOn7X4ylMk4l0xw9nxXf6D/RJLHCkiay3UO0xC2pj84+L2VR1+Gi/DbRaX6RwUgIKrHjz6RmGbUMVbp/ulI6it4LSuMJ1sdr2LIvTM8ZdmSw6bH+mmF4=,iv:/upkgLlhQi/HuZHs0kQIB21czz83D3NaU7hGpq0AD4U=,tag:FZbaTJZ7WxCIDbwgUOxQ5w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
