apiVersion: v1
kind: Secret
metadata:
    name: couchdb-admin
    namespace: couchdb
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:DAVEuh4=,iv:ki6cG9xRwoZm5PCtYhpHavBUBqn/tFjkTsnXsKzzA8g=,tag:YPBb6hTp3QKBlH16XQ4ekg==,type:str]
    adminPassword: ENC[AES256_GCM,data:zS1J/wqSFQUzVvq2to85eBe6Jvat1anegjUfyILTPOUXPXEYTKFUXKb7Vt0=,iv:6lwL8xm4oDU6oeiEfHr3zm1sP7orerKMYyfik1dhfGw=,tag:ROpJUEzQNSscY51lq2XFZg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ampPQ1dsWk9Gc2cxSGhT
            T0tJM24wVkNsQ1VUTzZtU0dTSXo5dzlOVEZrCm9LRWZSNGRhMmc4QXlxcmJOcUM4
            b2NJakhUZzZVb3FPY3dDUUhiL1VqWkkKLS0tIGVVekk5dk1ZRC9vbmp5RW0rdDhN
            ektoTkEvT05wcDdDblBLLzJybW0wUU0KLLiwk0qU/uQY89vrGTJDch1e3O+I+OQ7
            H0LM/9IkmwDds3AuR8su/bsdjIfZDmsmDjidFqm0qd9IyV1YqyarNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T21:42:03Z"
    mac: ENC[AES256_GCM,data:zY/R9U18ehfa2szOsqaQWnKm0p7SkMjYRWwyD0ufR3ntcoNYILmsqPV26ixXzgOhO5st0eMDQDDCBpaQckpDl3qpaYXI/xYQt4GGRejf6XmhleY5EVpKzz7zF08w7F1sWJLekml0T4FV+C9yx8mBGhsP1xdokEI++OKQHoKOugk=,iv:Dwot1yj24gCRe9isdQJj8Nhn6ek8LvNKwI9aroZG15Y=,tag:TF1G91dVO69BkCOJtV3ZNA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
