apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
stringData:
    bot_token: ENC[AES256_GCM,data:nYzj+LE231yLBR5PdWe+ZK0QcX50J1hDwPsKPIvzpo7bZjfK7p+NrOIuZnrrTQ==,iv:l1Z23bOtSHF6VHoUEfwepAvtgPEzhRKmdvkwhBxjroE=,tag:WNhRHf6Hnz1pJoD3shIbgQ==,type:str]
    token: ENC[AES256_GCM,data:87oNOconzwJ6H6CAAkdln/53ZWBHkO/4J0Uy8atRLhJGGcQp7mvFGdRv7UqWzw==,iv:MQdgsmdUH/mAcMTbD7udYaxipEEME4qRYFaOht2iUsY=,tag:eVoSmehHfJcewZormP0mAQ==,type:str]
    chat_id: ENC[AES256_GCM,data:1leJpO+3ko/S,iv:jegU4HY8hV5LmamYgOjmf/OvGL8DrzGwFNViI/9oUpg=,tag:kL3lMbq79mvx4x0oeJS+pw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUGhDdkdJb1kxZnpKdnpS
            ZU81ZlBhNUo3Q0F3blg3eDBZWmxBU0ZBQ0hrCk1ZOUs0VS91Rm9MbEtrSCtrb05J
            bENQRUdDZEFsY2VSVS9lejlocHdKZkkKLS0tIFFTa0diejczZVNZbUZXdXBxbXB5
            R2g5SXVaYnZPL09RQlBvUjFmL2Rvb3cKw1FuQQxqCd3o+IdDtmutGsZs7wzRAIrW
            abQUftpCkU3HbYNKwBOsqK+9smBBgL9ofapRApzP96a7gpS70z+Q9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-07T17:07:26Z"
    mac: ENC[AES256_GCM,data:42fYLr5LWO4xMAo3wv1493MRyZ5evK9Ad8q9pLCsPOo229M6iWulRoYn4+D6/pw3qI9ZDWjGnLfiIiJueRo1nKQ5zRAvjzY3kxiwViV/t3XiEEVJDQL6PG/hLCNeSWKdjqrHzVYvmzCLnovUbsIRiSG+B604eVhBuOUHgegq8RY=,iv:8Pfn8suAzxotlmv7KZ7X3ZN1i1WuCY1rcF3r1o1VvAE=,tag:jO1bxuus78slWCRXL83UEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
