apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
stringData:
    bot_token: ENC[AES256_GCM,data:JKnOv70JYOewKmDGFQqMPdp/wKoFygnPUYpY3VJCcXai7J7fO0bDooWjGe8NSA==,iv:icyikzUjUbjKMgmS5TN+d/O7557r+aKjcMHAZH1b5wg=,tag:k5Yt5nOipoJyGWySHR9BDw==,type:str]
    token: ENC[AES256_GCM,data:AUzj9DU0AbO9zlK8UQMFvTsMj/xVk7ffss+F8eL1i6AX7JqYceNCMiyEMPEk/g==,iv:A5hnCQbL5V+WdtJx575cCv967igHRD0utv9hhu+JYvs=,tag:RUQNQkhGV+T22Wp9xDHeqQ==,type:str]
    chat_id: ENC[AES256_GCM,data:1leJpO+3ko/S,iv:jegU4HY8hV5LmamYgOjmf/OvGL8DrzGwFNViI/9oUpg=,tag:kL3lMbq79mvx4x0oeJS+pw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUGhDdkdJb1kxZnpKdnpS
            ZU81ZlBhNUo3Q0F3blg3eDBZWmxBU0ZBQ0hrCk1ZOUs0VS91Rm9MbEtrSCtrb05J
            bENQRUdDZEFsY2VSVS9lejlocHdKZkkKLS0tIFFTa0diejczZVNZbUZXdXBxbXB5
            R2g5SXVaYnZPL09RQlBvUjFmL2Rvb3cKw1FuQQxqCd3o+IdDtmutGsZs7wzRAIrW
            abQUftpCkU3HbYNKwBOsqK+9smBBgL9ofapRApzP96a7gpS70z+Q9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T16:00:34Z"
    mac: ENC[AES256_GCM,data:tSyx9MhQXa6+hLg+3oBOgtpDyaRjdD0rwTpSX2hfRMGLsDMH7fl+hHhk+YUMlbhhlnahAVaLzERoIhXRy2PpcwmWW6yiO1KkwpJkf9fsWU4NFsd0nsV/D47Qc7rh6FIzhRNSmg7e19/CIAutw3an5bPEsNJS7IRMagsmO0liQ/4=,iv:3tqP2BXO6zvRgB7ZfF8FNaGi5ItJZgaauCsF5O+4Arg=,tag:ZZqX8ONbaLmuGp3Oo7TgyQ==,type:str]
    version: 3.11.0
