apiVersion: v1
kind: Secret
metadata:
    name: couchdb-couchdb
    namespace: databases
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:3SMm37U=,iv:/uBAyd51pwasgo9woThilKXdxK07xcMutNa9LfESBJU=,tag:pX1ECClPlroPQlJ//MEzTw==,type:str]
    adminPassword: ENC[AES256_GCM,data:teIkCEcTPZKVhRtwxv7SGn6nLYT9mRWJtyYBCiZBp10RizRrSpKUEw==,iv:xRmpN3OTGBeZHv91ADDR9rBZbHCL8J8WANl6rbWO+Bs=,tag:YW+haRIQDW/NYgYJAh600Q==,type:str]
    cookieAuthSecret: ENC[AES256_GCM,data:hY9OhHubn9uV0ckZwdULde6MF89LbeRR7Y6KVuocPfjkC4lIYbZ82acdsEY=,iv:H1IUORRFOXmD9mkIN53z8x3nsBhQwl8lQR+Y0F0xabE=,tag:9u4bxu17NckQ0QABe1yx+w==,type:str]
    erlangCookie: ENC[AES256_GCM,data:rmehb8jpRISpsom3j3D9DTHuNiH9jn1uqRZ+etsRBpwanWLUJmSIKuYI4Vw=,iv:p3KQHGSdEdr6AQVhzBmBkbHstIQsKZpbHbvbRhFalfg=,tag:qsEhFW1DEd2rQATJJ7bUbQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNCtCQ3pWUnBMUmRzZjlY
            WjNla0swa1pkZ1NwTUg5NHBlbXoxL3EvSFRzCllTd1VmYlRxTlJWMEZ3YzdXdG5h
            VWIxUnNHZUVka052MjQ3aEZuNDB0azQKLS0tIGIrQzJydDZ2bUg1SUs3cDVxbUx3
            M1NkVytMVVV4L296dDBHNkN1eWFvNTQKe1nROJYu89///U+bb64N/NPfi1SHIj3P
            rkc7Rz4kC0H4IvUoUUe22G2VOyietQ9gGaFxpNzP0bZEh+eqafupZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T17:30:20Z"
    mac: ENC[AES256_GCM,data:9Dk/Dq6/QFUXKd7FejijLzPoDu/Jwlfbr0A0U+r8P+eS7Ypgq5y5o4WXF5jyit5gpE6b1l20eaMsHWuzhWI+Wbp2oBDcp0CPHUAKsZgJxZeAGSA1Pn5Y43Cp3L0dAIoSIqOQPAVyiiZbpgWMZHpjyyI5FqaLNdtNuiAo01xtNsA=,iv:yF2IGzyEcP3fIfGZy2AYBIgWXH2r46fJYhPRyIUY+AU=,tag:Srd53le9ARv583xFffGz7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
