apiVersion: v1
kind: Secret
metadata:
    name: audiobookshelf-oidc
    namespace: audiobookshelf
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:Q2J9Kg2dskMrEXa0Lxk=,iv:cdEaAHEIlFNhyRHOlq8mptbPxQwsMed5wHX6xDHitZo=,tag:kUkL76PpV66M4CYoVABXkQ==,type:str]
    client-secret: ENC[AES256_GCM,data:1Z4ZIpaOV3VELQ4ksS1Ufl4+NbuheFQyhB+lFjfcPQ81z9gGZ6ADPU9oP9sHYKL78aBmej63tfeM+hzPX0HJng==,iv:gZhVuYF1W7Ck7AoVbsjmDPf6ANb38fNT0s6RfZ044BI=,tag:1+/6OXvGjrAWJrBomL4VCw==,type:str]
    issuer-url: ENC[AES256_GCM,data:N/dLVA33pHNlzRgXW4lN+eN27tGLWt3U+d3tR/BCI49caTXy9jA8XC71hCQwcw8ddUODSIhYXx/xVIoM,iv:lE284dvX4OTJq4sKweXYrWBFlCY+GKavjzvvUKM9cWA=,tag:gq8/RortBpwWSIGm7f8FoQ==,type:str]
    authorization-url: ENC[AES256_GCM,data:/WZoxmi+RcGxzCxhTOzpBquf1qkOWBW6gfFwyhaa/8VtPKoiItwKAEVgfCvrc1ytX/johXBQig==,iv:bRQiCwjnuX8lD3aVeTsbKBTG50TzlFfRkCbHaJzxn3Q=,tag:hen4G7PA5fMgvkUHsREPAg==,type:str]
    token-url: ENC[AES256_GCM,data:fAi5Kn5HnlldFfEH5N3jEXWbKmCd2Z+QYE3QGf+Lli6jxopXXFAAl3KF5h9IqUiSnJ5r,iv:W0qJyGANG+N5dJUUGMfgs69kLZEH9VRpS29FvHjCa5I=,tag:w+O3n08J1hoYWv4z07/tlA==,type:str]
    userinfo-url: ENC[AES256_GCM,data:sQd7OBpISlL/53d0oNfF8T9UJsF2htmmoVut/DKl5f/Kx0C8fYq3xgy3X8PMY4VDzTOac0Ox,iv:0XFKZZJw+C+VIXAcqXV3/ka7Z22yKzW89N+4MX/xBwg=,tag:7iVFqo53tlA6BBI9Po+IAw==,type:str]
    jwks-url: ENC[AES256_GCM,data:Kpz7Of61bwSD219QnFG1ZCp/HUhnniF7stAImuomYYlRPTHOc7alLjlBDyD0jEO+JNXi4463n4AJpOMVKivGKcY=,iv:+K1MrbegCufrW0Jdt4E+YxH3tB/GCM/j4b/HdQs3s/o=,tag:ASHtYO6P3shJzszh7NN2/g==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NytkQWFMQkFyVk5pVzBU
            N2dxMlFXRGVmYkFSZ0o2SkVLd1krRHBqWGdzCnV4N0t6M3hYSDdtaUdXVlh2L1hK
            akk1Wll3b0tvYzZkZmNkRi9hY2VuZEUKLS0tIENGSHdhdUxrVEtHWi9lLy9helor
            cVgzWEwwcC8zQTJiOXdEdmlPZmFkU1UKDDfjNOWX0nMZx0xZ9p7uTljMHhz+lYRS
            7B8AKn5qh3+dybeKWOneX9xyzMrkDneqtgqgBtlvXFsd6EPw4F5eng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T21:37:40Z"
    mac: ENC[AES256_GCM,data:GuK3uCPzihAtXh2z5afTSXMjNwLqruCTGB+d0yLMQp7dw0HFHtmfaglYYaHtFdLlEdR7vGBora6hSKP1wEj6GLGmVCLuV52qX0olMRvGB4vSC8ex5gsXIX9JIjPRUF2WXjn1Xvqpkp93130X8DCP9L/JUitPVAea87JpMgCXb/8=,iv:lgsgZXLj+e2FgJrzpuY6n2imdvH3cL1VmPaOSBJQATg=,tag:GQ3940eMk/CRyeJcsf7tdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
