apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:5+0O7MPEgHZnu/O99N1M0dLM/17DZxbQ90GLE5UFB1He+ltCm6t8aBdkVsAg7jx1durWfv1erIaKqn5Qi46uwP6NLy/RM68tj6S9I06tcjpbBqvoyVM/EI5Nl3F1DxPUJWhfPbn4bvbDNl+RymJ8ik5bxAVQmavqT3tdeiX8hsKlbDQ3hFRFP1IgO8bz3UuD4Aj9vl8qPB8gYdaQsv37iMoKRlyJ5B3EhHg664kN2vD0/41f/AiswOacrtWdzmFUXE9OIpkfm03PgaPDBQ7GsLpG2XeFjxBrj3BI+QzQ013AJfIP6wdNVOf/LtE=,iv:6eOlExF6FS7AUD4rITQh8oPoOmr38MY1X0C+MJYbO98=,tag:QGIS3K5RUznVYCslbCnP0g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age15wyev7l49up7nan7nwc0lk3k53kmkd37566cn28djsz036d7fqwssfahtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONUxidG1naURFdjdRa1Vu
            SktCNEZYTjMrSzNLNEtWRTF3bGgwMlgxV0hvClA5ZnhOanNBajR4UnlIbmIvekt1
            RFQrdk1kd3ZUT0d5RmMvM1hvMlhPdmMKLS0tIHB1YUkrRk11VWM2QUtrODk0dDhq
            SHpTTjdaM3hwV0RGUDVCdDlvN3AwK1kK6bQLLp7DRw7uDypqcJBEwoBcmkFdZyGr
            pHYoPcd+9NhTPLF7sYypmswch3oXBucAqdIdXRvPy8ZHTYEjtxD01g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T00:45:11Z"
    mac: ENC[AES256_GCM,data:I3UPtA2XXKmllJ0PCK1sLf8hdiNlMDxtbRQBDdkAGc88QKtWxTLOcmzgEU/FejZw0nq37BQYalO8dELgeeztBGbjDEtvHA4hAYYgPkVsSezld2PWHraC6hWf2iXX0fFmV2TAta1bjpTviaYniQP5fUm2aHFyK3LsbBUkSuQVn2I=,iv:VfH4ghTNTIWpYjN9cBWy5P+pAZfo85OnFrh4BB2dRjY=,tag:eUSigNSdK9BaLkTfJ/NYig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
