apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:vZ0pX1//aMDoXt09BJZF4aqjmAdmKJ1EZL3Jelh72skIK9FQT2d+lGn/Q8DZHXBG2UQJ3WPj0nAijXaqBrKUZpsYr+E=,iv:QTMykd8/BImMHPBgrMDGwtuTUo7pzujGVaFkLo66rqI=,tag:7ZZvxviWxVMGoKkDdODJ9g==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:NLdaFpgrbrZeWNplmLkTWE8LZE+aSjLIhyZarA==,iv:NR9qlUXvCx/qjPweUuUGZC1dX5U4wva7vACflrIBoqw=,tag:oYAPnZnBjoEjRCUI2hgS0g==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:IMJ9brDNYNSd+6lcZtJv0tPkgPxjbbo1iF8=,iv:sAdlomye7mZM7/WOCa3c6wzSmA3af/8V3gupUIu8whA=,tag:zgy+dGtVyetBA8WMloLN9A==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:EzZAt6/65zuMLgLorfTU3t9WVRZ4rMN5iUjfc0O82dnojgUtbtEE15TO7xCjyEbapg==,iv:S3sq/Ij3a+q5VirdnB8DzzW1oG7wiK/5EFWGqbvqsHo=,tag:TtOSyBXciKyGOH5dD28f9g==,type:str]
    AUTHENTIK_URL: ENC[AES256_GCM,data:GMEII6CDLj7rCj/PWrijoXPrkxNok8Y5XuxcyMWy,iv:amK13nKlYGf1DRKgHwRwTT4HXzj68mZ+2V1UaFTYggA=,tag:w/1HGvam28eJmr5bn1Sg1Q==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:WwgN/K8V88iXoa1zIzA=,iv:e+ldLjpICDt1vMOtmNOGYXYxCHO/Wu6UlUsB/mFSoSs=,tag:bKtMBiMk4uJLPRsGpj4R6A==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:ekxP,iv:kY55bBX0m1+KKlh/jHKIkj74kCcSfWSFieWjuuuuPPo=,tag:80HdLI4yTZ1SuJaYd22vGQ==,type:str]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:aqgr/4T0pY1fyjME/VS7VTUFINmNVb5+qNo=,iv:m+hulEyHRATfT5IEMle47ZdY/ptJ7Vohb6OqcbNktgM=,tag:uI4KxsgalZ3UA+bpcqVmCg==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:M83fGQ5HfV0T3APWxEzdBHQsHQ==,iv:4uttUGlhSdz20nBkQKfbv7wmYpnOM5Ab/9sdt2Il40E=,tag:OMcTHuWJRrNT3xWRMhd0Xg==,type:str]
    AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:n2zxdg==,iv:vrsY52ZegDQtQ6muVhaQDH4afTFsLdbbVKmK+pydVNI=,tag:LIKqSWDDfwQVJO6wxIKeOg==,type:str]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:RNX1TB+/TWMpH4qb5TCmBnxXLxeRrkfxdbI=,iv:pUMA0YOgDzZUax14f6rOeG4h6oVbWxQ/fgxXgHJelEU=,tag:OurhUqQd5T48p78SBRZMCw==,type:str]
    AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:D54=,iv:P6vmm3EIFU8RohLSFywn5Y/jw6x3nFMbyoI9QPIMeJg=,tag:NTlty4at5gExq62hyGja6A==,type:str]
    AUTHENTIK_ERROR_REPORTING__ENABLED: ENC[AES256_GCM,data:CVIIAA==,iv:P9hofC73+Y6EEfL14pM4JBUbf67Sv+w3Rhy6XFIZtzc=,tag:zB9HsOvQNM7T3akkFRCTnw==,type:str]
    AUTHENTIK_LOG_LEVEL: ENC[AES256_GCM,data:6ikvWILIsg==,iv:5xOkIhp07Z5C0nl8Lo1hRjj4h9QUeir3fDmcCqBkHtE=,tag:5jee/gdjn3B4vxfIyIxT6Q==,type:str]
    AUTHENTIK_POSTGRESQL__SSLMODE: ENC[AES256_GCM,data:FWkT/ySWlQ==,iv:NA3ymqVjVNFGYE0W4hU0cLclXGYZpc0pINdIuRlr3vI=,tag:u6f+5SY7TDeYO4enlhvsdw==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:qaWTx3vSBDd/lr+yNb1BtpoPnyXHu8oCEVFYvAGP1ROHvQE3yTXF4/7BP1dWYZTizqLh,iv:sWEF+j7SxwlPVrIaOjzNex7CIG8IEyNpVqqvhtgx6dU=,tag:6oDw3ZKotqejIuPm+ZqFIQ==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:m7Ph8A==,iv:8YqReKudbjyuc9y+Jv0TYMlPkg/6yoAdqEMdnQh5bCA=,tag:61zYHCJTqb2A1zBq/bLKhg==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:FajOUGQbXgwi,iv:fx+Ilcg8SMYwPlPhnjSQfMQTak2+YTaSSsiXCGUlG7Y=,tag:r5C3nNXhY7J67sA6Z9LAgQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:apKNpl8DZqG3,iv:vDlCejznkqAi/Jw1auc+I9G0N8MugW2A3F9j0T6t6yw=,tag:c4aJhye/2y3gIErewTb7bg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:JdjvsPUY3BbOFKFNU+wAVkEvHknxj2xYS5VrMm59ukWD3YroWVJTGksif15JliG5NfMHSnNLq08Sv1N1G6FtaA==,iv:7EmBy9iK/gax0sChsyvHj9FTfBfD6tThUggJv0r60R0=,tag:6pdo25HCZbmV67jyElGKCw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldC9nT0lZRzZsbC9hY1Z2
            VXRJTkd5aDhnbTVwYVI3dmpOaVdkUk02Tno4CmtHRVVmSllSZUQ3RU00WDBNWTV3
            Tkh6QWdzY0dTRlNLb2MwUjg5bEdMcXcKLS0tIHNySE84alNaUXUwbk8vbW5nL0Zp
            WktvRFgyN0lVSFJyc2tvdTh2UzdxZncKLCNQBjqVQ4nExNcffRohXL1CiVSrOQfV
            frEPkblPz0ic+ubAnKGkzdRvf3P5ThD30qgo9lAAblzynrCYWdbkEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T19:30:08Z"
    mac: ENC[AES256_GCM,data:LLksiLbEAFRCBI6ipFSfyZnk+yU6NPOFos+OdwkpQ5sqaaMn0AMqSqmN5qbn8Ke0Ji3wM0T90Fx5NK1ttOafl5J7ZwRRGn23ZoA1z8r1GiFLy8abEw353EsHSJJf1YRlzdZ/qcSbitZ0LRZwwEGtZFZ7cUgjRSn1OsWNexhzM3k=,iv:Lf594oCchDxufylg1PM8EGcNPeHNRhDweDAjj/6pyAA=,tag:39fc/LcJBuJABGocrtx9Zg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
