apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:bh2j/Kmm0um6/QMvFnBx9McHqM7QB/H0p+Ew7d4QpUtpN83y/F+1nP5NW1SJNLHTin4pWRbbc88PeVLrntszf52HYaM=,iv:B2xgDfT6/iALOzvDk9lExoivZyOPNc3xfVbfYzCv29w=,tag:SuvWYb4Tr7QeWyp1pRPUSg==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:C1h7rGPn87IbygQ+cC1rbo/TFzD2fkhK3rsZqg==,iv:2QU+BEYEBPJn0dJf1h8SoBkuf+emwVdytpf46996YNA=,tag:yR458Mt+DvL1gHr+JgqRdg==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:OvVffZiKENR0IZdG8cHefLmc0iYc0AzNNZk=,iv:fw3au241cTgEzqx1dY3ICIJmYq4xvWMSeh0Y0Lebpew=,tag:JqluLsN2WNMK+WgGmHgy2w==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:ajTTZ1hGAcYRkNmjZxvW1foGFzKMXndlnoEqtkMwcQ2mh8WKdgD51WebtIGYODcwnw==,iv:3jjL+tNUv+ymXG6KV0cgUWYOfXYyCvyXMJvLCn4GsXQ=,tag:HRMXMnMIyaumiphqiaqXIA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:7soO6pp8ryEYbRa4qzAa84+9SDFqyaXZHYKueiE9E608s8tbu+ZssUSAxS4=,iv:rEA8LPfQPaWeiRatJxbT7722QyWsZQeDyg5wpZpKHL8=,tag:EsVvH4xbjUDiX0BbR2Vbcg==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:F3YtUg==,iv:24k+y5uZkQ1wH/bYwlBoxYMvz5sFKey2m+ywhdHWSsg=,tag:ek0MB5ikMGmJLbnvZXjbUw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:fzQDFD9yPQ7D,iv:IrvobClQ0rOSEmj9oZlKVGVR+j1j9lYVSIO+MGiTBC4=,tag:Q3KxbkjhkAz5IZeeMPz4Hg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:5QIK3dfsfE4r,iv:fg8W0KS2jaYIE354RT5Y3tAkfZNFt7asGKZlHHL1yug=,tag:Rxdi8crRrtQiVkJpCInosQ==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:ao9OhxJ+opdsAj6//7FowWk+RwBFyDykBKISyR8OjxVZ,iv:cEPzkYv9y35At7mzZwHDjuxxsq0HTchiFSQuRwASl5k=,tag:lNvXls2Ku5nwfbR5YOUUfw==,type:str]
    AUTHENTIK_REDIS__USERNAME: ENC[AES256_GCM,data:kgBvRLYUxLwx,iv:ZW720ihuLcMNDz1M69GYaL/QKXP9Fftf8R7Vbu38IqE=,tag:FJqhpmEpMKYis+WIO2WESA==,type:str]
    AUTHENTIK_REDIS__PASSWORD: ENC[AES256_GCM,data:wlKxa7WR5aI56qVhpGEiekallmsjjVOdnJ9UjcR6MV8QvyM7VEMoGDCj6TMHRvqGcs8JKcBAWqIeWSvvKFj99Q==,iv:DSqgiVheDFMVAtkV8pouuRpbCPmJu92e9oMARsjNs+s=,tag:N8zIenSmMSuDOJZ2s07cBA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:DcJg5WneBf3mpoR2/CVL3HAhH6Dc+sOdjGV620G/a3P1aegYc488B+NljzctRtTl8sB4KCpdx395iVdJKVbOCg==,iv:lk7qYE1aNRqrBwfYJ72DV1YymnB2nkGnVF8nvxfBFEE=,tag:hDQGAs/Ka9lgrJQcy2k7XA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cUthN3Voek9TN2RwK01P
            S3YyeUJjUHpyckgxc0JoazJlSkxVaFI1ZVhzCnl6a1ZGcmx2NEpsTDNvbFNsS2pY
            TEEyWGptSWptQks5elNQeVUva1kydFkKLS0tIEs4YWpRYXI5WEt5NTNhaXZpNzg5
            N3dnR1RTbzloNndqcXQ2NXdPc0E2MXcKpbl4NTUIgxs8wIlnVsn0Gd6EEa/RbQsV
            uFj0cQ/MdjQyWnTVT/QAuNcNVV1Srh0YORKzPzjkZqxcH694xf2X1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T17:56:50Z"
    mac: ENC[AES256_GCM,data:wzbit4/Y5ScNtML/YNuh01ItyuHsivjegE01E85Je9w36YVGXaKpQX+BYFvPPJpmdYRJnd6qk0zCtLeo1lqXcf8nRpHKVPt0YkFWSJ8bBF46FnPIytv4cpyktA8AaGJ4PPuFmgNBh7Exxk0BGp44nJsGgUrHx1Eb2ZzguqAkQf4=,iv:Qd8mGfCYRcnXa8TjkYmU760Lax5Fp7iBrO5C3DG+eZU=,tag:15241IV6iUkKe2Lc7K93Ew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
