apiVersion: v1
kind: Secret
metadata:
    name: authentik
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:DKYHaJTbVqL4lDBxTOHBSAu0p5rRRzpds/LDqIHj+0OtXYDTpDql2vyz7o9hxQdF/KnECeLJO5/QVfnlvM7Z8uaGivw=,iv:tzJuFHFEaKyEHAfyItdlvziuiRb3qZ5h7KbS113iE5g=,tag:OJdcUs+e13Q4BeJljEPLHQ==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:vx4HwUlExZzPD4pkocXsBA7Dv91QJxKhBboJpw==,iv:r+hgzgZvqGv1Qr6T+ECRDraZnNtq4FohJ1OZj8Shk7o=,tag:nUZdOJ4938Y6YmseHJ/+6w==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:D539NrtxLpFREZVG10OlGBDaCfs=,iv:B+Wl4N+P5E2tOfaa+NcGZjQQNahN4ZUWBjMKhuZexeo=,tag:4tziiPY1z5jfo/FS52JZjA==,type:str]
    AUTHENTIK_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:Byx1I6RMz7pYBVh9+Gpx5suJeakqxfzwwhi939UwFpWP79KBLjWH/kmG1arecOn0mQ==,iv:Gh2ftWDBQYFdH/+5V9gcis1L8tAJ5r3SPQe3a8hQ8BA=,tag:O+jlBurNmGYlx/ACLgw0XA==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:pus8re0YPQo4AFEI7ldy0iq2zDMjydyJdovzpQpq9LSgSlkZH0FsqNYB8Us=,iv:ANbrAK/ohwvpyMbIV0zobZ/pG+GOo2fZzxvBfMNOCmI=,tag:fMNNIxclgPwJRhZkUCAqZQ==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:oIqprA==,iv:e+ViEQMQT5G/X2ryDzLSYvZP4seH4d1FhoGH+//p0LY=,tag:8e60cFIaN61xrr0Cuvn08g==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:fY4FECj5IYHn,iv:h9xQeKn7M2V7rn4RBKogQx6y2wPhbzCfCo04DNsx0CE=,tag:xdT4c0vF0QkqbNeANgTAQg==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:UgdzlhSQ9z0H,iv:OHEVjAUDIMkpFJbpqstqnnMjMGEgXdCHjl2x45Rv5KU=,tag:1E1E4m1Ue+3YWNGbjHF1hw==,type:str]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:ne2FlmGmw7haBKf7gCwCF38vhHh67yCq+eskfMfSh66R,iv:y3dXmriqoMPCfE7mpBWxsSBJZP6LRGhCwSR3M+V/Nec=,tag:yZmGmtr7esJXlPrQtcYGrA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVjNvMlVqZEtvRXE4WEZn
            OTU2eG5GSSswM1JuQmRqUFBtb2ZqaVowS1JVCnJlaUN6OUxWQU9rMllFVVcvcFVP
            WHNTOGlOWWcyd21RWjNYZmtEVVF0VUkKLS0tIDBZSmxqOXFJcjRUNW0yZU5BY3JC
            UXZ0S1cvRlJrK3ZHbGNva0JHMXRrRkkKU6sCWEQIqFYi5pnN/i6Gve7plxb61NmD
            F/ShPBiwOhoUGzvTW1ApbsI0kKVhcpIKy/+uQ053bThZwh7gFqkHWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-18T01:44:03Z"
    mac: ENC[AES256_GCM,data:dGHu443sLZAid8pcB/BvlTY/4oQfRTSrRRmZXrZ1MZjpU/F3If7G0j9mt4Z/n/BO2mcj5Aw7b6jlX3EdbYa5BtE/vkThc0mwM7OhJc2D0K5Gk3KhbziJtqzUx7CtUk5KMc0CQDdyAUxJfC9b1/0Uh637sTUjsv8kN0FEVawtHqE=,iv:xmyKRLN73LJoNzcAfRLUAHhz6oB2aSJKZPCBfD5wmkU=,tag:AgSYEcf4u1giUundGOCYOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
