apiVersion: v1
kind: Secret
metadata:
    name: claude-telegram-chezmoi
    namespace: claude-telegram
type: Opaque
stringData:
    chezmoi.toml: ENC[AES256_GCM,data:rm68jzvDrDPHiC1oKjNWFBOtaWqw1mlDMDKK3dS4B9mgB4KA+BN0W5iZsq8JV5fZ0soeWBiC66X/z9NvGFR9kuYZN6XinuFFYj6vqzw9pAjACxl8t4WErBBfGh0dbkZ7TiPqa+bGqCXOV/7++aDA5o/I39odPeWrPup6zSn/cb4/mfhxXBqGZiuTno2xuTo3c3Y1QknHeDowMYGfrC9FIRGxOv0GNbETQXbb7RaClcg5tdJbOCoJfzgmV2eK/wOsAuZAsZ4xbYb3nWQsn74cd6h/6w==,iv:x1yvGG2yt0XZkIGhAipJP29E143bCM0C5qJtuq7915g=,tag:KV3pKhVj9VnjQs0HbcVpkQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ0EyT0ZMRkg0Q0tlK3Vu
            WW5SdFVubWMvQWFpQ0thV3lCaDY0RjZ1N0hRCk5FWG5WM0pYcHBOL0JNMjFUVUJJ
            dzVnbzZ1dHJGOTgzMUNsRDJjZmw5UUEKLS0tIHk2a0wveWNMNmV1a05VekdFL2FC
            NGdDN2ZlTlRkMGNOUFhIK0ZTc1F3aVEKhA8eufPBPUSxlpGVbd8FR5x2aZ1/R7Rs
            zbwsgmTtI12Bie6aIAO+fUc5f6eM1Y2wt4Xa0lWI6jLfoq+bDtN4dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T13:44:12Z"
    mac: ENC[AES256_GCM,data:fK2GOgiI43hoZdd8q7JThVaP8goAAbBEO+rFCO0nJueZUdQCCyt8xX9t9eiMO3zf/+UjaWI4heWQVWmvAnsoKqDaB4ZDXz349eODwCOk7Uec+VKgzgwufm5RzDxr4U0SCJ9mSpYFhrO8r45ZvhvNrTWkixM8vuE6Nr4wiqDZNN0=,iv:ygDEBPya13UqGXIuKySiJNOl2g+piTeAUBoUdjG/opY=,tag:nu8yh7/L+c1UfmzcvqDPdw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
