apiVersion: v1
kind: Secret
metadata:
    name: claude-telegram-oauth
    namespace: claude-telegram
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:O4co0SS/vkHrHVkVbefIyQ0NQF1fg7L6gcaU5sMrPCMc8n+9Tpin8s29yDahS4IgqqgpryGyhHUdLAwsdeKFDnwY8jSOiPJ/oYoF/aYBBLiDzEbXeVUkNaNpwbsWVdWvGRQLPPHUmyueucOmVXZIcwhMa+NN1OuxcYSB9qn8Ukz9j4HaQ0yT7AyabQPKkcq1K3WDIyLQGNR/TKEsDS7kobWL1pNW1caK24hUoud5omMNsTgtS+JNYvRy4W2xyYjX1/UasU2HIcsdCaknkc2Ark9TwpvUMMclAey9gl7B95khsbGNs9FrK5mt+fSKBsvFtqrx2dCN1seHgjbsT378LBTs/hmTDOso6WmhDW0auGvVe9sKdkO3KBni3b8nPrEQhEYgBjq0CCK0LgSIm0YoDFCNSAH4ZpnxjioipGXhVYEhYWCeapcg4LAziXYvb34i/cwzG3WbKgGSpWndA6yrq53Qr5tqzK6swbJ0n//+1Nz3pKKYKME538afIXrHvQmDkD6mE5/WTLmLTRYD3fRGOyKd/ekhC3h8E/tliaRn0LT9UVFCNoj2M+84FsdDN/yFzwsJAQWNRy7UVLdWtBNc9TeU2mY0xCmGmdbilmWgeib1VPPK8eSnut9fcRgtX/jO9SPdWm/zbgTrv0Iz15vYhY9BjiNLBQ6QQhkrXwkr1vnWp5fmUVqYLjDCP6IsRPlpog==,iv:HqILiMBJEy9SKeQKUxjRjse+88qmCZZ1kcU3lE/r/mI=,tag:iHkNNTOeWB8mNmHY6QSjXA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcGJJNjRnRnRvd0VVeGRK
            WlpiMXpxSzBkdzczSFFlQzFLSmNqVmVaN1U4CmlLU2x2VnoyVG9kNnRtd1pZNlZS
            VndHTFNqck1BQzhkWUV1SllUVWMrZUUKLS0tIEowMG80N1BYUGlYTzBVbHFYT0o1
            V3ZyT09FOURoeGxQK0VLbnhPVXlxRncKdbAhpCW0qqa+khQUhtLDenKNUUqqP/gv
            W+GJ3/nljsNiGxlcJlNH3zU25gXfe9tvGGVPJOkwZITTndccnenIqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T17:35:32Z"
    mac: ENC[AES256_GCM,data:QeSUNWfwAE2DkGK7jYcKfP7foyJPCaUgspQTWpO8Vf4QpAuqrHAB1jM9TaDQ5kGGHyRHlxr7Kdjjf+qYFy3Po1dtXqyui9cJ5pF0McH81EcoMwICysy0O/Sfgetuis2BeNaxfP/QG6qqzUIIXB3OziRPxVBolbS89zPaqLmLLj0=,iv:KQmo3wSIbo8SyKWgFBTBKkjW8b8IyXODpxuLAp5P1GY=,tag:Yn2POpfvHtsApexhkxDt7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
