apiVersion: v1
kind: Secret
metadata:
    name: claude-telegram-env
    namespace: claude-telegram
type: Opaque
stringData:
    telegram-bot-token: ENC[AES256_GCM,data:uhCYgDMscHQE6pLKSgNYG9ELr8W7m2A/p3X5OjFjyQ7aY6JRrdWmsbI1uuWhJg==,iv:+Twz6WsT8wweUglnLUku3FQAn/goVtJouPjlPAeQOcc=,tag:UJukgwLWJDhPuZ/6ZYjDsw==,type:str]
    claude-oauth-token: ENC[AES256_GCM,data:LDsIWCI6KUvInk+jbkdmfQs/yo9beH/dXM9KgxVG0LOqO/ZamsvUQq7LxluzHxnLgJyvH39Bx2O914x7fHQDK0GTU/tHpzvuOBxxswuXGcmtPgJiyXNUNM0weItYZUY8dKjOjx8YcPfBOUM6,iv:Jel4nsgbN3mMT8CmwdueKOU+dk7uEayvU6DmZAplxNc=,tag:+aN83KRrmSGjItjV35tYJQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMEpVTjBSbUpKR3k2YStp
            Q2xqRHNLbWJrSmdrRVBLVVMvWmUwY0NzVFFFClJFcmF4Z0ZGS2pOZFR5UkVkYUVP
            KzJmREZsMEVPRzVTMFVTQ09ndEVRa1UKLS0tIEIrZUtaL1Z1djVRTlJIcFUrZTFj
            SGpQOGNISHR6WENsWHU4Wm5QWDdUTHMKo9eNEZ8nVw2LFfvnalU9p6+onaoV43Ry
            G6gU0A5YAWVT7Q3bjKZaa7sPJfEps9yv+cDJSsEfgWJw4rDaHsO8/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T22:36:08Z"
    mac: ENC[AES256_GCM,data:zpmcesLgs6i31+hZmiEkHNKzP2sWK0JRKTsaaeiuRu/r12sm5Tx8UxT/SjQLfJGMw3PKxHeFNki2D1XjSkU0hdbobXWc5vHFOyyKI0Nn6vECDvywSMU5n6ng+cozeofwycx+DWlgMoEaI6ZtBUBRMiaggZ65t5EZsNh7N5oQPGI=,iv:7f+YxowA3t6VWmEwhPBmp2jNxL3yEcKx/F9wRjvN40k=,tag:sTcBQ7QqhLa8tq9ai98iIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
