apiVersion: v1
kind: Secret
metadata:
    name: claude-telegram-oauth
    namespace: claude-telegram
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:UtaOYXtUCH11vb2npKWQMcAjHEzQPXYyO52Xky72pW6d9mZ0r3uaCzhwlio4Dt/YwcMw7Wn55UvbVQXibIO0703u/qDGmeJN9Wsi2Y4D1eP4ODeHBe+HCCm8Cy7qhsSGFLvvk8+/mBmdTv/BfnUxvC0CbUsRb0zOoLNW39GM754SUn0V1SvAkq3je4Se+PTjH/hvYXNBnBkmtelRYX4rNm/X1q3KlLsHo2y3TZ1s+hqZ8Q2di1UR+dADRqitxEkrWpiEM4uSkwjUz0gzFNyDIkKEyWPu3jUwuPdcwllpc0inlxxy+Csv9am6k5MHmY0DPlCZpo4LmRe3xCQ20fYfuXmYJYtnh4k5haYjw4F876aUda0nPW6omScL9T38nGiY7q8Fv/3v6e3qtP6X+kzORc4cJKbYhj+371V2EFlZVDQMAsdlA7+bOb1ya/N54moNxfvkLkBDq6tVNBWIJ2BUt2MRAjS2cmLGuQIh+QULLzk1I7ZCU8tpROlbV5seQEBzE3Ut0iamrbyukEmwhEMwGlOJh2d+fBE25nxojtsgIq0pE7MTmSiw2nO21srvKRVnfx7CfLVYEk7I63reGjAuzK7lEN7q5IFp9NzY5yHVOwvCYM8HXl8=,iv:PrWyFnfWcmTmwSbv8XFDGflMi1JXr2Yf+JEXkPdspSY=,tag:zxZpgE8XRiTWHdhyy4sPhw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzcGJJNjRnRnRvd0VVeGRK
            WlpiMXpxSzBkdzczSFFlQzFLSmNqVmVaN1U4CmlLU2x2VnoyVG9kNnRtd1pZNlZS
            VndHTFNqck1BQzhkWUV1SllUVWMrZUUKLS0tIEowMG80N1BYUGlYTzBVbHFYT0o1
            V3ZyT09FOURoeGxQK0VLbnhPVXlxRncKdbAhpCW0qqa+khQUhtLDenKNUUqqP/gv
            W+GJ3/nljsNiGxlcJlNH3zU25gXfe9tvGGVPJOkwZITTndccnenIqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T20:55:23Z"
    mac: ENC[AES256_GCM,data:uwtd7BdUJcGMOTlhBZh2BCjKpnjRJp0G7m0cRetEzMDkFLOooK/Cs+PC6QB/1zm3fRq95FOU0z+uCtMIjFghpxvWfKheSBln/jNsACYtF5ULeD+csOQeRkBAUhBH+RtLVWpmwOT+dDQ9plC0On76YkH2eBPtYhjRDHEVnryMN7c=,iv:MsaJ3VNHSl4UeWE/YbS8gvLLMd2NX5qKmUAxypBUhKY=,tag:1Fu8ZftR2VM2auxA1iELXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
