apiVersion: v1
kind: Secret
metadata:
    name: claude-telegram-env
    namespace: claude-telegram
type: Opaque
stringData:
    telegram-bot-token: ENC[AES256_GCM,data:YzfO2pY0XsUAR0seVbq5MsDa46Qs0c561KmUGVkR0o2oJhiZGphGnHX4/4FfEQ==,iv:T6r0NBplo1gHpqycA0/BuJ1761ArVJnEkCtwLXAX7ag=,tag:iDvoWrQ0aKQ80Mg319c9Og==,type:str]
    claude-oauth-token: ENC[AES256_GCM,data:+F4SOO7htk2IE02HEI99bOthEnSy3Ax665VqevLCAoS97se3armQ7P9bqCIdXLSmabQPjw2JgOAie7shyS218wI09nGyezUv/IBYszImN+YDdQMcuIJgfeT+IW7Ygw3Px23PexunbMootsi5,iv:KhzQ0yD/rZSLenfYduIiidxd/BjYnhS+fWUr3P9PyIA=,tag:1k3LMj5jORRdIhYvHC2RVQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMEpVTjBSbUpKR3k2YStp
            Q2xqRHNLbWJrSmdrRVBLVVMvWmUwY0NzVFFFClJFcmF4Z0ZGS2pOZFR5UkVkYUVP
            KzJmREZsMEVPRzVTMFVTQ09ndEVRa1UKLS0tIEIrZUtaL1Z1djVRTlJIcFUrZTFj
            SGpQOGNISHR6WENsWHU4Wm5QWDdUTHMKo9eNEZ8nVw2LFfvnalU9p6+onaoV43Ry
            G6gU0A5YAWVT7Q3bjKZaa7sPJfEps9yv+cDJSsEfgWJw4rDaHsO8/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T19:59:52Z"
    mac: ENC[AES256_GCM,data:IGbn9xlAshtrYMLk+6znddXGKlMdj6bMHrWXy1b2KmMpeQm00nMYUUpw9fPdmyfhwK7aX8ox2NjInYeg38kpnc4gDaNzhAMaCUr+4sERe1tGW6RiuIBsMbfFrNA8B58iawb83B7FKj6Nom9JeFYijQO+cXQpB7liEJycfoYi1xs=,iv:2T5FYYb2G9W64LwoBwwbA75YXxxbMhIn5DUknPESMW0=,tag:El8Zn6VAsss+iO22g5KL/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
