apiVersion: v1
kind: Secret
metadata:
  name: claude-telegram-chezmoi
  namespace: claude-telegram
type: Opaque
stringData:
  chezmoi.toml: |
    [data.ssh]
        master_ip = "192.168.1.127"
        master_user = "akhozya"
        worker1_ip = "192.168.1.129"
        worker1_user = "akhozya"
        worker2_ip = "192.168.1.126"
        worker2_user = "z3us"
        port = "65300"
