apiVersion: v1
kind: Secret
metadata:
    name: mysql-cluster-secrets
    namespace: databases
type: Opaque
stringData:
    root: ENC[AES256_GCM,data:ocja2K0fMEn0a056m3wKG8CFWjFJOTeCV1iSuYpk4EUoPW6q98zHWP/l+tNsN2J+MZ+ORUJzFg6Vxce7D2ny+w==,iv:D+RTfZzSGr4ivslXbkMCnEo1RgQ68D/xNGfbhXaMJGY=,tag:OhLTWCOpU4O7onVpLHy31g==,type:str]
    xtrabackup: ENC[AES256_GCM,data:GJkEYWS4YmdCHCXV7Nmp8IZwf7lfJoCJxL+6KQY6+mnXfvkzl3sQmokEYTl9wvkz+2sNniNwuI9YdMI6OK/o3Q==,iv:yeVlo6nk3gvEeyitTAp+9d5bJehZ+/i+zd8XYPVNiAM=,tag:fSgyLnsaLVKFRN/vzFRG4A==,type:str]
    monitor: ENC[AES256_GCM,data:RzaHPxHDEdVA60gLClyRPbEljYM+f3in1MsyWKPij8gdCCZaAr0CWm84+3isUYG46ZRt0Z50i2Uxs8tsDolwhw==,iv:bVsrj1+1bf6FEFhpQU75IV6VEW2mGWQi6YJpjFJu8iU=,tag:TVlAj1waA1BTRZm0P9epGQ==,type:str]
    operator: ENC[AES256_GCM,data:pbE9SzAJOBA7Hn58yDVbVuMnI40GEBWKdyNojQv4jppbOBPCGEFz1lmm/d7o2R23Sty1A/RofKMBOquHpOHuyA==,iv:SfESEEAloP9RCvBElXQ6m4zA+c8Fv/lK+0hUMMncmqU=,tag:HTgZlw1+vO+PHqO+m1CbAA==,type:str]
    replication: ENC[AES256_GCM,data:P1zK57xSu/0Fj0bMMTqxeengp/m2MCgTTpxPk2+g4Q4=,iv:moWSBkKUm4HC2XTJuOAs1SKD3mKEDO+6NRWGlzgaNtk=,tag:CZrEcZOdozfxrnP+MIzr3w==,type:str]
    orchestrator: ENC[AES256_GCM,data:tScFbztigZVkzuu4p+RLkeEqLdL8V/VHVNxglLEuiKQ8+W8uV42oqhxT/8lUkNfXp4nBUEEB/MFg1wB0cAwljg==,iv:8OZPpmEckH6d3w0RzViFEP6q2yutrK5aeBHJoMxBRAE=,tag:Ejo1H0lZuBekf6tPXNf/Ug==,type:str]
    heartbeat: ENC[AES256_GCM,data:hGPIEhckWaD8M6FMbIs3x+l81bnBuFF42Toz0DDF5eE=,iv:M+6myFsKuysBXVLzVczrRg8o9WAEq0oJLhftp9CNcaw=,tag:TjqiODNOLFTIXLFgVrcAzw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNFNEdTBTUk1EZUVUNUJO
            S2Z2OU1heHJQcmdFT3JUL25JdjVvRWRTNlJZCkpxZ1B2dU9uYzF5eGR6K1NoSkMx
            MWRKL2swWTNJK2hCWjVqRlM1aCs4QkUKLS0tIFJtempKK2Vac3V6M0x5WU52ek5v
            MXNGTWVWYjkySmplMUhxcGdMcFlyN1EKrZa4MIgHx3zKkYQGInnm8Xca63mFZ43B
            Ua53tryXFMAsSDicYVTCZxXNOps2uuQBEm1B033+olHON94E5c1K8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T22:14:09Z"
    mac: ENC[AES256_GCM,data:/LgEXhZkioFeT77wtd2b12Lsn0JHqnE4AXFsQKIdWbJFYvSBHxsTurxM+igQSxGjx9ARYMjSE0I/JfvEbnIer5idQZdV7PRkwUey7kbYOcc+aYK8NwhnBeTBmvZXn6Vj4OQb+4Ojq8MaMW5wTd0I0x/mf2WswM/+vAL9Oh0fuEw=,iv:2f//b2nX9IRImcqTt1baKtHNO9+Yrup114EBxwtQJEk=,tag:dFG07WW9lKox6gEpfRaMZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
