apiVersion: v1
kind: Secret
metadata:
    name: mysql-root-credentials
    namespace: databases
type: Opaque
stringData:
    rootUser: ENC[AES256_GCM,data:RfYWIA==,iv:UalwF0XyDZO8syUzLATQ0E0xEN4gG7MGmeGfm7Vtq6M=,tag:ZdJU5fCzw4hPNw/OedqWkQ==,type:str]
    rootHost: ENC[AES256_GCM,data:1w==,iv:Jdfc6fD7vdHwWK94q+cnrVM219xtIgytve9lAoaTFz4=,tag:5oXD/gTZljA/yrDIyq4GYQ==,type:str]
    rootPassword: ENC[AES256_GCM,data:oM+IqWosT7kLcpWcdHKgKCsZ7X4YJhGUdFENAIpOWEtgfCTLh3rxEUO+rIKZwlM4WN5xbmU4gCFLm/8uhHdKPw==,iv:xEpI3qLwyn3TiLK7Npn4jV3NZdM8qekNjoOMXPFfXGE=,tag:ADdVEUX5ILlXTmpsMGTulg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYm5uWEt6V0xoZGQ0UTVK
            blJxQzdzYW52OUcxWGxrRWRtdEJaWDVlZjBvCklxaWw0RDZCcVRSV3lxVmROTmVX
            L0hOVFJJdlpYVDNBekF3b0huN0wvQ3MKLS0tIHhWTytLUHBkc1QrcGIvK1NTdXJ5
            YWErQ1JpM3IwK3U2NndoTTlQS2ZrL0UKrxN1ghA6xszQoJ6EHjgJC2EkNQfaG/bz
            mmhZ20VGrxG4yP5yNEhaqPUyNs1jN8Obk35YCzl+4JgQwuS0ysf6yA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T23:13:18Z"
    mac: ENC[AES256_GCM,data:zBngj5AtFoX7t4QCKr1wFV1jY5ghk0leHmzWMbMBUPkFyIvKG3e0W6RCgd1/hdP/xmjKlJ5A5VMmxaX2XSEu+rWrZmJsGag7kTqX3Q6UoP1iAs8ca1CJ96UX///6oiJiPLsgh+pD1zyWKatAuf7sW84SM5ZNkMjbJ7RV7jDBR9c=,iv:aJM/6gq9OzCcnXjz1cNIRlW3a9ouwAqN4JSr4bA7TTM=,tag:MV9AR4+GHKjA3qyEEHV8zQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
