apiVersion: v1
kind: Secret
metadata:
    name: pricebuddy-mariadb-credentials
    namespace: pricebuddy
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:UPwBhsoichS0Cg==,iv:JO9LoPn39q27dCa50XAhpyIuTgNS8XpN8iqjOuUVA0Y=,tag:Q5ZAS7UrFIhekf4e/yOvyQ==,type:str]
    password: ENC[AES256_GCM,data:TFwiOtXH33ippk+peF9Tt6Z4tlPPQIN4,iv:nw6sB7LlBooLCnTuWQPAGy9NyTdV1GHtdRorRzGFFy0=,tag:WAmwjIJ5lW4lDt348bwN3w==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MkplQXl3dytBeExxRWJs
            RkVEc1Y3bEhuNzQ5L25reG9lMkIrQlpVSEhzCjVyT3VaSEFZRkxXMmlpbm9SeTh2
            S3VQb0g5dmZUL1ZLM1p0TXdlV1l0V0kKLS0tIE9vREp5TmszMFdXbHhzREdldjJJ
            Um9QclNCWnR3Ymw3Y0dIdVA0M1hKc0EK17GGvzLDkT/x30V7w322caN1yz4qWI4l
            YvwY7yUcdsZSltmewa7RO3a0/dmjgtbWudqDnTMWzGiqVV0Noi0TMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T12:49:00Z"
    mac: ENC[AES256_GCM,data:EUOThWyDvzZDgytCXbry3fNERx0zxP07FKiz6Wym0LN7jqZ/x273P9hulNu6FYzkivKlsa7xeDmwqOWF+Qxodc+Z8fZfX3w4zr7s1XfAI0/MRTiKuPlzn1Wx5Vo2mPoOuZLVWcW/2mcJyax8ExYENyTk3/DjIDByx8Mn98vIFkk=,iv:FvwESAfbxZsMlTiJFEzDI0k4p3NmxLJUPudsfoHuHiA=,tag:GmdqfQMDXsJ4R/Q3M+NEmA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
