apiVersion: v1
kind: Secret
metadata:
    name: pricebuddy-mysql-credentials
    namespace: pricebuddy
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:J6fsioACdIdoog==,iv:TA0pOWsJOTZbGo7XF4I3KElCk3iiYH/qj/V1UWzmpfo=,tag:jRnjLFaG5nKRhn3zw1lfBw==,type:str]
    password: ENC[AES256_GCM,data:lhcm/LkyAGjgyOLjOD/gXuf1dwR5Og5ydM+e8yOaEUo5Xfh5+8D+i8KypLnuUgYITasP0zfH6YW+liQMA3DuEA==,iv:XWIOvFT7gssw2QBcslLFiX2l7yNRNawsKY24Pw7xBwo=,tag:esFYCE7DgjUJIq/OiEzbLA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTGxxUVByWkxuL3hEY3du
            alFzZm56SW1VODdJVWZzWXlCTGMreVpjNkJRCkM2cjVFQUlibW5rZXNlUkY3K1dM
            QzVHc1ZKKzA5Y3dNSUFKRVZCVHVmM2MKLS0tIGIzYmRaSHY0dEt3WHpXSXJrVWZ4
            a0xRK2RvMHkzclpVSE4xWEpEeGJYNFkK4bIpIgebShoyJSwjV2Ov/auaEmgb6BJH
            mTU80k1hUdsqECjmkwhe/psg+Kp0O5YDE/MRosC+DbHCPv8YW/rjEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:44:24Z"
    mac: ENC[AES256_GCM,data:anW2fCzEYbEEOwTrOJWHq6m8WxIoP85S3uJoRdHTPMGHi9iJtV+IFDsv/DQJceiTMHwpG39bWiCgNNJY6CVOq0Gz0GkJPPAFv3ILTGIuBISNRn4xM0LOSaHVLYUaMrv+Z6a4aJYlU5NvU8CQLMnnTCIlQ2i6XEz8xmoGF9Xax6c=,iv:rDK6k2M7FqOgokZTocq0WAGNn0sIAX8/ZEeGsxm3BcM=,tag:wbsBFsFeViDOPL8q8nyjDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
