apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: couchdb
  namespace: databases
  annotations:
    # temp: gapless controllers->configs move (removed once configs adopts). 2026-07-03.
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  url: https://apache.github.io/couchdb-helm
  interval: 6h
