apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - victoria-metrics-operator      # VM Operator (CRD conversion)
  - victoria-metrics-k8s-stack     # VM Stack (VMSingle, VMAgent, VMAlert)
  - kube-prometheus-stack          # Keep during migration
  - loki-stack