apiVersion: v1
data:
    ssh-private-key: ENC[AES256_GCM,data:CXiU3PW7e0NR4MwWa2bp5Fjz+9T1DQMudbJ8Zge1B5YgJRzdntI7PDjsKKEulsdDIcAegFB40at/tp+0Kux10FaOSQefrBFWpHiVCOH3g5sgDttbRyQwFzHOn2+ATiohJ4XWJuU+BQAjd1Ik9EC64tCUm3kPRaYrMMOK2pgNUotJ88GBIFG9tYcB6eCVnsfKH+wOBi7sgwRG/Sw/FyL4anL9ossDX8Gl6iaK9RaJUVGFcb2WtPoYIqfWke8/qxuUL2Cuxp2vmff03X4DGaT+J/VMpO6llIRdAS2RXh8+M+F0Ftav4bqkLhxlodQRsT1DIZ9a8GIZ2qQEctZZhhqCsfoIqRFdYCChAzASKNkV089CU+MjAsKnqYS42VLEuR6J8nA9N9DGme7HnRFmUnZR3abc7zm9E9akXLyuhKKT+tXOxyQpCqCNKyClJxgxHaN0TOM0rO+Ht2kR530BkH2zCV5kk9kOEEhXjOHhSrq2Xjw3NmrtLy7AA8G3EkbNa/tNFhbZ2Cm/uAlXul189NxSGdecfczb04X6ZqrRGYGjp3YH5dFbqPDQ2n0PvNizBd1cVV94nDz+pu2pUMohupgoAO4t/x6L6cCtmQa+fx42rKInmECWMid8zGAcV0g7zM/pHqJnX9eYVgz8I4LTZlCcHX453n9limAC5IaeE7tiSBZznyQ1Ay770xJQMa41sB/Z5Bum1B9RrC4J6j3DSNBKxsLYDKin8u4nYDkxhP3ped0=,iv:3JS6lO0ghbrpyr6FvptsvQvA+mHQ20SldjXrZquMlTM=,tag:O2zsfu0FtSeuvdS3NgFkew==,type:str]
kind: Secret
metadata:
    name: immich-vm-heal-nas-ssh-key
    namespace: immich
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL2JOc3JlV1dLK0pOeldm
            YTB0NU4rU1JxU1Fxc1hxM1RsL0szRXlBZVFRCnk5RXViQVU5UC8rTGkyTlVFamRm
            ZzFtTHEzcUZud1hwcmNDK0VhL1ZSL2sKLS0tIEtiWW14UkdZZzkxN1ZZSUJrN3J0
            aStTZ01kTklkM3lMc2xkcEx4NE1YSVUKYaF6pDVKKSxn49eJSWiABPORJQa9vQOl
            NUxr7OgmPlG9D3EsJQmzvo0wHkeh47Q9kSxJ3Yz9i5CuYL8vaFGz7g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T23:42:12Z"
    mac: ENC[AES256_GCM,data:88wFrj5o1cSOaAAL8JMDN2eM+GMcOD4KFsmREVJ21noNz/4wxk7qDEBcIUyHQNPRckyZruavUOhsuGM4bzer6JFG24BYZx8L9nPBi1hp4UysbA6qTMo6rXg7LqM/lG2C606z2Xl/ZiwYD4qEZ3v3ILrrf0nT7UxzdIUcO+d9TcE=,iv:XVXbunQn1uGXALTqFTs1g0BZmB12fX3nM3oZ8+w/ahw=,tag:MVtO/gaGbbiQAsKZPT+Z3A==,type:str]
    version: 3.13.2
