apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: discount-bandit
  namespace: discount-bandit
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd,traefik-security-headers@kubernetescrd,traefik-rate-limit-standard@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - secretName: discount-bandit-tls
      hosts:
        - discounts.h0melab.work
  rules:
    - host: discounts.h0melab.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: discount-bandit
                port:
                  number: 80
