apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: discount-bandit
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secret.yaml
  - admin-secret.yaml
  - pvc.yaml
  - custom-entrypoint-configmap.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - ingress.yaml
  - admin-setup-job.yaml
