apiVersion: v1
kind: Secret
metadata:
    name: immich-admin-credentials
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:5dTG0fe57GolQAomTJOKQzRMhZSMmDgyny5zwmfSHrs=,iv:CqxurDTmP9GAehGyfvRc/j9xEGg+L5nKw8eFVg7MVGw=,tag:V2aNkNrafSBok0w7H7RLWA==,type:str]
    email: ENC[AES256_GCM,data:aaTCscVRFKp+lmR3ocKVzU4/i140HfBv+Vc=,iv:OlzWAgyaIMSqTgudm3tOlZaqj8tsImnrJwFlgUXk2uo=,tag:SPx47ue7ZVvBHrcf4G+CGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhaFg3TlJzS0Q3SHA1blFn
            bTlxd25LMjhwQkI5c2NiTUlpR1liVU1BQjFjCkJKOS9CWGs2NlZacTlLWDZqejR3
            TXBsajNsQ3lGeXVVQURUNkhhdVZmeHcKLS0tIDRQOGxDSTB3WXV4bHA5bmFSTUZJ
            R3BHam1IUkt3aUl0WlpUSURPU0RJL00KCCHnaXXNVJ/jh2K5RNJAFLrKIZzG2OSj
            KUSpv3Ah/b5ODN0lkMEgxRaezk7KpoK/fIJz/EL30QaClhYGUJ/N9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T15:30:01Z"
    mac: ENC[AES256_GCM,data:korJ9ZzKsnaH5hEEM4FxdMKTJEQg3ATknOh1yE4HbYe0WGRIYIFqN6Z4S1Xyu5vyW1bjn4kfYEFg39CkyqTfTbOzgri5xsHlf2dXrm3SonOSkufe36RlWI60xQ82M2PbJw968B8qBW2vp5mh6bI+sy+8ScB+6GcelJsLd7hc+9g=,iv:iFNCzbLbsqGzqvUw7RxTUKWaQekyjb+LgOXLMg/1Vbo=,tag:WjHoHyQPWjGr6353401eOQ==,type:str]
    version: 3.11.0
