apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-url
    namespace: immich
type: Opaque
stringData:
    redis-url: ENC[AES256_GCM,data:6zOc/fdXtdf9DEuE0ZTivSfcJpH/T0DtlqFrswuPpM6BlukB2KnbAhFXQQUDZ4Z/E9CXRNKQ3r7Wtz8xKAXnyYNbSvf7GREC8bYilT6+j1IaKK2EcGocSkjRuG90kFa4CaspJGC+1bBVIEmpVoWICT1wuiIFOmXf40y0Wf4sqv5Ou6Id13dYjebaYaZi3IuQkyRxEoNMTpFS8/wNk08AF8yFD7ayo3MQBXebyc9I4E5wfXQo9/hx9UNjlBdst7GdCh0S0lPxruPdCYbXEZEKa+2Ugz4gfmOXmfWx69AAnYQjQnMf7CoDyx7KJsE8z3fC9C8=,iv:M4EBGC8H6BJxyZ0E0QOQsDJg+yie8Kh7QwIk61YNTYw=,tag:3z3pkjZ1bkFa6b7i5Jzb2w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WUNFYWUwNjBRVktuUVNo
            a3hNUE1EamVFYU9pL20vYUgyNHRCTEZYaGdFCnVGcFA3UXVzWGtVTHJwTFNOVWt6
            Z24xVnBIUUYvQjM5MkhuSG5RWjVsaE0KLS0tIE93TXRiZzliSGVkVXltb2lFMlBv
            VGhpS3YwbHhPS0g5TGpmL2Z6bHZiQjAKRPobWxAun9vUwn95klZyk4/uS2WzTjkw
            xg1Vgx19uN98Vbsso4WrM4eWJpR+32JmphW8iAHhlnYxTPKhuhzlvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T16:42:51Z"
    mac: ENC[AES256_GCM,data:AfH4Ov3DT3CxNpR+gOVKdr/HVPS4mdtjw98QrjyvELkKJvZfXTpPKnr+A5Ap0r1mMaKA2GP1snV5IyOM3PrHRy/jy1nIT7Vjrd3M+/dkDu87IrK7d1XnP+QjaKq8nsL8ZOyhsSjYieJvVjaCT92Lqf9I00QtT7/CX9uy8plj99U=,iv:kHNrPnjiOv0q71bRbRoOGJ6KCc/LVs69C6kknvDriMY=,tag:yKRJJRCzPK/NH5/uSjO1OQ==,type:str]
    version: 3.13.1
