apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-url
    namespace: immich
type: Opaque
stringData:
    redis-url: ENC[AES256_GCM,data:8WXswH5xs0oUwByCk72Q3CBC6ru0n7gsGVV2dioZo4pPAw4G+yTYHPNeAU4tn7cY/zEbjy1Jy+EgEYveXXUd+f8IoyciZ4IJR+D/u88aeG6hIzEP/z2dRxOHnqqOgaKgzccvwY9uB9kVrIKSsCnXdhttfvqTDj2fNWOLSbSPDLukmVkGnuVWl3w5irZXFfpFKLoXYDVjNPD0HD452ZFcnvcuSckj4Ls/wwyhPvcoNOH2pkSEJOiGjxsEDnsTG+bKlpMDBh0qA28jvykJ59ngVIXtWO6i9ykAW2hQmW+lIzddY6ynRDvjxBgGqyIg8Yk+nZ/l8z18KcH9VQoGf9AhqQMvBsUKDeV5RXxQwPF3xR5ypHv9K+HDTQBA5XuJvA==,iv:3hgkrUxI5+CrHbo3r3smbNMOz7zeHif+XMeWDHLK338=,tag:FZexiYjYAc/lY4Rv7cvpYA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMVpkaGpXTXp1Z2cxVkJj
            Qno1eTlIWFozL3N6NlZrZ3BESlZzb3FFRlFJCndsczdXNHpvcTF0a2Jjb01Xanlt
            REo1a0YwZFNTTVh3R2g1aGE5V1g2Q0kKLS0tIGs0aUtlV2dxazd0dW4xUldwT3Vo
            YVVIOEh3NVplOElDVDBFZG9rY1h2R2sK99zaKmQqt7P1vKeQun/Grvp3320bwm/P
            kI/paVu3gBrXcPNLAhQ/lCmPk28jocd1RVIm8Gq1xYp0gtPxLt0PNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T16:25:19Z"
    mac: ENC[AES256_GCM,data:saOQ/OHNKrIjoEysYZFfa10Z9PfWrWZOr/bB8DnvTfTimiNdcnAzj2H1IZY1xDTvriOKeZXhsn2J1IGNC7Q2HOGvYGG+ZfTZLxnkjPHF8cJrXdsjm8o2MBWo7+7mv3fDMSio+R0N+lCSzLwdWnu/vhDkTUZl5h3OT9qrXeN86Ss=,iv:JaEX1gz2tIUS/r0sdSUtTrxLeTS5V27OvxkYfRc+7uE=,tag:FnORge2L7GT9nElRR/Xvrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
