apiVersion: v1
kind: Secret
metadata:
    name: immich-redis-url
    namespace: immich
type: Opaque
stringData:
    redis-url: ENC[AES256_GCM,data:Gs16H0yNfJgtrG9wJZT1GXXIoQuUlz/QeuoS/vOELaxi1x8TNZhncDqXGeIUKjBLdq4XTBG6wHQXghFEsPEk1thu0u1iZAiOwo5f5CT+RO8X66DvUSxi+ijdYBJw6aFR6rFdp/VyCPehI5M6boL7rq2wnE8rLzXKEAC90uvlzDSTCmmpBy588zRldCJS4hhBcivjXRCZxi5idoi+evA/1+yZI/8UdCfOdNBB6VwOhMF2q+nde6PHNXexGRLgFPTZty0Y8Z658KDSqXk2zOKnxM0aBlT95mBqy5GIhA9RJK2rVTXN4qJ4dwjwUDHOOoqKF5w=,iv:BTpdZoG+dM+YogKACqv0HTVHF1P9aPaRIeBxZAbPeC4=,tag:G4IpTmVVkzaq6Dde2Tb8xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WUNFYWUwNjBRVktuUVNo
            a3hNUE1EamVFYU9pL20vYUgyNHRCTEZYaGdFCnVGcFA3UXVzWGtVTHJwTFNOVWt6
            Z24xVnBIUUYvQjM5MkhuSG5RWjVsaE0KLS0tIE93TXRiZzliSGVkVXltb2lFMlBv
            VGhpS3YwbHhPS0g5TGpmL2Z6bHZiQjAKRPobWxAun9vUwn95klZyk4/uS2WzTjkw
            xg1Vgx19uN98Vbsso4WrM4eWJpR+32JmphW8iAHhlnYxTPKhuhzlvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T12:02:48Z"
    mac: ENC[AES256_GCM,data:0kVn0XrP0kbWxV6QYaOk7QDDmSzOYIZpVSiQ+8BereaeyYMwNNlWVfCSVcLnuvU+1CZdmoyBjSvqfvZCN0HqyvAytZmhczSl1Ccd91fCD/pYCISOIBWil03VFXl/QMvfwOR9LKsLA1ZC2KgbVg6XS5RxEeyPyeADBi8A8FlG/IY=,iv:J5EkYW36dYCmFnmzm5IYeHuxkJg9oAZ4yUYN96H8Xkw=,tag:KUM0+ovq54S/HLPLpbZ5kg==,type:str]
    version: 3.13.1
