apiVersion: v1
kind: Secret
metadata:
    name: immich-db-password
    namespace: immich
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:D8HeIc5yDmjlCfEGsH+ERcIQY59b2WkAU75xbzW+AFtZLytdpaVPEAIGgjL1oDkxWvUe74lbZDA973/MBz+uTg==,iv:i9d9VCHgJBzdqzM0vqLPFiKC8R1/OiYxgxt95d6dpAU=,tag:KoCNbmTCXgi8NGsEge6Q3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRW9PWDVYWjlZTklEK05s
            UmgrVzhaZjJ5MTVjL08wQVVOak1YM004RTFRCjZPWngyWGYwM2c3Z0dEc1dtWVNW
            VHVod1F3cU0wbkNwMmIxUmtQaFZzQ0kKLS0tIDdqVEQxc1ZrRDJDUzJ3ejZaa3Yr
            bG1iYlVWTm1mZ2FaUENxZHp5bGovL00K9KbJkMUvaqOd6DERI/2FGT1DBUXzgc+W
            OsXpcQR5cY+D7WYKD57LviROXTXpCnQHSy1YZ4utpv661IQZ02l4Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T11:16:43Z"
    mac: ENC[AES256_GCM,data:v/F0gf2Vj+pSCMq38OUU+c5UzhaHXN213UYli4nU6CkUi9DDIekOWYpIULM2XZt1U0pxgXItwTD1m+6XPQolxexjfrhp2CaAlXq8DwdnwvRkqQwQx8Qr3AHCaTdGFY6hjFgP52na4f1Hb09sYXjBbrGseXUIu2F9KnqFymguSO0=,iv:8JLHFFcM2+nQpz1mYXanlZNvYc+i9Er60aM350RLJBU=,tag:sSp3/WbEPfl1yTi3v4JuhA==,type:str]
    version: 3.11.0
