apiVersion: v1
kind: Secret
metadata:
    name: pricebuddy-secrets
    namespace: pricebuddy
type: Opaque
stringData:
    app-key: ENC[AES256_GCM,data:iKGdPLVatH1gpNbr6kubKgxXVJzVPQKZJMeIoxF04pPVJoqLw7HokMyHpoGfsqNZv7x7,iv:zNqXj6GyImzSboYyKkYKNQmoYt/ON6+dH6VUyYMO28Q=,tag:cPG5MWTX53mhYPLdihSbmQ==,type:str]
    app-user-password: ENC[AES256_GCM,data:GHkwkyMRKJx6SjjY/+arguTt9qN3/WZJ,iv:pkcysFEIzegmHBEqC5yybtlEsepb1HREYjdGofwVZFw=,tag:iv+u74Ni2Om4pYJcupg9Mg==,type:str]
    app-user-email: ENC[AES256_GCM,data:JKCAIpYVwfqqkhOmAzwat+JndVIid8Z1wqw=,iv:JSka+qn1tInmHiuYmKgW7iBiKGwOFfKWou26TrKJnP4=,tag:425T1MdTwh3SUM5KgKdXVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NTJ3T1JPbjZlc0lxOWUx
            QTN0MnZZYm1PTW9qUW1FUEZabFJCZnFJaURJClRsWjNaeWdvdVQ2SG1tMGVFUFNx
            cEJvdmtzRjg3N1dZdkxFRk5VSUh5WUEKLS0tIEliMGxkamg1SUtXdXNpUHJpU0NO
            STRyaE1qN2RwcXArV29hWWJWTnQ0eXMKjcoDW4vnSgF7BUrk+BpRWKnsPxRnSGF6
            sTR9S0BsJwbHcAzyaO8vEGdnxHh0nSvBc1y/OGA8yybDIi7kOTu3GQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T15:30:10Z"
    mac: ENC[AES256_GCM,data:V3nSgDSJM26kfmgnKRQ2xR6qHfSoYPWzb60SROGfAGzDfV9rKJdl4SBhSR9IjVFCM/p86cXBELYtBiT7BRgH5Wuw+N0+aW2QiYp1Mz8hzkW4Cho6/WDaIi/4NvoNlsrP9YavscoQX1lYIVsT2ewxZdI61UGW3QRS9BK7iLfs+ho=,iv:6N/48REAi6IYklk/CPuqZVFtUcT0ra5KBck9XWMIS7o=,tag:IY6ugcT/Xjn0TPslXcHJEg==,type:str]
    version: 3.11.0
