apiVersion: v1
kind: Secret
metadata:
    name: trivy-dockerhub
    namespace: trivy-scan
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:4wTx8fPgpLngQi7OePg/3c30RVskgtmVa6FnZqJ6xqwWctArbrsrSP2z1MBUrHyDOXSPF/mn754h6MR6RnNz9+5/tTlSawXzJLIyspGRYrQ8lpGrYjpifWW0KccW/6pzkYKqkrcKd593,iv:oexQKlwuioQrp2BG8PHo+/gJMEWARFi0YEKDefdMF3M=,tag:tDwHTIDSkTM7icm1mXbqug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQmxteUNvbDNrQWNvTUZw
            WkJZdFNVQXZRVDBXYW9WalN5bGhYc3BjZVVjCnQrdWVUNEVqaGVOSDFwV3g0M0hh
            Wjdoa2dwMVZiejFnY1kxckNkemtHekUKLS0tIDJTMzlSK05wd2NUMSt0ZFh1cXUz
            MENsY2ZjaW1KVXQ1bEZHbnMwMTMzMEUKADsGAiXOXZm3+Y8NfJivxcw/HQJIN++7
            pG2wFfnYtZsu4ggaO/7WuO07nRgKG89TEb7IHLg5d00veA0DrgfFLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T21:14:38Z"
    mac: ENC[AES256_GCM,data:geDvFuwOeoB3lJTUtMjq7YG7V25Iytx460CqMJc+WALnClOsUo/4xp96pDtY87lykSX5rsqo48BHKiwyQeN15Kzc8CFpC1JtHeFdFNya5bVpoOtJOQkyDfUKvKabBlA4R3Mj5qtNzuAbVq/0N+zTLPihCJjP5lkYHDzH8JBBRfo=,iv:hUKMi5QopbiuLGelUl5z1YaV0ajiq1ASzI7GG7G7lvo=,tag:DAnUKHjxz8yP5HtOGR3Pfg==,type:str]
    version: 3.13.2
