apiVersion: v1
kind: Secret
metadata:
    name: trivy-dockerhub
    namespace: trivy-scan
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:swXYi4kqJOIWP/MgTgXD1LFyZF2CbGTbBNZQa//qw66Ju2KrdowpCbE+PT3z3jFsVjdf7f2fyr/x7BxahtoYbG3hnhtGdcORT0Kvzq9D0CEhDXq3CYCE0Px8H1T/JrHTQRp1ehWbwf1vP9C/TtjorNGPx+3M,iv:FyNM/3YssVgG6Wj91RerPPj1Jhfjl0/0qPcKi4bzgrU=,tag:Paa77rmto84PBashEvm/AA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidEswVi9QaGlDV29yMDgv
            Q2ppUzdUWElFMzlZZ04xQXE1NmNpbGNTVERVCnBNaFNWeVpYNnJXL2NpTzJVMlRD
            ZzNzak9OazFaMzNGKzl5dnNucWtCWmcKLS0tIHpwRGxKUE42L3cwNDVSaTFWNFM4
            eFM4Q2IvYjBYM3lyUzNmNkN1WDVIVU0KpHisxO8yGnz92Aj2hoX6/TJ5zD5IofGf
            508oS91rF0X0zswQ9amFRVj4Y5KaaNjheSUoCAYwEzBj/F3qeDjGXQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T21:29:35Z"
    mac: ENC[AES256_GCM,data:fqq0RnarpwKMR3qqJl1vBkY8CYtcmPfb81rsHh4FHn3Ehrn68B9fFo7OFj/XoCu16cMhe/D4azqYCABrRD3iw49SxKPVjZAmqBpE3W8sN0wfTxsTzfZGotc0IFjabIdltoXLXUvGiWmyipjT/ZYwaMmjt7c7v07UbCQoiD3xkvw=,iv:Q12wb5TpIwYMfpUClXQt1jVQitw8RpygQQ0glPCygL8=,tag:EXYM7PAPBlKmadPOzmmqtA==,type:str]
    version: 3.13.2
