apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/databases/postgres
  - serviceaccount.yaml
  - postgres-backup-cronjob.yaml
  # App-specific database users and databases
  - authentik-db-user.yaml
  - authentik-database.yaml
  - immich-db-user.yaml
  - immich-database.yaml
  - immich-init-extensions-job.yaml
  - linkding-app-user-secret.yaml
  - linkding-database.yaml
  - linkwarden-app-user-secret.yaml
  - linkwarden-database.yaml
  - mealie-db-user.yaml
  - mealie-database.yaml
  - n8n-db-user.yaml
  - n8n-database.yaml
  - paperless-db-user.yaml
  - paperless-database.yaml
  - wallabag-db-user.yaml
  - wallabag-database.yaml
  - update-extensions-job.yaml
