apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-user
    namespace: databases
    labels:
        cnpg.io/reload: "true"
    annotations:
        cnpg.io/cluster: main-postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:2ry/,iv:qNOR3oANYC0f1B/Gt1O0EYzwWLz8A5Uks1yGOzSexJ4=,tag:KzjUo1DrKVzcqxl0x0gLiw==,type:str]
    password: ENC[AES256_GCM,data:4RSisZomRSwouzC1y/O4zESoXyYHWAr3aF3mrplCN6nfbmLduSLiOC8IZJqCWIVV806c/t7gPt7etcCyOJCcsg==,iv:Tzw1uHoW0QogZJIwXZ4ex+O84aPS2K7taw9+09GM1oE=,tag:E0uXT97vvUKbIkDuImcr/w==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YjhWK1k4R2J0SCtGaS9h
            OVNscW9ORkhZTmZSeG5ySm80V3JuNi9QaUZBCkg0bjB2WlZEOS9RdnZxakdKOW9Q
            dnVNUTU2QngxUkg1c01Vc09UL1F2Z0kKLS0tIGRRQk9IU2Z4bGdqZW9SZklybEdI
            aW54Y3pCNlNFazJWbDIzLzhLeVRrSjgK5vp0uSrR7tQfz3d2FL2T06d+Q+nwaKk6
            SR5K3mEMzTI+GkwXhPRABEO28dGl+dgrFDLtJ0/iwxGTWGUojeY09A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:41:18Z"
    mac: ENC[AES256_GCM,data:cI9cBb39fn7Cv6pmW2N0dvHALRpC3TSmBWJYGs/ry6tw0Y1IpcdTjGy6OVrxQSjqtjOtigbZOXTuAInesQjo6Xc274yly23vp44fUV+JVNsW71VOpT92WHPZTFJ/0f+TmLBHrFtGfcvhss8BtI05IX9G+dS1CFG6Hei99AdzndE=,iv:y6uJrbaJ+SupYzRtkx4MD9GHoTHHXdzImwxX233Sn/I=,tag:NI4nNt/E1TXZyN6w2dBuCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
