apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: couchdb
  namespace: couchdb
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: couchdb
  endpoints:
    - port: couchdb
      interval: 60s
      path: /_node/_local/_prometheus
      scrapeTimeout: 10s
      basicAuth:
        username:
          name: couchdb-couchdb
          key: adminUsername
        password:
          name: couchdb-couchdb
          key: adminPassword
