apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - crds-helmrelease.yaml  # Must be applied before operator
  - helmrelease.yaml
