apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:sEtBJw06Xt3TV3BAqmIPM9W5OMTH9hECfxwgytH6nfciDXeCZL1JuBZMXKCE7EVbWgTiz4w+LqHUA8cphLjW0r1AM3/NKxo/dlAkcuPkKXT2SA/dMSrC/QkfHdxsZ0mPNoxNgPlMAI4qJW4gHMxpkBRFhgf+XgkukWhTAQtlyzj8Lc1DIkq+wYECXgYDIU4WKsEVrCIsJk2aSxi++G7PBzxi5BfxMA4K35zbiw3t1NrW7WzdKUJ374Y9sxPJ6EdxaIxsvhMjWicSOtoe4/4UbZKUWqxC3gHwkF65NToy6AqtPe529ZEFCWtIXpg=,iv:PE1kNR4j5Y6JpDmUwQyXhHx81DCDj9AGEVLQHto2II8=,tag:BeECEG+SMcQtXkZuQKZXPQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1gzsym5v633tjlncmdhktv89w4p7gmurgvqwcy2xzj8jkmtygtqnqt2jxg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2L2dSUkpWUmhKay8xZklj
            akw4NW8zMkR6djRraExhOHAvRXg2QTAzamcwCnVmdE1XN2tJdG5TYUx5TWtHZEJG
            ZVFiTVVCamlqSTY0dGNVMTlhQk5MQTgKLS0tIDRlQkZjbXpWZEtzNUx0bmFQNklo
            YlZpRWFDVG84UDlVY1F4bGRkY2JiL1kKfK91NIwEIp8GT9XJEWXU5gMUMZZY2E3Q
            bW5U/YddQR8KSgAvPTQNES2C5VqNHCHda8avknLR6GoxTWMNDym58A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T22:04:30Z"
    mac: ENC[AES256_GCM,data:rNag/dxh39oCYlZ0lq0PP7UijEeNqfDJT3V21zc0LAFGofd1/kwfcuZC/5rJfTt1hwz2JP7Jl8auGqHkLT0Jw5zeT13Qg9ekeWE0svAgrIXPXfk4v3umrXYzDJFKa4J6S8qpWYf6nwISDFTVbw7i3xgWKIIvEcqm82zB6jQUUAA=,iv:eQDLOz2cDLy3qqOEtMNLDZIlj8qd+Cw/VztprosXvOs=,tag:0cKxOccj/AykGNeOwsZ0pA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
