apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:jweLyf+UQTJ5bWr+utTVmYJG0vZ2QZtNFbW23busXqiZDxKUnFy2eA06kjNAaDf4vzQNIMMqlxZR+j8E4V7FyxYhpOn0yjsiGucvqmFW7RtIkXxLxulGf+7wbTAqIpKko1eEVI/ZetvT5R8Ojtjmp9Jol3xT4xRohH4ngIOTcuVzojBIRepPRXiCgVu4PtWeSRQGS+P/JJaan0EQUpNyaowBSQxm43A1H9RvTBDQKzdQjxD7xFg2kEbsTo4vuwcnENBwVVenBG2vu9afmqrUa2nGCXjjo5zCuQqqAog+uHjbw65ApAwMyny9MN4=,iv:Ivnn2WlC0YTMZILs+QsVLSOe2XaHFChd85ix+loMsDY=,tag:pOVK+Sa29wvFCeQ4cApvWQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age15wyev7l49up7nan7nwc0lk3k53kmkd37566cn28djsz036d7fqwssfahtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKV0NCZE5acitUNFZMWWJo
            UmREeW5zd1I0aGs1cWpsN3dRN2hnVnpkRWtZCmIyLzVXMGwwditXL0EzUXpxNnRn
            RHZrTnJOTGsvb082d1FYTmJDRDhXOEEKLS0tIFR2NUgvbVFsdURqQ0JVa2ZRRXZr
            L1JlZTBBSkw2b3BPeGpEWStsZ3B6QVEKNV8PUwbqGE/GOehmcOwP6z0VSBnpD/OX
            ScRYroJeZ4cyeeR2cSMH9a6xAUtPu0JQlLL8wovo8WNZ/l8OhG3DJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T00:44:59Z"
    mac: ENC[AES256_GCM,data:247QyHNPQ1u25v3HO9cKkZNFhKXWzaqlzuIh60bN2ty22n4EHYrX6tCrYA1X4Ne2qEoqvuhhiV7ifUd0ra9ZHbUVNN3SzqIh/61Y4UQAmyQ91r9dQJu99xx7ls/+SfTohq1QdRBGxSb85tv1+aBguQbq0YHWsvOwKXojOUk/9Es=,iv:aCL1NiL3fKdujeo0yd/dM462w9KXz0JvgFwWwMzpVV0=,tag:IGFAtNFzcWsA+4xlv4vBvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
