apiVersion: v1
kind: Secret
metadata:
    name: linkding-oidc
    namespace: linkding
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:HXlPjCQxhP0=,iv:1bCZRJbg02tIF7z7enLA6m2FjJrYsKZ4n17c4cnfcdk=,tag:rjYt+4MCPKt0rnsq5B6BYg==,type:str]
    client-secret: ENC[AES256_GCM,data:iSEc92QyCs3N/pzcWQ4zHacwn2YQU4K/WLvXyUHqSnQhy76DNOxdVYzC6bhZoKrvLtKg17nejkZkWbisRFWSKg==,iv:DHWtWoBAqzX9Ss75pCVQ1m0zhf1aaTlVAYPZs69GdNM=,tag:Pp0HbezNa8h3UgJp1JXpMg==,type:str]
    issuer-url: ENC[AES256_GCM,data:80gPlSoDMG12f3Xap4ZtuQRc8lVGLtTcvzh+HQKI48ShAzADrl7nuNphkR55BvYZj7Aq44KN,iv:6gPGE/Qfg8JoYPwNsx9a7TrrTnHXd6edMhWSaZ0NRTY=,tag:F15eVW8Hat2V522xOpvjFg==,type:str]
    authorization-url: ENC[AES256_GCM,data:vmgv1uD0wlTa/XlBlYo6ME6b6dpEqsk5yxHbUGRP24tZqXbrKEyQW4vy58LxJUFXoYpfiT+i2w==,iv:RCjfopxOdOrqC41b+FNJxzLoeo9HFDlrf/ZoCiQ/00c=,tag:FlDFuTlZqFCB4nYRc60BvQ==,type:str]
    token-url: ENC[AES256_GCM,data:wc1hnzZu3LxqPUMMXLD+jCxivDLg0qClEEYl+Z9X8Zl+NIQX4TctgN/sC2bbxqhCpksg,iv:QHauNWFplf/MtM16EYe0qtfxQBlWDAT9vxhY7StwZHY=,tag:/MkPCKgI6eCdNdpx7NxvXw==,type:str]
    userinfo-url: ENC[AES256_GCM,data:7gfyaAWH95eD1X3zhX2cOH+FMhtiQ1Yy6pHRIxtVbSlTOpVJsGoH068r2oZ0xzxzHwCNdKlU,iv:AEuwLCVYs6RpvtiaEFdXS5sCzlHuY4Lw6KDpk3UZjvo=,tag:Xqemd9Jx9fImuP843WcCyA==,type:str]
    jwks-url: ENC[AES256_GCM,data:l9rTq6DOghNxCAqf0RPn83WyURRMALSygNaJpbxXOP5U/Phu4sY4km1vA7JMn2jFFAqKOBE+A0iY330=,iv:CbxJM46fuTPy2cYMjGzr2szr0KXVTLmqbzpZChzC/cs=,tag:mw+VptgxkIYaA4ytHVFYNg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNlNSNFMvdVNxcFBhY25q
            dkdLVnF5QXFqa0VUODQycVNoR0ZKWm9aVER3ClVtTzlra3EyMmdoTEJUYVVrQjhr
            dmswcXBMYjhRakMrV1Ezc0xTVURTckEKLS0tIDRWcThiUnBTeUNPL1dwU3BiK3Zx
            NmNmMng1SndtTGl6MDBNWnFETjRXcHcKyCdm1COgzma7LXfNwAcfCqzP9eIhbNDc
            RNKq3YgJtYUwAXNCXisuVbBVvvVHxb03R9tYASZRPZIXXPAFKgoosQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-20T16:10:40Z"
    mac: ENC[AES256_GCM,data:shH0arcCdDiFefzXRJX7+96VI8BO4O1+DygNSUMi38z1Gmc4RybpvVRqq42Mc2Ya/tXoPiWZi+BbRdskuT+bLzVrSwwXwkcG1BJayg/3K4st0vDCDvtOcNZHyJuyz5jys+o41gM91zU4/sMOqIB3sIlQdLjHwJDZ42B5Nv/v0jU=,iv:LlwnyhGsEAdZl8K0HHfAxXX+fPHm7tVkLxhFxCghp4E=,tag:IhxzZVOPCDZVOcvCYVijEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
