apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:XnhX0otmtTNVFgQ9,iv:g4IkmpV+ahBlQkXfx1t6u0emfOm5GHVCDFbRPhJTUPE=,tag:oOWfOLpBSGg306QZIl7umQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:RFwbir++dbMDXJFarYn4++1fu2SSlNXf,iv:vabiCZqiGTpqhovEbPc4+njNLjJqdqn7x/WO1ZIZHUM=,tag:2ThZxhvndbUCRT9s8QFJnQ==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    age:
        - recipient: age1gzsym5v633tjlncmdhktv89w4p7gmurgvqwcy2xzj8jkmtygtqnqt2jxg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOHhYZmhRT0Zwc0RxUExh
            dmZRckhBUnUvYmN5YmpYWFpDTnhkWGpjVmg0Cnp1YXllTVN6Ym9ZcW1vMjh6cndK
            Smo3OWhoMU9BQVRreTQ0a1RXQ2M0RDAKLS0tIDhxVjhaN0lnamJ3WWZNVGk3SGNz
            UEN0SjJNY1Z5cFZodzlHT1d4OFFsUUEKklBbBFs6bDYejktSiX5ofHkW/yu7pw6+
            db20J6tSqYfLCQrVIHY6tJMR2drIk/Fjim4i+iGz5vUYOfhcS2fiDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T22:09:49Z"
    mac: ENC[AES256_GCM,data:Vi+xlru0sFTeboQszNAQpRKP/MQUKOn8P/LrJ8rhqLO8gfMzIlBWS4xliG1Veo5O+5rVZWsDCvdrWM4srEVFvcfJVKciwwJN/ii4R8c3dW11+L43Odgfd4Q6nvAIRtctrVQ5Sa5RGfKyEyEZv+DfE06sc5QOwg+9jfpWJeqg3RE=,iv:4NqBSWNGpxVU7Ks1azPUX+aUygTHbYOvQMr9WJtQpzc=,tag:d5z5r6NA+rPmShmo0ZMNTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
