apiVersion: v1
kind: Secret
metadata:
    name: linkding-container-env
    namespace: linkding
type: Opaque
stringData:
    #ENC[AES256_GCM,data:FtDkqllpqOAhA5KMy9KmpWmOZtSPKfumwiUbj83JcFRxKGwH0QwkHwSwkS8sefcR/X//RVes29yuxoqw,iv:PPTSpVt62sHsR1kM6KBHS6EQ5CjHtuchcPOmo7ffG3M=,tag:fkAesUBjBzVvsLUG7BqAsg==,type:comment]
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:cKYbinEt7g==,iv:+0BVfMzBqO3J0z9EbUUOUSXljUGGLvF1yjjrX8p2gG4=,tag:f+l9WJDnKJloXa+9sBcUvg==,type:str]
    #ENC[AES256_GCM,data:iOPlHpqZXrWWZy5evJLX4VW49W83OnCzAbQEkV8WYA==,iv:rIMp8yrvSqzZDadwS8/cgkmsc1lZEgJCsBmIJ9fgdbc=,tag:nh4EIM8/N1y2TeW2XypCYg==,type:comment]
    LD_DB_ENGINE: ENC[AES256_GCM,data:e0MXK17XbgA=,iv:Nh76d2Ex3dXKsGUeJaWSwwmY89Cw73d44wQW7/EXidU=,tag:yifVEB4J/6ixxD04OC2Nxg==,type:str]
    LD_DB_DATABASE: ENC[AES256_GCM,data:WXK1t5byXmk=,iv:eKnzmF2HfXezzwrRtVdqTNrrFwqCxPwE8ideIWGlHq0=,tag:KGBZTZyX/TbIUm63BBUXWw==,type:str]
    LD_DB_USER: ENC[AES256_GCM,data:NLBZK36M9cE=,iv:1LRVzP8QUPMbjH8hhst4+6CFAG1363f+Fe5fQtAGDI4=,tag:e6Pt5vRZVoVBdysHF68wnw==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:8yd2Rp+G7sdWhUqFqtam2CrWzgMdb9U+eTgZwuTDSgTuHRs/Idc+01Q8On8=,iv:un7gw3B0/47rSznIhSxo5pIvQqtnPKa0XdWRfFO02Lo=,tag:uVJilYGJa83oPkWgDZ2mZQ==,type:str]
    LD_DB_HOST: ENC[AES256_GCM,data:w2pi41c5NzakBue4msLuAqBFpnLq6mhKVCaEjsqNJ7fN/JBnr75GbXSgNw8=,iv:Xj8h1BZX7+2qsGjtny8JmqJs1jVue/qhNmwmtgMFqUg=,tag:JQC2ZZOuLMsYWzAzTSkNXg==,type:str]
    LD_DB_PORT: ENC[AES256_GCM,data:cBApgw==,iv:TU/7KD3SAj/TBHjInF5UgV/q5bA8SV9x1R/L8y8tzNY=,tag:ZS0UVnM4kVc51PFXZQkg7Q==,type:str]
    #ENC[AES256_GCM,data:XADzxP9CqIkRMP0oZXFUCwxikKtsdHA=,iv:mKF9FephuPRyNanUl9fCjxDQmbtk/QXoDfnQ6Vd+/GA=,tag:fJcjntfO56et/J+cz/KK7A==,type:comment]
    LD_ENABLE_OIDC: ENC[AES256_GCM,data:z234pQ==,iv:osgGIUAmmb9sxNIuHPbW/WrIDzVlw1L5jooSt6KS0Jk=,tag:fg0blNDA3DmFRSPXiCRkCg==,type:str]
    OIDC_OP_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:LfoJINzsZ7KhFYGQ0LVDkL32S9sXyRdJgMa/zIk4Dy79CAtUwfLLPDefYBa0EXzHmRPQ5Sggpw==,iv:9E9V2F6Wnzp21yEcSJJ9Tg0paIkNWBmKn1yDIhy8nmc=,tag:+7dd/Z+xzqziC13h16fzMA==,type:str]
    OIDC_OP_TOKEN_ENDPOINT: ENC[AES256_GCM,data:SKKE/fKJfrit9lpooxirpskJVMc1IZ2DRwU6x0PBWE1cK5xrfESucfU2G6MbbKbkvtKo,iv:o5Qn2A/5xaoNDwvl8N1Fdq8wlvzFhiCxNlqRXl6qaW4=,tag:PtxZpcggyEkEMfINhGxmMg==,type:str]
    OIDC_OP_USER_ENDPOINT: ENC[AES256_GCM,data:IUugCRm9aAKzPTOWZDJD3ATHf88FUMVkhGjnEucGh6C0AHlcebvUZ7NgQBm+5MR7CoaXaJl8,iv:F4xjO1+owCK1397D2QNBGzV06t9Zfw7Hi+/aLJPDOpQ=,tag:pzbWzCg7x9Ey75TDqYKm5g==,type:str]
    OIDC_OP_JWKS_ENDPOINT: ENC[AES256_GCM,data:t7LgITglOoQ6ajp8dYDH5YmRnjf/wvWWIx71ij9AMuRvCqmA/Llr5zkQeYlAjDk14lAOd/W1fD4aPws=,iv:f+uAFSgJsPXuRBsu9nQ19lyBGECL1QPfPnnY1vyaF4I=,tag:oU6t5ZdFXVYm0+2wJH72aA==,type:str]
    OIDC_RP_CLIENT_ID: ENC[AES256_GCM,data:vsO6j0EF0Ro=,iv:EcjdS/OmVxlJypdq7ZAmD6aE8EHT5btnY88SdpbDQ5k=,tag:zkU1NV487dMqPTCSU/hh4A==,type:str]
    OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:S46wZSz6IRJX+44NbD9KXypecEx/o9oQb9C+AWEhtw8LQgHgfWhk8MF+A8jlrCruXb14yVa50QtZEpT85hnpPg==,iv:CXQbg1jFAUpjcxeRY2QH9JUxJsIDJS6WlnbEu+EdtTE=,tag:GXKop6G5ttFPpgwCXO6MLA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOEVGZVFHUXI3OTgvbDZU
            RTFxaUtvaVFPQmd2elRFRkRJcEwyY2srQm5jCngyaHk5Q28vdzdpUXpyeGMxZkJR
            bnBQYnZ1UzNFeHRWK3dNU3RreFlyajQKLS0tIEgrekxFK0E3dlhLSmdsRFFiYW1U
            Wnk2aGU5MExSb09oSFc2aHpVcGZBZXMKBAberB+TqUxcMMCqWu+guE+kFhETEdnO
            qBhc0jjm/UtpTcM1j9MFL9Y8omLSdczUNZT+0+4qMz1o6xp7cdVpSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-21T21:27:32Z"
    mac: ENC[AES256_GCM,data:mtsXMJWSw8SC1+Z0ruDuVQ8RmwGwJIzPdfnAGbQLTtY4p0Jhxl1gHehEgoFNmEtLhWno5dMF2wjFsahx/nN64+mKhq97S2sI6EcEfmHY2CnNe416JSrtpDeysrt/SKIsbNEEmWJO+YkWUTyXDOZXuvbLfBO2s0482KgcRYAdGO0=,iv:lFUI+kvrBNlmageNte6TqwNnBCVZ2Xc/D3YdgOt+d6Q=,tag:1O6V71iL8caTAwIJ1epGgg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
