apiVersion: v1
kind: Secret
metadata:
    name: linkding-container-env
    namespace: linkding
type: Opaque
stringData:
    #ENC[AES256_GCM,data:z+JbwI+DHyL8dBDkKzY45ZxcYg3fBWILwnGT6TGbXGVDDfEzvnBaCnl+V/8fS+VN4vjB1L3TQD/V4r2SJ3AfiyvFXHjsHGG2wfP6XCzfdg==,iv:Z4Rpn34BmiuDlpYSvDZIb/igaeFBjLzR3PGp1bkqPQM=,tag:I4VrmsdprxgdEYmieDryYQ==,type:comment]
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Lnuf8mHVog==,iv:7lA3Tp33Th3xJEAuvkoSJBhPu0uIXaz/Azm72SeWRv8=,tag:zmZiNo60U+4fyIKGgIJh+A==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:XA==,iv:FOeOjxd4k0dMN8gV+782XNqc0ZxExCRVJlv3hnb/66o=,tag:5m5mOhpx/jrxwg10J8scZg==,type:str]
    #ENC[AES256_GCM,data:ixVmDgpPhCQVFSk5gClkJleAYN0Bam6mVt8MfVDSqg==,iv:cEpxMWSCNGSKqe9qRO6cx3TMiwZ6/EdSHN7kBvCreIA=,tag:5l5rEB0dvgUMPcr8MZ9arw==,type:comment]
    LD_DB_ENGINE: ENC[AES256_GCM,data:WGVMoQ8ziyo=,iv:yyjyjBOzRANgpW1SS8Z2aLVe0XNxmOPRJSqc+QLuwHI=,tag:FpasAhwXS4R2o6cHfXkJ9g==,type:str]
    LD_DB_DATABASE: ENC[AES256_GCM,data:+6WAKEHwKIw=,iv:GHeQQicNkDXjc0I67Tf/14jJkFLV1E+Pcqq6VRVW3nE=,tag:dTovmYQBfU6UUF5Bzpv0UQ==,type:str]
    LD_DB_USER: ENC[AES256_GCM,data:hcUlytpW9WU=,iv:LcyBWS45RbxUZbSm/KYMCZUjTSklM1NmWifwNPHnzyk=,tag:Kzlal7XD/9l2R6ouiGOYXQ==,type:str]
    LD_DB_PASSWORD: ENC[AES256_GCM,data:1robZTrtoyxwB8PVroKWygltdqbW7p8kfJJNBA43qUIymKzuFkFIvB3kYnc=,iv:rSl8fWG4tZvccxqUUoIM010CRoQO3z07sGzBST0YipI=,tag:99hP9WgpVAnW99LaBlo9AQ==,type:str]
    LD_DB_HOST: ENC[AES256_GCM,data:fGboo/64WMaWCytdnNoaZ+NkRPQwFXJAovMUGUHRY2bJVqX/1q459d6fzx4=,iv:F5vtM44/uDXsiJmAK7GuEZNLoAYeqGp2uU+Hw6usPVA=,tag:bs03hOUjpnVHaddViprs1Q==,type:str]
    LD_DB_PORT: ENC[AES256_GCM,data:TfbhDQ==,iv:pdPtMPfjyc9ufFBfc/2jEuvw6QwdrG+qJMw13oNOkU0=,tag:/Sw7+jJFY7jOqJTHT7pTsg==,type:str]
    #ENC[AES256_GCM,data:T4y9/+PQhuA3TrFq/JLRw5kZ13iaajQ=,iv:yLfRsnrM8wWfh0VwP+Up0gL+/F5UczWawNnJC3faVlU=,tag:0rn8xV3l10/ep6J6J5wtxw==,type:comment]
    LD_ENABLE_OIDC: ENC[AES256_GCM,data:Dj7Wrg==,iv:UAxHYIrCcGPP9nsrZBZ7Mooiluu1t30Tm23VqKQ77Ww=,tag:+jeR8dzypXp105w47A7kEA==,type:str]
    OIDC_OP_AUTHORIZATION_ENDPOINT: ENC[AES256_GCM,data:tTNqPUKlx6mePCs5Z9i48aEgSONBAFzYD9bFMmVW+sHWBl97/ywrHC7RBJ5HWskyHs0qBZFwEw==,iv:fo7tNphWbP/0+mzpA1ZKtBhgDd0jdO1DtAjn6OJx+WI=,tag:Eqp7a/P9msnc7Qm8MovxKw==,type:str]
    OIDC_OP_TOKEN_ENDPOINT: ENC[AES256_GCM,data:cxDT8d1R4Mqdil6LaJMXJAGGjWy5EJyY31Yy+ZkRDPmu77B8/cgLWTsWZdIPQcQ4msBu,iv:0tePNlIYELPjA8ppWWX9VoYNocrMvmiVFJ1mnGK0EtI=,tag:xf6ZCzdS6Gr2OtY161ewxw==,type:str]
    OIDC_OP_USER_ENDPOINT: ENC[AES256_GCM,data:eHXZMvEpmM3JUDPRWZsbd46GZLZzv2O7P7VZ0fd/wzLpWsw8cg5lG81Ou+qnock3+IEEg2IA,iv:mSTLvx3ho2UZUjyFDH9tkRrG7JGGXm7iaBSSORj5t1Y=,tag:gK3viLeV6vEZhVutuqTBiQ==,type:str]
    OIDC_OP_JWKS_ENDPOINT: ENC[AES256_GCM,data:ApcRY46I3afS+TXIqa559okGoGLE+1FzWWxdOUXDirnGzkj1xoZWI4+kfOknOLGS8qdE9973gswybcg=,iv:yYoHGWBkwcja01YX3VK6JNDxnIS3ShWXdqbmDsV2lmQ=,tag:7SPoPKpBC4o9Fx/Wz1IqSg==,type:str]
    OIDC_RP_CLIENT_ID: ENC[AES256_GCM,data:/fqMh+uVGik=,iv:DH7IvGpf0ej9S2BxoRedTYlPk3hS+adZgqrmgRGD8eo=,tag:H1CYatybq6VC+p+2lG+PVA==,type:str]
    OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:HmCMr7+gQ/l+2NTV8/eMp4RmmFdRMzOJpTxetln+ICUQS6fdMJS1GlHGx+1/lalB4Y89bVsYCBw7UoM9kKUFWQ==,iv:bHWShDkzu5jjuL2BEhomLrCPfi3WvYU92JlKGOZWQoY=,tag:fgtE+MABgTZLHSp/hOifKQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOd0NyTjYvN0w0eExoMmI3
            V3R1L2ZnR3V2WVlsREg0Q0l6K3lRV0VoYzAwCmpxdE9ubmFGQnZ6YkUrcjFtQ3E4
            Y0tTRGg3ZnN4cHZ0U1ZwNTRVNEFNemMKLS0tIE8rUThHOG02eEhmZTZLVzNPVTUy
            Q1p3N05Kc3pESUVXUml6WG1yY3BDL2cKxhUbWvwVzJghqJ7I+suOGVKg8HEsTC2s
            makwmUZcJHiCcUTvEGxQ9ELhsa4/rqprT87CAMw9vqjL27ZOZuAkSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-21T21:23:38Z"
    mac: ENC[AES256_GCM,data:Wa4VkNcgiIyFvz7Zan8u0nNvJY/Gpi4teQSI7srPlND1rqqAZuhw22AMfPPYdFAJebzbjkx2wvLRpzRyZas60IVDR9v5XJcv/u3my6aXxyGmjy4qmIIFX/f4rjaqA52YACR7VYgk8NUGqgSw/IbtFf8bJXK1cX8pKO2JJEv2/Tk=,iv:ladSzyuiYcaldt8P855nO/SqNX5CdfM4bJb3c9wVPB8=,tag:retIioUvy+KOlIxlxEfD8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
