apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: cloudflare-tunnel
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:+i0AVBS9rKJhtha8yX6fGSfwwC2CDrr3vmvk3uyypRbZ8myX8rqtRadoH6OUssyUMl63LIHRrekA5YcL0m6pI8285iA1ORE8VQRYlBQfoRX4HlJa9lOCkvXAdZXb5suat8N7ERllnVn2LRI4b2SlYNh80RlUSiR5jv4bHcYUBfYNZOtFcPRZnES96xYLgUyU7AwPE3hpKNCCk2CKlQ7Et9+rIobsdrWl6qAPRek45wI=,iv:X7rZ6f2eQzkbdWKJ8t/o2qFNWeF9wDxREUxcvUMC4Dg=,tag:H1L57fWu+0OjpoLaQ3DzRg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWRLQnpkVzJ3N1JDZ0pJ
            N2Z4akpvOWh4c3g5a1VxN3JjL0dtbmtIelE0ClJ5SWI4RlMrZ3pQZFZSc1d1T0pl
            TjV5Z2ZxbW83QzIvQkJWSVNoaVFaWDgKLS0tIDJhcjJncUV0OHZUUTVxaDdhKzF6
            cW84TXFLaDk2dGpQTld6NkNkM04zQzAKGxLqkYqoEuvIEp+kH2IxsLHCMvzTgdAM
            Ipc2GxM1igzZ1JXmnvFVJH0nmK48mfZ238rbSydTkdBa+HmxA1r6Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T18:39:34Z"
    mac: ENC[AES256_GCM,data:dQKi2pFohzOAwuW+TeO1E4vCh3UaeNv2ku5IoqNmhPmYkxI1A88qAk4ZwdnG9xykx6vaRPXa2ayG3SGF0YrLS/XADKJkJ76thnfA0FeqGmW3TxZ7V2AZkbb8jwpiYeAVtaSK/n09wiOvp/uY0fedf8B5jIpbo46TO4tNWwWs1DI=,iv:oeSxoHQfsij2AJe6Vd+TuqIvHIYecxSLnDn8afT+KU4=,tag:9Sd9rzMjyS+K3jS88wBAIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
