apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - storage.yaml
  - networkpolicy.yaml
  - user-provision-script.yaml
  - ingress.yaml
  - certificate.yaml
  - mealie-env-secret.yaml
  - mealie-user-credentials-secret.yaml
  # OIDC config is in mealie-env-secret.yaml (OIDC_CLIENT_SECRET env var)
  - user-provision-job.yaml

components:
  - ../components/allow-dns-egress
