apiVersion: v1
kind: Secret
metadata:
    name: mealie-user-credentials
    namespace: mealie
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:o4kjlrTHUBZbOCQ6rg+f2IHEh62yR6IVhqM=,iv:PLdJEJ/q1eEygcvZKb9p8Ovf3i0EeaXoxBAbqRlyvL4=,tag:GOWMeBy5lJV5NVw15OYsjw==,type:str]
    username: ENC[AES256_GCM,data:2Yayqe2dPA==,iv:TVGZVlTCpIQZcpF0mKhjA6Lo1zEG+MJqT5mw55nVAm8=,tag:dE43RHIqiuh4t4JdMJRLSA==,type:str]
    fullname: ENC[AES256_GCM,data:PjtmBf8NFQCXNURsWPYb3w==,iv:mRheFazPoA/p7Yr4jKOey0N3fWOY/Av1eM6q9o7I+fM=,tag:cE/z5jF92h+W15nYfQy4PQ==,type:str]
    password: ENC[AES256_GCM,data:Lg5yFivCgHqJGM4j5as/BuotK1ued0/rrF0MTmNSnwCzX3McrrqcZKEs+z8=,iv:z2vnunfaIK9fgHN/mv4NMrQEttUhvquHNn06IWDWqNo=,tag:EwSrIMEf8AkxgQsQhXfBtA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVTZuUEorQnNUR0JTVjF3
            RXZqRjhZQ3VLclR2bXlXWVo1VjVjU2pHaWdBCnFnblpYK0VrNWN5UW5oYnd1cS9J
            RExQaXJmZjVCaHJCYUt6L2R6cSt4Wm8KLS0tIENtTkhDWXBVNmJiR3dQaVdPSFcr
            dnBYNTlwRWVQYkcrVGZ0cnFPblVCMEUK7sfZq/A8DW4aaOR08OsqmpIqaSQQfLHw
            wVf/dxGKxHtdZNYZiiu4hxaBfmyBVf7QlUMqvGdcyXiGSdSpoOVpwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T18:34:39Z"
    mac: ENC[AES256_GCM,data:ZZxWGKSrxvwfjR4F7J7DLn47Dt87xpjZXR/lrx+4luMpmL13Db3HjKkxPWeJLK1U43eiu+x736yIQ1KMEFoey/XtJQy7fp3M4rp0HokvKvMubpYf8X/i8offKPdh03XYJDoaXkoYmu+HK3sozDCh9UmJQPQLxiG4OL5ruHMUSEk=,iv:q38dXypPDKU7kOXXShLO/Wzl3eImMBNAjFh5YRKvfpA=,tag:EXCcmFo+6FrZe5N8M0jCwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
