apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-mysql-credentials
    namespace: uptime-kuma
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:sH6YJQoyXeS4EA==,iv:av7WbJKPi57TuH8rlbWIePXwGZi0K5NAiA0aLzFxrr0=,tag:wK8LmANZcja4iiqA7kgAlw==,type:str]
    password: ENC[AES256_GCM,data:+4jB7+NqVazbGkwISW+U/Jy1TD1InIi1Xb/JsHJIXmoB5I+hIR0de0jcg7nTl5eDNLeWIYF2z5gDnNnFgBoyZg==,iv:1lH+KuYqUo+e35mPt9MuGtrYL3c9mtV3NjCfKVTlBvs=,tag:rjS6NGilTHQNRJvTADvgDg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK3duYitmN1l0SlJZVTVa
            SGdFUnJlVXdZK2tjVGRJTnZLZmpFMFc2NkJnCjVLQUMrL1pvTEdTcDFMdU53bDU4
            d0RsNUZCS056UW5aZTJYMk9NWG9XVEkKLS0tIFZFVTBzZitlMFhZN0VQNXFhd0pY
            WmNtNm43RkVSRytnYUFFKyt6dkR2MHMKZQ+Eb5eoaNBAn0N8OhikubvZLu+6JofS
            MU0MvbCZGnyUbwZFCmfWG01/qrWwE1EymPT97XGKDREduMyX6cEbjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T14:43:52Z"
    mac: ENC[AES256_GCM,data:PpQQfw0Hg+nlqQusy6WekSCf+RDrUYYALmSlyHIYsLgEDSFpX9RVktIEitOEfNGjSuJP3NmoeMfMH1dcl7/jKX2ykxQ1ykMlgOWOGUB1oDWFd5zlX9OoPC5OUH2no8p8sOh/JxeAGuJmDddsV9DlBDonp6KyrIF+1D563cw9tMs=,iv:6yWm+WeXV6lg21lAdfEBFoZLkiYPJWXw7igeWBlHtk0=,tag:22uf5U5An2Vf4QZJA4PQNQ==,type:str]
    version: 3.11.0
