apiVersion: v1
kind: Secret
metadata:
    name: couchdb-couchdb
    namespace: databases
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:3SMm37U=,iv:/uBAyd51pwasgo9woThilKXdxK07xcMutNa9LfESBJU=,tag:pX1ECClPlroPQlJ//MEzTw==,type:str]
    adminPassword: ENC[AES256_GCM,data:8QAb0MpgKOU44B26QnjSO6wPkWnrVnGb0zMY1hzjKymJSHN174rBUTQi7qTTiknJPLaGBLe0PJqUvgIDrYGGJQ==,iv:84534FNhl4RynaDjLOqzXubfdlfqPEukoKTgj4IRdok=,tag:R+ceP8eJlY3llqQg2wjGLQ==,type:str]
    cookieAuthSecret: ENC[AES256_GCM,data:hY9OhHubn9uV0ckZwdULde6MF89LbeRR7Y6KVuocPfjkC4lIYbZ82acdsEY=,iv:H1IUORRFOXmD9mkIN53z8x3nsBhQwl8lQR+Y0F0xabE=,tag:9u4bxu17NckQ0QABe1yx+w==,type:str]
    erlangCookie: ENC[AES256_GCM,data:rmehb8jpRISpsom3j3D9DTHuNiH9jn1uqRZ+etsRBpwanWLUJmSIKuYI4Vw=,iv:p3KQHGSdEdr6AQVhzBmBkbHstIQsKZpbHbvbRhFalfg=,tag:qsEhFW1DEd2rQATJJ7bUbQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNCtCQ3pWUnBMUmRzZjlY
            WjNla0swa1pkZ1NwTUg5NHBlbXoxL3EvSFRzCllTd1VmYlRxTlJWMEZ3YzdXdG5h
            VWIxUnNHZUVka052MjQ3aEZuNDB0azQKLS0tIGIrQzJydDZ2bUg1SUs3cDVxbUx3
            M1NkVytMVVV4L296dDBHNkN1eWFvNTQKe1nROJYu89///U+bb64N/NPfi1SHIj3P
            rkc7Rz4kC0H4IvUoUUe22G2VOyietQ9gGaFxpNzP0bZEh+eqafupZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T11:57:15Z"
    mac: ENC[AES256_GCM,data:K96rW3JzkGOanhTubCJAPLLkYdvgnQEQbbp9Ty+RAsrmC+oL9QE4YSs6HrfXTd92dcMU/r0IeGR8Qo6o6nsnH+/AvZ/0QOc5oGmycvzQdmDnVZbXMxaPhHdFdnBnmrJZogHfKOPeiDmFZAqyZmB0Ss7Y60JxV8JfzS2k3RdOWCE=,iv:RZyPszjMzYyGDwAhW86f3CBuVF6VWB+Hrn5ObR8xd00=,tag:jrbKYu/y/owaMTMH15N2mg==,type:str]
    version: 3.11.0
