apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-oidc
    namespace: home-assistant
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:6FtFI2jsmDPQtcm0/Gc=,iv:v5ae4c4EKlp4KCEdhu2Coau5W5MK4fDHK49T3O0H0x4=,tag:4+f84RXUOi5r9KgGDqSYRQ==,type:str]
    client-secret: ENC[AES256_GCM,data:SZYSTczlDmTqTW5W15jgSOS/8eoC1t8ujI43yehKmKs918x3jO1SbRPurlqAC+ZbTP3FiaQBXsNaWv0fQijLqQ==,iv:+VDN6V6xgXfMMD9N8OvO3+025RaigOIxD6YFlinmZWs=,tag:H3ywgYu4I/qSLvUNnGvxsg==,type:str]
    issuer-url: ENC[AES256_GCM,data:b3oMI3kOE2l/EhIjFOimrCmg7HibaOFmF7LxGiUKPC/kHUaZZ2khhwPIQN/wn5n5qCTVL0m2uvqe+iRY,iv:oqxLeD4u1iFG+bWt91eVbtkQUrVJ3W+C6sRDdQmKyT0=,tag:hnNfn2clb7fjwiaOLcMAHw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcDhGNCtBbXd5bklEVlBF
            NHRmQTBYNGdSRWhReE81VFlCbDJWL29TUlVBCkFtMy9idHBnSEMzS3lmK0x6R290
            YnNiejQ1S1JtRklzRFpCUlNpTUF5T1kKLS0tIGRROGVZNnZjZEN2LzYzN1IzbVVh
            UnZOemhrUU1oaGxndWNhS2hXcTdWUmcKhgDLLprzPz4z+2heVnkTLEvtwEvuHxfE
            9uJTALByevbQ5n+ZQEubHZtsehMvj+r9DY+VqBKLms8RsfBCMUhAyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-22T16:29:28Z"
    mac: ENC[AES256_GCM,data:b3T9HpTtOlGgsdm2Z6VfCY6IT3KjrJJ3M07WvUSJKaF3zB7bx4vmKRoKHN3efFXfVsDEV/SaoymLUqMLG12EeEuayvGvtmL9ToCwfSzGeIwKoPO4l8nqmXPPmyP9hy4cwP9M9I7ImOhXMmOKzR89YbkcVnE5+o7JJT5WRt+9JoA=,iv:j8zmlEKB0qTFZrthMsbBWfpx7A8M8hrbxlAuJ3t3LwU=,tag:zDEuAqEsVbZkDm9rV39+aA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
