apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:Fx2G/s8Cr9N8VAWOoQzeN3YGY4IJSeKl5eJTHOfJASmo5Gty8bptF76ogMCexRvf0oXMPmpAXGWsz8KUfhVbY0GdAbdtohGZAqAYIghtb3M88SaYUWFuc/uUUX8br4DuSBOjfTd+KupAAYJwLsQivU6RU4OKe7cTmEkOP2/BwWcROuNFowMzpqheB3LdYBy2MBY2l+kiDUPkPvjGxa4RsdxHOsXCJrMzofWVsADK4gxiiZZDcRo+o9lDz+eAwJ5qGLCMc9/kjFqil7Wy5aiIPTk7u40+f7ji+cLqjZ+MErTQf5/5InBm06Y7vYMb1Fcj2+4m8laURvzvjl2tOL7A7tXpvwqMBhS946p1PsOvaS2KLHVad1vCUjzPjDMs6wvuJdP8IxGmVtS7WaNuROfFaqklrkwtAQncSE7L3eEN5k+l6dJCbb4Vo+hg3K1v,iv:gf+W0w4F+6hsJWZopBWCURUQZJ9Y1k4Uc983PDz0bos=,tag:DQ0ohtEK4B6F/eECZsM2/Q==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjlZaVRDZ1ViL0FmcnlB
            ZXJUZTAvRHJFdE9KaWVwenpQSzV6Tk5EZEdzClpIQm5yKzgzeWRHSVBUNGNDUWZr
            VEpvcXcyZTNwb3FDSklmUFgwUkJrbEEKLS0tIGUySHh1YWt4a3pQQ1lNelRubmQz
            eGFkRk9nNWpObUU4MTZ5SWNKY3ZBRnMKhzSO7D9Nwq4XCSRJexo+chw8eZ9qE2lC
            Yk8iQ6yrWpubLrASbjDvd5/BCm/aNc/dCAD85B/av7ZSot+9YbbRmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T19:12:40Z"
    mac: ENC[AES256_GCM,data:bNv04bREKksSARL6GXqEtomyVPdIaOXDgURKJYoDgyj4/kTnsIQPI+lvCevehiryRIuoMvPK146Gog2Yx0PLVRLZlnN/FTzDUAXpiXKPJoZtPxW4zksCCFs34waVgiAHReBtENLmXx9I0PAqjiGBdJCuPYB5actM83/8rOOfdec=,iv:1mz8VtcdnFXu83PgimbSD7iKXd2Z/SDcE+vw3nGVJlg=,tag:UeAsFrzo6t3pEzRYOFbXEg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
