apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:cNAfEMh8FIERikNS7BOAA+Jxquy+DhQQlThkrrrvH9l2pur1HDiVC+u8gHnHQfF6ogwS8wyeWUvLr49aMwbvWGxHeBXAn/IsQo6+4EUVCJN+4axpeZdlQtMTM6PMOeXI0Gbi71SRYYmIVXzJoLUcQooiIMzI0xjkARM7e42IaUvGhtO4D9g6MKPzBuYIopOuLNOJtf3dhnjD+uiWF6e2ZsheeBdIeELNplQhsb+C4kx7SxKjzbHIt5ZPjjJ8+rkY5yOqqjdTYvWT5S3EobZvrG57OCdQGXUiIAVCsxALvIZ2BJxvOtwOXNuG+oWzEii/EuHiUqm03alVUPK2dnQpIF5CGKdfSs9kVNYbOjzMvLBYKDPEgmxXE5AFj/TBCF44De2bB6uv6LngtfglXKmZ9i1jBnMjeOgqC685wJaMkxj/cT6BeW4HAS6Chn0=,iv:aW+Cag0wcKUk4/3lcgyVV0DUy54iHEn97NUDMpR9ZBY=,tag:da1YrscY+ipSTORL8eblWw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVjNtNldNMEUyaElwNWRU
            TFExSXA5WDN2ZENTeUJ0T3NYNXhiR1R6M240Cjk4YVhBLzRlL28zNE9XMW9Bbkgy
            djJHRVd6Q04vQlJpeExuR1UyeHFxQm8KLS0tIEVWS1h0WWd5bGVwRGNhUkZqNUxl
            SEh4L0xleWpwUHZkQXlxdVNXUWppTTgKPuFJf/ctbOdhDbHeyFua5d1NjpeRIxfX
            1W+VeKr10AYPWbsnMoJN20kUYq7hXGa997gmLwCDdQUFFhl9ffM0tg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T21:10:30Z"
    mac: ENC[AES256_GCM,data:Erv6WUC0w4B1dVjcuobvLesoL5KupOFeW3Da0RRbcIrgDxmVW1ZvyBgDX/4AlQNSAH3jsgIEliYyicsI7gqrie52iWCnayBJWFUAjHIEkcMjsLBigO4VJSzAR0spcPB0DOcn1KG0EsPaImsjVnltHkGP6k6gv+HHbHrNqX0z4ZY=,iv:3IK0RBZDP+U1MiM5V0EA1GY8GkLKlBamsIfSdfkm8Ok=,tag:O7kccwcTlTeHzuJuAffWkg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
