apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:G5tqk499/aDbnhl3eRxvv/OoUEQqfrzf2NO9sjC9WC1zJnkXXDydP/uoMTLBwO7ryd8/TpRkxucWFSAAxdVAaXNeDCF0Sv6kxQWYYiAzJZQ/5+eQEz7kcjYjUdfyMd8DtY1VOy22tslMECKkqK5fRzv78JIxThT/SernFCIRKcxU6rZe,iv:243p1XTya1RwiJccG6XidEVa4WdYttCO5Kn/GkPJ/V4=,tag:TMBZVOXhsU79XUtR8GdOCg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQzFneHNveGlBQXUxTTR1
            aUYvYmcxTVdtY1RzcldHL2prVDQ3Q2E3SVFzCnd0VVlSRkhNU0ZudEp2b1lYTDFU
            UGhqYUdjODBLcmswNmhUeSt3UVkwWmcKLS0tIGlrUHpkUS9EZVJCbU5WeEpPSVdy
            OU1jTEtHOXIwbGhMRmtSVlc4ZlRKWWcK/5cpx9+Tl8trQw+76Q5LB3cByVCptC+/
            DzsJRNByh+jGV9Qscu12yhwDma1+V0BG5JVZxtFYjq7rYS31wDT0wQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-22T16:30:04Z"
    mac: ENC[AES256_GCM,data:n66aZ6E3TgBHrh/yiojokL89W/sRDVRDwhPdUEz+lqziQkdu4aiqIneBG2w9IrRLWnirIQ7GF8aDgEv/F27js9mUDHHDlaQw4hvU6hFDrGxENkduGgWkFWzG8A2FODR+N9PKDT7jFJgW6f7HCYvWptXXbJwMsBGjLYk8DtBocQM=,iv:+iL+5V/hgDicA0ipYRdSPnZfcyU/eyDP/q8CnQ/2Fv0=,tag:kHAMOmG7ycwVmxleQWKRSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
