apiVersion: v1
kind: Secret
metadata:
    name: redis-acl-secret
    namespace: databases
type: Opaque
stringData:
    user.acl: ENC[AES256_GCM,data:uGaGuQKD5G5uP/A9qA2ypmyx7Xuqrp5xLeh5jmttcnTPrePMRz1JHL1lUUWicEi7nIAqTI67ePwAkK6+H8B+NuuxIvAaCjyZgSz29nw/Sf28qvXFfV4olIV82TmBR+WQQnO3aTRG7u0bqTBt9abvuxlz3YcLL8JNtbZBwzQLKvMMye3QN84E6ZP7HR9XciaXrYaMlYUZB2w6umFjzCVhRJcEQxG1PGgiJNI8Uo84FpUKuK4CctrubFsR5CUxjFWbi13wDl+Gbf4NOoNaOep8FfGlDoUJ0qodxrxaUEyxEVdCAdpU2pFKolGPA7Evkgw1kATKAh4ZLU/WU2EY2prHknEO1GrFPeUsUfa5uuUBa030FJ7DBEBiyyB9p+RFDUIda1V2bchx26OfsJAprKxlHFQvsq84wg/nit7Vyk43QQWfPVLfaAi5ehOiDjAQDBq7BO4/QXtl7hXhWnr3SuP8KSL9qN3g5ICk67mMIi8URL80HpzV9FlOAhOcsG/UPJab6gV1fryutMJSNeJIZ4AmNlwqfELx5rrtFt6ulYYPRRIIh9HBwgz8kR3hwCUGDYsoOGE9sgn9smDHeHeGgPsNDkDon7HnsGmS3TdKk9X+BJqdRjon2vwWHuIcgUIOyJL5Lfz+nuFzXMMIX0N336zGNmhUBg==,iv:9Iy0vrRp6NZt5qIG86s22AENb+rM1MogDslPtqRhWV4=,tag:i0Ft/ApSzSKxugIutRVUxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidFVjbkNIOVFRQzRidnlq
            eEFiVzdBbTZ6MnFPc0cxbUZZdFYxajFTaHdzCmlTaGloOFk4YVNpOFhvY0F0Rjc2
            NjM0ZzhGaFMyYXlDSUtMQ2FaMmtGbEUKLS0tIFpaeE5UbjVOa2VISWpiYUI2UWt5
            UEpWRFB0SVZoNVZ6Qm9ScWh4eGx6dTQKOQIthQxpJdvJ2kPMFzRVr0TnYl0B4wuj
            zcSd/esYOhKa+8HhfIWnesspHxCFqt6nb5cbjpKXTWCvrq6YlsUQEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T12:09:51Z"
    mac: ENC[AES256_GCM,data:PbgGNNVkwt7CJEXloeUj5yaq9I1xWqUCk7+0PswMel+E0Bv7yZecJQuwZB41jpEqLmIZRCNISBruZdcnzWQhAQbmVHfk/JKrnKnt53nlKYx8KCZCivPZ7x4vMRj0QhnR1gSYjyUa2nsRVV0wuG0gkRavjgnyBi5zoEup05xhLxs=,iv:2N5LY6K5GmlXIjXiKbHcjRpK2NlZI86O7MhGXeFYQU0=,tag:56UmxS4YLGSgkIornYKwmg==,type:str]
    version: 3.12.2
