apiVersion: v1
kind: Secret
metadata:
    name: redis-acl-secret
    namespace: databases
type: Opaque
stringData:
    user.acl: ENC[AES256_GCM,data:lPBBgpHUJ/uJiGp4A77lJ8xDb7ao9KlCLs12uEegGZW1CsCrtZEz8GJFfky5AeSz9QkRQtC6XAiy3MBVlS11PUYL974ld0cwxraLcb/W80AaU/X/iyb7egurLTU8t5L3kC0Xudfr8zaKNg+o/D3hkKwJ/QYca+VF6EV/gzrJS7g87FktLAwZuLLDtjoTgyRUgt1QYYeTXZR9TlpVcjQcrkYJgLNpoPQ3dCGjqwTaTPqQ2E5aYmbij/pMh9iDm+Svl7QXd4prDmPTLZXBSyjHBto+zu7OiZFzE9zDNcqn3MxRUFYDtb2Ulm2xK2pD1mw2aTcmlR0r3EA8O9XMqNdJ1xydSGzOMG2YUgU1fFJz02TfI9RIy4iBqT9VAJFWqjkCdxuOOgdvBGOyBFgG1srz1so931ZvczN76YRunVUV5hTFue2BrBuLsm59D5e4QYSWsPSEs/YRRD9z+24ZfMQUuap+uGweXc52UvyJ5tDXFd+GzVmT6TgOvOX+JrhRQbc3eOdUEB9Hfv4XwmHZD/+TUTYX0rywmTvsn25ccp6ulfLgDrqsUORuqK+hGPcinADc9TDrb5bO5pLYj/xGtGjAv/RvrW++amCpl6nYQrrmFthX3eDu2PRqcXh8cw==,iv:0yPTtEY+nseKAXN4TAaQhSZLjK9FDRlBWPEfxQD1Mno=,tag:Xwiz2/tIoaKLLvI/xXPIBQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidFVjbkNIOVFRQzRidnlq
            eEFiVzdBbTZ6MnFPc0cxbUZZdFYxajFTaHdzCmlTaGloOFk4YVNpOFhvY0F0Rjc2
            NjM0ZzhGaFMyYXlDSUtMQ2FaMmtGbEUKLS0tIFpaeE5UbjVOa2VISWpiYUI2UWt5
            UEpWRFB0SVZoNVZ6Qm9ScWh4eGx6dTQKOQIthQxpJdvJ2kPMFzRVr0TnYl0B4wuj
            zcSd/esYOhKa+8HhfIWnesspHxCFqt6nb5cbjpKXTWCvrq6YlsUQEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T15:24:07Z"
    mac: ENC[AES256_GCM,data:gT0MWMqlRsW37G2yd69pNWXlsfQB/uhge+jd/DPr0Op1fF3waH/At7TSC3m5jB3jZuUTbWisCmOh3iFgAhiZn+8tqHeqQo/FvRnI8NSMDBe0zipQsWGjjGzEabdCSKuPrPIFIyfMzayRcPmTAPTV51WuCAu5rp7/kE+TXK12ubM=,iv:wumOYc0sUY/eB6bLT9nLlJgLJEiv3c19LR3uz3Yyw2I=,tag:pExo2jUhea2vzip22ii1tA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
