apiVersion: v1
kind: Secret
metadata:
    name: redis-acl-secret
    namespace: databases
type: Opaque
stringData:
    user.acl: ENC[AES256_GCM,data:TKZlJ/v7pmZn5rGRxjigCANdK4zKnhJbQhSbWokgxikVLeuYXi8rd7bO6gcp7MjibcUQlMyCaf1SrTUnZO4oAvHLA2rLgakzsfn2HYS4WXEmCFInrRZrOGwRkKhKqNtQBnUq9UbnBr1ZoImKEhJNU9SEP4HkF+VwcplwtIobJLqBED/RD3aRW9p+wflhKPeHoCLtMWRrz9i5vBXIUBFcQYSuFDe9PFYp1mw+cL3BDLOk7zaGjYX/BUCp9DVl3PxKORjjg0Zo8NlqB1C2HXfPHfl/Sz2ZUtFuHga0IVvbM86afC0aCngrMvA9FG6kt1BfX9ODLdVVdSTO06oZHua6/3m0QIXDWkTsICglltY5vnMUfxL1ovRKOBmuFX0D/LXLTgc+uL0vI9h+glUZcsfu63kwauCmxH2KN6NjtqjyFOb9jT3LMp8z55Ztn2BcAbYQ9rtmM407xfV+xf+w+QiPa0Y9P2NV2gEE3qGC2gAAwnJ3eSvkhxNiu9ys2DzPTOCJmTb/5QrBpVeJRtKVf0hbSBQED0KnqEb4eONUHD5teAX1U5dRMs7wNKfwnb7ZCS7nYpxNla1NrEGn3zEp3t7uZi40JCEGXZ41TWEQdCkhNi8PcupeNiAAbJ8Y1XWn4cUYzvQD3jvPYAhudFQRbskMIHqGZxEC4Olk2dATOF//pluYGOcd0+29G8rO7fVUzCllnHQyGbttdvVDRdxvfIVRk6/itMZ22Ryy+Zin9seo,iv:DO2nJAqv5NCp8XFUaKEB6MjafTgrp8/4chVcKzTzdc8=,tag:Vff1SRKg2qfgK8MzeEyJeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidFVjbkNIOVFRQzRidnlq
            eEFiVzdBbTZ6MnFPc0cxbUZZdFYxajFTaHdzCmlTaGloOFk4YVNpOFhvY0F0Rjc2
            NjM0ZzhGaFMyYXlDSUtMQ2FaMmtGbEUKLS0tIFpaeE5UbjVOa2VISWpiYUI2UWt5
            UEpWRFB0SVZoNVZ6Qm9ScWh4eGx6dTQKOQIthQxpJdvJ2kPMFzRVr0TnYl0B4wuj
            zcSd/esYOhKa+8HhfIWnesspHxCFqt6nb5cbjpKXTWCvrq6YlsUQEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T16:14:20Z"
    mac: ENC[AES256_GCM,data:0dx74UVcQeZEG7fuyrc3K2UEPXNrhp+k0pISC9ShoOklRIydfXc/ZU4/VaUueWbOPkOaxpL9RsZNpvRO/jtUPKfE2doyZB44FsuC3dqoB89H+HUCC7Ss8jRoQJxoI95QuyFGgBEMlfoEKwuOnmvqeSBl6IgcdOxw+ulBlPs2sD0=,iv:/hhrMFtCUTCOddynrvX460cQaE9fQV+p/Fj8bLRfh4E=,tag:13kJ2AVdiRu+JXNZ++hh+g==,type:str]
    version: 3.12.2
