apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases
resources:
  - serviceaccount.yaml
  - redis-config-cm.yaml
  - passwords-secret.yaml
  - acl-secret.yaml
  - redis-replication.yaml
  - redis-sentinel.yaml
  - networkpolicy.yaml
