apiVersion: v1
kind: Secret
metadata:
    name: redis-passwords
    namespace: databases
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:OXW4HgyVw4iyNsNId6ksBbVK42oMgk15pCGujD0XCGZu9BsExuZEhdyESYHYrr00jPRse0zKtL3U7kNAz2/VDA==,iv:DGhP9ltxjhZ9Lt90vWgKG2s4b40AGfHsuaJP+CItUxs=,tag:syUHmTdMorvrDp4dvAxM/Q==,type:str]
    paperless-password: ENC[AES256_GCM,data:5ANnpH3shk72LI11KQXfBh3rLqAf0wDRdNHy5r3EU+drgoq9Kzs4haA2MRHBD9frbV5chmK/CREHUK4XflVTdQ==,iv:9ADdnyxrt4cdcvlPGhtC495iQfmfwGUfcZnd+8lXBGE=,tag:HaAs6AomMwphy+lXPgXXUg==,type:str]
    immich-password: ENC[AES256_GCM,data:dmKafL+x21Ed5O7LnKD5JM6cuTR82yMdrtq8GLwcxYAkprt3kmDdAVsXzqO5wvmhagKdObnV901dYVeXdMsgtQ==,iv:JlGpaU0t4Ic+sy0Tcj77caCw5b6G0BRxMeeCTKNbkRk=,tag:JaMRTGodlCnReh//AEfQ+A==,type:str]
    blocky-password: ENC[AES256_GCM,data:GqHyBO4gDDqkdBC11HXINos00hBDSD43umUfu0uUGsS/pOycSdHu0LjzevLYv4nF65jJEtPa0lJlK7NKYJa9mg==,iv:87pqFGDrwqv84R2BQPeN/xpoFsCSU0OBiEuM1Mf7aZo=,tag:OdcZ6LLedoDyfL1AvEiSpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTTNoUUl4Q0lLczdzZU5R
            N0tpS2cyaXBsaEx0dmVuY3FZdnNkQU1wSUVZCmdpeitlUWp1anRqcm5tblZGYmcy
            SUJPeFRTTllOcVhuM0F0MFJMcVpERkEKLS0tIFd3K0lnb3kxSk1Hb0NRcHh1U3cz
            b3NpNFRSUjVIOEVTOFljOXEwRXhpTHMKQwPxSWBY6FxOCCH2XtxCqtbeJQRqRvZ5
            yV1iU598WwCJN0i4PVKP5yQLdLAhK3geUGcL6bEFOHLMuIZ2NQLQ7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T12:07:38Z"
    mac: ENC[AES256_GCM,data:WC/4JBTYizlqleLNMDsQPILTVF4q5wyBqi/Zz74wCosbiysq4cwgCai/m6++KAsLGT6vqdzedfKiYrHYygh+TBkC136FOp9e3NKWL5vH/D0Tv/4TYsciRdQv2yDQtesf4l1fiWmYBsmeKW7xLYmwZYgIe+r+99RvDfNCi42bXCc=,iv:3DGVEoDVgCeV0PYIQtyKpILGvd8nrCcpvwS088AUxsg=,tag:X6qZhw/sl4zfQQSl1Aqd3w==,type:str]
    version: 3.12.2
