apiVersion: v1
kind: Secret
metadata:
    name: pricebuddy-telegram
    namespace: pricebuddy
type: Opaque
stringData:
    bot_token: ENC[AES256_GCM,data:cGefOFW9E085FSQr1FlCm4W7jA7a14fOGeMQxjfRu7BF+Pjpxjbnckxjn2QCZA==,iv:UtFI7P/Xq1JVqfxuiGPp6nqyT4IksFNfwBNLV0e6u5g=,tag:n/IuAlVhP0p/JBtXzbdl6A==,type:str]
    chat_id: ENC[AES256_GCM,data:fTCmHSTTsom5,iv:jQ0zT7XTITXIWpSNtTdIkWdoMnSVQkB3x+yMBECSnAs=,tag:F36EgIK/hGQzioU4r7cfqw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNE9sbTJtNTBKOVNEWVJR
            NkRyS2RxU1ZpcmxydUlJZXNpWnZsOHFJelQ4CmFYTXVLbHJwSkR1L1FPaXF1Rmxv
            QldvVDNzQm94d2ZOUEVJK1JGdFZnNHcKLS0tIGx3SDZZUzVQUThScXVkSXN4MGc5
            OWJaalZCSmQ1aUtqalFNNytwWHRTKzgKGd9ojGu3UWZHeaBxQwPxnKTWhttFo0fQ
            1XpGi9RKueaKC2mNBophv9a0NOCd/i7GyGmEeFL5QGWrjC+rzqETOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T13:28:15Z"
    mac: ENC[AES256_GCM,data:RcYWwP76myJHaEBlvCfohPAEOog83CXxQh/gT/KO6gOwLd25BZ9MovZ6UZ3Btc4AYcwQU0FqGqbEbYgHj5IJbLGgcIs0pJQZlesjTuXcXVKbaZ6HZRzFsOplPM44MBBrEaRbbDF307XLdtuAAY6AzL/XKWLDQaDlC4yCQQGygHA=,iv:P2mAEIQ/jFCa0nFH45yUzub/8KjkniJ1Zsz8itmz338=,tag:ivZvy6Mzv+fRwSTT8bZu3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
