apiVersion: v1
kind: Secret
metadata:
    name: pricebuddy-telegram
    namespace: pricebuddy
type: Opaque
stringData:
    bot_token: ENC[AES256_GCM,data:Uv0AlV7CG0Fc69vEgtQegHTUoO+eEa1nY9F/GkC5zs4O3JYqA/03+K7YHw36YQ==,iv:JKMdr+id1YSWMIpNsoge11HhoqlEwWJmQ1p2dzIikkk=,tag:0+2wegz7K/i5xg0XO8S5aA==,type:str]
    chat_id: ENC[AES256_GCM,data:CdW80deP9bJK0ndUQko=,iv:KpdHVXgerxnzYYhkWvfUmL6ukKwmNTfw8geS9giiOcI=,tag:Rw8i0U3CbUyrL9jvIxlbmw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzejZrZ2hOWkNkMS9FdzZo
            SER1ZnN3ajFBaXZPYnlJTE92Sk00RXlCdkhzClRTRGh1ZVkwdW5TMkZTd25ONGE1
            SDZnU3JNUFZjMVgyci8yc2xqVDBDNFkKLS0tIHlBZTVIeWk5SW9vTHhYQkVhUVNL
            cUlWZW1ycGJHM0R1QnF4eU0zc0p2amcKJTDtQIeOBGzzXPcqhtKiA1fzRq6zV6Vo
            y8SAFKZRiGwgBK8k6OtopKMxM/PULrAoH0Cj72banKCciGBPm7zsdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T16:39:32Z"
    mac: ENC[AES256_GCM,data:i8qHGwypJO/EGpJ7U3L0uGQMkRizp0o3ypVT44xgzSXT92emrp3xkg3t0H1EsAubM0tN2chDA/wXsbmr66tZt3qgn6Sge5mUAZm9g4DiA6qNAmGk2j3xM52AgFaDEcs9sqwfL0a9muSx6G3BEaYXPWnbEqiP4X9WedWBGw5Yddk=,iv:j/miz/koqgUELfi0bNvje2Inp9yPgA94+Yhdp3ZiuXE=,tag:40orx/4ETbivNobqylXikg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
