apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blocky
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service-dns-w1.yaml
  - service-dns-w2.yaml
  - service-metrics.yaml
  - networkpolicy.yaml
