apiVersion: v1
kind: Secret
metadata:
    name: node-maintenance-ssh
    namespace: node-maintenance-not-deployed
type: Opaque
stringData:
    ssh-private-key: ENC[AES256_GCM,data:8exS1PtQ23VbNsQCIC52lVpldW+hQ/cT/vjNZioN8s/RJHaRspabmXA/IOnKbs59K9HzKZo1qPJ1cDooL0FWeAB/7fcE3y2WMl3ELD3c4d3SKJoFLZFcGAfsgrrK4Qr9QpvpaRwAIlDrqdFDr3mkIMFjgd4kAtQpQmO8j0NdxGbfiOF+/jLROnLdU2i9qN0VEYOo9t3R252fUol4UUCSAkpLgSidwQcqa6xrzmgrn6esa7tP8LKhWWQj+XOH7DddW9aLMFL4wmVlpiGn/yJoE128IGvF4u9gvXfhgd0inRO1fNAIS1ZhEKiPKimxVknnMKWrx49rvyefByMK0wv5Avb6RlAbzUgitJsCeOi4jVYvGfbgcVJaDx9EH4+1G2PFYUc21P6PJoSTPW9luswS4SgU6bBXy22hDJEo/5k2YmUZoXumLHy0Q6w3K7R9oYB+0DzJ9TymwUQbAZc1hpSUCuPVe179lYyxmz/GiFG3yAJrV65iASu37k/ikxwFPK5hqjttyNlCpHdR8opMf3nZ4vb9UwV2F0w8MfdtjnWa17NKrlPlD6bNyvRV+ZFaWBHZINAz0/W7kkftjneb,iv:iszaCUmbZqdDfr8Mag7GlfH38MOMpU4CBZamcjZ3qOI=,tag:r4CUu2DBnlsNreLxq0ppFg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WGJMbXlJWXhNNCtxeFFB
            eU16Wkk5aXcvYWI3eUtOZFlJL0xuTExmTTNzCkFvdDg0ak9IOWtqeG5CcWZ2NlB4
            bFhiUWlvOXk0RThqU3BuMExxQVpuaEUKLS0tIHFtdk40eUIyR0VqZVBvTHZjRlA2
            TzM0STEyTS93Tk5JREwwUzVoR2p6d0kKnnECgiDuMDHNie9pTK2+uQ/IxhqwWP85
            EF6hlAprfPaLdELpKm0ugHVFxm4DFl73PHtbTrw4IEtEU7C6eU9/zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T14:41:15Z"
    mac: ENC[AES256_GCM,data:sZwvkFIL+U39QTYVbRXPsWuUujq94nNMekmvuCudMkUYKZepX5ZmSPv4/cFqH6g3WW2W+UExrjPNWzBunYHDVJeNTs/J5aIL3oEr5n2cLxPzcZ4CebVtgQ45HhTymqgCNchNAp42oqBcGiVgncFvgul2dWENayfXmKDo3LvMDLk=,iv:SOtmA3xpJ2SYqvV9LKHLWZzC5AJHUFYmMrthQqZCXMI=,tag:RU3/T28a3KVe/PvMTmWzPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
