apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - postgres-admin-user.yaml
  - authentik-db-user.yaml
  - linkding-app-user-secret.yaml
  - n8n-db-user.yaml
  - mealie-db-user.yaml
  - wallabag-db-user.yaml
  - paperless-db-user.yaml
  - immich-db-user.yaml
  - authentik-database.yaml
  - n8n-database.yaml
  - mealie-database.yaml
  - linkding-database.yaml
  - wallabag-database.yaml
  - paperless-database.yaml
  - immich-database.yaml
  - immich-init-extensions-job.yaml
  - update-extensions-job.yaml
