apiVersion: v1
kind: Secret
metadata:
    name: linkding-db-app-user
    namespace: databases
    labels:
        cnpg.io/reload: "true"
    annotations:
        cnpg.io/cluster: main-postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:3OKyxPL2W0g=,iv:V5DfTByip6WqckK2/wgFVgYwsfc21Uo50hOTOMhU+l4=,tag:1lMG67jhp49dzNtZWgE5yA==,type:str]
    password: ENC[AES256_GCM,data:B3ERvNKsQ0Lf38mzKlSw5h+7oAt2xg6i6IB0awUwetMMYih/mTHrtHPM7aU=,iv:7cu162aFXCwV2xTJebfvjEIqyr2FuJYSYbLO/SEYxgs=,tag:CWVYcMQtCLIHhCtxbG0NVw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUSt3RDVtVmEyc20zTGZT
            MUtXWVE3d3E2WFA4WUMxa21CVzNpK0lzeUNZCnNTZDRtSXRoV09qR0oxNG9Qa0R5
            SjNVQmlEYVluRGFkOW1rNTJHc2ZKQ0EKLS0tIFhrQ2V3cHJyZU0zYmlQT3dZRDBK
            ZWppemtkRzFBREpBZW43Nlh5R0lZbWMKkAtTKCQXl6207LxDDlBPl+GHFb5Z9f3e
            ylMgfGYApHdmqTNG58pUVPoWbyx0Vy96BLXbBabKVWnMIRTDcC57VA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T20:56:42Z"
    mac: ENC[AES256_GCM,data:bLXPpfao09hQ9O5c8kJH0B9kHmQIZgtkXbfJ7d7CXUWNHFACKYx2CY5aW3fRUwObRZirG9NtQtr5Ua3FTrVfJ2QZ3H5R+z34M35+a/K5gG0UfwYJb+FDoUZBTaXm3ahzCeLZUWBipq9f6kZ8z8HkUSRogswCB4uQxb27FAmbAjo=,iv:XQKD2sgcZlUNY0njMj43iXl/bnKswhDtMyf9vxl8tUA=,tag:8cuX0Ke9HFOJlWCJvXWF4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
