apiVersion: v1
kind: Secret
metadata:
    name: mealie-db-app-user
    namespace: databases
    labels:
        cnpg.io/reload: "true"
    annotations:
        cnpg.io/cluster: main-postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:JZszwhsg,iv:XfmhDWdxpdHYr8WpSuz8Fyg/wivDIt8J1p7cwU5n8y4=,tag:O7ANdXvyiIF5Z5b4O0udnQ==,type:str]
    password: ENC[AES256_GCM,data:7tmb/tsH9grSN7iO9W7Fvafbfjfq78qu+yos7Ucxy+Rvjx74GQJLWMHlZHM=,iv:eaMDvYFeixkdZOcp6tgRyCQySJs/MJz7xVnydqxA6Is=,tag:oLRzv9yr8eMix9jSD9t3eQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFVzdYWXNBWHorUUt6WGty
            ZW14Tng3MTdsdnZuZUxTcnlSRGp3b0lqalFVCmpFZHZHMlFjdDhZcDBaZ2lEWmth
            Q09FMFJKY3ZEbHV0dEhNZE1BenhJWXcKLS0tIE05YnYwN1ZXMjVTNjU4aEtWcFg1
            akx5NDVNeE82c3QwaUUxa3NsL3Y2YlUKuZPN0qUwsncz99s2PhM9fVWyRWqGGFOl
            5xgn6rvoGNBJ0bJfg3oFPr9bKcMO89oqxtp9mEH2oniubKN38QbPOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T00:18:13Z"
    mac: ENC[AES256_GCM,data:9ZSNYmG5gYKCJJQP3VV37XFHCoMOOKa+wV3PXuE+cs8cOPj2vAgSjJDkLf+mm+ok6FwtfuVbzfVsdSAm7vSfeQWAJPOEYEHRlVabUdD8Lk6P42bByBy4WB4Hwbo83tzrkm2Ao2OXLeRKr4vnUXV2ndkzE1LA5ihVwIKI12+tQr8=,iv:tCdq1PdL6qiw5tkYVCOFmd7hANp8tuOm+u7gwx9Hieg=,tag:4QQ6x1NBRB3clJXVyDWWkA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
