apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-user
    namespace: databases
    labels:
        cnpg.io/reload: "true"
    annotations:
        cnpg.io/cluster: main-postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:hiiz,iv:HgJA3e5A/oA2I8K1bKWpncbqB9NoCdiFkTOcybo2/Ew=,tag:7GRtdI/6DPh2Fzd3eoX1dw==,type:str]
    password: ENC[AES256_GCM,data:zQP4DMGuLvLtlzY7aMiC7jBv8FRRUpPlFv7O8wyel2KQoavGZPxP0IeN8cs=,iv:lkU+IfX7yX8rgYQolyVSbkT84J+1WDBiKhWNifLDYxc=,tag:+HCy1Pl1bKaYaXAtlk2DHA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzdWt1aTRjQTMzbWJhbFZD
            b3krMVVrK0xPMWgrWlZwWkJsNjJQTUMzekRFClk1dnFlbUpTY0pIWnVGZ1FXejMx
            WkkxNHBSSGpIdGpUVjRjdGJob1ZzUFEKLS0tIFIzM1hxK1l6NGd3TkNCc2lqRmlF
            U0dMMllrak4xZTZmTVhsQjhScm1sUkUKduThuXyHceuMTmje1/d/EW46gIYE7lPx
            22MnZLcT7RsUo3dA39RP+tFVXYVY6gdqUHX6dQKa3KceQ0t19TGpfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T22:46:31Z"
    mac: ENC[AES256_GCM,data:gdLQkXwf7Mfmy9548t5M7nbG47qKbuvPrnUyhvaaAvMIK1vKZdv22u7bQEGie8fnrpWeaOYaDLEdtM+sBdL29Ab0TZpLCvKDw3o50qDHr4vB5QfC4D3bz20JAPJyxUY/ZM1NGAHWPBwRp1dtunF/tr49k5hi7ZAi5463jFQR8jI=,iv:vYvkdaZ40YiLmSyZu82xOnaXvEwZwQRn+XcokX6Gun8=,tag:6WQVhWOn1ijs3DCD5nNFGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
