apiVersion: v1
kind: Secret
metadata:
    name: paperless-db-user
    namespace: databases
    labels:
        cnpg.io/reload: "true"
    annotations:
        cnpg.io/cluster: main-postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:RPf0omkw5CSb,iv:NGNxHsS3Haj8wuEax917CtmFgFgayRp0Obv14epgqkA=,tag:PpNGoZEm8jVoOvBGNWp5kw==,type:str]
    password: ENC[AES256_GCM,data:rNhBcau24lpZVEq3HjFUUjHDS1Aci6NTMFyd4SDGKhk=,iv:71HQ80z8SfI+jL8lN3WPpjaCSW6hV3C0I4HCoCf210s=,tag:x53hRwI7j/c6zJlRRRsJRA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeHR6Q0RQMXd0Rnk5R0ZQ
            MFZLSjlDRUJwTVJoamlJSWFvOWpDcHoxWFJVCmVRVFB3Sk1qQkc4Umw1M3lRWC9E
            a1p0OHRsdDhtY1JkOTN0OFYrZnR5cDQKLS0tIDlyVVAreEdRTi9EQ0JldlcybnEy
            SGNEUjNqc0FHTjhxTGtLbHptSnV0Z0UK5xWtIpY0M8BtmMwj2y6648EehAHv2Lvm
            Dr3DPsvL0I6AnrIAN58rwzBXbg2PpK+t0SGpdGnofjJFQOLaEGQj3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-19T13:27:55Z"
    mac: ENC[AES256_GCM,data:jiPhaqt3O+1xA1gBFz/+JEqgxz4uzzOSpuvgMypwuB70iWiHUxGS3TzHUpVrAG+/i10paaTId1T7gncbvXeeLPBp+rEA3ibPLo6ZAUl8u/rr1Xe8KMSrMnqAXWoTPzJPyUtFAUvErwAswAW4Pedbbq2tdJ12dr6OLIl4BC+uOEs=,iv:i3718cpf6FnN9Uq0RWXY2CGp0YV4KrD4YCrC1QRDZIg=,tag:510hdvjojr0k9r3v6qpSVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
