apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cnpg-postgres
  namespace: databases
  labels:
    prometheus: kube-prometheus-stack-prometheus
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: main-postgres
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scrapeTimeout: 10s
