apiVersion: v1
kind: Secret
metadata:
    name: wallabag-app-user
    namespace: databases
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:gfVtgK4Cvpc=,iv:RM22cCKcRtG3D0xTPJPIj0gFGvtH/LwLYv5JITlQSi4=,tag:7e6SOiWv6yAIEsIdreeu6w==,type:str]
    password: ENC[AES256_GCM,data:/GMpq5wsu1XDAnSYtiogUG/S30d8paZUdRc/sFiUBzqSZB2C9zjpaMuqKjWnCz+jo6kz2y5Qy7T84xQrpdgEFw==,iv:czbjbf9g12n5NFVh5bmOQ65QfuOKVeKbxq+XsTE5ws4=,tag:XZZsu1RqikuZva1ShQZsgA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U0FPeHNhWkZReTg2bVM2
            RlBTOEh0RHJESGs4R0RNSnlHc0hSSWt4dTJNCkNBZHdrZGNvK1ZOSEtaWW1EcHZm
            RHV3cjBTRnY2T0gyOUFWNDNsdDNxTXcKLS0tIEo4NkFnLzF6dDRaZGpDc21UZ0to
            OHlEcUFmZHI3UkR6L3B4bWdacEkrMmMK4v7TEsxMwa2dZj9L0xHFQfWCx5DI5FEQ
            eIeoFXTxLmcox76RUzRzKTJrjX1ZTsaleGKESGkOkZow9DVwaH6Aeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T12:40:58Z"
    mac: ENC[AES256_GCM,data:uhxueR9bGHBmhhRLtcmzbl0/qMtL/TYRdUu1TzYF3SPjPnHyCvGkzR0pOY3WZEvwxr9PMbnHGjq9qHXLe1LX0uoRgsdU9k2EAx/u02BABo47lGGvjlF4eJon+d+tgfgXihV55BhccGhhHvnCJBs0lvZxF7cvygsYMj2mbpPU6G8=,iv:gBI7tdAsYU+wucDTwKJLPCjbKS4mwfHiWH8AQanxrLg=,tag:5bb33yTwikLz6voueOoL4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
