apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: discount-bandit-grant
  namespace: databases
spec:
  mariaDbRef:
    name: main-mariadb
    waitForIt: true
  username: discountbandit
  database: discountbandit
  table: "*"
  privileges:
    - "ALL PRIVILEGES"
  grantOption: true
  retryInterval: 5s
