apiVersion: v1
kind: Secret
metadata:
    name: ha-mariadb-credentials
    namespace: databases
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:huLQ/G0ClL7q4Jrf8Q==,iv:iKjHhX2RBbz+i9ZHvUF+iampUAJc/56CVdwYmruWOOU=,tag:nWDUsearZl+2Wy2u6omZVQ==,type:str]
    password: ENC[AES256_GCM,data:w3QV8Mm4pha2nBJxRYjBJttRpU81w3S+TIcAcIEFjG0=,iv:kBAx2KiCNhjK8dCaQ8CMvKI144oPyMI9jUIPo5V3dfg=,tag:JeKpvZDqUlKXL54mFnUU3Q==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUm1vcVphY1JKckVSNmdm
            UVZUR3ZxSjVGZVNmMjJlOEFVVGE4RXdia1FzClgzWGl4bGJLbVhsVVp4aGFvKzZK
            NHpkNFlycHVWb0dqUHZUNUlkRXlBbWMKLS0tIHVHTjA3QlV5bFk3RXlHM3JTZ1lo
            Tmpta1RRdEFiZEltRnRValo4VTZ4VFkKK6ak1CGtSQ95nnwpe55dmeauWtGKk5lL
            6+yVAuXn/balg4xxbxPbdUg/0J4v1ROHzI5VrVsRIWYrvNMbUxMHAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T21:10:01Z"
    mac: ENC[AES256_GCM,data:pF6G/REg7QUaa1CQmu7ClCBXL3deNCHh1gQ+kW6rm7yBaLopSKai6JlQSaDaXPbfkiaYojGRbHumihzzz31CKvif35dvFnr8Qd41UEJejbjyr9gJly/aIaqPkAfKJ653cg5I2Lmr3w+vDSoOhYANJSYykbrRAnpFDPtOg7YsOxU=,iv:/xPfAqkeOC5NXgCGNS3SF2Wvfv/S0sA+Tt47ge6zl+w=,tag:xDyE7ORHJ8DDM1stKpy5jw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
