apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/databases/mariadb
  - mariadb-jobs-serviceaccount.yaml
  - mariadb-backup-cronjob.yaml
  - mariadb-binlog-backup-cronjob.yaml
  # App-specific database users and databases
  - ha-mariadb-credentials.yaml
  - ha-user.yaml
  - ha-database.yaml
  - ha-grant.yaml
  - uptime-kuma-mariadb-credentials.yaml
  - uptime-kuma-user.yaml
  - uptime-kuma-database.yaml
  - uptime-kuma-grant.yaml
