apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: pricebuddy
  namespace: databases
spec:
  mariaDbRef:
    name: main-mariadb
  characterSet: utf8mb4
  collate: utf8mb4_unicode_ci
