apiVersion: v1
kind: Secret
metadata:
    name: pricebuddy-mariadb-credentials
    namespace: databases
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:v0/kJ/IgxCG8WA==,iv:13v3gzLNafyXdjE3V7dt/RDIPtZq799d3BOfV+gFJvA=,tag:9nVhUmRzL49h7GuxHjqNig==,type:str]
    password: ENC[AES256_GCM,data:TwF62c+37qL5bVbS///uKhsw8dOdjHlw,iv:LnjLuYiqtKBO5CWSCQu/DJZJZrXtfo1cptSB0SGI0AU=,tag:lpTPJ6/cYU/4eRU2IsjleA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjcnNGdm1nMk42elFzU1lC
            SzZua1FSVmRwcUtuYk56Wi9uT2pqM3lCU1hNCnVoWFFiVWQ2eHdFSjljalNpUW02
            MExhVVZkdVdFY1grUEcxZk8wT3I4QVEKLS0tIDNrMy82Y1pzZGpJejF5M1lOaFl0
            L2YrYVRUVVgveTRyQlFsWVg1ZnhvaGsKlwrN+AkI0qvLzcsy1iScej8M56i3WkNV
            Id8I5S5Uvh7AyIA0/reP+c32DwzPyqwi+y5SG0wKemurILZpadL0kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T12:49:00Z"
    mac: ENC[AES256_GCM,data:VbqhMiJxOnMwL9JX4bSZICCXI8DW6xtw2FXVka9Q6S1xg5QuRagW36zaNSOHfsjCPBFcvqRGQPkJ5gpGnzrOlhXPbj0JXjE9xQ4SXDRG+Vu3eIKv1CZ2AzlFfWjMhktV23a7rNChBO8Z7nNY85sj+Gf3pkXPlbze1j+r1YJqxEs=,iv:CLMV1OjWrJawbortgj4VeFopX70tZ/KpyCSIvxiMOQo=,tag:gZZSS6ZZY5IP/HXtB3zHPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
