apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-mariadb-credentials
    namespace: databases
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:gBonvsNsmsalxA==,iv:BoiWaSukaPaxhlOKE0k6jLtsr4xemDrODXLwrsEY6xA=,tag:8yCQfOFexgsK9lUV0pMwuQ==,type:str]
    password: ENC[AES256_GCM,data:S015vjSdAqhhkdksatHvEUyr5jWCK9UQXDdtZ4aizLU=,iv:VtlpaxxpmrsEYBOpg05TWEoxXbMKwUU1QJLT1Ogq9+0=,tag:+MiPgti38hSlXHYeX67rZQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSk5iTXpHS2t3OGU3eWUw
            RUc3Vm15Y29zcnpadUlHSitYQjZRQWIzOXcwCldGMnZUblRFUnN3ZHBHV2tPS1RE
            NXpzbXJjSS9aZE1BTVU2REhSb04wcXMKLS0tIHZBd0hqc241WExzVmJUa2VBWU4z
            T3hBUTZmL0ZMQ3d6Z2lTWjJyREJLWWMK6BQcH2PVqKJNUyQjnZ2Ch0uEGr5mB70L
            NvQpi2+KJ+4DchjXEmd081/J7pyBSXZorWSy+DcyUlW1OKLbf7STLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-24T21:12:12Z"
    mac: ENC[AES256_GCM,data:izsbQI9lWHDAKD/ZqSWGxlKmvtl6UHknRM+eQotWU+OTM3U7/3E/DwEwTp96D0z0ZKjK0g/sEySLhIRvD6fx4HuVGZY41IpHlYs6z24TMHh2vs/4fOI1M99qmKRztu3t4uQ9JZRzefsgkerucmEOByr9bqHlqlnrHCUgrLkGSFw=,iv:nG7MH65oJ9XElc+XmmAGIWiJphPERcusFqu207lafR0=,tag:/TjKt9siNB4L5qEXNhqrFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
