apiVersion: v1
kind: Secret
metadata:
    name: couchdb-admin-credentials
    namespace: obsidian
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:AqCb4vQ=,iv:4G8Z1ZWyQBNub6xDmvI/0n46cBfXd+Z8F9Sozwy6cww=,tag:Q9SbGs8lZGMGOJ+yY+kUSA==,type:str]
    password: ENC[AES256_GCM,data:73HPuDF1BnIz4ZvSjCjgFeAhVwzGHDGVXe+3bkpUFqHGWoZ4WY0Wpw==,iv:4YWuvxXxeUV32msaRR8VZLGNJkY491v8CC7bNZvx6as=,tag:TfH61Q5sUmycWGwsAhYTZw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS3RINWUycnlLNnJkcGpj
            cGU3STc2Z2l6cHFvNnNRSU5ZOEtnbE4rNWtBCllUK0dMTnJZNURBUUU0TkNOc2ZF
            QkhSRnRPYTZiczlWUE1sQzl0dUFPUjAKLS0tIHI3dUZ4bHM1QVZnSGx5a0JpaGxj
            dG9STEJ0Tm9mVEhkY08vcFpCM1ozQjgKdNoLxahIzDBViYpGsga8+izStDco7AlQ
            6e/ueRmF8Yx7ZhZFU0qv3/5a2kcOmCPiQN3y602l3XUWnSvJvEia4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T17:30:20Z"
    mac: ENC[AES256_GCM,data:h+9/2DxiHHWWSm0zRqD9w5mzPmpqfLTrrdzZ1R3NAZaIYZ0fh9i9/TRgFvWQVxI7O5wPfXZ2t06Ja0Ko942dgcFpo5WYk+5Uy8AIeMNV2rt8DMJcVrs843uLZ/XxbpxpzdM0olnZ7Fm5Ft48Cf28XgbvGeMAoU7lKgbLibN66u8=,iv:IpnK35HlxZF9kXvuThIgDBpN2wLJXNvG7iO3G0Xi/Xg=,tag:DLT9Ro6MaPjv1o2wLET4Lw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
