apiVersion: v1
kind: Secret
metadata:
    name: couchdb-admin-credentials
    namespace: obsidian
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:AqCb4vQ=,iv:4G8Z1ZWyQBNub6xDmvI/0n46cBfXd+Z8F9Sozwy6cww=,tag:Q9SbGs8lZGMGOJ+yY+kUSA==,type:str]
    password: ENC[AES256_GCM,data:nbRXLxVcLyUpJjZrWe0cFACfog0tf/+e+YQK0Nup1PU=,iv:wwTuYkXArHwVLzNwX+nbX9xctuxz5U2f9iUiXQ8sZ7U=,tag:79bwABS0+Y6T4EIwmsgbrA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLS3RINWUycnlLNnJkcGpj
            cGU3STc2Z2l6cHFvNnNRSU5ZOEtnbE4rNWtBCllUK0dMTnJZNURBUUU0TkNOc2ZF
            QkhSRnRPYTZiczlWUE1sQzl0dUFPUjAKLS0tIHI3dUZ4bHM1QVZnSGx5a0JpaGxj
            dG9STEJ0Tm9mVEhkY08vcFpCM1ozQjgKdNoLxahIzDBViYpGsga8+izStDco7AlQ
            6e/ueRmF8Yx7ZhZFU0qv3/5a2kcOmCPiQN3y602l3XUWnSvJvEia4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-23T13:06:36Z"
    mac: ENC[AES256_GCM,data:Rdb6d6wjKgCX6/DxJwLaXYd8IYZh95wKHtZxv+WTlzz9VAc7YfXRCwMPWEs2oGyCVHyyPtz36rFUVtb77/6gFPUkTcXh9auQAUIN/IBvf8ImiBGbvS/VH85JtbaIzYINufMyNuzuxSWvy5mVPFHw+pZnXzPEgontE9RxusTZrKA=,iv:xPl8dWDF/rFwHnA9UE2IE++7H4z45lDudROE8zvJXvQ=,tag:ahtmtFPPwkAwOs+RQE64eQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
