apiVersion: v1
kind: Secret
metadata:
    name: couchdb-admin-credentials
    namespace: obsidian
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:qwM21ag=,iv:T2YsxeSSm4IvQa1fzE7KNPcHCxWvW238PR7IUUw7vKg=,tag:FjNI6CzatiI58vKtwqzRww==,type:str]
    password: ENC[AES256_GCM,data:HLMO2QGLAowCBJJH8Trvk90yNW0/nVdygMpTSCor/SM050XTBrLWn3h+N34=,iv:18Mi2Mu2z+VRJObM9PmIZiqjptn1tHMMOCLOWy/Rtto=,tag:LVpz5yA1fbYpgp7KLCNvkw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMjF0Mjk4WjRnOExCTjhk
            TVVyWmxUZ04yMTdZMFNMOGdNaWpuZ2lTNEh3ClhlMkNwYzdya1BRcXMyaEhrTHJp
            d1FIMHZqMm1JVUhldW1Ga2xiS1lhVWsKLS0tIGlQNEVpd1BFV0VnY21YbGZFdnRB
            TVNSZ3ZBYTdGZXhZNTZJUjEreEIwNWMKY3/WGq3fJ4ZLmXJzgT+KUdilRAhroaEU
            M5x8+d4Z/TKizrvJS5QVRdtLeDT5ahloJdTZ/PEBj3Mv9Uxkv4DEhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T09:55:57Z"
    mac: ENC[AES256_GCM,data:ecCJl1LnphGeTB/B5K86cSfL81RcinH4X90aZbQcPtMpSE1e56CS1ShedR1A0+bCmf+R6TB9yvmgQaIsdWz7pzLO6gt+tWTowr9c5iJtnxj+8KVH4AWq7Rfm/EEkCpV74oz0Q0UDb9nZWX2cbuWMkl3J+BGo3r98/RO51xei0EI=,iv:lcMYTDD+YxskV1w+u/EOxg+0dpobcWmIzjPOae68Yzs=,tag:mD6FZoakeVRqaK+3Xz+kCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
