apiVersion: v1
kind: Secret
metadata:
    name: couchdb-credentials
    namespace: obsidian
type: Opaque
stringData:
    #ENC[AES256_GCM,data:hxz2LxMxbqIenOLlSSkB4+kVNub/Yal5OogAc3KhaJW+DN88DenPnLH3g30P03zu7t9i/+FC9PHyuvfBbIpfFj6LIBHu,iv:70vOh2ZcCousPAQR0byVU+bVLhVD6y9rvpVxCf7lWHM=,tag:lkN5bg1DkE9vfbcIe3Ip/Q==,type:comment]
    database_url: ENC[AES256_GCM,data:U/IpKqCdwQQBAqHbRzvtVK6Ky1OlgR64UMl2sq7+j9U+qq/h2GaIuGbIz8jQhuLGQ2JWoD9sIgzbZzE=,iv:UXbTXRqsTHMYOcPlIVe3zHRITedNotpeIblGpkV1YNg=,tag:TIOborH9DjQqHLc76EutvQ==,type:str]
    database_name: ENC[AES256_GCM,data:071htxRtCjEXYokwqWjTL9o=,iv:gjmwj2wGTPwEKeKdcU3k/tyjXX7w4kX65xuTqO+YoCg=,tag:NEc3nV9pYS3jrKvqQDNdvg==,type:str]
    username: ENC[AES256_GCM,data:CK0sl7tzkmL3yi0Uow==,iv:gcya3CZm9z6XddeJtk+rOnyYsJmWbHyOVlm1dNOkZ/E=,tag:8T3ypDOdn//ILx6o9KpI/Q==,type:str]
    password: ENC[AES256_GCM,data:q8j9Q/WEmbxDfk7Ys1etG3y2jxqgvN+QibnT44l3BHMlUdVwCBq6iX1HONVhog5w/VrcNtis1hcafolxm3WrJQ==,iv:h3mBnRpC1+BrdNBQ9Ieb2K6njHzY3y5kx5wIu/irwts=,tag:nDZmGzJ2H+CXr6jayNF8fA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWc0Q2Q0RxNTdaU3Avcldx
            QTY0aDREYWVNaUQzV0p6Y1I3SWYzdkh2RFRvCnNaOUl5TzFJUk14MW9mMnhnbmRz
            UUthM1dDNnIxeTl0L3pmcUxweXpCS2MKLS0tIHlwSkJlMmF2UUl4WkJ4c1lVMXpY
            U0dmVVkyeExuMTQxaUxTM2ZTWHBGRGMKTk3A2KPp6Ek4xBKUFtH0agxRAk/Wnwni
            H32I/kf4OuLCrUDZKYwjTSUPgPLvLnRxpD3CLIb+Piqqasgrc8yQHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T20:32:37Z"
    mac: ENC[AES256_GCM,data:j7Ul5Z0ZawQB/NcolqNQbkb7mUeyduaHqPy2sgqGXd5G0VbqCYBFdISfjL0gq16p6nK41UZUuV0OGU7MLrnNeu5RJgGLdRoQKj3KD356X7PbDNKCxdktIM/dAluFhumxTgHBaorZIpYCsqSDDdPxTExm1AoYiRPRn9y+A6EDehY=,iv:CwW/c89j2vVcSp3v1DSfsE/hSM94DbO4qtAerT0BPnY=,tag:/SRcLTxMu0cbPlax5diuIg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
