apiVersion: v1
kind: Secret
metadata:
    name: couchdb-credentials
    namespace: obsidian
type: Opaque
stringData:
    #ENC[AES256_GCM,data:wO2eWUK4gZIDN1Kii1PRGCv0geesJZ6JCfiY,iv:2we2v+5M6O9liQEGd6heEwa7HJZ557KI8U/TKyungs0=,tag:CpSbcuDOVaBChcXS1xhydg==,type:comment]
    database_url: ENC[AES256_GCM,data:IaV/t8ZTuFssQnzXovEx9uvre2MxTOKwD7suHg==,iv:Rl74t3Nq5fIykQE+5Sb3QVdp/oFucUAcWdmxVcdlkeQ=,tag:PbkgihVJtxIB74OcTqTM/g==,type:str]
    database_name: ENC[AES256_GCM,data:pEwvQ6u28nMm/iNl+OdRt8s=,iv:Zf9FjVHT8AJtMkHvsZ1zXjYIBaRKxSZZ0a7VX16246A=,tag:F9E1huZ/XwBsA8aarksGQw==,type:str]
    username: ENC[AES256_GCM,data:R2zS7RnmKuu/ahF1iQ==,iv:qOSRiJ+L8AvaEp9p2hRY8h0F/wdsqAqoxcs3s3rVOUg=,tag:t1+La1LYocrjsbVY8C2eeg==,type:str]
    password: ENC[AES256_GCM,data:pPUgQY5BEAhmdoCkNR88WaOgsnRcySQ7PTgGunoL4NvYYtCCOQ9lP5aaMdQ=,iv:/JayxWRnCruLvqIEr21ZXjcwYR0PwXl07LaZytIs/wQ=,tag:12ghEpgRdTzWZePkqMaNeA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUnB1MjkxTElFd3BrOHQ0
            NzFXZTdQQmxIdEVLa3lpTTdqRE9PRWtUZ2g4CklkV3BXYVN6OGZ4UU0vVEs1aVp0
            T1I5SDd0VmZZZHpnVDQvZTMxQjNoL0kKLS0tIGVhYlpOR3N6MWNGWkZXMndLdkw5
            Z1lwMG5EcEFkVzYrTzY4Q1h6eE14bDAKyhKOUNpNrU44FZBjRosmM/RqhUaITwff
            ZfPJmUVY5UIQ4QQd3PMqS3NRykNTKHrS2uIZ3vYCXUkZ7/Xm0qVN7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T09:54:17Z"
    mac: ENC[AES256_GCM,data:Tz1WU1x6yHN+tOK5x3MmEbmccPMBon2BTsTWuS5CP3DhYTILMkED3x9H/lbVdsmNufp9iRqCFl1DVn4lw1trarlKUdZW4iKNimxBGLTTm33yJ9CjMGYx+as9j8Gu2S+Rc+OVkQga2Ywl457NoyYGbF5/QaAVhxdW7M40UQWgDTg=,iv:4tD8UkoPh8FPurCuH5izetjfz5Nl4Xlf924tkOFs51k=,tag:00trRy2e4uIeMijZ14mReA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
