apiVersion: v1
kind: Secret
metadata:
    name: couchdb-credentials
    namespace: obsidian
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Xb7s1emdNy74q6cyxeX/tK/yp1cgvwEv5CaTyNTxPd2asr4CCksSPQf6Fst0AeGgCZUQ5ZSfVhIjnlpEFK5h5QvW2mSM,iv:MgJ37DzJwJkqRn6nNwL/5ovDpdrYZZxBaCO/VgDRg5E=,tag:aIgPEnAShE7u7o1vpBW/Nw==,type:comment]
    database_url: ENC[AES256_GCM,data:+RJsE63WXJI7KTO8k2brBmjY+ct8CelxefERyvYp1QvDYy0DUxMvB2LkMLGXmGsy8094CWKBuYZn,iv:RSNq1rFKwf/PGL1gJ0H2yk9VzPQ5T13mXb8qdJdNo54=,tag:o6mmk2aLLWtQydlB42S2lw==,type:str]
    database_name: ENC[AES256_GCM,data:nVr6zGXU9lF51YQmFBWAE/M=,iv:+yLcVj85iX7jOvo7XRaNIL99gMmk+gzkl3zW9aqzZIg=,tag:of9WF4fAkoTwpG20PFr98A==,type:str]
    username: ENC[AES256_GCM,data:gENp8UolHXLrJgfIVA==,iv:y0Pxi7o5ahm/0DPDAONzOc5Pco8y0BeopmJCA9odp3k=,tag:FbGKhBJ7U1IdFMleYT5wxg==,type:str]
    password: ENC[AES256_GCM,data:i0ttApAFywceqGqbpVZqB0eMPX2IVBkpBX0re2ZALz/ZkoVZ6LngrD7713o=,iv:8b6q4yJM7fDFrasdBTzWq010irk9acKvSqOeCg3/ECo=,tag:qq3HSNTW9IZIFAtiqeuPrw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WXVTOTFqVDducEdFL0p3
            ZWJBY1RFenV1TEF5UjI1Vzd3YTBnQ3QvQWdFCnlkaFk4dGF2am5RVXZ5Q3BzYnll
            VS8yelRYcEY2ZjBMdWtXekxFc1Bub1kKLS0tIDlNNG9zYkFBTzlDZzArVW5JVnI2
            bnNmY1V1a0N0WE5BRHljcWRCa3NOeEkKjJfQ2CFRZo70HCbP7CkX5dXcbykDEkCp
            kHbVM3ERCXj3Ba6DwVAFvJYP6fxggkYIgO11ufT0CIbaHvh3NZ2cxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-15T20:08:37Z"
    mac: ENC[AES256_GCM,data:nmqUNFKTQ2hjTNq2JxuNyzYwsMfPj20PiKsIgHB1XjNduaCzEcL2w+2oL9/7u/2iffkw3VU39t3XUe12skARgfVl4Ehfq4sWZGcVDQdzPyqty1vabmV9yFC42YspDpJNu3Ev0Bw1aJOZoSOmLQStsMXPYlilePrI94uikg7uP/c=,iv:3EgsFMag0Xi8IR4AorLZG4Q4E4rHoeWcyeQ0fi4bOLA=,tag:d+m64gcecIfKaZX0WBJcMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
