#!/bin/bash
# K3s Node Setup Script
# Run with: sudo bash setup-node.sh
#
# Bootstrap-only: AUR firmware, ansible stack (CP), bootloader kernel params,
# K3s config directory. Everything else — sysctls, sshd, kubelet, udev,
# tmpfiles, journald, logrotate, UFW, packages, K3s config.yaml — is owned
# by ansible roles (docs/scripts/node-maintenance/ansible/roles/) and
# drift-healed daily by node-maintenance-config.timer.
#
# Sections:
#   1. Bootstrap packages (ansible stack CP-only + AUR firmware suppressors)
#   2. Bootloader kernel params (systemd-boot entries — not ansible-managed)
#   3. K3s config directory stub
#
# Works for both control-plane and worker nodes (auto-detected).

set -euo pipefail

echo "=============================================="
echo "       K3s Node Setup Script"
echo "=============================================="
echo ""

if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Run as root: sudo bash setup-node.sh"
    exit 1
fi

HOSTNAME=$(cat /etc/hostname)
if systemctl is-active --quiet k3s; then
    NODE_TYPE="control-plane"
    K3S_SERVICE="k3s"
elif systemctl is-active --quiet k3s-agent; then
    NODE_TYPE="worker"
    K3S_SERVICE="k3s-agent"
else
    echo "WARNING: K3s not detected. Assuming worker node."
    NODE_TYPE="worker"
    K3S_SERVICE="k3s-agent"
fi

# CPU vendor: used for AUR conditional + AMD amd_pstate boot param.
# Microcode package: ansible-managed (host_vars/*.yml ucode_pkg).
CPU_VENDOR=$(grep -m1 "vendor_id" /proc/cpuinfo | awk '{print $3}')
if [ "$CPU_VENDOR" = "GenuineIntel" ]; then
    CPU_TYPE="Intel"
elif [ "$CPU_VENDOR" = "AuthenticAMD" ]; then
    CPU_TYPE="AMD"
else
    echo "ERROR: Unknown CPU vendor: $CPU_VENDOR"
    exit 1
fi

echo "Hostname:    $HOSTNAME"
echo "Node type:   $NODE_TYPE"
echo "CPU:         $CPU_TYPE ($CPU_VENDOR)"
echo "K3s service: $K3S_SERVICE"
echo ""

#######################################
# 1. BOOTSTRAP PACKAGES
#######################################
echo "=============================================="
echo "[1/3] Bootstrap Packages"
echo "=============================================="

# Ansible stack (CP-only — only CP runs ansible-playbook; workers need only
# python3 + openssh + sudo from Arch base).
if [ "$NODE_TYPE" = "control-plane" ]; then
    echo "Installing ansible stack..."
    pacman -S --noconfirm --needed ansible jq rsync logrotate python-kubernetes 2>/dev/null || true
fi

# AUR firmware (mkinitcpio warning suppressors). Kept in bash because:
# kewlfft.aur module requires per-user makepkg.conf on node-maintenance user
# which would clash with rebuilderd /etc/makepkg.conf.d/storage.conf. These
# packages install once, never update — zero drift-heal value. yay itself
# is AUR, chicken-egg before any AUR ansible task could run.
echo "Installing AUR firmware..."
# kernel-modules-hook keeps `/usr/lib/modules/<running>` populated when
# pacman upgrades the kernel pkg, preventing modprobe failures (and the
# UFW silent-disable cascade observed 2026-05-02 W1 incident) until reboot.
AUR_PKGS="aic94xx-firmware ast-firmware wd719x-firmware upd72020x-fw kernel-modules-hook"
AUR_HELPER=""
if command -v yay &>/dev/null; then
    AUR_HELPER="yay"
elif command -v paru &>/dev/null; then
    AUR_HELPER="paru"
fi
if [ -n "$AUR_HELPER" ]; then
    SUDO_USER=${SUDO_USER:-$(who | head -1 | awk '{print $1}')}
    if [ -n "$SUDO_USER" ] && [ "$SUDO_USER" != "root" ]; then
        # Per-user makepkg.conf override: rebuilderd storage.conf points
        # BUILDDIR/SRCDEST/PKGDEST to root-owned dirs — breaks AUR builds
        # as a regular user.
        USER_HOME=$(eval echo "~$SUDO_USER")
        USER_MAKEPKG="$USER_HOME/.makepkg.conf"
        if [ ! -f "$USER_MAKEPKG" ]; then
            echo "  Creating $USER_MAKEPKG..."
            cat > "$USER_MAKEPKG" << MKEOF
BUILDDIR="\$HOME/.cache/makepkg/build"
SRCDEST="\$HOME/.cache/makepkg/sources"
PKGDEST="\$HOME/.cache/makepkg/packages"
MKEOF
            chown "$SUDO_USER:$SUDO_USER" "$USER_MAKEPKG"
            sudo -u "$SUDO_USER" mkdir -p "$USER_HOME/.cache/makepkg"/{build,sources,packages}
        fi
        for pkg in $AUR_PKGS; do
            if ! pacman -Qi "$pkg" &>/dev/null; then
                sudo -u "$SUDO_USER" $AUR_HELPER -S --noconfirm --needed "$pkg" 2>/dev/null && echo "  Installed: $pkg" || true
            fi
        done
    else
        echo "  Skipped: Cannot run $AUR_HELPER as root, install manually"
    fi
else
    echo "  Skipped: No AUR helper (yay/paru) found"
    echo "  To install manually: yay -S $AUR_PKGS"
fi
echo ""

#######################################
# 2. BOOTLOADER KERNEL PARAMS
#######################################
echo "=============================================="
echo "[2/3] Bootloader Kernel Params"
echo "=============================================="
# systemd-boot entries in /boot/loader/entries/*.conf kept here (not ansible):
# drift risk is low (not regenerated by mkinitcpio or kernel upgrades) and
# a bad ansible regex on these files = unbootable node, recovery via IPMI/USB.

# Crash logging: EFI pstore + printk dump + panic reboot
echo "Enabling crash logging..."
CRASH_PARAMS="efi_pstore.pstore_disable=0 printk.always_kmsg_dump=Y panic=10"
for entry in /boot/loader/entries/*lts*.conf; do
    [[ -f "$entry" ]] || continue
    current_options=$(grep "^options " "$entry" || true)
    [[ -n "$current_options" ]] || continue
    new_options=$(echo "$current_options" | sed \
        -e 's/ efi_pstore\.pstore_disable=[^ ]*//g' \
        -e 's/ printk\.always_kmsg_dump=[^ ]*//g' \
        -e 's/ panic=[^ ]*//g')
    new_options="${new_options} ${CRASH_PARAMS}"
    sed -i "s|^options .*|${new_options}|" "$entry"
    echo "  Updated $(basename "$entry")"
done
# Runtime toggle (no reboot needed for immediate effect)
[[ -f /sys/module/printk/parameters/always_kmsg_dump ]] && echo Y > /sys/module/printk/parameters/always_kmsg_dump

# AMD P-state active driver (AMD CPUs only)
if [ "$CPU_TYPE" = "AMD" ]; then
    echo "Adding amd_pstate=active..."
    for conf in /boot/loader/entries/*.conf; do
        if [ -f "$conf" ] && ! grep -q "amd_pstate=active" "$conf"; then
            sed -i '/^options / s/$/ amd_pstate=active/' "$conf"
            echo "  Added to $(basename "$conf")"
        fi
    done
fi

# PCIe ASPM off (NVMe latency + interrupt stability)
echo "Adding pcie_aspm=off..."
for conf in /boot/loader/entries/*.conf; do
    if [ -f "$conf" ] && ! grep -q "pcie_aspm=off" "$conf"; then
        sed -i 's/^options /options pcie_aspm=off /' "$conf"
        echo "  Added to $(basename "$conf")"
    fi
done
echo ""

#######################################
# 3. K3S CONFIG DIRECTORY
#######################################
echo "=============================================="
echo "[3/3] K3s Config Directory"
echo "=============================================="
# /etc/rancher/k3s/config.yaml + kubelet.yaml are ansible-owned
# (roles/k3s_config, roles/hardening). Bootstrap ensures directory exists.
mkdir -p /etc/rancher/k3s/
echo "  Done"
echo ""

#######################################
# SUMMARY
#######################################
echo "=============================================="
echo "       Setup Complete"
echo "=============================================="
echo ""
echo "Bootstrap applied:"
echo "  - AUR firmware: aic94xx/ast/wd719x/upd72020x (mkinitcpio warning suppressors)"
echo "  - User makepkg.conf: BUILDDIR/SRCDEST/PKGDEST override for rebuilderd nodes"
if [ "$NODE_TYPE" = "control-plane" ]; then
    echo "  - Ansible stack: ansible, jq, rsync, logrotate, python-kubernetes"
fi
echo "  - Bootloader: efi_pstore, printk dump, panic=10, pcie_aspm=off" \
     "$([ "$CPU_TYPE" = "AMD" ] && echo ', amd_pstate=active')"
echo "  - K3s config directory stub"
echo ""
echo "Ansible roles own (applied after install.sh, drift-healed daily):"
echo "  packages / base_config / k3s_config / k3s_image_gc / firewall /"
echo "  hardening / security_scan / rebuilderd (workers) / ad_hoc"
echo ""
if [ "$NODE_TYPE" = "control-plane" ]; then
    echo "Next steps:"
    echo "  1. Install node-maintenance:"
    echo "       sudo bash docs/scripts/node-maintenance/install.sh"
    echo "  2. Reboot to apply bootloader params + restart K3s with templated config.yaml"
    echo "  3. Enable secrets encryption (CP only, one-time):"
    echo "       sudo k3s secrets-encrypt enable"
    echo "       sudo systemctl restart k3s"
    echo "       sudo k3s secrets-encrypt rotate-keys"
    echo "       sudo systemctl restart k3s"
    echo "       sudo k3s secrets-encrypt status  # Expect: Enabled + reencrypt_finished"
else
    echo "Next steps:"
    echo "  1. Install node-maintenance worker bits:"
    echo "       sudo bash docs/scripts/node-maintenance/install-worker.sh"
    echo "  2. Reboot (or restart k3s-agent) after first CP ansible run picks up new config"
fi
echo ""
