apiVersion: v1
kind: Secret
metadata:
    name: uptime-kuma-mysql-credentials
    namespace: uptime-kuma
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:sH6YJQoyXeS4EA==,iv:av7WbJKPi57TuH8rlbWIePXwGZi0K5NAiA0aLzFxrr0=,tag:wK8LmANZcja4iiqA7kgAlw==,type:str]
    password: ENC[AES256_GCM,data:Hc4bgUfq1StenYArhq8BI65R9v7HcsYKe+o+kb+RPsLT7/EFfykmPkxbMovOtpRrvNuvnZhwg0Sk/XAAmEMV7Q==,iv:j5AiIttBi8ROPBUwX+LWeuUAPf0if19O3MkwYyCjA5Y=,tag:PPqvBWbEG96mBYMyq4V5ag==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK3duYitmN1l0SlJZVTVa
            SGdFUnJlVXdZK2tjVGRJTnZLZmpFMFc2NkJnCjVLQUMrL1pvTEdTcDFMdU53bDU4
            d0RsNUZCS056UW5aZTJYMk9NWG9XVEkKLS0tIFZFVTBzZitlMFhZN0VQNXFhd0pY
            WmNtNm43RkVSRytnYUFFKyt6dkR2MHMKZQ+Eb5eoaNBAn0N8OhikubvZLu+6JofS
            MU0MvbCZGnyUbwZFCmfWG01/qrWwE1EymPT97XGKDREduMyX6cEbjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T00:00:31Z"
    mac: ENC[AES256_GCM,data:9vMARl8peaWa0iuoW3FD+RkepeI6U3G+SA1bpp3rOWDNlhhtQSQwm2NzIawFetxZfUX79g5CTg6J3/NL0mX6iWiQm8LvpMKOgmK3lOJFxsC6gGWLmlahPpO57fnMUPQ4WbzCtFRz1t+x8SPci8yZekbrsLSJMFqZz9HyewFmklg=,iv:Rp5NaJoMwn6wqfk6zeH0UR4fJTltrW5NG3DJ73k5nJ8=,tag:EPv6eS4vMPLRTJ9Ue/YH4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
