apiVersion: v1
kind: Secret
metadata:
    name: nas-rsync-credentials
    namespace: backup-replication
type: Opaque
stringData:
    rsync-user: ENC[AES256_GCM,data:3KRONmoPeg==,iv:3Mb0PJ+kgn+KH2XMck1lnwC4utQu1YoavpL4vupM2Tg=,tag:8QiTdN1Cva1OKbDVwDRV8Q==,type:str]
    rsync-password: ENC[AES256_GCM,data:UaD1TWE8vhgZmHDK,iv:qO8/H3TaCMF/RiaPPb1aHvTMGijqPgz1s/eS0LM+DHc=,tag:6WxqnPCrDjIsxcL4WskqYw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUjhzUDR5WGV0d3V5L3kv
            N0c0NVRGNE5VTjA0YzFUNnAxbFE1YXlUZ1NjCkw5Q2ZEcnBwSHIyQkVyYlZVV21h
            Vnptb2NJbVVyRnY3b1lsZUtsRUlHQkEKLS0tIHFlWlY5S21DNTBEOFVNZU5LdnZL
            UTNtczduNU4xaVBvMnNKYVpSQllIblkKWLC0aIQkQKQw1IORT71KwCjt9hBarPXt
            W0Q7SyImPnOwyd8ChmGLWAVJw13uh8+95ahAaezcdpLochgtGQZL5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T14:05:17Z"
    mac: ENC[AES256_GCM,data:Owp+ZenoegyUhH4b1q+SwD45/An7xtm8EF05etyMBQQVRPMaoY46yi2y0W42qPrija/UmXCFyKjk4VVncuHWURfnJnErHuAxuLnoyjkt9cFBI6kHX6Pcf4u6aAXveAX27TV4oo5lhVuQl77Y175GzprCyfJ4/3ul1lMTWdp0frE=,iv:8vlhYHKLuusu8UrlV019Uoz9ug42L/763r7b+8pcRHA=,tag:Nix9Gh/UDhYV4JM8hC8OWg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
