apiVersion: v1
kind: Secret
metadata:
    name: nas-rsync-password
    namespace: backup-replication
type: Opaque
stringData:
    rsync-user: ENC[AES256_GCM,data:mj7oKi/wEw==,iv:K0n0WrMVI1PVgXDQy7qptxbetsgfz2B0mgrk/NVWSwY=,tag:wheUKwmB1EhUa/GXTiyC4Q==,type:str]
    rsync-password: ENC[AES256_GCM,data:SQZmVQyJjJBoGc28,iv:a+UbQ1ytCIroqaJX7NcRD9PYzaaqkaJiB8oTnQ/dfq4=,tag:etMZRDbUAn2PBt3jSBz+1Q==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NXdlMFFJbEE0eHZwR2hv
            RnZ5Y3dza3V4S0RhOUc1YnN5czBjVzBxejNjCnZvSDRGWDIyYml3WUI4Mk80WDJJ
            bDJSSzh3MDNna3E5L2ZSNUxRVG5VNnMKLS0tIGlEbFVWL1JDSXRtMzMrQ1RKSWxK
            NW9HN2oxZG9mWHJEZ0hYbk1MSWUvREEKsyz04WCbWnIVWtKwv3Xgw/QTahf6ZlaF
            rffhv1Cb7Z5piz6B7TXWrCWpHZ2pXwlKWqH8+6hYwM5enfahHMRUtw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T14:01:22Z"
    mac: ENC[AES256_GCM,data:5hUJmooTDJznDpki2HpvDNKzMZMO/zO1VEKyyZsQZfLK3+zBw+l8cFTXSR76cL9u2xT1lPFhOcZGAOhesPlF/9Jb9Cf6lD44T9z3c7ZF68xRg8+4QlHy8W0bTI0Xx9gMM3KRggKDDxS2I7IUB4JD4KkohUfYOOKxloO6erwBO5c=,iv:g1fHQrsatyuKHZ6GKLox6w2gC9nj16DK61S5F57GYCY=,tag:XNTm2+yTV4AynR3hVLwkxw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
