apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-known-hosts
  namespace: backup-replication
data:
  known_hosts: |
    [192.168.1.126]:65300 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPn/DiB72vSy0+PFWUHC33Ckts+mvYXpwDiScrVCL4pn
