apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: n8n
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:elN9cNUnrVnd663WmDqnjMerKHWubRszdgn/05d3xqMj/Jt+iLmrP/zqCuBCpj5L04fD/wPYFQ9y+PGPH37+qRJW9IfLqi5QtJZs/RYXpZHHV4v8GCmFi45nJJoLVgHr4lQx7ydT3Z+SLjqN76P6Uqs2INWBQA9j/0kca1pxGT96m8P+6OPuYYwcDeZXdaRUvrCU0ojjRzzsrMyMnJHfDSBokNBTYtFi6m3geLF1qw==,iv:7rdW1CaMQRNmsc64zwqGDI2KWf3+wv67Nog2sQCgqg8=,tag:Yn8EFPvYQvUeXDxoYC3SHg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VmtnVWRXOVhFa2pwN3hR
            TEFGZ0t0UlI1Q3kyVnFFR1htc0FWK1NMOXpjCkhBeDZPTWxpOStoZ1RoVDZCVGJU
            WWM4SWw2VmwzV1k4VVpvV2xsejZzOHMKLS0tIGphR205YWNIV2kxd3FOc1QwREFD
            SHNiaC9hQ2VLOXk5OWdLWW8rN0oyQjQKoyYzGVz4HOg/S5CqqWWR2vWhlsp1LlIh
            noraweJFszSyeOE9IA+bW/y9P7a3b1ZrJbKzy727P+tj9YE7uY+jFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T10:22:48Z"
    mac: ENC[AES256_GCM,data:vNObl4yEUTE9O2EE1+x4fBNtqJ7spXBH+NCAwiOJpEEmSMBwNSxK6UREt+cY1RllZmpELfb+19e/2+9dK8EE/0kM4y+9NIopOxCnZPga25/58Eof5w1Ja3q7O4XI9sJRyeuzXrSuWOJ8j5pxoZx9zXm4zTJa+KnvKzZG1FzlNrM=,iv:AHGN+Ckb63TNtvk04Zoo03Apr5KVkSkD925+5gZjvnE=,tag:uXef9zRWRJ4iU3JsApuAqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
