apiVersion: v1
kind: Secret
metadata:
    name: n8n-user-credentials
    namespace: n8n
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:SNpSBwCg3d1rJyRsJosHBGsejUBp,iv:Vg4RRiMdkTdk182E/6ZzZwXMuYnxmG332eQBlBCPGWI=,tag:vRbKqiI2Bspb1RifvON9nw==,type:str]
    firstname: ENC[AES256_GCM,data:QNZ7TuH9+A==,iv:L2tvQU5ik8B7WdOnQq6eqN6Frt8TionLg5uCSjpzvuE=,tag:ygN04ES1paoXLF9WETrIAw==,type:str]
    lastname: ENC[AES256_GCM,data:YYnSG2I=,iv:pGjL+KRocGeE3l/wGJxLtYkmMUpGiwTJk49ADfw+UoE=,tag:MI3PsNZdHxYGFlWIlgKZ2w==,type:str]
    password: ENC[AES256_GCM,data:y9nqtyByK5y/kTcDQA==,iv:uc10AP3s557jX+my9eOMPaTyXeEqEenUpZ1q42DG2is=,tag:tvqb/geZeBgKztwHcibKQw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjc1gzTmRVUXM3YmpWTGZh
            ckxkaXltUHpUMFcyWmRVOVYweDhaVjRvaUFjCmZGc2MzT2hyYWRhMldBYWpCUzE0
            NXhDZytQVjJyMFRVSDlpclNNQzVQK2cKLS0tIDN0ajJJSWh2MjVKQlVJcjFMc2ZN
            Z05FYzROTGY5TndLQnpvYkpDQnErNVEKb89p2lKTWGYS1ZWDKYhojXieopthLD2B
            QoMlxWTUjCvlPhgDOY2Zt7ow4J6JLlBtMAhgGbkraIYS/KvM4tnyeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T10:36:50Z"
    mac: ENC[AES256_GCM,data:Xqkx6MkHt2B4j+0o7O5Zw0jqHkivXpcIDNheFVhl/w5CIFWx0lnGYZfHhHnGDj3hfcy24cSsDebizuZpQW4YGwWi2913XnMdBZaO/HZFuWdyiaOz213KrgT1/okbgDj9r5+ZWCAuJOAx29MylXjYwcGbXBRZomDZ/GqsvyItzLo=,iv:ITFddTj+nwoionp6gMbnDb+yQki2OUQIjbdodCcIP9A=,tag:+7/l8FQ+zW1AQDZiIy2orw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
