apiVersion: v1
kind: Secret
metadata:
    name: n8n-env
    namespace: n8n
type: Opaque
stringData:
    #ENC[AES256_GCM,data:VM1oe6gACMXV7//3u/PmsAbTCY2EMIo=,iv:rzmcEW9G1ETn73IsCHy2y2Sr8PN47VU4BiQ5yan/htg=,tag:faMZjPhAOjF4HrqW7L4huw==,type:comment]
    DB_TYPE: ENC[AES256_GCM,data:uZVJs74SY1rw5g==,iv:0eerc7heH6BN5VRnb0g6nkwsJQ2kp86NzDRA/Z/l0Po=,tag:lBLin08lG6iLhcppNEc+Ow==,type:str]
    DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:EcB0MUIPsuOsFJ4GCNfhxF0wxjRdwlvqY8mjMaf0bHyOxWerF3SHA2/YYGCDVrKM,iv:6cnSr5DZs09p24SSDfXCtWVuMSnElTRSejS+NuSSCkg=,tag:4jXADnyw7uWAWq/7mdWDgw==,type:str]
    DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:ySEiBQ==,iv:sf/dOOYASaKyd9t5V5fzYVmMcvnnXFpeS86VlEHUttA=,tag:NASzTS7WUSkrB73tfT7iRw==,type:str]
    DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:2Rh+,iv:lTXCMNFhuw2iRCzlcQDfOP+XwxTm5CgenlF0FlhUg0U=,tag:ociG4nr9VHym2CpAcxSEHw==,type:str]
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:tqy9,iv:CnDJXorNTndqzI+L0e05GlbFcFfWGD1Lk3SiURwRWKQ=,tag:xh2bEmYndZAGpL0+qe7hUQ==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:j2cZdiwsGXwwO7thDislf2o/6vTirW9dfv3slD/qAuFa7kHM1MadRd24Rh8=,iv:opV98PNAeVelOM9iyrY9YbR9jKvswEk4jKsjdsp+LvI=,tag:CVMiYC2BpJZJo0OwYvMtNg==,type:str]
    DB_POSTGRESDB_SCHEMA: ENC[AES256_GCM,data:YPI3fDZc,iv:QTbIAovBsDvbEOvRD0Hs6jylr6LpvTdjEvYQxsyT2FA=,tag:kIUNvquOyfUqovKLa6HiBg==,type:str]
    #ENC[AES256_GCM,data:9zjF3hQCVOL/M0R3tUR1tOJj6KB/pXgoBu4J1d69,iv:VHnG8AZyETLJzfDnYFuhr8mkuZbTZtJdnNY1g2iUm7w=,tag:wOntUJiMAka16/LbBsnNAA==,type:comment]
    WEBHOOK_URL: ENC[AES256_GCM,data:/qm9kkwy5o4YFcUmkxX+XhvUkLPSPAduHA==,iv:V44GVWXq1qnaMo0njm2EaETtWdPxXhvT+oat/Xgqmo0=,tag:wFEgHvaO3+/RvmviDQI7Mg==,type:str]
    N8N_HOST: ENC[AES256_GCM,data:EpoRQZPO3z+Xa8f+PkzwTQ==,iv:HmldmuS9ia6xhQQ4u5MZqDHyshdOgmXcxrki/FPk5tA=,tag:PtFVncPeSx8DKgfZIvDRQw==,type:str]
    N8N_PROTOCOL: ENC[AES256_GCM,data:0qhIoAQ=,iv:cQhEatRFZfQ7IYal8+9yK/t8nZ8wzc8pbx0CDSu2ZmE=,tag:mmExy6mlNMPSf5GQp/DbPw==,type:str]
    N8N_PORT: ENC[AES256_GCM,data:Os0nHA==,iv:S86UObdQmxl0u+QRjaj12KPFLXPjG5Kvh019Um7nWgs=,tag:PZik/xBG9Y/sWIfwaWgBiw==,type:str]
    #ENC[AES256_GCM,data:/yF8N0tPl+CY,iv:QZ/xYLw/4q03RjmwGBnRvt1i8QRxlMfcp1C+7F4XV/k=,tag:oajt/ppvi0C8NlXMDDHURw==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:lhwkArdo6I+DnbeD1jiZop/yBh0Qd85J1w+o5U9uJQFpep2Qu8e0Br/tkW5uHzGuUnt9pw2z/by0tsRBZdueOQ==,iv:2zKLI+PcT/Xx/WAjrPlLRtYaQnprWcdUJFE0beIZJ4Y=,tag:KXaTno0elEAwwUHKuUbBbw==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:L/LIQIulUz+nHg==,iv:Obi8PVgo52MHCgKmpwL2YQ62TUJvHrv9p3daulfrXfQ=,tag:6lyCyaOScXX4/HMnONx45Q==,type:str]
    #ENC[AES256_GCM,data:9vxE/E6iaqHd,iv:IUsY71D781qDIJZXS6q5RnNkyedMlfY7HAfrnXbvfnM=,tag:8s74cOD9wwdzOn+q5kznjw==,type:comment]
    GENERIC_TIMEZONE: ENC[AES256_GCM,data:3urzZMb2lakgZsKhDN2gkA==,iv:7PYC41TcFMBkoqNHUj+7qp3VTk8JZK5QPPgBDUMZSec=,tag:YgltekuT3JpmAq4eSHhK/g==,type:str]
    TZ: ENC[AES256_GCM,data:pYddoCE1gDIdIAENNO65UA==,iv:ERL68muOSwOtD0q/XRIKhvyjnyNhUTkEB+XKDCsKVf0=,tag:tHE7saPc9jxdZN0AOq4jWw==,type:str]
    #ENC[AES256_GCM,data:5wzRH3+LWuLyA5h6CG0kIUvxWPaTzRs=,iv:3aoK2sOzMk7i0/lZk0JnEr19B7sx1Uq+4ruZZE22OH8=,tag:8sIpAM5NHfxu2Q21kSQnDA==,type:comment]
    EXECUTIONS_DATA_PRUNE: ENC[AES256_GCM,data:vJE4mQ==,iv:JhL7fN5b1Ghi9egLPfKegOBLZccUMfYZno50+dApMPM=,tag:+FdUZYJpgKi+688fcNa1Jg==,type:str]
    EXECUTIONS_DATA_MAX_AGE: ENC[AES256_GCM,data:3x75,iv:RciJqM/6Gc9KYCNcoAKiGIJcuxzLR2O35bfKwhw+AQc=,tag:H4cnVUlw/fu9MrGgRNcypg==,type:str]
    #ENC[AES256_GCM,data:sprI0ozSk7E=,iv:dVRMCkREh4ZOxBToePMINgcHI/pUZ9lV4sUOLNxoJOI=,tag:kkhWdIx1yRNoBqFQ+1N13g==,type:comment]
    N8N_LOG_LEVEL: ENC[AES256_GCM,data:AkrCnQ==,iv:IjycK7/o2RiyxtXHB8btCW8nMswNYkvPnC17zQe5mBg=,tag:YPNDp669EjSfST/L2rWJGg==,type:str]
    N8N_LOG_OUTPUT: ENC[AES256_GCM,data:LciUpvHRnw==,iv:mqUDSF0s25TZ2867LJqe/VgSGSAm8IwbUXyIFLUZD6U=,tag:RLD3CWSCZyoaxSPbIeXM7A==,type:str]
    #ENC[AES256_GCM,data:e+9fEI57OM0=,iv:m0VKXgxcqvMDmp3wQ17kCZvpjTnHFreq1jWZYKgrWR8=,tag:OyxLx05Se2DiqNGTOpR7qg==,type:comment]
    N8N_METRICS: ENC[AES256_GCM,data:nK9dZbU=,iv:pbC1EEKMPNTD+plfXSDubC6kBq12sQrnZWTSPTtLHkw=,tag:xzf1kjfvazSfvivoZF1wsw==,type:str]
    #ENC[AES256_GCM,data:6M+ba6EhWy4hc5Py,iv:LXD5o3yfKOrVMjG5kMK720Q+r0heYWWeWaokFFG9rBA=,tag:nS9I5LJYuvSN7WL1sOijUA==,type:comment]
    N8N_DIAGNOSTICS_ENABLED: ENC[AES256_GCM,data:DBmq2io=,iv:z+UsYEwN21I2t94KjQqkvjd1WqT18xukm22S+NKYjGk=,tag:Pt+nizLWZxgkyRFroz/WpA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UEJRTHhzc2VjdDFLV0Nm
            dXN6MFI0c1hRN21XbFc0cmV0OUpBek0xQ2dzCkl6OEREMkxZMlpvZ3lWd1VESU9O
            RFhDRnFKR2pwWGkxQU11aSt5Z2xFazAKLS0tIFMySmM2WFprcm1FeTkxK01yWUlu
            QTRJZ3ZhTVhMekswU1JiOEMwTmdzYUUKjwPe1wjbb8dungyFb1aNvfxmukGvvDeL
            vpuzaVoa7I8uqa37qF3z3W6sG8/Y3yIddFWT2WmFmqsSjs4PBPURSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T14:57:47Z"
    mac: ENC[AES256_GCM,data:hQ6gMFhXSjIF971MbGYKQBk54pTnu/uIEn/VlMXq8587AJ+5eFUCrWfEG+gXblrTefXC45WDRE6UKLje1Q+jbhQXucyyf5+gP/BoyUrI+zV+vcuaSnDAZJL2veoRfQmPDTW8dyNVwNOJWZ+CXTo80lc/G1UCKUckASM2bMcZ3fw=,iv:fJDeNJ7ys/Osc4HjBayZArno1sfzuF2F4r3SxcNfEB8=,tag:WVgtuV/aCgUiaSVJS/LoEw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
