apiVersion: v1
kind: Secret
metadata:
    name: n8n-env
    namespace: n8n
type: Opaque
stringData:
    #ENC[AES256_GCM,data:vEbnntAXkbBleQkJ930M3ITD3cV00zo=,iv:p6wn/Bsnww1qJ5J/0BSi4hYKirxjNG4WSqZuYbf/sig=,tag:80vInR9Dxhrw081XNroZDQ==,type:comment]
    DB_TYPE: ENC[AES256_GCM,data:hZg3d0y70DX8Jw==,iv:ZKDAMs75vZK+3PBRUHxlMqIG9I69xKcd50VuEn7A4N4=,tag:T36bkwM/j/tqU1sV+hamAA==,type:str]
    DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:iUSF+FJE3Fcf7XXJmzFkMG9tsRTJFq+O8k78VxSLbhLLwgV27qZ8KyCtljpseDM9,iv:1IlVmfVBnuRPxzwA6J5t3Jj6MEImDILJI9U8E2i7m3c=,tag:yixfKyDLIxSB02Qt4RHwrw==,type:str]
    DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:xTqFpQ==,iv:p4nyZSTWK6Yu/v46JbRYKjiaRAVRVHQaUiaATmhZNiI=,tag:Z1RuCCNjW1sj0LL5QbGijA==,type:str]
    DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:SIn+,iv:FvSJGhtbJJLECTGHGkI7oYElz9PTZskaEJO6UyGskQY=,tag:9sfbTWQo768XVBF6pU3mSQ==,type:str]
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:EnoD,iv:1o52aORJstn63nHVHgauwN+RF7Kh+M/of3uzHqZy0HA=,tag:/5sIfuf44O68pQQfUSbz8w==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:qEdaekNHwed5YQSBHu4sNLtlHcSy+vhpVQ8JjFrgkUHmmtxtu6nMcYk34Z0=,iv:ehMiYu7x32Yc6vlZoREReTsehFm5dvto/Q5hhRyjMws=,tag:RtTpGmOX7bllTw4eP5nVeQ==,type:str]
    DB_POSTGRESDB_SCHEMA: ENC[AES256_GCM,data:mtMgcj+k,iv:ssEDHUpRTC4nOa/mdFedqLt1ddKCYIIbu8r1rogcXSo=,tag:QAPI+ftWoKEvsuAoDR/teQ==,type:str]
    #ENC[AES256_GCM,data:3QDw5MYGdwhxt5JHfOoNiFCUW/aNI0jKJcmC9Jm0,iv:da5vzXZ+2KOZVuOItz9mikq+SXlJE3gIl7SDygrTbis=,tag:yh7AWvbvLqvMmctFoZ7XaQ==,type:comment]
    WEBHOOK_URL: ENC[AES256_GCM,data:ZhfGhehiPlqQrMTr0kF7KyoYWEj9mMOa7g==,iv:M2mKyOAXHq+Uv6CIJIbgnHgM67ZlU8if0j9TaJm+MJE=,tag:jfHw7NhcmJdjK8EYmQ7b9g==,type:str]
    N8N_HOST: ENC[AES256_GCM,data:r/8LVQ7J3HqjWMqueBlwBw==,iv:c+Z6VtDQXdtHCJcEMKQrfVYlxcP3ZZ1FDuOLgeZGN1Y=,tag:g29JHzkOBNnsyMuqWm3QUQ==,type:str]
    N8N_PROTOCOL: ENC[AES256_GCM,data:aOeRCBM=,iv:RSOGBVWoKXEBDodqkvGODUntLwde4cjeeiExmxZFK40=,tag:PSioUPeoHIIo8z6LRNN6NA==,type:str]
    N8N_PORT: ENC[AES256_GCM,data:eR3teA==,iv:seBYElabWknLLPYGmf4/50MFkZPkOUrvNDclhpsXkT4=,tag:csy1oQx7u5eGIOl05zgitA==,type:str]
    #ENC[AES256_GCM,data:0oopDLvulik/,iv:jSBXfoHGrq58YAsebPr6nwGGEhDXrSG6bQQ4kpZ2lPQ=,tag:ukxCZGzjFh7wpRsKZJw0Vw==,type:comment]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:kq6uwApbBr1ELqQGEOleFkDc13WFOG3Ky8EiXknijE9UYxGxHbqf414po++Rk4C5ddbon8BPyQyVsEZItUfwkg==,iv:TWCFAXwXG+tIDlyG+kKSQB5Z5owaEfaMEY6CfqbLXoE=,tag:tKR3xsz24xwoY1PSs3VVbQ==,type:str]
    NODE_ENV: ENC[AES256_GCM,data:f83xi7DincxIfA==,iv:ZSUaDYTFoqSOgb3l2tyQ95G8ftH4L10sBcwqurMkumg=,tag:ZB+06bd1QE8Kp9Hy1RG7GA==,type:str]
    #ENC[AES256_GCM,data:D+1TOUIv1d9n,iv:sCFrF8fDufLvuAqstYl2Ta/AgUND6W5UvhzLdhKMtlk=,tag:+1WUbdPkHPP9WdBluw1wtw==,type:comment]
    GENERIC_TIMEZONE: ENC[AES256_GCM,data:1b1naU4xTr7+THbf9Q==,iv:tc1Fd6S19qnbpRn3k22lrNV1qw0/MycRNA76swT6+bQ=,tag:NPRhOqFJ+eWyf3RBdoVfCg==,type:str]
    TZ: ENC[AES256_GCM,data:lLJ0GuXWxau31TD+BA==,iv:zIVAvjByI0HbZAEd8dutLaOZ+S5xaMekQtq7APjRahY=,tag:4Z1NYubAkeO+v2bH6dZhFw==,type:str]
    #ENC[AES256_GCM,data:R+2JBc85fbfkXS2GadlRUSESnG37crg=,iv:JxULkjDMCQBnP82cBqvqxKcBPNfqU3efjv42B2D+DOA=,tag:3LZOp6BbGyDIlWMpyHS2kw==,type:comment]
    EXECUTIONS_DATA_PRUNE: ENC[AES256_GCM,data:OgLq+w==,iv:6q5eXH/KbjKR24XdbT0Enhu547bN9uVbn54eAlYPQso=,tag:DQRUC3OBy7Kuo6SmaU+79A==,type:str]
    EXECUTIONS_DATA_MAX_AGE: ENC[AES256_GCM,data:iG8C,iv:FjGgsBAYzuSNl3zaoolr66X7EsC+7VhlWykU7YV58jk=,tag:ndXq3G4I7CrShFg/Gkh5vg==,type:str]
    #ENC[AES256_GCM,data:7ZtO74VAHvc=,iv:lwGr2c+g9VE5QM+LZTDBzh5360605knjWkhrFKcBCQw=,tag:9oZjP/ppL7/u3Q4xHUX5YA==,type:comment]
    N8N_LOG_LEVEL: ENC[AES256_GCM,data:iGHFaA==,iv:KMdtvM/wqKybB2IgBeq/7ShX3b/Q6tCcYjIMPM6dVyI=,tag:YKoE/5q61sv83hNJx3XYsg==,type:str]
    N8N_LOG_OUTPUT: ENC[AES256_GCM,data:RytepKdDnQ==,iv:Ft3JuZnd9QbffBedDpbsz7plMx7NLuXbIwRkvE5T+/k=,tag:C1HIUraqrtpV6EnDuac7cA==,type:str]
    #ENC[AES256_GCM,data:WFvNMy3yMqw=,iv:s0WOvBkIU4v55Ui+jVyb8ocfRyWqFC6xk2/u6YYXQsk=,tag:jiQVLHFyw6XYSeIeEhUmVQ==,type:comment]
    N8N_METRICS: ENC[AES256_GCM,data:zIFNEds=,iv:TMJPX3kzS1SA9Q6Ub71NU1uQof9zOyGHdHTVg2eiLI0=,tag:fibu4pAO7AdW7Nz0kFAYLA==,type:str]
    #ENC[AES256_GCM,data:tGFh7RPWTqkjI+3R,iv:7gxg0C61VJgo6O0PZNtxuiyMQrBotSwQR6C9Xt/RInQ=,tag:f3PXU2ma4U1tmqq+LK/BYA==,type:comment]
    N8N_DIAGNOSTICS_ENABLED: ENC[AES256_GCM,data:AmW57uo=,iv:c1OHokVDIYKtNLCdIBE6HZgfVq5Nu2SYpnvIKnHUofU=,tag:kD9Zf3ssp86sHqT56MXf+A==,type:str]
    #ENC[AES256_GCM,data:rQNr13jEQG3MWqGWLTuXCjOCgiVFXApzmIzQbu/zClNeL25d60XKoE0C,iv:Zg8Bfi7oaKjTe8d+SI9RugUGhG6owJbUuaoxSBkcQnI=,tag:6WX884Oz2b9xu+ZQm3NhOg==,type:comment]
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: ENC[AES256_GCM,data:IzTZvg==,iv:bORa6aHsusx7BcYrQLyvcds2A3xSjwdflPMXQM3BsQw=,tag:hJ5BrWcqudSPQCEY4KPidA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcEZWVkFGRnNiNWxka1ZM
            N2dja3BpQjZOaVk4TFREVExCd2pnNWNQOWdzClp2cXgrU3FOc25TOGZlcktSaFlV
            NmhsdzZ3YStGSWRxMXJsUUtiVVp6WnMKLS0tIFB6dEtrcWVJNmxDdHRQWjRkeGgw
            dWxVdEpsMkhyYUthNlBWUjFvaHRUK2cK0MTYKpiOl5qVLbbx2HLlameSX98rxwPS
            iUP4HSK75t82/PlPOo6fISf9IJ45TdYVkWXvDd3OvqOLNxlktbKxdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-10T08:16:34Z"
    mac: ENC[AES256_GCM,data:XVuWoUmSzlP6al4u5Jxqe47G8OyxUGfYAKdP7oU4Wk0q0Uk1Pen4md43Et5gvNxmlhNirLCLiTMH5+gzVGOf4y+7vxIsgVr885C6j/naEC+k3f06FqwWo2NjKnNKcQRYOtytAomRNn7tj9Er12Nnr8f/nwHaxpBYG7OGM4tEG6Q=,iv:cCSMdfcBkth02QcT7r+0ff3WkPGw8BTNYAeHdwBH/lk=,tag:XMt9WPexGn6+VoDzcpWJZg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
