apiVersion: v1
kind: Secret
metadata:
    name: postgres-admin-credentials
    namespace: n8n
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:JKq5dBODKg==,iv:/gtDa439SVR0IgyrmjsZhg6qMkew7PhdxJSYv7KORmM=,tag:Yn/+6DU1WHkZXuJ0/aldkQ==,type:str]
    password: ENC[AES256_GCM,data:/YAfSboyE6xqa4dfSusuY04=,iv:K51PYDHcaibabYsWOHOlWMywErb7Tj9rOEQTkBxsTa0=,tag:0BEMyUlmvUoWiXDp0Jow0w==,type:str]
    host: ENC[AES256_GCM,data:ARZf8u4qn3g6AAT7e057Qgh4gJNaAVV2sdfdEwZRuBIOqXWkJoJvaDfi6Eo=,iv:cWH7xlG0NqGZNaOjDKAptLh9RS77bsE2rjWwN0wOCH4=,tag:e1z/Qn2a7paLxUBcORkhxw==,type:str]
    port: ENC[AES256_GCM,data:1nDECg==,iv:MdR7PtTTX2i46qSiqMwdrGCmRxLGBSmNEs39lgvEEls=,tag:ef9ZnWvdthTWdue87rXPeQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q0M2VzU3V2ZaRkNxNFBj
            Q0NXYjFRZ2l1blFqeE5JaWZ5NWNyT0ZJM2w0CnVWck50OFV6Q0pmR1ZJdFNjZWZI
            UVZ0aGdjSDRPWFdrbE8yUjQrYjRHaFUKLS0tIFc1RWJWUGpWQVJVWk9DM3JiQ1ht
            UVYycnpUUWFrQkJOQ0tPOVdLcGhnMzgK+rBbAdNe3DHQLkWW47qSvoAMJ3xh9ouV
            bDMKMs6xtN9XT8I+HD55CCqhv4OCjG8k9x1DybTeISyXatX6+Fz8Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T14:30:08Z"
    mac: ENC[AES256_GCM,data:WVP3SgFS9WDU3nwbueJv+4v2WK6LkC2butRYkMUUo1vNj13rH0hexeG5MqX+Cuq2fNT37yA2TPbSIMTOAbZhJkvKZThNAIvUvO6RO+XI0e81emiMdxhmL3RGSC0nj7S3I7phnUHfKDYTpw0WcZJ1YQc+Di0TCGC9myqIqUXgEqI=,iv:xGMMWwdYBsMgj7E3fq2QpDZdThxP51xYkPt1ROADD7A=,tag:zdVeAURGd088jBetP/DPRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
