apiVersion: v1
kind: Secret
metadata:
    name: postgres-admin-credentials
    namespace: n8n
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:jYMmw7uUNg==,iv:eucOBbM7hw5/gzlt9u9rbmXcF1byAFvkEMPpmCHf5/A=,tag:n9yRqa5nNnHpZ71UAeRHgg==,type:str]
    password: ENC[AES256_GCM,data:9Pu0DPjMEsJGVZC361zMnUQ=,iv:S3XPDSxJWVjwZ0S2iu+0yLptX0Q6BNcPA3UK7zK2VVY=,tag:oMsc9M3fEjxLztRJwMN83A==,type:str]
    host: ENC[AES256_GCM,data:0r0rWBMPCALTlrvEyAvUtSDx6llIdPGZo6cjPtCbYpNEC1w+9ZubQ1SeuHTEiivQ,iv:5jQIvTVNHx18ulT6680trXpBpeodV8BxY5z/0Dg81L8=,tag:Ip+aiwjowpDG9gh7yPuoDw==,type:str]
    port: ENC[AES256_GCM,data:M+o9jw==,iv:G+LksqodVFZ+jeoykMP94yh52l/cNXkQvbLNgs6tg4s=,tag:3yqjoKFit29Y9Ky/a4gngw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZ1pHb1JQVEFYQzRiWFph
            bzNKS2xJMnFLd3hqNEYvd0kzRXV5VmNhcVZNCmFUTzRleUs2bWl4ZGdhS3ZjcGFP
            V3FRWEt3N1JoWlViK2dJMHRTNTZTdkEKLS0tIEZ4ekZhM1RmVzhPeExKV0tta3M0
            bWRnMEg5VkpkM0tUN254cmJmM2QrdW8KgHH8txiixX0NaWIaNdMyvN27oIATTzIZ
            oKYtrM+aUwgRtZGltMrI0qRY8gpVYETGWHgwCnP1yGd7fgZrHMuUjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T10:29:50Z"
    mac: ENC[AES256_GCM,data:5ageDntgdnrhXSrAtQYlvuGednbJL1NJUg3NINVZrSPU5dZeXD2L83z4NZ+7cH5+6k6xVsSkf3m2dODG/Lkaki5B+4inGK74A3UlNhBL8ZJJ2HDLyUWq9uSDS0+2xc/Yen+hDeYihO6DIrvhoKzirbO/A69QKfVlUwnStkhq0o0=,iv:3048Dub+W8NIrHLIUztKGe/LGhcsTaWo4urpw2iwEIA=,tag:n39dw0MXz5MIt5irPlV5bw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
