apiVersion: v1
kind: Secret
metadata:
    name: postgres-admin-credentials
    namespace: n8n
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8G2oa5LwNus=,iv:2kafMQbeF9hd6OXWRdTl0SwUnY+dQ8AloOt15dzpSe4=,tag:QlA2g8XljXALO6+537opPg==,type:str]
    password: ENC[AES256_GCM,data:h0qb+kg9P/WfRFjBvEzhPNc=,iv:ybvPqoIFPhO3P/flgQv2YdrIE/rmRm8OJ6MCBXv0QK0=,tag:lbOL7PGR2a112ByEK1DUkQ==,type:str]
    host: ENC[AES256_GCM,data:rUQ+5S4isuHa+IUJFdyWfkdVLtUGpcJQFOgqGtHJLa5MYOHlBE2Z7cVrtkixm43y,iv:oe3bLLSbsGjusxe66xCXLn/znVD1lXJMmsyhNlSl4dM=,tag:L7qSy1gAZbT4ihvjtvhgWA==,type:str]
    port: ENC[AES256_GCM,data:jsgLcw==,iv:P+ksaRmvY+GsMVHIE0q1O/7Z5dQuSJF5ImUxJSQ5IvU=,tag:/T2EDqJHJPFooZLGDiQg/g==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxT3kweE5ORHF2QU9qQm1z
            Z0NVdzNSaW1wdVMySDN0b2x3QlZaQXg3d1NZClRteUNQOVNsSVpWa3dob1hQKzQr
            b3ZURHZRVVVkTm52ZzlHa2R0OExkbW8KLS0tIEsydU9wQ0pKQlZoK3pUSCsvVGFt
            MG1STEhnVUNtK2hUSkoxcm5uRHBlcUEKK4hAiT8+4Z8HvCqy3aPbipofxIeNheMV
            tsO6Sla9BOfG848/ZTQ5zVElncdUGZ4x4tlKW+4PGwmdbg+NbqI8Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T10:11:13Z"
    mac: ENC[AES256_GCM,data:QPomwTbkzvXIHO6FgxvYxQlKGeEp/2HOEkGYSd7FoLasSgn2wIYYaVhTMjWV8XBdTlPeweWyE2mWTO7TMsAiw/ChrWfbmcb8YVOXjSFiHGU6IQznekZiWNZQnIxGLgyNL62kOgKYH/1lEzZKH6d5c/v1+3bUTfvlyEZAU1Ly8cM=,iv:yVXmgYrwpd64D1kio4PVQ8Ym14SgNylVvGiXowK3/58=,tag:/OdXyDZW/Jcg86vPrbASPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
