apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-admin-credentials
    namespace: home-assistant
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ShmNdw9CWynFgDYEB/YQ3sVn4GQDu3FpUAGFJG8WnYLBXqyYbaGqzAltN8o=,iv:2xQ9fqgxVypiaPn5YR+uOMScFsRaFFnmz50Y21JvCvs=,tag:/Ml513jqJKv8EeCbPBaJwA==,type:str]
    name: ENC[AES256_GCM,data:yiWWZPSqnty+2UjU90I2wQ==,iv:z4sGlrpGN5CQWTjbVaFx+H7/cRueSPxK0PkJ9k5g8G0=,tag:DjKtzWtnuf5v4ihOhsbGEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUUFSdlJaa2R0TU1WSmpX
            UXAyL3BMbU5SMEx5VFJXTTdBZU4wOUpweWc0CjJoWk8zT09RbzR1ZVlwSzBJenFH
            VXl1MUxoSENucW52NTNrS0NEdlJSL3cKLS0tIDhlb3lkd044VEVJaVpvSnVjQmlw
            MElOTHZ2UGhlU3ZsVHBkcWxYTGc1YmsKiBJm+EthXx9HUKyZ2D6MJUIxFyycfcbX
            vqGBEsbDttpfvyoe1VngDUgOFSopXu/F03/U71gn4anvCZ+29xGKMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T20:48:09Z"
    mac: ENC[AES256_GCM,data:y60YMyqhg5kq1bCNd4HN2IyvPj3huRjug1hhMpKwoqMJPtOSQjH9ZEp5Jvy7VnVw/pRTvHZJhGbwRl5iImAEfdCsjXCSBU9StxoTbAHp+6UOL3frEVtSLuj4csT5nhNO/Iok3EJP+jRc6U/UUiiEn2ctHozH05L5UHnKIeAgl3M=,iv:oiU5GxIJ7e8gAVdrnxC/IhtgiHmT0IRkliG8Dl+reLg=,tag:+GpP7Ve6xWoJc3r668EMGA==,type:str]
    version: 3.11.0
