apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:8F6qU8CqUY7i0cazSi6v1y33H2fDUJWNuC4s0SCZ5OYABxzj2evuou0/u2i4eO0zS4sCSKdhKRiKgu17epGEkSWiTDsli3+yCB9rDugDBYVXBbuhTOvo+BRP6hkI4JAMRT6zpgVMTGBSZdQR0bLXvgFANOkgZPFo7Ek/L/I9GT9xUTTzmSIxgyl65+2qzgZ4s6aDpw9bTr/EqLFj9+Wx8ME3WoYlrDnxIINntXqYjrQpzjjCaujP/5ozdjRWN7oLpctVDgcIkDwBEaWhKm1YZti5QVK+8EaqLFbcHWW4Uv2DWesyMIS5+pilILAyl0Wf1LvDQXbEBvHZitwqlLnLa1vXRdVMVqWHBzqb0sxzpjVincBpZ8JJJb6gg5th77ZC1l6h11R5LzSbsQM8a3+/xKvUWPZxEjBJ8y8orX+9CYLvUaeahvFg71z8IAFi,iv:dS2uRyNGigT9y9pp2kznVQ/sfYkHltFX4D5B7N2pe64=,tag:a/efQINcNkA6/ZP5hRuBeA==,type:str]
    db_url: ENC[AES256_GCM,data:pvkEhAY6z/OotMHmiUeZqx0+7jh1M50Lo+QOi+57Mirz9d7f9t/0+I0kbR/+VNwzMukdSoOY4DcA+XR9PGVLscs9+vx9pdwbRvjWP2R99yUrSbqTKCnRYSlpIrnHDK82duNv36A+mWB3kkvGm5sNBAIjarLuixmsqg23I6oqqyfGRcHUy27fcsOAdAYQTNlyY9mCXuPQbng=,iv:fBCSQzAhAa80U27Z5Rc0PyDTDlEqHxh+sVpgu0hzsIM=,tag:9r6n/dFrNCkkkXNMhNcguQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjlZaVRDZ1ViL0FmcnlB
            ZXJUZTAvRHJFdE9KaWVwenpQSzV6Tk5EZEdzClpIQm5yKzgzeWRHSVBUNGNDUWZr
            VEpvcXcyZTNwb3FDSklmUFgwUkJrbEEKLS0tIGUySHh1YWt4a3pQQ1lNelRubmQz
            eGFkRk9nNWpObUU4MTZ5SWNKY3ZBRnMKhzSO7D9Nwq4XCSRJexo+chw8eZ9qE2lC
            Yk8iQ6yrWpubLrASbjDvd5/BCm/aNc/dCAD85B/av7ZSot+9YbbRmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T10:54:09Z"
    mac: ENC[AES256_GCM,data:I2spUIDaSToWyacwYgRL+WQws1hrN1Dh3pCEDUxjpNajbssbFQXtUYlZSYBgCqJflrpPIpWl6P+oxCMbFtES8lLgovkrpAy9wBhgv23mFQn8Y6Qr+3RAdxpbrrQrxR3o7AUOPKvDyjrYSc4C1riAx//e2eNLKD/jjP64UQ84FJA=,iv:LEfwMQbP9A18SHYypGg7p83hUTjfka6KLxcHHsLySos=,tag:FhbVBWtgXdeopJw/XoejPQ==,type:str]
    version: 3.12.2
