apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
type: Opaque
stringData:
    secrets.yaml: ENC[AES256_GCM,data:Fx2G/s8Cr9N8VAWOoQzeN3YGY4IJSeKl5eJTHOfJASmo5Gty8bptF76ogMCexRvf0oXMPmpAXGWsz8KUfhVbY0GdAbdtohGZAqAYIghtb3M88SaYUWFuc/uUUX8br4DuSBOjfTd+KupAAYJwLsQivU6RU4OKe7cTmEkOP2/BwWcROuNFowMzpqheB3LdYBy2MBY2l+kiDUPkPvjGxa4RsdxHOsXCJrMzofWVsADK4gxiiZZDcRo+o9lDz+eAwJ5qGLCMc9/kjFqil7Wy5aiIPTk7u40+f7ji+cLqjZ+MErTQf5/5InBm06Y7vYMb1Fcj2+4m8laURvzvjl2tOL7A7tXpvwqMBhS946p1PsOvaS2KLHVad1vCUjzPjDMs6wvuJdP8IxGmVtS7WaNuROfFaqklrkwtAQncSE7L3eEN5k+l6dJCbb4Vo+hg3K1v,iv:gf+W0w4F+6hsJWZopBWCURUQZJ9Y1k4Uc983PDz0bos=,tag:DQ0ohtEK4B6F/eECZsM2/Q==,type:str]
    db_url: ENC[AES256_GCM,data:nQfAMXC18HYdb6wGsH7OMoB6VW8YKUjBw/wr/dS5iTBs5Tn8uC95BBDa9vfFfVoJ3G1OfX9ylbvYzSry6BrVlZ7EQp0fsTzXRL55Ro+/cb8lrD9eysXwvtBgJ2jw8nmdr9lHc/zM93xYE3AestFwT0nZy+alCyDh+idPQnfsJhXsQoZQ3a5E2yqY2DlSbNyp5tytoh2k+0M=,iv:tKUpf1vkf1botr9qDTDnjgwUsHmudCTfQrM1mDRyZfs=,tag:xVV8Kh3H2AJfFuqaweG9DA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYjlZaVRDZ1ViL0FmcnlB
            ZXJUZTAvRHJFdE9KaWVwenpQSzV6Tk5EZEdzClpIQm5yKzgzeWRHSVBUNGNDUWZr
            VEpvcXcyZTNwb3FDSklmUFgwUkJrbEEKLS0tIGUySHh1YWt4a3pQQ1lNelRubmQz
            eGFkRk9nNWpObUU4MTZ5SWNKY3ZBRnMKhzSO7D9Nwq4XCSRJexo+chw8eZ9qE2lC
            Yk8iQ6yrWpubLrASbjDvd5/BCm/aNc/dCAD85B/av7ZSot+9YbbRmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T14:43:54Z"
    mac: ENC[AES256_GCM,data:qdYrDjIhTJihLu/3DEZ4tOQbOyXwOtQ3y57Yprb66wt40lpgXuXYn3Vxodukv7ALlvEeIu35oqGoabpQnR3/Wo7mHsoDWCwcj6uSWKGvFoqOWAY3ljfD0cCsNjLj5sU0e7gESFzsRfgvvE+jE1FkQ7o2QLbZHn5EmbFhD/4Uwcw=,iv:RMoioeDK+wkoUIkdS/YA1YX/G5FYw+QPE0SvsoVMUfg=,tag:b9kAer1G45yDdC/sAyUY3Q==,type:str]
    version: 3.12.2
