apiVersion: v1
kind: Secret
metadata:
    name: audiobookshelf-admin
    namespace: audiobookshelf
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:hyeFK2ppWQ==,iv:SzEjwOLkK+W9QWcLlfbNsXcyqj7yFyn59bw4r7TDZRM=,tag:nMHe/MbjeqRyF0wb+KH49Q==,type:str]
    password: ENC[AES256_GCM,data:kDpMbuiHGa22lghEgAmcCskjsWcnOdhLpXrxxXKLysgbQgkMNskRw1PbQfTop6wMBUlgPMZiAgPXEk80Ig0vVA==,iv:UlCckC469E8A+jvnv6H5EKiU2Nbj1T2lHlFNuTtYucM=,tag:JFOlN19fb4liOu+tdU7MRQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0SFk1azZRanJ1Tk1KcmVr
            L05kWHRVa1ZKNXdxVWtDRURFU1FsTEJSbUcwCm5HcmJiTWxTWmM2cDIxaUUvOEFW
            a1dJT3ZRTlhmUFlDL2hxMzN3OGwxNzAKLS0tIGxQTlJlNWNtOHA2ODZuaWtqRGo5
            aG5nbHFvQmxwTGpxdDBmS09mR1dtV2cKUBa3So2YNIv/Jtlg8NHcnifV3nq60kxp
            zJxgoxIbo8flEIuPxrzeiJEzegm43iJIkGH7TKOc+HmNKb7valRcnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-21T21:01:38Z"
    mac: ENC[AES256_GCM,data:X3hRv/UpuWY0j7Z+vqQM+HMFZ79ZtnNSA7bQZn3lRGriJlz1f9WazL7N97AUk6qGzd4Sq5mOV44cOpwbu3AOnuqt3i94T9OOgqqA85vNGrpbh8XSY6igNWWvZ7syBvhRImke0wBdU+oWow5JFVuyC3Mjko8ZQNS0PR/CuTlvQ3A=,iv:mss/DNv3FbjMXidcXixFnMPuz64H3DVSCvIZOAmbN20=,tag:w6IdIFjfZNohKuxfXDm1mA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
