apiVersion: v1
kind: Secret
metadata:
    name: couchdb-couchdb
    namespace: monitoring
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:0fMZQkA=,iv:y+AzVm/dMHV+tbV4JyaFbzX5JQPlPuWKJcV7Dd6sqz8=,tag:juJxxNtfMuoMBqDGcURMmg==,type:str]
    adminPassword: ENC[AES256_GCM,data:6pE6KOQrB0nhVKwMQZyZ9fQwQ7PkO1DreLyDaYAix1pS2x5Lz4/cYQ==,iv:0gUDWL/H2C6y7fa45c2orsgDV+t98z3oHrW0w/pApNg=,tag:PLjdqnkWP55LDNW5UL/yOQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORjVWSEM1bmxwMmhyVVNB
            eWVUOC9SbXBXaDc3Z3hJeUNCK1M4UlJuZHhNCmJ2S2hZV2x3RXcvdTNISVZaWmlE
            MXZ6eHBVQ0FqUVk5aG5vd3pZakFXbUEKLS0tIFlVTjJKT1JIdXl4bEdaYVdELytu
            MEVsZkVFd1B1WGs5T2ZpTm1lVm1kd0UKINN+NaATPIuW3TnzEnK00KHxuLTt/hpo
            8mkmQvV1tDbYO2ILBHNv9biyHcumEeBgxkRXRzRmH4m/OwlwEgeAVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T20:37:06Z"
    mac: ENC[AES256_GCM,data:hxAf0xrtHfVk8O+sWQTIzFykpq/QVcbj65mkpnvcDHROwh64DrZnjMml+BdZfwg462gBfcfSihaDcoj3YEQqrb0wrL9o+A45VeLtRkwiHDDnSohWi3Q1PCLYKPhqFLbI5ZaWlZJ99KOhe5RG39SydZqzafc/Bt7FScfM3wMTVOI=,iv:0/67QAaJ7wa2vCBCkFZosv0Ubl6dgXqXJspzx9uR8p4=,tag:p0upsaPxooVo4GTRAgJ4wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
