apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cloudflared
  namespace: monitoring
  labels:
    managed-by: vm-comparison
spec:
  namespaceSelector:
    matchNames:
      - cloudflare-tunnel
  selector:
    matchLabels:
      app: cloudflared
  endpoints:
    - port: metrics
      interval: "60s"
      path: /metrics
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: traefik
  namespace: monitoring
  labels:
    managed-by: vm-comparison
spec:
  namespaceSelector:
    matchNames:
      - traefik
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      interval: "60s"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cert-manager
  namespace: monitoring
  labels:
    managed-by: vm-comparison
spec:
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - cainjector
          - cert-manager
          - webhook
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - cert-manager
      - key: app.kubernetes.io/component
        operator: In
        values:
          - cainjector
          - controller
          - webhook
  endpoints:
    - targetPort: http-metrics
      interval: "60s"
      path: /metrics
      scrapeTimeout: "30s"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: alloy
  namespace: monitoring
  labels:
    managed-by: vm-comparison
spec:
  namespaceSelector:
    matchNames:
      - loki
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  endpoints:
    - port: http-metrics
      interval: "60s"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: loki
  namespace: monitoring
  labels:
    managed-by: vm-comparison
spec:
  namespaceSelector:
    matchNames:
      - loki
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
  endpoints:
    - port: http-metrics
      interval: "60s"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: immich
  namespace: monitoring
  labels:
    managed-by: vm-comparison
spec:
  namespaceSelector:
    matchNames:
      - immich
  selector:
    matchLabels:
      app.kubernetes.io/name: server
      app.kubernetes.io/instance: immich
  endpoints:
    - port: metrics-api
      interval: "60s"
    - port: metrics-ms
      interval: "60s"
