apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: cnpg-operator
  namespace: victoria-metrics
  labels:
    managed-by: vm-comparison
spec:
  namespaceSelector:
    matchNames:
      - databases
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  podMetricsEndpoints:
    - port: metrics
      interval: "60s"
