apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring
spec:
  image:
    repository: victoriametrics/vmagent
    tag: v1.136.4
  serviceScrapeSelector: {}
  podScrapeSelector: {}
  nodeScrapeSelector: {}
  remoteWrite:
    - url: http://vmsingle-vmsingle.monitoring.svc:8429/api/v1/write
  scrapeInterval: "60s"
  containers:
    - name: config-reloader
      resources:
        requests:
          cpu: 10m
          memory: 25Mi
        limits:
          cpu: 50m
          memory: 64Mi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  extraArgs:
    promscrape.dropOriginalLabels: "false"
