apiVersion: v1
kind: Secret
metadata:
    name: mealie-env
    namespace: mealie
type: Opaque
stringData:
    #ENC[AES256_GCM,data:CsTK8XN1NoL7pSzwIDwIMkbjeGTcW2iOXQ1JafQtIE7cQp++IyqPyF77bU+WIsnw1pyGc2o=,iv:EMPuqaX8m/oex7+OTGTH2H9MIO4Try2GW3cR+FxQhCY=,tag:85QQ+aK0hg/QnhXZJp0u+g==,type:comment]
    DB_ENGINE: ENC[AES256_GCM,data:ccQmEVzO7DU=,iv:GOTFjIRlKKtznoImkeld+FqBSYRo8+8kIH0PG+j9XCo=,tag:rUoMJHmRo99ypQGXC5BQpw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:kkfp0alz,iv:P1uMRZVY/kX/3PPXHBRV75KS3FhUPQ/lWLjLFv8URPc=,tag:A8oogjzLyjGu8yDah4/I7Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:t3GuFO8DPE7TAW76mexVeIHBEPuoe8jN7Sf/j8v4OQaOyzRe8PbwtONV4Oti1wU2/z6/+sHcVmO8nbHu10nWWA==,iv:u7nSCGUtztoraLtm5ZDu37dzqiB62HX39hIf/H56aIw=,tag:/al9uhN4tXo6mDrlCY9z2Q==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:hsRxKiTafV7EyvrvSBLn5j5dNcb39nDiZ/UoSPsFcSJjh/3zTFABL8F44QM=,iv:ulIa6zgqXBFXK00U09fS/lHal4pRnjhmUBQ0eAbiFDo=,tag:lh56+V7iJ2p5lEZRMBzo2A==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:Mwvjxw==,iv:Ft2ch7UrML2UxJCpx2SmanQyo2nqJnkbQN4lYoPCvQs=,tag:R7GGZOOk25u8aV4/KbuNZw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:BuqYZbNY,iv:vvV75Fx2QzRUK0Be/y6PHbMDxk30D6YWGUu9UUFTbpk=,tag:YpdPV4IvvPhcr9dr4PacwA==,type:str]
    #ENC[AES256_GCM,data:qCXS4LNCG2KdNxZqdSiV/Ud8uNo21N/G0PRAqbY=,iv:sKb3yECRlImxusVIEVD/dMkGE6q1+dWZuJY55kfYF4I=,tag:VfeoCSxuhNwKc0t9Yvn4ww==,type:comment]
    BASE_URL: ENC[AES256_GCM,data:y0LALA9ZOjeS3e34mUEzcEcBDznv3t6k1uXg,iv:A5yV2CmhUoaCYZFduc4CoBu2Oavii2nCJ5mgpV80Tik=,tag:adXyolcRzDeXdF7J4hqPGQ==,type:str]
    #ENC[AES256_GCM,data:Vu4hhLcTdYyq,iv:BBYyZoS0O7YfNdBGY0acG6JrZVb5iBaiUxV4ayfSADQ=,tag:20/jTxH7W/TNIaUZV23CoQ==,type:comment]
    ALLOW_SIGNUP: ENC[AES256_GCM,data:1YS98nc=,iv:TioOB1Oj9kqx3bp3z1GNBtBeyYQtCli/T2JQ6SG1W2I=,tag:WTkAMm/gqYGHYqnMyDDDkQ==,type:str]
    #ENC[AES256_GCM,data:1MHHdBsLNXsx9T0IXfikq9V+,iv:MOwtMfQkQjUD5EvgH3S2uKdJx+m8IhgHBxzNb/mnuQM=,tag:+rUCmIRX0wVi5/dI3kQ2PA==,type:comment]
    API_PORT: ENC[AES256_GCM,data:SRyTNg==,iv:B+1Zfn8tjSDrRcLWopRKH+ndnykSwSAAsSemvQHe+UY=,tag:9LZ6a979nhpXhHigNH8lSQ==,type:str]
    API_DOCS: ENC[AES256_GCM,data:YS8PUaM=,iv:OYmE5UWijkOIQy4eDSFPZFHHpCawSJOal1XJAjvoRmc=,tag:ahdn/IQRJoGxA8IuhKD5vQ==,type:str]
    #ENC[AES256_GCM,data:LIE81APLxojg3RjVJddw4lw=,iv:kqBFx1wsPJiMHWtqJV8aQqpoZ8himGAVRrc9t1qr0Qw=,tag:UOuBulvDhqGRp88Nje1VxA==,type:comment]
    DEFAULT_GROUP: ENC[AES256_GCM,data:kZStBQ==,iv:VKYrluGVfS5ccHqC7OzFxnXWt+Q+HohigLokMoO6TtE=,tag:r2I5lqd5PSOltkbO1z6J3Q==,type:str]
    DEFAULT_HOUSEHOLD: ENC[AES256_GCM,data:Ugdv9r7R,iv:t3MpXwd+mzdHnH7RGwrlvmBQFvqWDJJ0xqrnlLgKlis=,tag:Hg7vpsm0O6olTLhRuWRE4A==,type:str]
    #ENC[AES256_GCM,data:aWL8vwrsp2FqzC3ZNAXoP7lFKgeh164=,iv:JNCE93S0hlFrFPKjDRA9XNPBSiItyeWxFnGp1lNSq/o=,tag:r74xOMCdoXCbBuhzL18ipw==,type:comment]
    OIDC_AUTH_ENABLED: ENC[AES256_GCM,data:u1D/pw==,iv:NRW4k2qS1lyUFRWAha3dEe0SKlv6Qsun7LLlHfgg960=,tag:QH66epCXxLdl5UxS7emsxA==,type:str]
    OIDC_SIGNUP_ENABLED: ENC[AES256_GCM,data:mt6VDA==,iv:q9UqWKByswBiBpvx0ZwkkDtNT7bR3W1cKuEQybGZAkw=,tag:7s3y3cvcLEqadQ8Mvep0UQ==,type:str]
    OIDC_CONFIGURATION_URL: ENC[AES256_GCM,data:Or1PcHvLarcPC2urBZkwzV7la6zCfx6ev41y/wGJcfOMvtqUqg7qyI1R+6R3G/J+Jjpt1g02pJoAWE5GwWytRwvP1K3tQakwJYvEt/vyrcfK2Hja,iv:2uN3uoYOS45nW5d8awHZ+x1SqFZbaz+5E7XNSSyCERg=,tag:70ZcKQ8R83lBZdQ0uB1uBA==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:29p7IrYe,iv:93HbUNhv7mTzVZdsYRT28hZSOoS0nZqlu4TIXMEFKvM=,tag:s16IyjCCNDKglo5zYYY/Xw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Gpc3Efb9BYt63hOcHX6rPCocYuopm4ViWVm0BL+cA7G3m1m4T7ZrJKJJfx08ow2qkmKBOznZWaIkZeV2uAwkdw==,iv:NljzQQtAEYrvKDznR9tu2fLmmvQPwHgcdr0lgpEU3ts=,tag:u/U9SzgbK9K64tn1niJQug==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZzh2SGVrT0JMdjF5SHlN
            T1pKRXc3Zm5xdS9LTWhERXpzMTdYbHRXSXdFCk5xVlFqaTh6L1FQUDR2YUZiSThI
            RnlVUmJFeStLdjZtQ0F4cmlHaFRHSGsKLS0tIHFIOWZ0Wi9OUnloVmJhMGFzMUZM
            T3RoUkRsR0Exb1dXY0U4T1h4WjJIWHcKM23szcN3KqyPpDgM3O9f8vjLyHoheSaw
            3wDZ/AgKmzw21ecbYrB+zUNfl5wqBIXv5f0PyGYRKu83+7omf3+8HQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-21T19:40:22Z"
    mac: ENC[AES256_GCM,data:tyRr6C3jUObxtrXs7B3bGYjLl1iMFpNDTYySgvQLmaR2/Ypawe2bzkBiwAxa0aWVBgnFXf7wPiRhR0n7tCeYDeM2XMARiUlMEaZGO4Bdahae5lq+63G1Xgi9DTvAMuxZle3tuySsyMGFqMnCY7Xu0xkCJfhqAupSuJ4VYciOrRc=,iv:DQP84o5zG8ZM+HhEPaDpFj3quKIEZo3LRkbGIc7EaJg=,tag:kURvGPzEk8yJwiPUPVRDRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
