apiVersion: v1
kind: Secret
metadata:
    name: mealie-oidc
    namespace: mealie
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:jrJHu2KJ,iv:MgAFGPz5sGr3Rsqr+LcV7tXKMQYCDNpW6isSLMjOTek=,tag:X5A0phxHtfbOTEiwTo5GHA==,type:str]
    client-secret: ENC[AES256_GCM,data:0No2MltpFNVTs6jmy3hbOEJUnai5tKiOEZR7vwjiv4+lqSCFNDtcNU2eKxfY/x21R5cw+KSNdpXKCjKyrQvKlw==,iv:tvQNlxl99oJZzQ4Q12+sNmPyZeAPKosmUJHHhQZsGYQ=,tag:DZ+DdBoDvhDzStvbfsvHcw==,type:str]
    issuer-url: ENC[AES256_GCM,data:CJcvtjJI7IWxgmVvg+iLb4LHIU9r0RvUynOg19UeQyDyFccCvLZfmv1xqJcBfZDZNwqv7Q==,iv:uBXqM1IFamFSUELsEziF6P3kZzYZwH1Sz2FexXGylZ8=,tag:7FGS/4ff+txro+hIeFgC6A==,type:str]
    authorization-url: ENC[AES256_GCM,data:XvIiSiRSrXBzpDGYPOkk3RFZdlVpfb8IVM9hjCnESYsfhsx/5BuAZiCvp+iYCeOdigR9Zb3fFg==,iv:uc+k6aWI/Rf7WTsWsM3zGmBZ9QOoXjgqgldSdux5lpM=,tag:3zuszYgrPPFL2E+oYfi0JQ==,type:str]
    token-url: ENC[AES256_GCM,data:rWAZz5y76lcAIztA4ipfzyuZJK2Jik5nPRkpvzQVAf//wGmHk94wiR9SVl7Eon8Kn4Gk,iv:kj715I9v2nMfrsnXFBx57GwYTTnXXcFDt4v9wZzAqs4=,tag:snEE+dSuy23mpomtokMDhA==,type:str]
    userinfo-url: ENC[AES256_GCM,data:6ODZj3L+Svykb0CNxruNgSnUUULOiarW1I3s+CI9l52UkvsXXeBTRK1nrGTmBkOOn9fXlmHv,iv:8I1DjuIb31u7xROtQBKaFL6tRmgxyf9jlqjdJK3Eit8=,tag:4l2XTs3BXCE2VCBrzUoIDA==,type:str]
    jwks-url: ENC[AES256_GCM,data:hFcgpwpf+0kzsbwQ8amxW2lIN/deqGNQ+SGzMtCanrkRmuak8Pzkb8DlMTH4BkqTdV3z0mkx7bET,iv:VLZx3ZY5bxmUahTRv1kxCz3uVVgRUcs7q5Opn/NQIQU=,tag:YdRfODBpj5GDHYFCRuJvsQ==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQkJ2NGh5UW03bXl5ckpT
            djNLM241U1hlWVdROG1UNzVpRThsMExnSEZJCmIvQmNpR3dvZ29CdnV1SFlJejhm
            clY0U1Vtc2RCZS9NKys3U1NmL1doSVUKLS0tIE9iek12b29nNW44N3N5ZDRPWUox
            Tk5naXN1KzBxYWZGUkVsTFNYaXBnR1EKYn9dPlVFxUpdx4KPJ4B+E7Rw6+o1VX5o
            Rq9bQDwMJ/NW8fcvTnqsuZhBsqUZsy9XUpSOifzJ5eN6Vsjaexsm6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-20T16:10:40Z"
    mac: ENC[AES256_GCM,data:T4ZeLuwlM9d7/2KtUO6UN7x6Chp8dao2yvZ9rbiC09xtuunbttZPfNVuuNzd8JFQ1NyNQRKeLT5wyAnnjHQbhVll7NUvUSM9Bhpla88UkEeR+GaqRRuGqUHPsCSGwMJeufVpIZeupVda6Wngjk8sNlF8RR/nXRyIkyWzV819w0U=,iv:ZlC0bEmRcZ1LOD2qMW721yvzBOQ2cB1AT93T6FLg8i4=,tag:+056BXxptSDq5Fy4+l8DUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
