apiVersion: v1
kind: Secret
metadata:
    name: mealie-env
    namespace: mealie
type: Opaque
stringData:
    #ENC[AES256_GCM,data:OZa6/fVzGyyCl68K3lx70RKmlhTSBI6PBySK35aFW7LbBxQ+sH8x2F4HySvk2rpentdqFnE=,iv:g488Pyhk6/Tv4LHLK1/Nx3HWN+5V7WyUuc/7PIPQzq4=,tag:iZST6Rupoa17lHgRqOWo7w==,type:comment]
    DB_ENGINE: ENC[AES256_GCM,data:kds48bDAA/g=,iv:4jq0/WDb6xCNn5LRs7XIxGuGjQy2o+U48voPZEsaN4Q=,tag:H+diMcJj4S05ggi5c2trBg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:bRkl/jYr,iv:yayGlZGAVLpmJSY1o124Vz2x9SwVUWt3ReYeOWuyGWU=,tag:/DCGuCVbbgDvIYoEZUty1A==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:kHFkpFBFGkjgBcbQ3NYYYQFaRTNNDMErsqZmPTcbzbPB+ajOzqvOnTmcwZeQxxcdaw5QA7cIHeSh7omnXbQmUg==,iv:auZIpixwFiOQDFGS1g3nbHqd115nYHmspfEv1atDkXU=,tag:PJ3fZywaO/9X26YiX/dK/Q==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:hlABOaiUhzdRG/tff6+0RZQbnA5JGmhfsFLhzsGxScsTxUSf2kuC0h+yBFw=,iv:q3M8NMM/Z2VSuvBmX23tOMK3XXVrkkbxdQIX984wX7M=,tag:hpujw0/HR4pTR1keoIhL4w==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:HoTezQ==,iv:Oo3hkCJokjuIYfwYUQQf9TVp//R8kH13BboxZH+0l7I=,tag:6vIufIJDEVBq5rVSKdWhcg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:fq74bwM7,iv:li9z3ScO54wWg4W62h6Ei5Ku99jGpk8PAkaO4W6Y774=,tag:U7FeXuglU6LuEMyAj8WnQA==,type:str]
    #ENC[AES256_GCM,data:bn4fkzVVDvEASgn7KUCKKxvaGc7ifS9EtYrOnOM=,iv:exKUCosuXsFO2swYIMfd4G71hU1nzwNS8S1A69HLUnU=,tag:Ut7nOS15DQ5gKiS0rC6TWQ==,type:comment]
    BASE_URL: ENC[AES256_GCM,data:90Pvn/B2hfli/zDzbQwGm0IVoqIjKPl+RIXW,iv:FoQjVEzyLXAz0enwwCXgf7N6KVIta4bVzjT7f8AqiFw=,tag:kl2MHOLhn8uCFuPaV0ciCQ==,type:str]
    #ENC[AES256_GCM,data:E02KHaiDRVHT,iv:R4DR9sg02DtKH7KgsIRC88vJlVdK43z4LTHebE8RVH4=,tag:zkJlNuErTa0OszgfThA7Zw==,type:comment]
    ALLOW_SIGNUP: ENC[AES256_GCM,data:YLsVd4U=,iv:jsAMJ5uoBs92xC3xSDxU96XrE6apl6XYnktq3oUkFvw=,tag:sLxTA6iNLy/SxgEBT0tpxA==,type:str]
    #ENC[AES256_GCM,data:V7XX65M5uTSYnCK/pjmml1SP,iv:/V46nd37UnsMg7bx4YV0Gehzz7XES3vtYvSt+Gz9+Po=,tag:vrFcfnH5uqDgMY1ZuCPzMA==,type:comment]
    API_PORT: ENC[AES256_GCM,data:s54F3Q==,iv:Z9XoHGoSg9wyxW3u3qArfLQU9i83Yy+S5iXqvw7GRm4=,tag:A38R9kvXaZor+kAvov4IuQ==,type:str]
    API_DOCS: ENC[AES256_GCM,data:h25mssQ=,iv:J2Iq+X5teRS2St7Tl5L0hybvty+68Kxobk8wOEy9lYo=,tag:mM7lXRkULHuKvj50FrOnXw==,type:str]
    #ENC[AES256_GCM,data:anYDTKAEKlsB3RmQYQjFldo=,iv:QAibVYTDGFbz3lvVdD7W4Cft9cVAzT8GenMO6zpwFH0=,tag:ItbDmoFWH3LIrDRNu/eAVw==,type:comment]
    DEFAULT_GROUP: ENC[AES256_GCM,data:evdzww==,iv:hIi5fcmfTw8J5g9HnSO8FqLeazFwrVYxLz1/H5yipU4=,tag:QnOXqmxCnApclpQlBgHI5g==,type:str]
    DEFAULT_HOUSEHOLD: ENC[AES256_GCM,data:csJTN44J,iv:um71bQeNSJkVlGfy4F5cWiW4Y5bV8sfyfWe2kb5NUSM=,tag:YWhfv8Q7+rQX7Q2kQKmiYw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeW54MmZoU3pGem1EME94
            a0gxKzdlVkRsZkV5WXc2MndaZ0FieWNLRncwCmwxdXc5SnJGL1lFTzU5cVdyM0k5
            ZVowZjRHWHRST2V6ek80R3hZWjhKQXcKLS0tIDROa21GS3Nha1loK01wODM3SWZ6
            UmI0SmdycEoxS1Y4SytZMXRHMS82b1EKXqObD7w7Njgswjx6SVnt4ourniXXZiNz
            BdsF1C4opow+oS1R0i/2U8EGXMcWpJ65zdeGlK6gWNHiAh/j0/VS3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-17T19:18:42Z"
    mac: ENC[AES256_GCM,data:jaq40yWnlscHFvHGK9A5n1Dmme0wS0iajm2ga7x6RJEqPyAlsfXdifX0enQWdTp5UpKMX+Ud3y1MOXdrJSokQGGnGf7bsvRKYMcqp8wwPrjlwXlyQsppIHIHIHUffwTxTaOkxf1H752MMUq+wsBcCFfh8dxWbQFZrGqX1/z6DMs=,iv:d+6imvOEBcgCeutkC8V0fBNerMTtqZrFZOtLapmQ1QU=,tag:tZCQXpPKy8TvPfUKTstpgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
