apiVersion: v1
kind: Secret
metadata:
    name: mealie-env
    namespace: mealie
type: Opaque
stringData:
    #ENC[AES256_GCM,data:JyD6wbH4PbBmdcQ/yI6DYN7f+WstzKY=,iv:f0DExtf10Czm/riyC25rk2C5cvLlE3iuoIDWP76us2k=,tag:KHOapL51mLFtMWjRBGHvbg==,type:comment]
    DB_ENGINE: ENC[AES256_GCM,data:odPBiWjvj/o=,iv:Y1sNeojEyzpZBlAto+OLo2jLhr7E1f12a7bp/Q/+xCM=,tag:UW27nqz4XdKxq2C/APWXRg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:8f+nyh0L,iv:DheTu1YPDSj2I/pHNsAFLm2lBgFAo46Y1vx+ATe+WYw=,tag:ApPQZGLU6rEpirE/+Omg7Q==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:h380/4aYpvw9/Ap1ASTZVOXq4C57FMNKbj+M9v4MHMxTfQ6YcNOATmUU6As=,iv:p7dUoxoXUuoTk6Cry+nt+TsiQOVVM4nAA4irhv2N3LM=,tag:XRkXhQskubeScxtDFlL9pA==,type:str]
    POSTGRES_SERVER: ENC[AES256_GCM,data:CbGUI1IHKsBGtBw5KxGOWffmDdexpySeEwHY76qIEWnrtRb9PSKAsCgOOPp1/DLj,iv:RJPHKoYzvc6pCYVBhOtjKKSj0jN0CCca3WmbwDChCKM=,tag:+1kAF8zTXsnPPVS/lnPbVA==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:5N+2jw==,iv:hk5LrqQJPcLe2ZwMW4EsHR+gL/wZZh0K/uskuuKoatc=,tag:nWqfVPoK7uCLwazcv4Z4xQ==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:boqPStpu,iv:U36MHFgIPxMQ3EauFhggkPNqwZ9T9iv/Atr1xa+OF40=,tag:m4ex9b6XTX+Xy4mHJDj+oQ==,type:str]
    #ENC[AES256_GCM,data:1O5Db+OhP5C79sRUr02rtsC1qdPFjv8G9LhSghA=,iv:Aa55fK0LoF58bpMQwsVWC74ubLvYW+CeTykoEBMgXR8=,tag:udlFNBUdTOzoAZnBmURhug==,type:comment]
    BASE_URL: ENC[AES256_GCM,data:g319fvsaJRX5AfXFA5VyeEyNnWNpQbZSfN/Y,iv:wqxNemoFgQXxvEjr93/tO9O3BYzROIHSX3mfAljDGjA=,tag:rN3+kEQjQojuE7b9pgp3kQ==,type:str]
    #ENC[AES256_GCM,data:7bi0lrcVXZ2r,iv:EKPNz6qxMf4jWwQtktyKGq0Ge8UGbQ85OhgN67wX0ok=,tag:iKD6w3rt3BQdlT9YbjjvZw==,type:comment]
    ALLOW_SIGNUP: ENC[AES256_GCM,data:Gp6nx+8=,iv:x3852pcEmlYijm+z6rjHgXzFqBhhq5iKSngYZwWmqW4=,tag:8EdSt+p/xrqFpMqVn+Md2Q==,type:str]
    #ENC[AES256_GCM,data:Y3Sv7kUCnBs7r0391b7u/oTV,iv:Ib/pAxCtygahKwRvVEhWRyJI1uPliROLAZI75ZW1GgA=,tag:WJqI9FwcdO6dtvGGbJmu2Q==,type:comment]
    API_PORT: ENC[AES256_GCM,data:3W/uxQ==,iv:UCVDuFkkCHsYT++6+rS93ZcSzol2pjcpyRXMkVNlkpI=,tag:1dOleiiUrtEaRb3O9IKN3Q==,type:str]
    API_DOCS: ENC[AES256_GCM,data:di8g7d8=,iv:U+PXqQwwMamULBsrEr++C2oCPj8RuPZiqUHgOzpekAA=,tag:kKeiIDyoqud7lAXBVDbdWg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvTCt3MjI4ZS9Oa0s2cDdk
            eWx4dThkWUMwbnlGdXZtMTBEaXJjR3hrREhJCnozNWd3SWxlREFUbG96RnhZenhy
            dkhIRGlPRW9WRlNnSzRybWwrajNjWm8KLS0tIEg2c3hKSHBGSnRCTnI1RGhneThU
            Z2ZhNWZwenZYSm5hMHpwb3ZuMXRWbDgKOJUojaC0A5wSy8JlgJtTo6c+cKkdPY1I
            3p2qaUgkIl6HG6goQxLPymTV3VWqiiaBc3vIcmjRYcDM0SXH/wt18w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T00:18:22Z"
    mac: ENC[AES256_GCM,data:Bvv/INlZbKfwxbvz6ipNS6tT4nWs2voh6pLarFtAL7upXpCCymJB8bnHaVwr1PXpOM+JzA3SMa6r1DzZUDeyyAtPr/KAc9AluMYJnBqxvtr9U5iUZTX1CbI41XxNW77GXnh4FPV2hQIYNOc9LTpwG0/STBuqwJFDRzWMAZ5udyk=,iv:mVGfI2OT3+DB9HUe7Ol6BiPxO91P2VIIopKa9c5Ff9M=,tag:I133aYV7ibbXhYngxpVFug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
