apiVersion: v1
kind: Secret
metadata:
    name: mealie-admin-init-secret
    namespace: mealie
type: Opaque
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:CeUG5gTPaA==,iv:aEsCnC737/xdKtKphAIXRHk3kwjcmPoSPynULSl99r8=,tag:eydtoM6NFQT7rnZp+yB00A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:X8CbBpMjPVuaAi1yIcg/Kg==,iv:wbH//j5f0wCV5XkKqMx59oR4cMXN44Gf/5rLApsXIiA=,tag:OtckSBSS6rGqLy5EO6ooYA==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:x1aR/3p0GeDq5UU2omTZTq48mRHlBhL5e8c=,iv:6d5JkgDtJDt9rTtqs9PWke3Qo1AUtiumMz+BAQtL/b4=,tag:60rZ3WAPG+xctRkHkg4Q9Q==,type:str]
    ADMIN_FULLNAME: ENC[AES256_GCM,data:6tvkqUZj2ds8D1T2mu9KXQ==,iv:MQCkOYB9EijN6iiiCtT9M4uId1WS7nqr+SiUgANIkbg=,tag:TEOZZj11Pl+VdGIkH6fb3g==,type:str]
    GROUP_ID: ENC[AES256_GCM,data:vcT8/YYZSNHpQcQrRF75DyIKs3EbyfrTE9CRlqhCEyJBwyv0,iv:Upazd6pMZpTAzzia5PWDJWEtP8WeW2ffaB9bjOzFC7w=,tag:KzZxptfTDUTBVL3FfKcDmQ==,type:str]
    HOUSEHOLD_ID: ENC[AES256_GCM,data:rLZP/8oe1Y0cueYEMxBl72YgMQ8rAUAvJNICXSEtwsBdwm+h,iv:YlZlY5sm/3hd071OH0/QJ5LXafDQa8Uw5TeUq+t8qeA=,tag:yNydJRreIQ/GuvH1Lnby+A==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TDduWjZiZHB0L1NPeHZK
            QlVTanJUZndEUTJ2eFR1WEJxbXNmb2x3WURzCnFQMnhvTzF0SjZIVEh6cXMxQTVv
            RldlVVp6SDRSRzI1NExsQlZ0N1VQZ2MKLS0tICszakhOS0daV1NjYXFxbUF5OVY0
            bVdKcDVRVDlxREdqdzJ5Wm5rTno0VXMKHWnvObXm8aPli9u1ikCeWeXJg8fJY0lJ
            JE/kpHTPXMvT5OqrRR5FmpdiW7K2Djk1BIQqj4rnbkrB/Lq0MqFHKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T01:03:43Z"
    mac: ENC[AES256_GCM,data:I2SKtl9JmWVSdyN62J/BlyTcGAYmkfL/hYMhVVeMUc/N84jYMOEWS3nsaCw4hzkbh6VmIkZMiuW40tr59Hqg/HmbUZVOm2pcfbbyjS7IMVrE1maf1898FDpKceqi5PSDCBQLM+PGIIJCA7uNa1z7j3I0dzSD6OIBPSCnEX2Ri7M=,iv:Q37YEqYRKA+hI3t9Q21KHaa/p+PF2LYMB9HsXr/jGP0=,tag:7zmaCWvNrWdOc3sCOcpz0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
