apiVersion: v1
kind: Secret
metadata:
    name: blocky-db-user
    namespace: databases
    labels:
        cnpg.io/reload: "true"
    annotations:
        cnpg.io/cluster: main-postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:w2UBsdIQ,iv:Z1hwAd112nlI+SdSxsWZRd9sOMcu7IZHdMwq24C9ul4=,tag:5kS92kxZTMNTJewsjAv8ZA==,type:str]
    password: ENC[AES256_GCM,data:M8lHsKYimJKH64McpLf1c9smZuu0+Gg3P6t5DyjXQojmgX3SOwutnrClC/ZtUfs3,iv:FkNnByt/Ciz2BnvLcZF+AtbA4a11821hJ/DrlxUtm1U=,tag:uSJKTu4h/oevHqWd6OTZJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQ2pORXl0dUdHejdaZXdQ
            TCs4RTE4QUtSV2FpZ3ZaWDlIbmgrc0xBYW04CmRtNy8vNlFCZWZvNHRzcHgrZUNZ
            TTl2ek52a3gxVExkNmFCM1dFelZiUEUKLS0tIHFlUnB3YzBNQjZ5OUlLWFd6dTNj
            WHpVNnZOVnB2ZjFwY0ZCWXJlVGVmaDgKv5rwyAchgVQaPnvflnp45nFqDEu4XMWy
            R5CUAYXYiWiWIGFAX0LwmAk9xzYhP4h0AUY2ufzqL7ZrfOc2fSUohg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T00:09:26Z"
    mac: ENC[AES256_GCM,data:zT6i1JNlqPNeR4pWicPz5vHiOHEVgjqdPpKZwgaffRM6XmgH0SepbiEM6Hk0k0Lop508a4u33m2ZzVyKgK+nv+KIjlorSbDRUTSI8lj5+wCCZowuwvM9lhySTwvB4LYlFtfMKGp+Wly3yKP83qELtQ7f+aC1jIAxmoSdkBiJbbQ=,iv:lz0YSHzKK89a7jgsmfl3wy86t9Y06bFYMImR66dv9AQ=,tag:nRuy8ngq1lceEY+bqTrJyg==,type:str]
    version: 3.12.2
