#!/bin/bash
#
# GitHub-friendly wrapper for analyze-update.sh
# Outputs markdown-formatted analysis suitable for PR comments
#

set -euo pipefail

PR_NUMBER="${1:-}"

if [ -z "$PR_NUMBER" ]; then
    echo "Usage: $0 <PR_NUMBER>"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# GitHub caps a comment at 65536 chars.
MAX_CHARS=64000

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

{
    echo "## 🔄 Version Change Analysis"
    echo ""
    echo "> **Note**: This analyzes version changes and breaking changes, not code quality."
    echo ""
    echo "<details>"
    echo "<summary>📋 Click to expand full analysis</summary>"
    echo ""
    echo "\`\`\`"

    "$SCRIPT_DIR/analyze-update.sh" "$PR_NUMBER" 2>&1 || true

    echo "\`\`\`"
    echo ""
    echo "</details>"
    echo ""
    echo "---"
    echo ""
    echo "### Quick Actions"
    echo ""
    echo "**Merge this PR:**"
    echo "\`\`\`bash"
    echo "gh pr merge $PR_NUMBER --squash"
    echo "\`\`\`"
    echo ""
    echo "**Monitor deployment:**"
    echo "\`\`\`bash"
    echo "flux reconcile source git flux-system --timeout 45s --force"
    echo "flux reconcile kustomization apps --timeout 45s --force"
    echo "\`\`\`"
    echo ""
    echo "---"
    echo ""
    echo "<sub>🤖 Generated by renovate-analysis workflow | [View workflow runs](../../actions/workflows/renovate-analysis.yaml)</sub>"
} > "$TMPFILE"

OUTPUT_SIZE=$(wc -c < "$TMPFILE")
if [ "$OUTPUT_SIZE" -gt "$MAX_CHARS" ]; then
    head -c "$MAX_CHARS" "$TMPFILE"
    echo ""
    echo ""
    echo "⚠️ *Output truncated to fit GitHub comment limit (was ${OUTPUT_SIZE} chars)*"
else
    cat "$TMPFILE"
fi
