apiVersion: v1
kind: Secret
metadata:
    name: linkwarden
    namespace: linkwarden
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:AQ7Pm4597BWQVwDiGa+Sr0jKWPOjOR7fbIfzXJ93TOgzs0anfv7BafngaSjfy9p4bAY1QUOkjVDYGJyRaQwRlvCBFQTS4qQPGpYO/fPpwVhXvwC9TmQ94VnkbpUr+h8e14SlyzJifQ5b4T/I2NkCpTWPSaGOAYZ5E5yznp2caS8T7FXzn5KOFcq4Qw4TTBFNTDW1qsAwZMe5i06B,iv:6XhI7g/+NEFlhFGXHLVKImJwDVdE7iOdksJy1rfRIVI=,tag:kQOR4c97chyUThBGdu0rUg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:VnCkQhqs9xcZZ7JATXK36wQhdoV1L9m+7gm5YNpRTtZ9cDb6wXJeV17EZCA=,iv:/i52mrTXv1HJgbLC0U6PQkbY8lfjmCZvJ9Z/YutDjNI=,tag:/5czyg4IEYdQCy4AdBZrag==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:1BgJ/PG/apv3OL8l9mD2LYhwReWvcnTTmwlFNRhmVDIXC/jlA3yH7FnlfQ==,iv:kBMDmMEUuSNlXAe22tA5zDRrS3OKJDsRC4e5qcCpcW4=,tag:rNd6X+QHHEmDe3o92xLaCg==,type:str]
    MEILI_HOST: ENC[AES256_GCM,data:7Ch+PMEoTgk0bpDG4HqPvoIIGeeTjfSDWWRa15vHECtaVTLCjo20nyPFyuJ5NRj2zrDvEQ==,iv:YRHvIJ4oPRAx3L8udI3XeyGEcZd2PvnQnFF7euKPZzw=,tag:wHa4j/54RA8JWKxAbDYOkQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:nMswUjWug7IWkz4uVqV8caNr4NILfHlsL0WmzsZCve4=,iv:i+GZ1VltRnuIYUFg4kufGwN4CJz34OUMrKnwLq8XO+U=,tag:xXUXaPkSCJrEIBE5h/NkRw==,type:str]
    NEXT_PUBLIC_DISABLE_REGISTRATION: ENC[AES256_GCM,data:BCytgQ==,iv:j2ooraARvMo7sp36LrXCAWF9vflyyuCG5VxgJbpwgMY=,tag:t7A8iJYMxkopfUNX8P3omw==,type:str]
    NEXT_PUBLIC_AUTHENTIK_ENABLED: ENC[AES256_GCM,data:UjOz1w==,iv:Lhz7Opw3CegK/wy+x3tiC/as/q1tTkW9VMLrkW53WaY=,tag:35XU9wBY5VXNlD89KZgr7A==,type:str]
    NEXT_PUBLIC_CREDENTIALS_ENABLED: ENC[AES256_GCM,data:Hq1NPgI=,iv:MDeIEX4TzwHyDDO+e/sCF/4VPHn+OK2yIZ2FrMvTyMg=,tag:3LfrP17O6CcX39LEu9KLkA==,type:str]
    AUTHENTIK_ISSUER: ENC[AES256_GCM,data:fBCZg7+t/i3bneO8pRhwC5RdSRYZ6RVOFuYssUnEt//jc+wUwVgn4swc4EH2MCWm9JYvTXhG9g==,iv:ESoI6WTcFbz+1TLUgqS3DPVWTCO86Eu5DYUAOxKjDbQ=,tag:fDLpI97Vy0srMLX9v/fgcw==,type:str]
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:pmKmKZ/k19KBa9tbh6346+u9/NTa3XKB+w7rdsP6d8O1Ujd5jRWghw==,iv:PN/mROqAQ8ANtkfDO9w4DRJ3r4wKTd4GkNr2OILb/vg=,tag:ubndDfUWx0nLv13gviTSdg==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:WEICrBqIpNOouoFNNe6E1DPSOBJLw+4Uuky4RjBGPDdnrp/LsNT9iuWf35wF8bpPLyBk0IKXdS2qoKv4LeIIZjXssTpFMihluKeTDN1J9cRsCitsmknGWQf8KOaqM8YDYUKknWWdCcdMoHJdtT4Hw7/GBx6DI6k/0KQ2qNpTzMI=,iv:Mw3ycVX2bH7wotw1fCCfjZqbXQ2d1gohiagZdQtmcCc=,tag:ahqQMvasGW7IsnxzUXRA9w==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWXBWTzdTMEZCVkROajYr
            VWN6ci9jUFlzRGdUcENuSTduYUpwZ2hmMWpFCnRSd3RpTnhZSWJLQm9GS1hUck5W
            YlBtRFhaakZnMmhmVWxPSlVkTnJsTGsKLS0tIDkvcHBxSU8rSHFsWnZCR0w4OWMx
            YmVQdytOaUVsS05QWG5GSXVYY01mNUUK5FveoQhvPATeH65F2p52Vqnl4oLQUKns
            rOCkgGswD9vJLAaxLLU98JMAPIKiod97mt2khJGOBIFdDuKh5zGoMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:42:09Z"
    mac: ENC[AES256_GCM,data:Gm0TzdW9NaA8FcXxZ8Nb+ka3t5nwbcVNxBPSXQucGwSST/yPnpeevD6GIGHX1lxXCUseUsIcvHVhYDHdccgJ05EZ5cWTiO39WEkV6dfKQWISmv/s+HIdtYfTcpw9YK2pIqhtFeVH8+e3X0s2IqpVWA7plmPlhtxh7WgDPWFsirY=,iv:AEW4AKGjcQu7EHXqtMhdINjBjxgmCKBnCaHIq69f1Hk=,tag:6M7zgWOPgVMYNqeXL2lTww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
