apiVersion: v1
kind: Secret
metadata:
    name: vmsingle-auth
    namespace: monitoring
type: Opaque
stringData:
    deleteAuthKey: ENC[AES256_GCM,data:9Go4QjCwFT+ZF8vLTr0I0HWgFYq2VP3rgoIrqutMnl9uAgDniN1xCMCaUXz22OyGfIKySfG96ZmGHbD3bho+6w==,iv:+cmsi1dstLQAiE7RAITltxfrL3H8Le4Qie6mPdnqV6U=,tag:i5+IjarYNTC/NwzOPtPKpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTVJ0N2ozSmZrVzg2WE96
            OGVzaU1tNllhWjlhbEhPb0s5TVR3K0szMGlVCjZIWGR0SFJQc2t0WFcyOXgvaWV2
            M09kZk9qbXhUUk1OdmZ2MVlTRnFqSDgKLS0tIHJEQktZdHRpdk9mSGpaRkY5VUlk
            Q2I5eWRReVhTUXdRMjlZK0RXM0lybWcKwawU54TNXitX7ZVclOdqelIJJPcy6nMd
            Ji+I0/Py+xDNyNlyyKtdU38nKSMw5vLU3EgVCjks2BZ8kXjo67O54g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-29T18:02:59Z"
    mac: ENC[AES256_GCM,data:aowjfkfKaP9mnN0APjMlZhnN7kKrR7MpEwRZ1LlbzlKkmU49aIPwjpjiUGLg9P13sSYKTWX90QqJXDmwF+QrqlCZvOR6zFW650Z3yig9MsCiTqPe5xYHREJ5vBwvQKssgMeRkK+K7pvuqBvA4yYYCc9pIqUDi6T5mMpW0FWLRng=,iv:zREhttMc10H1QPBLFvTLBxakMPY8Add0tJv/AY1FxTQ=,tag:jvuK38M30Shz7VtjEWmXCg==,type:str]
    version: 3.13.3
