apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  homelab.override: |
    h0melab.work {
        errors
        log
        hosts {
            192.168.1.129 immich.h0melab.work
            192.168.1.129 paperless.h0melab.work
            192.168.1.129 stirling.h0melab.work
            192.168.1.129 n8n.h0melab.work
            192.168.1.129 mealie.h0melab.work
            192.168.1.129 wallabag.h0melab.work
            192.168.1.129 linkding.h0melab.work
            192.168.1.129 audiobooks.h0melab.work
            192.168.1.129 couchdb.h0melab.work
            192.168.1.129 authentik.h0melab.work
            192.168.1.129 home.h0melab.work
            192.168.1.129 grafana.h0melab.work
            192.168.1.129 uptime.h0melab.work
            192.168.1.129 ha.h0melab.work
            192.168.1.129 am.h0melab.work
            fallthrough
        }
        forward . /etc/resolv.conf
        cache 30
    }
