apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-admin-credentials
    namespace: home-assistant
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ShmNdw9CWynFgDYEB/YQ3sVn4GQDu3FpUAGFJG8WnYLBXqyYbaGqzAltN8o=,iv:2xQ9fqgxVypiaPn5YR+uOMScFsRaFFnmz50Y21JvCvs=,tag:/Ml513jqJKv8EeCbPBaJwA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUUFSdlJaa2R0TU1WSmpX
            UXAyL3BMbU5SMEx5VFJXTTdBZU4wOUpweWc0CjJoWk8zT09RbzR1ZVlwSzBJenFH
            VXl1MUxoSENucW52NTNrS0NEdlJSL3cKLS0tIDhlb3lkd044VEVJaVpvSnVjQmlw
            MElOTHZ2UGhlU3ZsVHBkcWxYTGc1YmsKiBJm+EthXx9HUKyZ2D6MJUIxFyycfcbX
            vqGBEsbDttpfvyoe1VngDUgOFSopXu/F03/U71gn4anvCZ+29xGKMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-19T14:58:25Z"
    mac: ENC[AES256_GCM,data:hgyYI4FLNhZ5ZWyZoU1k0eG4yuMRx2xzanr21HwEtb/4IIS1Q+zWT658rzFbZjBvlM5LBo1nssINRniE/AfW2ECs9eX/MausNcH+4/8f+9I7lw+UzyzWM2P+pImrmRjWYImpEYwbKsQLdQCYDzlKna1KGNdZJSHcL5nSyDXUqeI=,iv:Jrr7SkPO9gSYT+EvRdN8PXny4nPsTZKR/vc4LzGAnNY=,tag:8w5SING4YrY2DeNK/RMYxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
