apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - storage.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - ingress.yaml
  - admin-credentials-secret.yaml
  - admin-setup-job.yaml

components:
  - ../components/allow-dns-egress
