apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkwarden
  namespace: linkwarden
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meilisearch
  namespace: linkwarden
automountServiceAccountToken: false
