apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky
  - linkwarden
  - audiobookshelf
  - obsidian
  - n8n
  - home-assistant
  - mealie
  - homepage
  - uptime-kuma
  - authentik
  - claude-telegram
  - paperless-ngx
  - immich
  - stirling-pdf
  - homehub
  - pricebuddy
  - rustdesk
