#!/usr/bin/env bash
set -euo pipefail

# rotate-k3s-server-token.sh — rotate the k3s SERVER token cluster-wide, non-leaking.
#
# WHY: the server token (K10…::server:…) is the credential that lets a node JOIN the cluster.
# If it leaks, rotate it so the old value can no longer bootstrap a rogue node. Per k3s docs
# (https://docs.k3s.io/cli/token): after `k3s token rotate`, the server AND every agent that
# joined with the old token must be updated to the new token and restarted.
#
# WHAT THIS DOES (run ON the control-plane, as root):
#   1. Refuse unless the cluster is fully healthy (never rotate a sick cluster).
#   2. Back up the CP token file + k3s env (forensics; rotation itself is IRREVERSIBLE —
#      once rotated, the OLD token is dead cluster-wide, so there is no roll-back-to-old).
#   3. Rotate the datastore to a NEW token that k3s GENERATES into the token file.
#   4. Point the CP's token source at the new token, restart k3s, prove a fresh instance serves.
#   5. For each agent (serial): update K3S_TOKEN in its unit env, restart k3s-agent, prove a fresh
#      kubelet heartbeat (node-Lease renewTime advances — not the stale Ready condition).
#
# NON-LEAKING: the new token lives only in shell vars + 0600 files. It is NEVER echoed to stdout
# or the log, and NEVER passed as an argv (would show in `ps`): the OLD token reaches `k3s token
# rotate` via the K3S_TOKEN env (root-only /proc/<pid>/environ), the NEW token is generated by k3s
# straight into the token file (no --new-token on the command line), it reaches agents embedded in
# an ssh-stdin heredoc, and env files are written with the `printf` bash builtin.
#
# SAFETY: dry-run by DEFAULT — prints the plan and exits. Pass --apply to execute. Reuses the
# node-maintenance SSH identity (same key/known_hosts/user the drift-heal uses) to reach agents.
#
# Exit codes: 0 ok · 2 misuse/bad args · 3 not-on-CP or cluster unhealthy ·
#             10 rotate failed · 11 CP unhealthy after restart · 12 an agent failed to rejoin.

# ---- config ----
DATA_DIR=/var/lib/rancher/k3s
CP_TOKEN_FILE="$DATA_DIR/server/token"
CP_ENV_FILE=/etc/systemd/system/k3s.service.env
AGENT_ENV_FILE=/etc/systemd/system/k3s-agent.service.env
KUBECONFIG_FILE=/etc/rancher/k3s/k3s.yaml
NM_KEY=/var/lib/node-maintenance/.ssh/id_ed25519
NM_KNOWN_HOSTS=/etc/node-maintenance/known_hosts
NM_USER="node-maintenance"
NM_PORT=65300
CP_NODE="gmk-k3s-control-plane"

# Agents: name|ip  (hardcoded like phase2.yml's cleanup loop — the fleet is small + fixed).
AGENTS=(
  "worker-node|192.168.1.129"
  "worker-node-2|192.168.1.126"
  "immich-vm|192.168.1.231"
)

SSH_OPTS=(-i "$NM_KEY" -o "UserKnownHostsFile=$NM_KNOWN_HOSTS"
  -o StrictHostKeyChecking=yes -o ConnectTimeout=10 -p "$NM_PORT")

APPLY=false
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"

log() { printf '[%s] %s\n' "$(date -u +'%FT%TZ')" "$*" >&2; }
die() {
  local code="$1"
  shift
  log "ERROR: $*"
  exit "$code"
}

usage() {
  cat >&2 <<'EOF'
Usage: sudo rotate-k3s-server-token.sh [--apply]

  (no flag)  DRY-RUN: print the plan (health check + what would change) and exit. Default.
  --apply    Execute the rotation cluster-wide (CP first, then each agent serially).
  --help     This text.

Run ON the control-plane, as root. Rotation is irreversible: the old token dies immediately.
EOF
}

# k3s kubectl wrapper (always present on the CP), bounded.
kc() { KUBECONFIG="$KUBECONFIG_FILE" timeout 30 k3s kubectl "$@"; }

node_ready() {
  # prints "True" iff the node's Ready condition is True
  kc get node "$1" \
    -o jsonpath='{range .status.conditions[?(@.type=="Ready")]}{.status}{end}' 2>/dev/null || true
}

lease_renew() {
  # the node's kubelet Lease (kube-node-lease/<node>) renewTime — advances ~every 10s while the
  # kubelet is alive, FREEZES when it dies. A post-restart advance proves a fresh heartbeat.
  kc get lease "$1" -n kube-node-lease -o jsonpath='{.spec.renewTime}' 2>/dev/null || true
}

wait_lease_after() {
  # Wait until the node's kubelet Lease renewTime is STRICTLY LATER than $ref (an epoch captured the
  # instant the restart returned). Only the NEW kubelet can heartbeat after that moment — the old one
  # is already dead (systemctl restart stops it before returning). Compared in epoch seconds so an
  # empty/unparseable/stale read can NEVER pass (it just isn't > ref → keeps waiting → FAILED_AGENTS
  # on timeout). Fleet is timesynced (≪100ms skew), so the CP-vs-kubelet clock gap is negligible.
  local node="$1" ref="$2" tries="${3:-30}" i rt rt_epoch
  for ((i = 1; i <= tries; i++)); do
    rt="$(lease_renew "$node")"
    if [[ -n "$rt" ]]; then
      rt_epoch="$(date -u -d "$rt" +%s 2>/dev/null || echo 0)"
      ((rt_epoch > ref)) && return 0
    fi
    log "  waiting for $node post-restart kubelet heartbeat ($i/$tries)…"
    sleep 6
  done
  return 1
}

cp_readyz_ok() {
  local out
  out="$(kc get --raw=/readyz 2>/dev/null || true)"
  [[ "$out" == "ok" ]]
}

wait_cp_ready() {
  local tries="${1:-30}" i
  for ((i = 1; i <= tries; i++)); do
    cp_readyz_ok && return 0
    log "  waiting for CP /readyz ($i/$tries)…"
    sleep 6
  done
  return 1
}

# ---- arg parse ----
while [[ $# -gt 0 ]]; do
  case "$1" in
  --apply) APPLY=true ;;
  --help | -h)
    usage
    exit 0
    ;;
  *)
    usage
    die 2 "unknown arg: $1"
    ;;
  esac
  shift
done

# ---- preflight ----
[[ "$(id -u)" -eq 0 ]] || die 2 "must run as root (use sudo)"
[[ -f "$CP_TOKEN_FILE" ]] || die 3 "no $CP_TOKEN_FILE — this is not a k3s control-plane node"
command -v k3s >/dev/null || die 3 "k3s binary not found"

log "Preflight: checking cluster health before rotating…"
cp_readyz_ok || die 3 "CP apiserver /readyz is not 'ok' — refusing to rotate a sick control-plane"

# Every node (CP included) must be Ready — a token swap during instability wedges the CP.
ALL_NODES=("$CP_NODE")
for a in "${AGENTS[@]}"; do ALL_NODES+=("${a%%|*}"); done
for name in "${ALL_NODES[@]}"; do
  st="$(node_ready "$name")"
  [[ "$st" == "True" ]] || die 3 "node $name is not Ready (status='$st') — fix the cluster first"
  log "  $name Ready ✓"
done

# Verify each agent is reachable over the node-maintenance identity + has the expected env file.
for a in "${AGENTS[@]}"; do
  name="${a%%|*}"
  ip="${a##*|}"
  # SC2029: $AGENT_ENV_FILE is a CP-defined constant, identical on every node — client-side
  # expansion is intended (there is no per-node value to defer to the server).
  # shellcheck disable=SC2029
  if ! timeout 20 ssh "${SSH_OPTS[@]}" "$NM_USER@$ip" "sudo -n test -f '$AGENT_ENV_FILE'"; then
    die 3 "cannot reach $name ($ip) as $NM_USER or $AGENT_ENV_FILE missing — aborting before any change"
  fi
  log "  $name reachable, $AGENT_ENV_FILE present ✓"
done

log "Cluster healthy, all nodes Ready, all agents reachable."

if [[ "$APPLY" != true ]]; then
  cat >&2 <<EOF

DRY-RUN — no changes made. With --apply this would:
  1. Back up $CP_TOKEN_FILE and $CP_ENV_FILE to $DATA_DIR/token-rotate-backups/$STAMP/
  2. Rotate: K3S_TOKEN=<old> k3s token rotate --data-dir $DATA_DIR   (k3s generates the new token
     into $CP_TOKEN_FILE — no token ever on the command line)
  3. Update K3S_TOKEN in $CP_ENV_FILE (if present) to the new token; restart k3s; prove a fresh
     instance serves (MainPID changed + active + /readyz).
  4. For each agent (${AGENTS[*]//|/ }), serially: rewrite K3S_TOKEN in $AGENT_ENV_FILE,
     restart k3s-agent, prove a fresh kubelet heartbeat (node-Lease renewTime advances).
Re-run with --apply to execute. Rotation is IRREVERSIBLE (the old token dies immediately).
EOF
  exit 0
fi

# ================= APPLY =================
BACKUP_DIR="$DATA_DIR/token-rotate-backups/$STAMP"
install -d -m 0700 "$BACKUP_DIR"
install -m 0600 "$CP_TOKEN_FILE" "$BACKUP_DIR/token"
[[ -f "$CP_ENV_FILE" ]] && install -m 0600 "$CP_ENV_FILE" "$BACKUP_DIR/k3s.service.env"
log "Backed up CP token + env to $BACKUP_DIR (0700)."

OLD_TOKEN="$(cat "$CP_TOKEN_FILE")"

log "Rotating the server token in the datastore (irreversible)…"
# Non-leaking: OLD token via the K3S_TOKEN env (root-only /proc/<pid>/environ, NOT world-readable
# argv); --new-token OMITTED so k3s GENERATES the new token straight into the token file — it never
# appears on the command line. stdout/stderr suppressed in case the value is echoed.
if ! K3S_TOKEN="$OLD_TOKEN" k3s token rotate --data-dir "$DATA_DIR" >/dev/null 2>&1; then
  die 10 "k3s token rotate FAILED — nothing restarted, cluster still on the OLD token (backup: $BACKUP_DIR)"
fi
unset OLD_TOKEN
# After rotate, the canonical full token is written back to the token file.
NEW_FULL="$(cat "$CP_TOKEN_FILE")"
# sanity: the token charset must be safe to embed in the ssh heredoc single-quotes below.
[[ "$NEW_FULL" =~ ^[A-Za-z0-9:._-]+$ ]] || die 10 "rotated token has unexpected characters — refusing to propagate; investigate $CP_TOKEN_FILE"
log "Datastore rotated. Old token is now dead cluster-wide."

# Point the CP's env token source at the new token (if it pins one), then restart the server.
if [[ -f "$CP_ENV_FILE" ]] && grep -q '^K3S_TOKEN=' "$CP_ENV_FILE"; then
  tmp="$(mktemp)"
  trap 'rm -f "$tmp"' EXIT
  grep -v '^K3S_TOKEN=' "$CP_ENV_FILE" >"$tmp" || true
  printf "K3S_TOKEN='%s'\n" "$NEW_FULL" >>"$tmp" # printf is a bash builtin → token not in ps
  install -m 0600 -o root -g root "$tmp" "$CP_ENV_FILE"
  rm -f "$tmp"
  trap - EXIT
  log "Updated K3S_TOKEN in $CP_ENV_FILE."
else
  log "No K3S_TOKEN pin in $CP_ENV_FILE — server will read the (updated) $CP_TOKEN_FILE on restart."
fi

log "Restarting k3s on the control-plane…"
cp_pid_before="$(systemctl show -p MainPID --value k3s 2>/dev/null || echo 0)"
timeout 180 systemctl restart k3s || log "  (restart command returned non-zero/timed out — verifying below)"
cp_pid_after="$(systemctl show -p MainPID --value k3s 2>/dev/null || echo 0)"
# Prove a FRESH instance is running (not the old process still serving /readyz on the old token).
if ! systemctl is-active --quiet k3s || [[ "$cp_pid_after" == "0" || "$cp_pid_after" == "$cp_pid_before" ]]; then
  die 11 "k3s did not restart cleanly (pid $cp_pid_before→$cp_pid_after, active=$(systemctl is-active k3s || true)). The new token IS in $CP_TOKEN_FILE — fix FORWARD, do NOT restore the old token (it is dead). Investigate: journalctl -u k3s -n 100. Backup: $BACKUP_DIR"
fi
if ! wait_cp_ready 40; then
  die 11 "k3s restarted (new pid $cp_pid_after) but /readyz never became healthy. Fix forward (new token in $CP_TOKEN_FILE). Investigate: journalctl -u k3s -n 100. Backup: $BACKUP_DIR"
fi
log "Control-plane healthy on the new token (pid $cp_pid_before→$cp_pid_after) ✓"

# ---- propagate to agents, serially, health-gated ----
FAILED_AGENTS=()
for a in "${AGENTS[@]}"; do
  name="${a%%|*}"
  ip="${a##*|}"
  log "Agent $name ($ip): updating K3S_TOKEN + restarting k3s-agent…"
  # The remote script runs as root (node-maintenance has NOPASSWD sudo). The token is embedded in
  # this UNQUOTED heredoc (interpolated CP-side) so it travels over ssh stdin, never in argv/ps.
  # Remote-side $vars are escaped (\$) so they expand on the agent. `timeout` bounds a hung restart.
  # SC2087: the unquoted heredoc is DELIBERATE — CP-side expansion embeds the new token into the
  # script stream (non-leaking); remote-only vars are escaped as \$ to defer to the agent.
  # shellcheck disable=SC2087
  if timeout 150 ssh "${SSH_OPTS[@]}" "$NM_USER@$ip" "sudo bash -s" <<EOF; then
set -euo pipefail
envf='$AGENT_ENV_FILE'
cp -a "\$envf" "\$envf.bak-rotate-$STAMP"
tmp="\$(mktemp)"
grep -v '^K3S_TOKEN=' "\$envf" > "\$tmp" || true
printf "K3S_TOKEN='%s'\n" '$NEW_FULL' >> "\$tmp"
install -m 0600 -o root -g root "\$tmp" "\$envf"
rm -f "\$tmp"
systemctl restart k3s-agent
systemctl is-active --quiet k3s-agent
EOF
    # Reference epoch = the instant the restart returned (old kubelet already dead). Require a Lease
    # renewTime strictly LATER than this → provably the NEW kubelet heartbeating, not a stale/old read.
    restart_epoch="$(date -u +%s)"
    if wait_lease_after "$name" "$restart_epoch" 30; then
      log "  $name rejoined with a fresh kubelet heartbeat on the new token ✓"
    else
      log "  WARNING: $name k3s-agent restarted but no fresh heartbeat. Its env has the correct new token; investigate: ssh $name 'journalctl -u k3s-agent -n 100'. Old-token backup: $AGENT_ENV_FILE.bak-rotate-$STAMP on the node."
      FAILED_AGENTS+=("$name")
    fi
  else
    log "  WARNING: remote update/restart on $name failed or timed out. Investigate the node; its old env is at $AGENT_ENV_FILE.bak-rotate-$STAMP"
    FAILED_AGENTS+=("$name")
  fi
done

unset NEW_FULL

if ((${#FAILED_AGENTS[@]} > 0)); then
  die 12 "Rotation done + CP healthy, but these agents did not confirm a fresh heartbeat: ${FAILED_AGENTS[*]}. Cluster is on the NEW token; investigate those nodes (they may still be running on cached credentials). Do NOT restore the old token."
fi

log "SUCCESS: server token rotated cluster-wide; CP + all agents healthy on the new token."
log "Backups: CP=$BACKUP_DIR, agents=$AGENT_ENV_FILE.bak-rotate-$STAMP (contain the OLD, now-dead token — delete once satisfied)."
exit 0
