apiVersion: v1
kind: Secret
metadata:
    name: wallabag-env
    namespace: wallabag
type: Opaque
stringData:
    SYMFONY__ENV__DOMAIN_NAME: ENC[AES256_GCM,data:aAgYiE34b3DOA0eXCa2NwgAlwBu0n0ro06LwUX4=,iv:4HcxpYH6+rMWljxcXpKKkesQlaHk9csi2kIbwJhcWyw=,tag:tjqsRwZu82fpksCAIK6Icw==,type:str]
    SYMFONY__ENV__DATABASE_DRIVER: ENC[AES256_GCM,data:BEdEVlLBCDfj,iv:CV5uDqfsuWOuT5896LtpGN7DeruvXGqI7P8QluTWUwg=,tag:zzozX7+09kVpe+jq+SgqLQ==,type:str]
    SYMFONY__ENV__DATABASE_HOST: ENC[AES256_GCM,data:cnKE393IeR+EjijmnjQLZIetMgk9eNyJLzj5ywxlt0KeAwW4vXZNU9Ux3e/rsFdH,iv:9bSXWg3P/w63jpmwdwezJxhc1yA4NcHoY1aR0KBJWXo=,tag:1nf2FUkDy6rnnTh9iT1iXA==,type:str]
    SYMFONY__ENV__DATABASE_PORT: ENC[AES256_GCM,data:XZmpAQ==,iv:rtFDWSmKwzYaoPcMW9vC6YImrHbWLLQmuQoGVVr79gw=,tag:eg3gXUyJz3DmiGOfW5YMyA==,type:str]
    SYMFONY__ENV__DATABASE_NAME: ENC[AES256_GCM,data:01nXN2WPnSs=,iv:ncchbpAcSs5SKKwA3ZO5aW/Fr1o5+Gb5ewIQTQ+zCYo=,tag:S9Ksm8rHbhI5DU1mD8ULsQ==,type:str]
    SYMFONY__ENV__DATABASE_USER: ENC[AES256_GCM,data:OinFN/T3+zQ=,iv:+r1+g/4m+D7wJhTZbeIOdn23emjEKCz6KRjFGfkggqk=,tag:p9X5L8wUmC2kKzRJW2cwtQ==,type:str]
    SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:GLqgpzvlcwl2clvYB/aYRsEQuOQAYFXfeC8EEq5yuDJtwRVjnovWHtypFboMdQJvern7ywrz4CcB9rHJ6n+5ug==,iv:tFKQ5MFBaQ1sV3p3ZNrEVRBHItJzlwfvEvQyKQoQu+w=,tag:u8rhLbJD40BKxHEf3UQbKw==,type:str]
    SYMFONY__ENV__SECRET: ENC[AES256_GCM,data:bTlf+uC6FJG34x8EFafwMlQpQczEenk5zxIf6wHnJaS+8n6zw7eI57A/ZJBvxZAdORmyssypB2LHY8ifddluDA==,iv:zp59eaoKUr7uNEKuuOt7VkIjb+C8D/kmjJKdeb2MJF4=,tag:fqNF6f9R9wj2d3RNbyqzzw==,type:str]
    SYMFONY__ENV__MAILER_DSN: ENC[AES256_GCM,data:zOJdBxll4/nsRjY=,iv:mZkrn+YXowv7MFDULf/1SkH+oMTeL3ZoDOpBtsvYX7E=,tag:gsyQUkMYeSpm+jDTkjzX4g==,type:str]
    SYMFONY__ENV__FOSUSER_REGISTRATION: ENC[AES256_GCM,data:oWW5spY=,iv:+g/RM4nrPHA+tUzG6TstRonztXDdUoq/kSxana5iKXQ=,tag:+uQYcgvMVJmCuTs2erCCpA==,type:str]
    SYMFONY__ENV__FOSUSER_CONFIRMATION: ENC[AES256_GCM,data:IIyudn8=,iv:AUKnJQYSUh2kNwfkIZElcl9JByPmistMvrH3j8sKo2U=,tag:ehb8wb/7k7LVfA0Xf/gEqw==,type:str]
    POPULATE_DATABASE: ENC[AES256_GCM,data:z0EUfg==,iv:ic8mnL6mN9BAUZ844hRau4TyJKFiZLuIVrHsfTjN3Y8=,tag:/VQ8S/LGZN/gB+ZKaZ3I/g==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTVNvSzRMdm50djQ2STla
            M0diVlczNXZEOFEybU5jNUViMlh6OGVyVFJjCjNXOTJidFk0Z3RGbXpGZEdhUXVo
            Z1BaVmdvVHVlQXBqUEJHcFBGbnYyb0kKLS0tIG04MElrVjN1RWtDYWxodHhod0FJ
            T1J0cDFFWkdEQmM0ZURYWmJjOU1vdXcKhOJHdpssVqqP8NMyLTfcNqTpkgLCV9Qg
            3Dg/4oinOjWN4DgFKHfvv/mlW8v4fBgFA9Gv6JnYfcGBk9uGe0M/bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T13:02:57Z"
    mac: ENC[AES256_GCM,data:EjeAsnIe/eLBTkvjUDy3vs3QHetI38Berl3skF4czldM/3I85huWVPQ3kYgp3QoVoA0HXzT0hU0Ov7fgtZPKzyYKrpZGeoZsPt3pqllKZpHIrkPo4olWqz9QDtx5OH8qzhxIWYgkgdRGLqqzIYvkv3TdXNaXWl+sspZOfsqSLRM=,iv:lhQ25ClKQrrmgyJn7S0Oz5pr9ppimR9O0dsry2QXxGE=,tag:mGVJG4f2cxoDs158xadh/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
