apiVersion: v1
kind: Secret
metadata:
    name: stirling-pdf-env
    namespace: stirling-pdf
type: Opaque
stringData:
    #ENC[AES256_GCM,data:uuq6J9s3py3ZDu0NPVREGKIsyn1Gm628bII/fDe0q54=,iv:FNHkIUzplO0oYNFLHJnmH7VMvH8FFP3h6K4g2pWP0+E=,tag:wkBrRtUy61mqOceRLJb7cw==,type:comment]
    DOCKER_ENABLE_SECURITY: ENC[AES256_GCM,data:kOIXwg==,iv:sTfi5SJ2PeDlIkjj6upakq+ObFFUHp7rFPog6mOveqk=,tag:RXuBqlmukwDEkeP/16E4pA==,type:str]
    SECURITY_ENABLE_LOGIN: ENC[AES256_GCM,data:NjBkRw==,iv:zVnBNudGm7j8TnLZPqIJgYCfdF9BiwcdmxaDr/wcU1E=,tag:ZLoGmZEutKfysle5Srz6Iw==,type:str]
    SECURITY_LOGINMETHOD: ENC[AES256_GCM,data:JHEaiPmu,iv:Wg87ZgqyI8MQNryNc3ITQQcVg42LnaWJHvVsAmDxem4=,tag:ilDXzQEBwlZt5j5OpocDBQ==,type:str]
    SECURITY_OAUTH2_ENABLED: ENC[AES256_GCM,data:1fdcaw==,iv:Ys3nxdSPXD8OsoCkYk/wyUWCFR3xuH+6TcI6EYRg8JY=,tag:RB+oFAiG0EuZ+CVnHCWrSw==,type:str]
    SECURITY_OAUTH2_ISSUER: ENC[AES256_GCM,data:PEhbSKSkhgVrgzpfvmqwnKNjEhNsnEAo42F3O3UYC1ZSJDGv8z41KTufJ9WiCNsRiFPkgU1fzjizmw==,iv:k4wUIbr6WqS9pRx2YK5/VX1TqsGbG58oUltPAyZNnOQ=,tag:m5dCQoGLPYy3YMext8jMeg==,type:str]
    SECURITY_OAUTH2_CLIENTID: ENC[AES256_GCM,data:fXDsku/fe/D2DqC/Eb5HLhJwRw==,iv:tR1YylUlsRYSOCQBaLCbwzvN6GB4E9hTjWhmjSbM89U=,tag:6+uEGiFDqLa/SpQUFNywhQ==,type:str]
    SECURITY_OAUTH2_CLIENTSECRET: ENC[AES256_GCM,data:mzlLHD3itU7jW5s+tzVeASQUxybWsvFEVHzQ3o94LJ8fwv2oQJZHwsQlWsCpevxK4rxccHTGG7OmTsBM0Z9MKvmM0+yNL7Vr6bJsfKVO/YcZ1ZNU3V4NbMIdG7DSVAstxmhPCTWlOaMeDa2kZ4tSF425FyyOVM+GXZtx/9i2+2o=,iv:f4zRLT2ly45mnaHHWwVFPetdNOTub7ZJukol/KiMFwM=,tag:DgDqzutcFAuQjVy4lTQsQQ==,type:str]
    SECURITY_OAUTH2_AUTOCREATEUSER: ENC[AES256_GCM,data:0Kv2Rg==,iv:orAG+00DCfCgkj1l/g6ytULpVg9SLAJ1XcQFH1aSLRY=,tag:qg0iDoE80CDfhpGBzRPclg==,type:str]
    SECURITY_OAUTH2_BLOCKREGISTRATION: ENC[AES256_GCM,data:A8dUeOM=,iv:oPKmKssYBwBBasCT3ZWwv+QNcfFd3YppYm2TGC7ZJsA=,tag:9FXQdwyxGAQPKUd7g1JPUQ==,type:str]
    SECURITY_OAUTH2_SCOPES: ENC[AES256_GCM,data:nUn/AF4YNTD+K8Fi+J1FMHnaB1c=,iv:ljq3RYhReVKODI1SL1RDW5al/oZMU2GllvYWZyBDWPI=,tag:R8ZFI1To/W+Zq4l6WY+j/Q==,type:str]
    SECURITY_OAUTH2_USEASUSERNAME: ENC[AES256_GCM,data:V3REb4M=,iv:s1FZUTRApbmXriPuhqMcsFerXuZE8AKsr6YgqbPxv3Q=,tag:Vb1IHGGrNb+x9Nc4VD0wOg==,type:str]
    SECURITY_OAUTH2_PROVIDER: ENC[AES256_GCM,data:b6940kQUvIQt,iv:k/1WbNJd//w/rZ9iiv9/I4YnSxDCmaPUGSQOAW137aw=,tag:UzBgA8xgPSzZ8DfVpfa6mg==,type:str]
    #ENC[AES256_GCM,data:Tvprd7PUL6O1wqbapmhp1+noXfft,iv:7btouxZK7omru0M1n+JSYUwzOlgv9aGZnq4OfXbmNLQ=,tag:KE89HtMMCo114a02S9+DYg==,type:comment]
    SYSTEM_DEFAULTLOCALE: ENC[AES256_GCM,data:eYE8d4w=,iv:0IuAlwdelI5cnKhE9SFspkZGpJHLIYr/tvEidtn95ZU=,tag:ZKmK/KU5pyccJYrHQNI/YQ==,type:str]
    UI_APPNAME: ENC[AES256_GCM,data:yB1xGbYzxiphjbLE,iv:fIkfwYlo6Zu2/e5gPArFmRSn+QvSSdBt3TnkeFlsh+U=,tag:M9T+yOwgM6SfVmpPvN8i8Q==,type:str]
    UI_HOMEDESCRIPTION: ENC[AES256_GCM,data:95k22SJ419uoyL8FwOCXZlCEbHPN0RGUSzR0ZHvmHjurNaOljOgG7mQuxD18WIA1,iv:ee/TLE82Dc9+AFxphK3LJHGw+XmsOMc6gz06ARMTSgM=,tag:I1nHfr9ZKl4rvR11K9rQjg==,type:str]
    UI_APPNAMENAVBAR: ENC[AES256_GCM,data:Kekw0CR1UsEDtNG3,iv:2OrIxcVUXkL/xhWIdJpkXWVq1qdyQK07Rysz2EaZOv8=,tag:M+4/GFC3VJwJv/HpYYWnBA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRU1pNHZHTmk4MWU3Uk5E
            M3l6elRSenliU3JVNUJkSVF6R2t3NjNsb0RZCk1SaVBIbm5UYno1V3c5dHZPQVB0
            MVNZS2NCUWhoU21mNm5TcjBoTE8zN2cKLS0tIHJneG8vSEozdHJFMjFXdWJ6R3R1
            c1U1aEg1d3lENXNQdjA4Z1pRRDVHdTgKHQ0Jz5MnDivOBCZLWP7OON+dfkF+rDsp
            psfMoNzQ9yTEefh37XU5Ek3fVtGKrnsDQK1HH8K1wowjoXOJ6DWPfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T00:16:51Z"
    mac: ENC[AES256_GCM,data:wQBZqMA6h5ebhsKcvuhpIrkbCgQCrgAx64rq/XymH+Eb2zsAdKBn/7pkjfT24k84e3Y9ifL7rCUemqMow/WrQpFCkI95zGnq3h+IqnpRaEN6lj9xs5iBngRBnr3xxLxgaRc68E4klMyx4r0lzzRYIFggJ/LREfV+WaZn7OHTSCU=,iv:RyUQ6B7FmtD20Od7iTHl0JC8Ed2PYhnYhJ2EsWmw+eQ=,tag:OQzfpa8AMcfPqvZV0jNOYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
