apiVersion: v1
kind: Secret
metadata:
    name: stirling-pdf-env
    namespace: stirling-pdf
type: Opaque
stringData:
    #ENC[AES256_GCM,data:rLYP8DSDmuInH2JXEelOCW3S8SShw45bUrOBy/D3HTM=,iv:/sAUy3cSocHssVymTArNEryv5+/wHvg44tjjMSQt+9c=,tag:ST4UISuv1ub33sC6ATqGeQ==,type:comment]
    DOCKER_ENABLE_SECURITY: ENC[AES256_GCM,data:XAanvQ==,iv:UX3WHjYOjVFAxeP3oQCdD5FWUwvoC/Rqv4j9YXfB6tM=,tag:kPBFmoR3N4+x+aIzzIpcnw==,type:str]
    SECURITY_ENABLE_LOGIN: ENC[AES256_GCM,data:J3vYSg==,iv:InlgzLOlbNC/lD9CdVonhfgvCLfkWykLNkkinZxiTQ4=,tag:QyB01PUlDgVFBlspzLcJqA==,type:str]
    SECURITY_LOGINMETHOD: ENC[AES256_GCM,data:YPoGexoS,iv:HaFMinISOSrCtuKOHlUURdV3eckVHwFE11b4W37mLcI=,tag:8d04aY0j9OJfGnPevVJVuA==,type:str]
    SECURITY_OAUTH2_ENABLED: ENC[AES256_GCM,data:hR3Kig==,iv:iLsa5PdczqFu0LQyqt8DjvLt5JWtMbRE1DVMIZ+D3DM=,tag:jnLgtWsvJ4ZSlzikq9cZ/A==,type:str]
    SECURITY_OAUTH2_ISSUER: ENC[AES256_GCM,data:3MrJaOQ1vkpWr+uw1EVcFpYxAKl1Sfic0JrcqvwnR9WS0+WAOnHisaUJvHmdjkwe7cvMwzFnWkYNFw==,iv:ZM/YGDZv27ZF4iaWmNFA42xDDd+xoIl9L+8gp5dhUWo=,tag:PiOFLhS581UM165PlJskPQ==,type:str]
    SECURITY_OAUTH2_CLIENTID: ENC[AES256_GCM,data:GBh9lftKoCGVRfEPXVyXBnEKEQ==,iv:0KASIcJch7NLrdqfAvWcPWZOW2OtPK1kU9SDm8hSecM=,tag:u6VGdKIkYolR72h0O1LFJg==,type:str]
    SECURITY_OAUTH2_CLIENTSECRET: ENC[AES256_GCM,data:/JBwLh/tft7AX/SpSEipzOs/54ywnJYkyf/AReXuFED9icPPpEbz88vDVl0ZWV3reoNeDL0Y+JMZP1oHW574NtkWbiBVJ2fxFi2n+/rc0PS3b+29q88mqzDArupGvFqTSVRW7pM3tOEtBqSWBlCeHbASl9q6f3pSpnE7W7NIUeA=,iv:gvdQBu5oFO5vt8rycOt3O4lsjp73/uU4JwCpZLJVUtw=,tag:sUYr5r8/DeYUsfZfrkPVmQ==,type:str]
    SECURITY_OAUTH2_AUTOCREATEUSER: ENC[AES256_GCM,data:rzakxQ==,iv:bCuSdSRnXQwUbXsQuX3jHxeNBeKr7nxJ6wuxshicq1M=,tag:7pFMtjpOXJILry7Sd3Nrww==,type:str]
    SECURITY_OAUTH2_BLOCKREGISTRATION: ENC[AES256_GCM,data:vtXcMDI=,iv:+P3Yq9OQpF6e+B+K3c0VFz+Mn4mYgo/sODEhACYjCO8=,tag:H3zBfcOULF9t1L1zUUxQDw==,type:str]
    SECURITY_OAUTH2_SCOPES: ENC[AES256_GCM,data:v0KwZAYDrrZ4JdhqAouLPE3xiuk=,iv:bA2rG1dGa9fztrULbE16HbKXf3dtjUuPcpSov5pXm7U=,tag:CY/yQkPHU/Bm3ijXklpMsA==,type:str]
    SECURITY_OAUTH2_USEASUSERNAME: ENC[AES256_GCM,data:1H/tMi0=,iv:l1Lu/3CRe7UlaJGgS5Cecy0gftuM76n18yweZfv54hs=,tag:/4fuzvnaZeLCJNhOvMms3A==,type:str]
    SECURITY_OAUTH2_PROVIDER: ENC[AES256_GCM,data:hoag9uQ7+Hu2,iv:MlxSvbhWDv48BEp+ZleLAUFMkNZyuifG0yN2fzvB/30=,tag:Aenk0IDL0iC1sbG/x9YuKQ==,type:str]
    #ENC[AES256_GCM,data:JZtylv49mAYuBHYR2wb5atOoG6QsqTQ=,iv:C3YkEnjX30h/ixqR1AGsmRWFbLGMBHqasCP9lghwQXs=,tag:X5J5iV8FV0SdH5Hqwln5Mg==,type:comment]
    DISABLE_ADDITIONAL_FEATURES: ENC[AES256_GCM,data:i6FIVAw=,iv:YBjHZkrXSUUrArkVQZNO5D8AxAazTBp8xWfPVxQ16qc=,tag:6YQTI2qWY3ZLkf1eEG8WJA==,type:str]
    SYSTEM_DATASOURCE_ENABLECUSTOMDATABASE: ENC[AES256_GCM,data:gpmxvQ==,iv:hMJ6GkcHl3TJ37MAjFzr7ieNr0etowHdmbXRfucLy2E=,tag:pJGg/3Gw8YsYNaVpVRuPAQ==,type:str]
    SYSTEM_DATASOURCE_CUSTOMDATABASEURL: ENC[AES256_GCM,data:N7FgnLwV9ZMsjUk34ULWRtiaIizeTSGf3/jJIbb45S/Mk8QX2jv4eTdlRU8HtsL8Qm1ZWtIldYVtnLaCuEUX0dA78uQD+G4MEXjc5/houxme9wE4luo4RPg=,iv:8ZIRWxeoF+O5BuBYdRd0+CHsJy/o0Hs7TgkhYaAikA0=,tag:fIC5bU87GTBKLt6NRLb8Ag==,type:str]
    SYSTEM_DATASOURCE_USERNAME: ENC[AES256_GCM,data:tlrYdqlrUiO3w94=,iv:A6aYbz5pRFRgHHOgKqueTLHQIOiqsQQpFQlXgRikvac=,tag:moeN3ZlXViMh/0i8DBSS+w==,type:str]
    SYSTEM_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:FM42X/AVGZMQjvr+vv0XclQDkWGKR0hLuNk7Jx2x6yGcDZdloPmEy4SjHuBE5RbX,iv:CnRhsVkLBWzGZtIHISKJejdXLHlVS2tQl9xEmhcpyvg=,tag:U1G6ExCHg4cZYvwaQuI7Ng==,type:str]
    #ENC[AES256_GCM,data:N0sexmxq5lMsEAZ44PXrGmIczu40,iv:r00yKD/0Vp4Jz1EAP9ZEm68WrpokNDUE5bL/t0hGsNk=,tag:Ur6Zs46X81ohUwivC+gy5A==,type:comment]
    SYSTEM_DEFAULTLOCALE: ENC[AES256_GCM,data:w4yxHEo=,iv:8j8CUTwdsiHeQrsywh1v7mmK55/nN31mMm9Kd+e4npE=,tag:04fviPG3MnTOtbWRyxjdZA==,type:str]
    UI_APPNAME: ENC[AES256_GCM,data:l6TL8ho6nQ9LaK5q,iv:935NgCRgoEIeTSmHuwgduFSuFq3yAMhDI+cbfnXCMnA=,tag:G/3/ttr3jEUDDexMxDUGNQ==,type:str]
    UI_HOMEDESCRIPTION: ENC[AES256_GCM,data:wO9B7H6NbBQqJ7lsndx7BIDQw3kVmPOY4j1r0QjwD7mroQhW8gm4PLhqePLYxzp1,iv:xfCYNsSWrznUNXfV16IumeKdk0zI7VjcBl6OmuGJZ18=,tag:f9QRL/QVP6L9lqZRei/7tA==,type:str]
    UI_APPNAMENAVBAR: ENC[AES256_GCM,data:YV/DQkDa2z421Bbi,iv:1Y8awu86WS7Rgcl2/RbqKcPvAkzdOvN/DNeBGVvul68=,tag:0WFlAH2/xQlnCYdnOkA3zg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMGgzZHVQMkUwVmdNdEFG
            a3BzVGIvcWM2WVlKeVNLNDdvU3FqTU1qNEdRCnZ3WnRCc2cxcTg5cmFSbEplUlJ0
            ZFlsdjFnUG5EZFo3WDNESG9CbDVzNWMKLS0tIC9QenlkNEIraE5ZS3lvNE53R1Jh
            RFB1UldqcUxTYjVzS3E2YlFPdWJzencKL9phCQoLyPWtzklP9DI9uJxv+qEB3hz4
            ObZkpzNJn/HfvoIeH4jZiRDWF9COYx111efEKO/uspwMHoWiIHXCPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T13:57:01Z"
    mac: ENC[AES256_GCM,data:BUeVxBKGWpDD8RjTNDG8+BbrqwmN56W2184nDXCyAvnnPMj2Q4qcuYGESnVPi7uWlaSRNGSdU6aaBUbKvvab9jD9nyXL0+1IqULoA3U8Sgxp9uknN/2zniPqeSlChOU8BLVQ22GIKiUPBE1NL79r5pUDeglztHBJ24vzcv6woKE=,iv:DH8LIpcIlyueN52MwNWU6lz0DoC+zB9/xFkSJjQzakM=,tag:6kCvr20ZMQZPYQbuX5wKFQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
