apiVersion: v1
kind: Secret
metadata:
    name: stirling-pdf-env
    namespace: stirling-pdf
type: Opaque
stringData:
    #ENC[AES256_GCM,data:eZRrklIhQ+Wyo1+vlcTf3GQBf8NXlLyONlI/OrSMvxY=,iv:KRGneaXVgAL0ZdfYKtwO236g3CS+NA3ovcsfrjFR/1k=,tag:6LufrHvbg4wrMZsIyp6YQg==,type:comment]
    DOCKER_ENABLE_SECURITY: ENC[AES256_GCM,data:Ng6vfA==,iv:Wkikc5dld3Ptg88/sZxdTyEa6HKPt8A7WJXAvxJ8Kq4=,tag:ehdOnbJ9m5MmiJfWR5LjDw==,type:str]
    SECURITY_ENABLE_LOGIN: ENC[AES256_GCM,data:C2RDjQ==,iv:thynQaZG+CoWFzgccY3/iFChulj4De7JRLMocRAPxj8=,tag:hb+bbnZGdzX2b2SKY4RWTg==,type:str]
    SECURITY_LOGINMETHOD: ENC[AES256_GCM,data:N+esX2a1,iv:MuRdrdmkGAB5vK5NLEBGu90qzmDei4dg2OL8nnfoRCM=,tag:njVVflM74MlqtK5mGsRpkw==,type:str]
    SECURITY_OAUTH2_ENABLED: ENC[AES256_GCM,data:QMFhFA==,iv:0wIHLi+ELuZKaD3FmkDv19PhsnSu1OETON/avLPIFns=,tag:WCyn2e49zB78VE0QJoKb9w==,type:str]
    SECURITY_OAUTH2_ISSUER: ENC[AES256_GCM,data:QX4k4/O59H9ITfS4wF9h5t7Wnm06GEUZJAw50JwBsJigsxeBOtvbvwkkclMTqJjkirsyh7XTL0bw1Q==,iv:LKfIYIZFdqOvrkfDAACzLk39JDSYI0Htqp9b3qc6Acw=,tag:ZctbiHFv/8Cr1lEpXFALpA==,type:str]
    SECURITY_OAUTH2_CLIENTID: ENC[AES256_GCM,data:yBdoPgXUjuGofPZY8RcwbaxQng==,iv:vpKb1KYHzKaHjI6JFoJNT83RynzEMPbwTlU5AwdIzgs=,tag:OpPRxRUooXLPO0VrxCtFYw==,type:str]
    SECURITY_OAUTH2_CLIENTSECRET: ENC[AES256_GCM,data:f0NsrZDJbQp3BtlgbvcpcnW/pg8byvTMhwfRhGEgpFpsB/aK2NF9zlizxZCq5aliNGl1v494cuDtP0Ziakzgvw3eeaEBdEEynWcymVRwqrIA2uGR7m9sPM8q5uktFNtOebzbOJdFNLIRv01ezGPzM9MxXO/d7zJC0yk2qVWv33g=,iv:E7DaiKgLg0nP2dC2PItO3xI39Wd1Hd2xvfHyYZ4xQY8=,tag:1DboPH95a3+VF6Unb7FuZw==,type:str]
    SECURITY_OAUTH2_AUTOCREATEUSER: ENC[AES256_GCM,data:8GVbMA==,iv:qthF0o+QynTiKwY7yc1hmbZ1G1bex5GiydH6T6xa8Is=,tag:QAgLq8BRd/XFIq1+r7vlIA==,type:str]
    SECURITY_OAUTH2_BLOCKREGISTRATION: ENC[AES256_GCM,data:TzcxZg==,iv:zzpIl/dNgtTLu+f/yHRZupn707vW02nnxJgUMWCzcdE=,tag:TZi5hB703yYMnyucLZU/mA==,type:str]
    SECURITY_INITIALLOGIN_USERNAME: ENC[AES256_GCM,data:rEyLwgr8CKBJmBwzLX9uigzFvxk4YngJEIE=,iv:FOgC8g8y1G50LoEx6JNT4Fk9zlgta517s4optnIGbbk=,tag:3aAgKSmcPld9iiA2DYi9lQ==,type:str]
    SECURITY_INITIALLOGIN_PASSWORD: ENC[AES256_GCM,data:/mylXfohO/62qxOtWgsopVP3d/VqYg==,iv:xL8l56UzW7+qCPHYYicxbejdDdmbaLqPsjc0fY50hqE=,tag:zyntnLw/yOiDAK72UxKBfw==,type:str]
    SECURITY_OAUTH2_SCOPES: ENC[AES256_GCM,data:AtVDYuX+CbHFWw+lJFF7/LJbaRg=,iv:1zf9MonnRh4T1sQ3SUSDk0Q29/h+c5IsZ4MFlpjuv2g=,tag:bpuk/ek6oo+OS8nuWzd47g==,type:str]
    SECURITY_OAUTH2_USEASUSERNAME: ENC[AES256_GCM,data:/RRDN7I=,iv:gHheX6GPVwEEMNcBKFNZESrYaWbEypHf8ZV6K5OcAD4=,tag:8BLKDjpt8jzPsemM0FwIWg==,type:str]
    SECURITY_OAUTH2_PROVIDER: ENC[AES256_GCM,data:PeEd7EPXAf1R,iv:EpGs5Az/5n7wPO+HpzfuYsV1SjWTwWpV0PyUias2Agg=,tag:T2+wtaH0SialDcS4JwS7rQ==,type:str]
    #ENC[AES256_GCM,data:7mL4XBjNQJGgwXXjdLu1oyx03xtj,iv:RicuRkIWzQWjEebr+wKW9P1w5tx7f1nco9eKumr0zcU=,tag:tPxDmOfuVa/qbAJjaarBtA==,type:comment]
    SYSTEM_DEFAULTLOCALE: ENC[AES256_GCM,data:DT441Sk=,iv:O76oCmgc3M1uwW3R/QvPscmiAh2c06DXIW7j/XUJbVI=,tag:MrMh+OXTNibCECdp8Dr14Q==,type:str]
    UI_APPNAME: ENC[AES256_GCM,data:BBwFy4YFnAjcVSyE,iv:3iZ1E0flVSgeb6wp1J/hIMllTOu07x6LpfncylGVRFA=,tag:lpPr1S77Z+stUzeq4C0lUg==,type:str]
    UI_HOMEDESCRIPTION: ENC[AES256_GCM,data:A91QJhZyTly+vt4zn6KXquBzwkZdnbbwkLTc32bp0n69lf6VddSCKyjFSvvNmc1q,iv:RnuzBobQ4RObNDAhzwax4F47w9/1JczgyNJMWtqLOY0=,tag:k3e/E3vEXBg+aZfM56+uTw==,type:str]
    UI_APPNAMENAVBAR: ENC[AES256_GCM,data:s973RYC1LFKY1WKv,iv:ecwCT1Gwdw3vY1yWS+lKTGQbpvxZPVEsOntTmTLylg8=,tag:ZNQ3jiUh8d4DSHeh8H+CAw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBST2RLVjRYRjNpZkROaXRF
            MXRKbWRJMVREd1A5YW0vcnV0NzJoZjIxeDF3Cmt4dnJPeXdsQmdwOWlST0tFaHBh
            RTN5WVdxOThQNmpyVU1DcDRsZ0ZYSDQKLS0tIHdrUkNVOFdNTTI3UGhrcGRlQlVF
            Y1pTZHoycjRrYkM0K3JjcDZ4SUN3NE0KpUHDqkO3BDEBRBw2PTlMs2eV7K2n+xcb
            iVTSCKknLxeasuwJWgoF8TbW5Icb+K5AkmaItAsSdxgoo3Y3pEJFpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T00:14:40Z"
    mac: ENC[AES256_GCM,data:q78TElMTn/ZVu28kRtxkFYOgOVeP3/GL0dZ5Tj0aGZW0H/jTEC13XNy490dJrSVkMXG1SMC/ViFG7P7oH0wkoPrJUeV+bgjGOwu991HVKP+HiUTsqwY7ipyUPMD2pIGGq+4PcmEPlLIpPaqHR1RR4XHHe8HiBhDMZmO/7nP8m24=,iv:Q20L2+NaiYoFNv7LNzPNPfFqh2cZj9Ru3Ycbxb9g3iY=,tag:sDqUwnLRCM5yvJILuETetQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
