apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-home-tls
  namespace: adguard-home
spec:
  secretName: adguard-home-tls-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - adguard.h0melab.work
  renewBefore: 720h  # 30 days
  duration: 2160h  # 90 days
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard-home-w2-tls
  namespace: adguard-home
spec:
  secretName: adguard-home-w2-tls-secret
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - adguard-w2.h0melab.work
  renewBefore: 720h  # 30 days
  duration: 2160h  # 90 days
