apiVersion: v1
data:
    SEARXNG_SECRET: ENC[AES256_GCM,data:XYX99kY8kTFQ3BjKboY6pqklQUuaRB/9o/XqVCIxQT47m6yjYQkk3/9g3hiJQ69n2YwbET+8ryjbWuzL5AWiOdMmdSIPfVhbCTeDF9PFEEWFL4pFWsyHFg==,iv:UzQ12ozaBqkFyrfe2VwzlgmC4Mcq9QOOz+4lUmqJ/JI=,tag:lOo98scWDlsWs0B7X1qfeQ==,type:str]
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTC82SVh4a21hVHU0T0d5
            K3ZnMXpDQ2lzUUthMzF5NkxlUSt5TDJKYzNNCktSYTdFejBxdzVTMTMzVlNiaWZt
            TTVHTVFxRnEvMCtsdkdPMU4raGtIUDgKLS0tIEloYkwzOXFBdXIwbElNQ0lKTXRv
            MHNJZy8zT0IzZ0dCTHBKTktjTTc1U0kKjZ3RdnjWF+1oWneKoB4lIGS0iXbPhwwq
            8CrSrE2kxraKQj+57OGt3W1pdbPmpzO4rpSG4MdxJS07XbEh3brKHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T21:43:00Z"
    mac: ENC[AES256_GCM,data:L6J1uXcQ9efGPo/2W2h1rYjd5CyvmMsDPQK2lOKGUViEuSwTONm/X96lu6l9Gr1giRzZQxy6XXUAVrUWfQD60kZJ93kmqHzrNmd3HeOPXUaVkqj30nJk0yRw/y6mNcwi8mMP3uYW84rrn9AnWpfXbLCBW0sIuE5yCA5OKBi5bb4=,iv:CcJTgg4zHWqH844zengy00pxZXWGiUWa7ahSVy6w/r0=,tag:6D33rYjVtlk2JDcPlESsJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
