apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stirling-pdf-pipeline-pvc
  namespace: stirling-pdf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
