---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: linkding
  labels:
    app: cloudflared
spec:
  selector:
    app: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: linkding
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-metrics
  namespace: audiobookshelf
  labels:
    app: cloudflared
spec:
  selector:
    app: cloudflared
  ports:
    - name: metrics
      port: 2000
      targetPort: 2000
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: audiobookshelf
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
