apiVersion: v1
kind: Secret
metadata:
    name: grafana-tls
    namespace: monitoring
type: kubernetes.io/tls
data:
    tls.crt: ENC[AES256_GCM,data:Cs1wcwdheNNThRUjKfAavPKmLH1SjLJKvPaJUs1E8jcJzq9WXYGk+cxMhgRW,iv:Vgv+2HVNV2W6/UwMWLjarWJHgwGDGqxbT/sAdnNvF2A=,tag:CvfbRK5TsBXKoWG/XfDokQ==,type:str]
    tls.key: ENC[AES256_GCM,data:ufwN5gO4a4sxa83M2V1n1YTLHoJjCA12YCor8XdWjm1V3Jz3NVUo/ftf9UML,iv:8PMEE0Tm2XwHNW7BLJdRfPchsnr28VxNkYv3T1XT0b4=,tag:6b3XLWYcS/C8f4qX6B2N/g==,type:str]
sops:
    age:
        - recipient: age15wyev7l49up7nan7nwc0lk3k53kmkd37566cn28djsz036d7fqwssfahtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbTZucG9sQk1adVltQ2ZG
            Sm56MzRUOTZLWTNudWI4bnlPOURCVWlUYldZCkFyOWZrdmZ0TDFzUWlqdFdCVGEw
            ZzltNVBGT293Y2k3NVFCREZTQVk3U3cKLS0tICtDaGZDbWFUbm1wcnRRaE43RVA5
            VCs0Mk10aDRZdThaczZUOU1ZRmI2a0EKbPQWiLTrPUPQhkz6GxZg73nE2FUBp6/T
            L4CdxomGrUspYXLgPLF4hWqQniXbsNHo5g7dMD+IDNiRmaSYn6XLGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T00:52:31Z"
    mac: ENC[AES256_GCM,data:NQCHRt1PBaE71KW9WXRhXCQRqgFT+NLcZRWlX3lcMrgf93CIMIcoLtV9mFqfeJ0XWVjB9gAgnMbzLdGz4lerWLc1msLZeCituSgU7emg1zRYP0++9NYeY2XS2Uzgb1ALtVVCfMSfiIny4Ea8fdKcR7/pEzExFlK6muZnRgGFOmc=,iv:yl4ksOfv+8vCbV/rrsPdDg+s8eCM98Ys8Fwu+y+nw8E=,tag:aHZ1v77zSdQxV5vCobIX8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
