apiVersion: v1
kind: Secret
metadata:
    name: grafana-oidc
    namespace: monitoring
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:Z08XmesbYg==,iv:PqxOZoOGmQp6e0UVzy8HGIxU8ljpFonfaL5cNwjYkWQ=,tag:VRDXCwGt10Z0v72A/EwYhA==,type:str]
    client-secret: ENC[AES256_GCM,data:2fh191azBzlH1+8tOV6y3+im6K7+/G8+7AGi2kn2kv727CT3cHqxewOVDK2Vb2Hn+3w71pt2KK2RS54eyFtJ4w==,iv:1xGq2ZBe2O1z5d/a0x6b+141dcthKs7MZxvwc0efiPM=,tag:l7SIhqYe2NPug1opCkMqfQ==,type:str]
    issuer-url: ENC[AES256_GCM,data:CmceYV6BZDx3N0/7exF/artXxVvH3rraxEcalZMHG7vV7pNHmig0oijxTmT+5eNrVgrIJWQ=,iv:xxtIuzrRnuxuiozRRDrj8oNwJw7Q2UGz+w46Awy61k8=,tag:9Ieeh66e9jgOvy6JqNs7ww==,type:str]
    authorization-url: ENC[AES256_GCM,data:ROwrFNiPPtPromJ21UEZ3XSKrhKjIHc5++cPA+E7Z8svZFYM4jDgMzUlUJgwplX/licXKe8uMg==,iv:K28isYobR+tN4X7Zc5NeHMlbWS1wZJkSczO6gXMdNa8=,tag:CdR1B3AkgA56KO7S7wKFfQ==,type:str]
    token-url: ENC[AES256_GCM,data:k77XxedyPoyDIfGDhgzvyeQyRaXt6K7Bnnz57FcWHeblR5cQX8go7Oltt8Q8Z8Y8fs94,iv:+4ADVLAmZyNbK/BTtOXXRVhg8W/WVS8WoKGchEvfhWw=,tag:bEml6lek3Il5EPcrXPM64w==,type:str]
    userinfo-url: ENC[AES256_GCM,data:lsoQG/lWFLlpv48GSUInuNbLr6QD6C7Ib/Yj+Hv5LHpuO0vFUu4Ja3X4rIjgpcGPc2qr0Pr3,iv:00w2GuTdKox8BY4pKt5TeoMsDSd3yCIChIlyxSay4Mk=,tag:RdsLrboCyW1rcmsE5eW6tw==,type:str]
    jwks-url: ENC[AES256_GCM,data:yxBbC73acwchtBPHKDGHGsvCnyJfmByXMb5SruLmxyJM+YC9Mb5YsDVGE94980P3aDMdwVvDHKQXqg==,iv:EDa+aOtlrOD2eHIo6FoobOAtoYj4r4LlpdGqBmw1cPU=,tag:GfsvS8AbzI+lCT+2qBKvgA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOEVvYWpWSlBySDdxb1dY
            ak5oaGpUelV1S0RiUWRPb3hldFlHZi9zblhrCkpmWjJEMHFJRG90TEtreWlabFR6
            aUloVWJROFZIV2tpVE5zeHlpek5zakUKLS0tIGc3aE9BQ3luS0xoUG1aYmdzU28x
            QXJjQmltay9DSGZtdjVuWlpFVnY5K0UKuzxEwWnK0jgtmMLw9twF0HZ/2CYxfTjT
            osOWCY2Utf2MZi1iSiUeggohYd4CmWTaU627an1v1in+7yxfnRY5KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-20T16:10:40Z"
    mac: ENC[AES256_GCM,data:IN5kcnJpiaDPyFmjYV+EUH0G+pmAnC9fxf5awF8xtLQG5ge8BwdcaH16ELmQ6AdxVbIri29QUgp+M9CtLqBQDt0JaG95oIBvKrEvSAg2PCEmf6z705Dn7yuajGglpZHgC0ogkAfwLBxiF8Enmc3IZYcndCcOaLlvRfcKIMqE3WI=,iv:qU5vS7s5EEQxOpv72cGC3OFRjlDgs7durFohe89hYvA=,tag:H5Uh71Q/OcFrE3Tlt5UqMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
