apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:Wsar7kvR94J0RnXb,iv:NKQsJkkv6Oe8l7xeddei9vJIoVDtvdVct+CUnvKTGO0=,tag:AqmgzvQkhjRmoNXnboBg/Q==,type:str]
    admin-password: ENC[AES256_GCM,data:FNUiiO+Ge7kF82tAanpv0K8z6CI=,iv:aCbolxcHh9JDwoOtnevM+77NChzjeL30l6cRlWbq3WY=,tag:uWtgte8VOmhnkfqqE6wZUw==,type:str]
sops:
    age:
        - recipient: age15wyev7l49up7nan7nwc0lk3k53kmkd37566cn28djsz036d7fqwssfahtm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAreGJ5Ulh5Tmlja1IwR3ps
            V3hGUjFlTXRVSGN3MlUvM1BSZ3BPNzZKdzJvCi8rVFR5b1pOaFdKK2JFLzdOUlB2
            WFltZnI0aHU2dGowMUJSY0xlMWZLYlkKLS0tIFdudFhDem9YM3B0Y1RHd3VxMDkw
            Z211ZGFHV21RNUtEVHNOTVN5cnNXU2MKwT0/q1ma67POO9XbWhq7Ce78e1CQhk1O
            Ws5poLsSqxSJ4SisOx1ehzuVi+43DdP1ks7oDhcDPqz/Zr8W4fU0zQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T00:45:11Z"
    mac: ENC[AES256_GCM,data:4Cn6csjJyB6rqHybCk5oJTJ7zR6ukAK6yCIpYIk5ePRAthcBCp5xbNLcLyf6ryJvLNF7Ng1lDaBNV/SObDuu6TKFPKnSeFbqjtlJYtDjjJZg4py+LDwuph50tdiL4w9wXJVZbrggeDpbre9q0/YI6JhRnKIipfMeNim2XKB87ps=,iv:1D+5bKboXyxSpMz7e0IwV/m6B4E6OZKeK19wCGyZGxg=,tag:LlBuK7gqpnX3kcfu9fI8aQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
