apiVersion: ENC[AES256_GCM,data:Wj0=,iv:G3GEW77OMTlADSmmKLXQPFr1QbmCLO/pyaM6rBRzfBk=,tag:Pa9LsoSc4NKImeE5ywIIWw==,type:str]
kind: ENC[AES256_GCM,data:PQt9kdMW,iv:DWwlonr71coJsRWj82tUFBcKVbeyyLGXVvI9uIt5jec=,tag:whXMqNra7d10ytnb837YWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:k/aaM8iPNoDn9zo8L+UWGVWCOtQ=,iv:IbVGSk2o4R4Rrmw2cFsqIdcVUlvjrPKXTaFI4kQRM5k=,tag:7HXdN95CH41+xEqGWMrSbw==,type:str]
    namespace: ENC[AES256_GCM,data:Vz/FP88SQletnA==,iv:eHkvbyDHrerVMzF8iFVbd/O0my9wDW6Na3l7MpsyI3c=,tag:S9yVI5K4XGoXAi76NVJ7eg==,type:str]
type: ENC[AES256_GCM,data:4TelmU0O,iv:LZQgKH9LzLxLb8rHHFgKmX/I0VDMlilmb7JX9nI8Idc=,tag:4NoNf55mMUY6IJFfZfYjVg==,type:str]
data:
    #ENC[AES256_GCM,data:iXMh4Ra01P7M/oHJg6436Gc=,iv:lxxhoFmySvwZWq6KHhUKCDX/ddVLhOjL+SbhMu4YLtc=,tag:trqQNran6qjVffvbh79tYg==,type:comment]
    admin-user: ENC[AES256_GCM,data:/NFBUdtGHvX7w+Gt,iv:1ifQDCicPUUN9++ixhlyLKg1qdOsXKCJMcgj7ZqmJdE=,tag:E6C27RGuddEQ9hZ1nn9fuA==,type:str]
    #ENC[AES256_GCM,data:RzF9IMDiH/nw5xa7w1Hke4f0D1fLpP4=,iv:bm8VFIceXqPdwcGSQSJwctIXtq2QcrkwsmwkpQCuoF4=,tag:CEyGJeY5pri6s4Jyf8O4mQ==,type:comment]
    admin-password: ENC[AES256_GCM,data:NJaGicjoX56ulBFoWccFjQebvs8=,iv:g2+HwS3tqeL7Y+F7zZfiqXTxjI3BpQKGMgNOzGKBpdA=,tag:qSY+8o39CfiLyvj1oBaJNw==,type:str]
sops:
    age:
        - recipient: age1gzsym5v633tjlncmdhktv89w4p7gmurgvqwcy2xzj8jkmtygtqnqt2jxg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZFpvR1VTN1hGeDE1M016
            bEhxM1drNW1LL2pjc09Fc2tGdXJuV3NyNm5FCmFYc2dnV2xESVRLeHlrSTRBdnJP
            Y0I2U2Y3V0tkS25rN2pJNWRoRm5jeEEKLS0tIHFhYllvWnExSE9reFB0MmoySGF5
            V1piRWVMWndvWjR0YURQeG5tRW5PN3cKZ3FQasXHgkOOoatCc0dq4BczXPTmF47E
            QC1wfuDvwH7sqpF6ytld2NtlwDrgGk+BhQeRuvBRFM60MnCAuk6cUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-05T21:55:05Z"
    mac: ENC[AES256_GCM,data:eocObGaJ7GjjMcAmOW0G0hkvn/ZVTNPcchS6wdZGHHYcY+hJ15nwmyRzgcsIaYF8uiHXSJISRwWQ2mQw+nIY6+QjDQnC7GvN4epdpq8AC5zvi2xNFrUvVGPUZJGgzrp4pRKfmVcHnTZb/HE2eESNrDWoR5lHxzHwTvAVBLcdaZQ=,iv:eA0ZujEIQHNJWsK/YgxZOpmmFYnjyTeKEO6u6QsF0es=,tag:yJ0pc48wYL9kFApWtiyHMw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
