apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:SL11c9Zwr5SQReG/,iv:8PNykd34a0xF8FXMkBR3CWvF3B4CmSTF2wBPuuIw8B8=,tag:LmMtddqbSnBB33j4zc+wzg==,type:str]
    admin-password: ENC[AES256_GCM,data:gRS42T/41GwoC8J7NEx+AJFaNGA=,iv:62FeyyfKXI5kyAFGms84HDmKzNfbb81JrC6t09ZTckU=,tag:QBXdqg2EUHVcnbwQ0P6UVw==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdzVaay82aHJXQXRJa2M1
            OTFKcjVVY1lqVHdsWHFmZlNXZ2h5OEJLUmxVCk5pV3JFVHljdUswUzd1eDRKNkV3
            QVNjUTdSSWF5bDE4RUdTMUZha2JsRlUKLS0tIDNQRFR2eDJ5TFVwOXkvY1RrdzRK
            NjI1UjJqcTMvV1d6SUh2QnJMN01FMjQKv9VIRYi+7NJRDOWkO/jaPVajFTwJtyrn
            1+cJpSqX+Fh36k7I6awEd3TAqcM6dks3l2rwZwCwuMTFB0vCff/nGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T01:07:34Z"
    mac: ENC[AES256_GCM,data:uRsMTgtwILVwhbV/EUK7wxwGsZMTKd4GV6gdc6cverpzwBCl0jI+VAEvs+cnyW7yTQCqBEZj7xDuQeYuXIVbq8j73Aejx5UHgTn3v5ZZR4+0hekYn0j5zcQG413QDJL431il3zijpUyl9gtZW9nCoIK/aKhA0cW7OE0g9FzsWI4=,iv:D9qF9hp07hhoa+VrnDBSKw81HoQoHCY2Ds3E87Twc5c=,tag:qOmTOeZrIdAIBI/n+6ZA4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
