apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - namespace.yaml
  - repository.yaml
  - library-pvc.yaml
  - release.yaml
  - networkpolicy.yaml
  - admin-setup-job.yaml
