apiVersion: v1
kind: Secret
metadata:
    name: main-postgres-superuser
    namespace: databases
    annotations:
        sops.io/encrypted: "true"
type: Opaque
data:
    username: ENC[AES256_GCM,data:xjLHvOydVRjeREwy,iv:Ooj4TB/iv0z4YdA8C1Z7sQDMFzSsLJWeatgxZsjFZFI=,tag:gHvNZwTtqF5/+X8Sjv8jYw==,type:str]
    password: ENC[AES256_GCM,data:1T6zFXnS4GsBITcLBF4L4TgFo44=,iv:q0nRdFbT0sYIZXpVkc/mUHQksOLw15cOArN8GnVo9WU=,tag:g0PHQR1TMUqRFAhEU6CoPA==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QlNWcVkrd2x0QUFhbm5t
            MTZTZFdmc0NPSUUxdHlMSEllc3gyd2tvcER3CnRraWhMQmxUSjZ3cDEvbzVqdWdq
            YWF0ellFT1lSZUxBN3VEYzYvWUpGb00KLS0tIGRwL2JMcFhUbVZkb1NTaE1sZHc4
            VmttczJxUytYSVI4STVlRlBvditXNU0K8XmvYPvuRWg5scykHiI1PagvgKK/7EoC
            Q6Al3NJfT9XtD4/mxkcW+ydX8BiPzYFdCLgLZAsd7dwjYUxKXypK8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T14:44:53Z"
    mac: ENC[AES256_GCM,data:8dGic74l6IKzMFTyChFZVfNj5DaClHgZUpXiKIZvskXTRy/Z4ve6N3b3VGXFAOVzGgGEf1W8IDNwv/4zUd76ac+Qe7KasYo7vd0HrzJ06R2oRVMEPr899+t2RYQERE9khAng9ToqzY4UMXSfvcugasw9H081rUytvfdInnO40WQ=,iv:aehMRfvwPNoAzRIqQfgYyFmw6k3d10NNC1ZYtJJgkPY=,tag:DIvD7cW+VhV8eKaFa//7yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
