apiVersion: v1
kind: Secret
metadata:
    name: linkding-db
    namespace: linkding
    annotations:
        sops.io/encrypted: "true"
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:bZnE85uaU6w=,iv:FikOvyKfaLJ6YMWcO/zYgbCyfUTS99Za/EYGqZWA4LA=,tag:QuN84hyew9zRWpHT3uTfww==,type:str]
    password: ENC[AES256_GCM,data:LSE/x2iTIjuO3Y4DBG4=,iv:o761J/gBul1gMNjVcLD0KNmWUdais4XsFZijVcgChyo=,tag:oWSFRqRFsKKKfXC1g/9mcA==,type:str]
    host: ENC[AES256_GCM,data:fqULU4KMkaORfOm4refzrlMJWeK6S84VAmoCQYAuOC2oz33AoSyr2wDiArfyHfTF,iv:s/pu3DpwtP31b7XzDnZJfknL0mwT+wG6Qq7nYEUSltw=,tag:oyOInVPVl8soXkHDiDZ8jw==,type:str]
    port: ENC[AES256_GCM,data:7bcxcA==,iv:QUiB31uFr+J7LOtt8IL0bL8PuvWR+6D0xTO5XKm37t8=,tag:KTas76HM31IfHuGpKGto3g==,type:str]
    database: ENC[AES256_GCM,data:WiutHu/X/KM=,iv:VCc64WhBbYFfxtiXHP8iVSqhMxM3DmTZBny/fYUp8rM=,tag:5phXSls+goZDI1boaauJgQ==,type:str]
    sslmode: ENC[AES256_GCM,data:1HWAgpPUPA==,iv:wU/WbayH6Y1K5Y3CaICykXXdGZaraIPmm1Oauf+so44=,tag:nllLyTdVtUSzKvaaZFjNBg==,type:str]
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0N053TE1uTmRHRENqZXBw
            OE84empQVWw0dWloYzc4MzZ1Sm90T0J0OFRJCk04bit4a2l0d1R2WXZGNHl1ek1N
            QlRyV28vK1RyOVlZaVpteEpPWUZ5QWcKLS0tIE0vWWNGOUt2TDRBYkw2ZW1VZHhr
            VjBXZDJsbVRjK2Mxck4yTmNRYURnVVkKLPEDq/WHodrcTtQtIEePQzFm2OqCWCvn
            xa+4OcH1kuG5yzXRlQJnLAiGkCVozTTNVfqSilk3cPDsLB3AP+JOFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T17:58:51Z"
    mac: ENC[AES256_GCM,data:Hxw/D7AeUgxxdvuZ0xl7QaqA2ICjQiuDeubu3JDPrtCDPISBH1f6dEhiUf3I+u2N+Q+kF3TTQamCsk/5HqtqX0qglAXr3ljyHnFBdMFTJC8O04iFwWOiuehcEOItpv+Ek88yajWb6z/9667NLzfKXoJbbVGc0CRh0x3wPgsgz5A=,iv:WdpdQMksD3SjYmQJDYkbosQ3J4zv7T38ZYSdSAhrcZo=,tag:TwH8uxb70HmG6o5dTKyRrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
