apiVersion: v1
kind: Secret
metadata:
  name: main-postgres-superuser
  namespace: databases
  annotations:
    sops.io/encrypted: "true"
type: Opaque
data:
  password: ENC[AES256_GCM,data:G35Oaxucov0T/XPMGjlIvEBMdfk=,iv:LsPiApPmTBSma18HsMzS9zS0O/4GzwTm9zkA6EBvBDM=,tag:pGKNhuYrHgi1OGsE6NWMFg==,type:str]
sops:
  age:
    - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUlg3WHFmVmdtR1NSUXVY
        SXVYanRMWlZRL3hGS01oMkkwdEtYNlpDbVhzCkpaSEJ6SEZ1V2V0YU44QWwrT3ZN
        bVZqSi9zTHFKL1AySWxWZjBHS1Bpcm8KLS0tIGd3cWJYSzdock1XUFByNmVVSUJa
        amVzVndUcEMxTEJlUHB0eEQ5OVBqMjgKs+BSLb9RolPc23enEmLsiddqQRZd+gtZ
        SWFqKgqY78BKOaA0yRBKkqfpn8zviMFMA6rUmZ1PPVp3DIyXolLj3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-08T17:21:34Z"
  mac: ENC[AES256_GCM,data:oeqJ8n+RWQdfsq6IdGLbTN0En/PHk8Gt0eJyKUJ3HV1xoA3mW6mB5zAywSNOoHKTcrxL1rBkVGN9wyNqDbe2Y5GlO1bHJu50cxiuaKGETr6si/ISPs9cZdeoj/ulGUPhhGcTlLqjEQ96ddopbvoi5N62SN9rIDUp8bID2eCDOdA=,iv:+syrEXJBrwaSTgLCHEQj8NhiklaNArKqDSylsUsulMI=,tag:HDzlnvVxDinu404cgM1Blg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
