apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:NqoZaLUub6RYBkfFVFMkBWRVJht0Gc6dhMMmFP/jWukZoKN5UgyTVQDNs1rZvcREUhfFp55Px0o=,iv:ENuEWWb7Td1EWhf1p3pTpK9ownIIna1GNuvPVAftGFs=,tag:rgDhGMZbhHN4mIuPkkHIMw==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1jwjtfrp625gh24xd8rds9zcz7arsgmqf8y3nn4j9redfcvfvcuhs4fv3sc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WnFaQVlDbEIxbTJyS25U
            dUdMcVE5Wkx5M253enFwQS9PR3FUSk1hWFRBCjR2dmNCSWdZK2kzUzFNNVBDVCtB
            eVpZamQ5YUNsNDlHanBuUEg3dzNEbGsKLS0tIHlYVDZCVGhYYjIwWGJjaUNHamtX
            L3o5OU9uTUlmSFRkTXFtMzN2aGhtVWMKDLc559t+IHkK5kAGjNdpFkWe1X2Brh42
            D4ARHfhabsp7zUBOeMKUiW1iNW7J0+RsHO0wR7tVBAM67JrKreYJzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-06T01:07:28Z"
    mac: ENC[AES256_GCM,data:K2iMfaMw71fXZ/tudpyMX1wPlamdkSeHnxJR5AarxhLOPy0Kacs/z3g5XT+qJAxkOK+/wYrVv8sgeEddt7H4OpZOkS6DMMEKLSAhkfGhgSAD7et8o2iPhGBA29HJ+G+GdZFCTLdUPsrtz8eIJQ+1aMPJ7DdAE7dDBR0nZ/cmq30=,iv:V9CWFyV11WQ2Q4pBGCmwyFcgQ0D/43bC/qWd/t3YUj8=,tag:/cp6wUXTki28j8rMaCbF1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
